### ISSUE TITLE
Can't receive whatsapp message is encrypted

### ISSUE THREAD

**Issue by clintoncheuk** [mgp25/WhatsAPI-Official#109]
Cant receive any message sent from ```Android/2.11.432```
My code:
```php
$w = new WhatsProt($username, 0, "NAME", true);
$w->connect();
$w->loginWithPassword($password);
$w->sendMessage("852xxxxxxxx","test");
```

Results:

![2014-11-12 11 12 00](https://cloud.githubusercontent.com/assets/9696471/5012458/5adb3b22-6ac1-11e4-94bf-8311594a55aa.png)

```<body> </body> ``` is missing..

**Comment by mgp25** [comment]
I close this issue as now we are not having any encryption issue. If in the future this happens again, i'll unlock and open this issue again.

Regards
