### ISSUE TITLE
annoying .dat files 

### ISSUE THREAD

**Issue by kareem289** [mgp25/WhatsAPI-Official#225]
i edited file whatsprot.class.php to make the .dat files into cache folder , 
because it generate a files with every number i use to send from 
i think it should be a constant variable to make a path of this files 
i edited the line # 2288 
```php
$id = fopen($identity.".dat", "w");
```
into 
```php
$id = fopen('cache/'.$identity.".dat", "w");
```

and also related lines the use `file_get_contents`

**Comment by archergod** [comment]
I vote to open this issue, as it is feature request and you agree to work on it, so why close it down? 

My request is:

To have a Folder path defined so we can ensure that identity.dat or all media goes relative to that path. Currently in Media Download the MEDIA folder path is relative to current executing script and cannot be defined unless we make manual changes.

Thanks.

**Comment by ducch** [comment]
@mgp25 Shall you reopen this, I'll take care of it.

**Comment by ducch** [comment]
pull request submitted.
code was not tested yet, so let me know if there are any issues.

**Comment by mgp25** [comment]
@ducch i did some fixes and improvents, the code its working but still to be finished. See lastest commit in dev branch

Regards

**Comment by mgp25** [comment]
I fixed a completed a few things in dev branch, i tested and works. User have to set a path where its going to be placed all the wadata and create 3 folders.

Create this folders:
- wadata
  - media
  - pictures

One folder, and the two others inside.

So you have to set path in constructor:

```php
$storagePath = '/Users/mgp25/Desktop';

$w = new WhatsProt($username, $storagePath, $nickname, $debug);
```

And all nextChallenges, identities, media, cache, pictures and messageStorage will be saved there. Identities and nextChallenges have their own prefix so its easy to search between them.

Try it, tell me and if everything is fine, ill merge it.

Regards

**Comment by ducch** [comment]
I don't think it's a good idea to _require_ the path in `__construct`.
Maybe make it optional?

**Comment by mgp25** [comment]
@ducch i can set a default path but the folder must have to created manually, and set optionally to the user change the path. Better?

**Comment by ducch** [comment]
Why can't we create the folder from now?

**Comment by mgp25** [comment]
You mean that the API create the folders?

**Comment by ducch** [comment]
I don't understand what's the problem/your question.
It has to store text files inside the cache folder, just like it does with pictures.

**Comment by archergod** [comment]
If we do not use __construct for path, than I think we need to detach the initialization within construct. And yes, API should create folder structure by itself.

**Comment by mgp25** [comment]
@ducch try lastest changes, it will save everything in a default folder.

**Comment by mgp25** [comment]
Fixed in latest commit.

Regards
