### ISSUE TITLE
Some optimization suggestions

### ISSUE THREAD

**Issue by robocop249** [mgp25/WhatsAPI-Official#227]
Hi there, I am not sure if this is the right place to tell some suggestions but here we go:

- You often need the whatsprot-class in subfiles or in events a.s.o. if there was a singleton in the class you could call it with this instead of accessing global vars

- Outsource the constants: I need some higher socket timeouts and I have to think of it every time I update the repository. This is a user-based constant, maybe we could outsource those?

Btw. thank you for your work and merry christmas to you!

**Comment by mgp25** [comment]
@robocop249 We are going to rewrite the full API, once we have the libaxolotl ready.

Regards!
