### ISSUE TITLE
How to intercept ping result from whatsapp server

### ISSUE THREAD

**Issue by boxim** [mgp25/WhatsAPI-Official#254]
Hello,

I am sending ping using sendPing() function every now and then in-order to stay alive and I noticed that after sending a ping - Whatsapp server returns a result:
```xml
rx  <iq from="s.whatsapp.net" id="ping_-1420039342-19" type="result"></iq>
```

I would like to know how can I intercept this reply node to make sure that the sender account is actually online..

Thanks in advanced,
Din.

**Comment by mgp25** [comment]
Using events, read the wiki: https://github.com/mgp25/WhatsAPI-Official/wiki

event: onPing

Read the wiki, is there for some reason.

**Comment by boxim** [comment]
I created my own event:

look for 
```
			        if ($node->getTag() == "iq"
            && $node->getAttribute('type') == "result") {
            if ($node->getChild("query") != null) {
```
within "processInboundDataNode" function in the "whatsprot.class.php" file and add the following:
```
			if ($node->nodeIdContains("ping")) {
				$this->eventManager()->fire("onGetPingResult",
                        array(
                            $node->getAttribute("from"),
                            $node->getAttribute("id"),
                            $node->getAttribute("type")
                        ));
			}
```
			
add another event in the "AllEvents.php" file:
```
			public function onGetPingResult( $from, $id, $type ){}
```
			
add another event in the "MyEvents.php" file:
```
			//        'onGetPingResult',
```

mgp25 can you add it and commit to WhatsAPI?
