### ISSUE TITLE
`no_routes` recently appeared on all numbers (This might help you to figure the problem)

### ISSUE THREAD

**Issue by karam89** [mgp25/WhatsAPI-Official#255]
Dear all:

thank you very much for your nice script,

I know that, `no_routes` is related to whatsAPP server

But in the last few days, I noticed this strange thing:

If I ask a `codeRequest` function on "localhost", it works like charm, I get different results, like `sent`, `too_recent`, `too_many` ..etc.

but, when I do exactly the same thing with the same numbers on `hosted server` (online server), I always get `no_routes`

I mean:
You get different results from whatsAPP for the same number, on localhost works fine, online server always `no_routes`

Notes:
1- I've read all the documents, issues and also your code and I know what each response from whatsAPP server mean

2- Every thing works well online, except `codeRequest` (always returns `no_routes`)
& `codeRegister`, 
I mean sending messages, media, getting messages .. etc, all work fine on hosted server, except `codeRequest` & `codeRegister`

3- The online server has all the necessary libraries and ports it needs to work well, (and as I mentioned in note # 2 other functions work well)

4- I noticed in the last few days that lots of `no_routs` issues were opened, so I hope my previous note help you figure out where the problem is.

5- Tried lots and lots of numbers (Real Numbers & Virtual Numbers) => the same mentioned case happens

6- Tried SMS or Voice methods, also the same

Any advice?

Thank you in advanced
Karam

**Comment by karam89** [comment]
This is the debug result

from localhost (Works as expected)

```php
Array
(
    [in] => 7903524281
    [cc] => 44
    [id] => -id here xxxxxx -
    [lg] => en
    [lc] => GB
    [mcc] => 000
    [mnc] => 000
    [sim_mcc] => 234
    [sim_mnc] => 000
    [method] => sms
    [reason] => self-send-jailbroken
    [token] => 3ORhkE5owD6yvZgkaMzDAwzqdlA%3D
    [network_radio_type] => 1
)
stdClass Object
(
    [status] => fail
    [reason] => too_recent
    [retry_after] => 104526
)
```


from online (`no_routes`)
```php
Array
(
    [in] => 7903524281
    [cc] => 44
    [id] => -id here xxxxxx -
    [lg] => en
    [lc] => GB
    [mcc] => 000
    [mnc] => 000
    [sim_mcc] => 234
    [sim_mnc] => 000
    [method] => sms
    [reason] => self-send-jailbroken
    [token] => 3ORhkE5owD6yvZgkaMzDAwzqdlA%3D
    [network_radio_type] => 1
)
stdClass Object
(
    [status] => fail
    [reason] => no_routes
    [retry_after] => 3600
)
```

**Comment by aalyusuf** [comment]
Unrelated, there's no difference between a hosted server and your local except the ip

**Comment by infoquestsolutions** [comment]
Yes but whatsapp server can differentiate between a genuine request coming from residential ip than server.

**Comment by blu3bird23** [comment]
same here.

**Comment by mgp25** [comment]
There is no problem, i receive perfectly codes with my phone number.

And please there are many duplicate issues, stick to one of them.

Regards

**Comment by Kson2** [comment]
@mgp25 There is a problem. It can't be a coincidence that we all started getting the same problem at the same time. Have you tried receiving codes this week? what carrier are you using when prompted in the script? maybe thats making the difference?

**Comment by cppvb** [comment]
@mgp25 Please make a deep look on it, Lot's of us experienced the same problem!

**Comment by karam89** [comment]
@mgp25 
And I also perfectly receive codes ;)

"but only on localhost"

I am trying to help you figure out why lots of people facing the same problem at the same time in the last few days, there should be a problem and there should be fix

I know it is a duplicate, but do you have an answer to this case I'm facing? (`no_routes` from online server only)

**Comment by clintoncheuk** [comment]
I can't receive any code on both localhost and server..

**Comment by cppvb** [comment]
@karam89 I'm facing "no_routes" problem both online and localhost.

**Comment by MrLight** [comment]
I have the same problem. Tested with different phonenumbers, different tools (WART...) and different Internetlocations (thru vpn, what should test the localhost trick...) 
I think Whatsapp has changed anything in the registration task...

**Comment by Kson2** [comment]
@mgp25 All of your efforts are very appreciated but if people can't register then the entire api is useless, there is a problem and its an important one. Deleting my comments doesn't make it go away :).

**Comment by karam89** [comment]
Updates:

1- Currently can't call codeRequest & codeRegister in both cases (Online & Localhost) even with a proxy or vpn or CURL_PROXY

2- I did the following experiment:
I brought my old mobile phone, updated the whatsAPP to the latest version, and then registered with a number I'm testing, 

Surprise: I got the authentication code (while getting `no_routes` on the same number I use in whatsAPI)

I tested several numbers, all authentications codes were successfully sent using the latest whatsAPP version,
But non of them worked with whatsAPI


Any ideas?

**Comment by karam89** [comment]
Update:

Can not send from localhost any more,

So I installed a VPN
and now I can send codeRequest from localhost (If VPN is on only)


So I think the `no_routes` thing is also related to IP

This explains everything except that I can send from whatsAPP application using my normal IP without VPN

Any Ideas?

**Comment by robocop249** [comment]
Yes, This is an interesting point you got there... So it must be a combination of the ip and something static. Maybe they block the api?

**Comment by robocop249** [comment]
I just thought of this:

Try change the mac of your pc if you connect directly or via router. If you use a gateway (router+modem) try change it there and try to register again.

**Comment by karam89** [comment]
My problem is not with localhost since I can send requests using VPN

Its about online servers :)

**Comment by ayswaryaprsd** [comment]
Any solution to work it in localhost?

**Comment by darw1b** [comment]
This guy has a good solution. And now he can reg a new numbers using python https://github.com/tgalal/yowsup/commit/1279940031d129045a17d8ba1a5aaf8863fea065
@mgp25 can you please made it for php?
thank you

**Comment by technocode** [comment]
i can confirm its work 100%

**Comment by mgp25** [comment]
@darw1b im working in many things, expect a big update soon.

Regards

**Comment by karam89** [comment]
@mgp25  Great News

**Comment by kabelaffeNET** [comment]
Hi guys, had the same problem as @karam89, nothing but no_routes with numbers where the official WhatsApp client had no problems at all. I tried VPN connections to several different countries after reading this issue, brazil did finally work like a charm. So for everyone with problems, try a VPN connection to brazil when using WART or the cli register Tool.

**Comment by enzolarosa** [comment]
I too have had the same problem and I came to the solution, whatsapp blocked the ip of the server that I use to do all of my experiments and consequently from that message. I bought another hosting plan, and for the moment everything is back to work properly

**Comment by cppvb** [comment]
@enzolarosa It also fixed the no_routes problem?

**Comment by enzolarosa** [comment]
@cppvb  solved the problem, at least until the next block

Sorry for my english :)

**Comment by MohammadAhmed** [comment]
@enzolarosa please can we talk on skype?
it's in my profile page and picture.

**Comment by clintoncheuk** [comment]
It works when using a vpn... but not all

**Comment by darw1b** [comment]
Now vpn is not working more. We need another solution

**Comment by karam89** [comment]
Update:

Now Most of the VPNs returns `no_routes` for all numbers (90% as a percentage)
