### ISSUE TITLE
problem receive whatsapp message

### ISSUE THREAD

**Issue by ahmedashraf** [mgp25/WhatsAPI-Official#257]
why don't show my message

**Comment by mgp25** [comment]
Post your code.
Post your debug log.

**Comment by ahmedashraf** [comment]
function onMessage($mynumber, $from, $id, $type, $time, $name, $body)
{
    echo "Message from $name:\n$body\n\n";
}

$w = new whatsprot($username,$identity,$myname,false);
$events = new MyEvents($w);
$w->eventManager()->bind("onGetMessage", "onMessage");
$w->connect();
$w->loginWithPassword($password);
$w->pollMessage();

**Comment by mgp25** [comment]
Try this:

```php
function onMessage($mynumber, $from, $id, $type, $time, $name, $body)
{
    echo "Message from $name:\n$body\n\n";
}

$w = new whatsprot($username,$identity,$myname,false);
$events = new MyEvents($w);
$w->eventManager()->bind("onGetMessage", "onMessage");
$w->connect();
$w->loginWithPassword($password);
while(1){
$w->pollMessage();
}
```

**Comment by ahmedashraf** [comment]
rx  <challenge>????+??uY??0??@???</challenge>

tx  <response>m??*	??Vnc,?g$?????Vu?:?;?+?6</response>

rx  <success t="1420265149" props="4" kind="free" status="active" creation="1416911290" expiration="1468447260">??&?p???+?J?P4l??</success>

tx  <presence name="myname"></presence>

rx  <receipt from="************@s.whatsapp.net" id="message-1420166626-1" offline="0" type="read" t="1426144790"></receipt>

rx  <message from="************@s.whatsapp.net" id="1420138804-3" offline="0" type="text" t="1420144796" notify="************">
rx    <enc v="1" type="pkmsg" av="Android/2.11.473">3???!????C?g?o???Hrx  </message>

rx  <message from="************@s.whatsapp.net" id="1420138804-4" offline="0" type="text" t="1420146094" notify="************">
rx    <enc v="1" type="pkmsg" av="Android/2.11.473">3???!????C?g?o???Hrx  </message>

rx  <message from="************@s.whatsapp.net" id="1420617240-1" offline="0" type="text" t="1420219493" notify="************">
rx    <enc v="1" type="pkmsg" av="Android/2.11.473">3???!????C?g?o???Hrx  </message>

rx  <ib from="s.whatsapp.net">
rx    <offline count="4"></offline>
rx  </ib>

rx  <presence from="201284755198@s.whatsapp.net"></presence>

rx  <presence from="************@s.whatsapp.net" type="unavailable" last="1320223917"></presence>

rx  <presence from="************@s.whatsapp.net"></presence>

**Comment by mgp25** [comment]
@ahmedashraf We are working on it, messages are being encrypted, we are implementing libaxolotl soon.

See #109 for more information.

Regards

**Comment by ahmedashraf** [comment]
Pending the resolution of the problem of encryption
Thank you

**Comment by rohantk** [comment]
Any clues of how to get the decrypted messages from Android devices? I am using WhatsAPINet
Please.

-Regards,

**Comment by mgp25** [comment]
@rohantk Yes, you need to port libaxolotl to C# https://github.com/WhisperSystems/libaxolotl-android/tree/master/java/src/main/java/org/whispersystems/libaxolotl

And once then implement it in WhatsAPINet.

**Comment by rohantk** [comment]
Hello @mgp25,

Thank you, for your reply.

Could you please tell me the steps of how to port libaxolotl to C#?

-Regards,

**Comment by CharlesOkwuagwu** [comment]
just open the java source and begin re-writing it in C#
I've already don that in vb.net

**Comment by rohantk** [comment]
Hello Charles,

Thank you, for your reply.

Unfortunately, I am unaware of Java programming.

Is it possible that you could share the VB. Net code?

-Thanks,

**Comment by CharlesOkwuagwu** [comment]
Still need a lot of testing...
I'm more interested in re-writing it to be a lot simpler.
Anyway...email?

**Comment by rohantk** [comment]
Hello Charles,

Ok, thats fine.

My eMail id is rohant.kunnat@gmail.com

-Regards,

**Comment by CharlesOkwuagwu** [comment]
sent
