### ISSUE TITLE
Not receiving confirmation code.

### ISSUE THREAD

**Issue by NickCis** [mgp25/WhatsAPI-Official#258]
I've downloaded lastest version of WhatsApi. When i try to get the registration code with the registerTool example, although, it says that the message has been sent, it never arrieves.

    [nickcis@myhost examples]$ php registerTool.php 
    ####################
    #                  #
    # WA Register Tool #
    #                  #
    ####################
    
    
    Username (country code + number without + or 00): 541135683012
    
    Nickname: Nombre
    
    Carrier: Movistar/Telefonica
    
    
    Type sms or voice: sms
    Array
    (
        [in] => 11356*****
        [cc] => 54
        [id] => ****
        [lg] => es
        [lc] => AR
        [mcc] => 000
        [mnc] => 000
        [sim_mcc] => 722
        [sim_mnc] => 070
        [method] => sms
        [reason] => self-send-jailbroken
        [token] => 9PITIgRMVu9KssxuN%2FAUBPE0lMk%3D
        [network_radio_type] => 1
    )

    Enter the received code: 

I've the same problem using [lastest version of yowsup] (https://github.com/tgalal/yowsup/issues/477).  
My carrier, Movistar, 's mcc is 07. WhatsApi sens `sim_mnc=070` while yowsup sends `sim_mnc=007`, none of them work. If i use the app in a tablet the sms arrieves correctly.
Any ideas how can I help to fix it?.

**Comment by Kson2** [comment]
This is a common problem, mostly with virtual numbers. Use Voice instead

**Comment by mgp25** [comment]
Duplicate. Search in closed issues.
