### ISSUE TITLE
Socket error (broken pipe?)

### ISSUE THREAD

**Issue by phpjoker** [mgp25/WhatsAPI-Official#259]
Hi Dears, when and why this exception error happens?
Thanks

**Comment by mgp25** [comment]
Update the API. 

Regards

**Comment by phpjoker** [comment]
excuse me sir
I now use latest API but this exception occurs.
Is this problem related to my server or 
The frequency of the incoming messages?

**Comment by phpjoker** [comment]
I was forced to change API because when socket_write incomplete , API dose not work for a long time 
```
    protected function sendData($data)
    {
        if($this->socket != null)
        {
            $cbData=strlen($data);
            $sent=socket_write($this->socket, $data, strlen($data));
            if ($sent!=$cbData || $sent === false)
                throw new Exception( 'Socket error (broken pipe?).' );
        }
    }
```

**Comment by mgp25** [comment]
```php
    protected function sendData($data)
    {
        if($this->socket != null)
        {
            socket_write($this->socket, $data, strlen($data));
        }
    }
```

**Comment by phpjoker** [comment]
Say me when socket not null but socket_write incomplete , what i do for this problem?

**Comment by phpjoker** [comment]
Please help,
why and when sent length and data length unequal
then what i do!?
