### ISSUE TITLE
{"status":"fail","reason":"no_routes","retry_after":3600}

### ISSUE THREAD

**Issue by MrLight** [mgp25/WhatsAPI-Official#260]
Hi all,

I'm quite sure, that the "no routes" problem is not a real problem.
Since a few days I have this problem when I try to register a number with whatsapi and with tools like WART.

I have tested this with a lot of different numbers and also with different locations via vpn and with different carriers.
I have tested cellphone numbers and classic phone numbers.

I would really like to see a open issue in the tracker to collect user experience relating this issue. I think its not the right way to close all treads related to this topic.
Even if it is not only related to whatsapi but i think this problem is related to all Whatsapp API alternatives...

**Comment by mgp25** [comment]
Duplicate. You can stick to one of the closed ones. We still reading closed issues too.
