### ISSUE TITLE
Is there a way to change the phone number?

### ISSUE THREAD

**Issue by shyper** [mgp25/WhatsAPI-Official#261]
Hi,
is there a way to change the phone number? The official client has that kind of feature, so it would be nice, to implement that into WhatsAPI, too. Maybe it's possible at the moment, but i could not find any function for it.

**Comment by karam89** [comment]
Simply request an authentication code using your new number, then register the code.

**Comment by mgp25** [comment]
@shyper Yes, working on that. I'll implement that soon.

Regards

**Comment by mgp25** [comment]
@shyper I recently added that feature! Now you can do it. The function is called `sendChangeNumber`. You can see it here: https://github.com/mgp25/WhatsAPI-Official/commit/b48e0331edac6676ef3f6fbd0960952c83c74211

```php
$w->sendChangeNumber($number, $identity);
```

Explanation of usage in the wiki: https://github.com/mgp25/WhatsAPI-Official/wiki/WhatsAPI-Documentation#migrate-your-number-to-a-new-one

Regards
