### ISSUE TITLE
Late in the Recipient (Blue Ticks) 

### ISSUE THREAD

**Issue by phpjoker** [mgp25/WhatsAPI-Official#262]
Hi, i have 2 API on my server, but one of them late to the Recipient (Blue Ticks), It's might 1 to 3 minutes but another not this problem.

**Comment by mgp25** [comment]
@phpjoker are you using this one? If you are using it, it automatically send autoReceipt.

Keep your script like this and give a try:

```php
while(1){
$w->pollMessage();
}
```
