### ISSUE TITLE
problem show empty page

### ISSUE THREAD

**Issue by ahmedashraf** [mgp25/WhatsAPI-Official#263]
problem show empty page?

```php
$w = new WhatsProt($username, $identity, $nickname, $debug);
$events = new MyEvents($w);
$events->setEventsToListenFor($events->activeEvents);
$w->connect();
$w->loginWithPassword($password);
```

I think the problem here `$w->connect();`
Then when I print is not printing

**Comment by robocop249** [comment]
Try enabling error reporting in php.

**Comment by mgp25** [comment]
Set `$debug` to `true`

```php
$debug = true;
```

**Comment by ahmedashraf** [comment]
Enabled : $debug = true;

**Comment by ahmedashraf** [comment]
The same problem

**Comment by 0xTryCatch** [comment]
It sounds like you have a fatal error in your script. Debug to find the cause.

**Comment by ahmedashraf** [comment]
When I delete this line $w->connect();
This shows:
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="*******************">,�)1******************�Y�N��G��)I!yV]U1820574066WhatsApp/2.11.473 Android/4.3 Device/GalaxyS3 MccMnc/602002</auth>

**Comment by ahmedashraf** [comment]
?

**Comment by ahmedashraf** [comment]
???????????

**Comment by ahmedashraf** [comment]
The problem is resolved install the server profile again
