### ISSUE TITLE
Number registration

### ISSUE THREAD

**Issue by farkhad81** [mgp25/WhatsAPI-Official#266]
A quick dummy question: Do I need to have the same simcard in my device when I request a registration code?

**Comment by nephilim1973** [comment]
I guess, it is only important, that you could receive SMS messages or telephone calls. So, the simcard has to be placed into a device, which ensures this.

**Comment by mgp25** [comment]
@farkhad81 If you are using a virtual phone number, you dont need to. If you are using the number of the simcard you need to have it in your device in order to receive the code via SMS or voice call.

Regards
