### ISSUE TITLE
#109 . same number receiving message in .NET

### ISSUE THREAD

**Issue by Abtab** [mgp25/WhatsAPI-Official#268]
Hi

I have tested  number with PHP and receiving encrypted message but when using with .NET i can receive plain text  message with same version, user agent and and token. how its possible?

**Comment by mgp25** [comment]
Becuase you are using a number registered on a device, then the keys used by axolotl where send and stored in WA server, so people can still send you encrypted messages. Register the number again using the API, that would solve it.

Regards

**Comment by Abtab** [comment]
@mgp25 while registering with api i am getting no routes error.

Regards

**Comment by cppvb** [comment]
@mgp25 me too. Any chance you can fix it in WhatsAPINet?

**Comment by mgp25** [comment]
@cppvb once we have finished rewriting this API, i'll update .NET one

Regards
