### ISSUE TITLE
How to get the url of an image?

### ISSUE THREAD

**Issue by clintoncheuk** [mgp25/WhatsAPI-Official#269]
When I set ```$debug=true```, I can find the link. But how can I get the link in PHP?

```xml
rx  <message from="852xxxxxxxx@s.whatsapp.net" id="130651802117238605-4" type="media" t="1420709677" notify="xxx">
rx    <media type="image" caption="Rh" file="Ao34I0uLqhzqHanIatSGfG4dncorlP7icWSZRYcMaUpq.jpg" size="43780" url="https://mmi206.whatsapp.net/d/KKiqGa9EStIZssjhTdLnalSuTy0ABQwgv6imyQ/Ao34I0uLqhzqHanIatSGfG4dncorlP7icWSZRYcMaUpq.jpg" encoding="raw" ip="198.11.217.201" mimetype="image/jpeg" filehash="3Gl6WRQjzLS4mC2VqAKABHHNP1713cMDD1xug/jLRfQ=" width="480" height="720"> 2709 byte data</media>
rx  </message>
```

In ```class ProcessNode``` (Modified from exampleFunctional.php),
I know ```$text = $node->getChild('body')->getData();``` can receive the text message.
I tried ```$url = $node->getChild("media")->getAttribute('url');```, but It do not return anything.
I am using the latest code.
Thanks.

**Comment by jessereitsma** [comment]
Why not use eventManager to bind a function?
`$w->eventManager()->bind("onGetImage", "getImage");`

```
function getImage($mynumber, $from, $id, $type, $time, $name, $size, $url, $file, $mimeType, $fileHash, $width, $height, $preview, $caption) {
  return $url;
}
```

**Comment by mgp25** [comment]
Please check the wiki before opening a new issue:

List of all events: https://github.com/mgp25/WhatsAPI-Official/wiki/WhatsAPI-Documentation#list-of-all-events

How to use events: https://github.com/mgp25/WhatsAPI-Official/wiki/WhatsAPI-Documentation#using-events

**Comment by clintoncheuk** [comment]
Thanks, I will try it later.

**Comment by jessereitsma** [comment]
Maybe this will help: https://github.com/venomous0x/WhatsAPI/issues/588

**Comment by clintoncheuk** [comment]
@mgp25 @jessereitsma thanks
