### ISSUE TITLE
Calling codeRequest fails with 'no_routes' error

### ISSUE THREAD

**Issue by dovfrank** [mgp25/WhatsAPI-Official#270]
Hi,
I used WhatsApi in the past and all was just fine.
Now, I'm trying it again with a new number (new sim card).
I'm using the following code:
```php
$username = "9725832****";//My phone number
$identity = strtolower(urlencode(sha1($username, true)));
$nickname = "My name";
$debug = true;

$w = new WhatsProt($username, $identity, $nickname, $debug);
$w->codeRequest('sms'); 
```
What I get is this error:
```
Array
(
    [in] => 58532****
    [cc] => 972
    [id] => %39%2e%d1%0f%63%37%ca%92%67%8f%26%d6%0f%46%0f%11
    [lg] => he
    [lc] => IL
    [mcc] => 000
    [mnc] => 000
    [sim_mcc] => 425
    [sim_mnc] => 000
    [method] => sms
    [reason] => self-send-jailbroken
    [token] => xVQPurwFPON6dwa%2BEyO4fG%2BmZ2o%3D
    [network_radio_type] => 1
)
stdClass Object
(
    [status] => fail
    [reason] => no_routes
    [retry_after] => 3600
)

Fatal error: Uncaught exception 'Exception' with message 'There was a problem trying to request the code.' in /WhatsAPI/whatsprot.class.php:436
```
Am I doing something wrong or is there a bug?

**Comment by jessereitsma** [comment]
If you search the closed issues you see that there are a lot of issues with a similar problem: https://github.com/mgp25/WhatsAPI-Official/issues?q=no+routes 

If you register you number with the official WhatsApp app (on your iPone, Android, WP, etc) you can easily find the password on your device.
This way, you don't have to register your number via the API which results in the no_routes error.

**Comment by clintoncheuk** [comment]
Try to register the number through vpn like http://superfreevpn.com , I can get the code via this vpn.
