### ISSUE TITLE
How do i send url that clickable to the receiver

### ISSUE THREAD

**Issue by nayaenndu** [mgp25/WhatsAPI-Official#271]
I sent a url to a receiver, but the receiver is unable to click the link, it is going as plain text, 
Please tell me how do i send url which is clickable to the receiver's end.

**Comment by mgp25** [comment]
```php
$w->sendMessage($target, "http://google.es");
$w->sendMessage($target, "www.google.es");
$w->sendMessage($target, "http://www.google.es");
```

All working.

**Comment by nayaenndu** [comment]
Yes the link is submitting but at the receiver end he or she got the link as plain text , not as url or clickable

**Comment by mgp25** [comment]
Its working.

![link](http://cl.ly/image/3L3Q373R3D0c)

**Comment by nayaenndu** [comment]
the number is added to your contact list that is why it is showing just delete the number from contact list and please try again, then you will get the result as text .

**Comment by mgp25** [comment]
You have answered yourself. This is for contacts that have both synced. Not doing spam.
