### ISSUE TITLE
Profile Picture

### ISSUE THREAD

**Issue by faisalcse** [mgp25/WhatsAPI-Official#272]
How can I set profile picture while send message?

**Comment by mgp25** [comment]
Set the profile picture after or before, you can't at the same time.

```php
$w->sendSetProfilePicture($path);
$w->sendSetProfilePicture($url);
```

**Comment by faisalcse** [comment]
what is the recommended size of the profile picture?

**Comment by mgp25** [comment]
Max image size is 640x640, you can set whatever size you want but it must to be square.

Regards
