### ISSUE TITLE
no_routes temporary workaround

### ISSUE THREAD

**Issue by jessereitsma** [mgp25/WhatsAPI-Official#273]
Hello guys,

The last days / weeks I saw a lot of issues about the no_routes error which you get when requesting a verification code via SMS or Voice.
I had the same issue, and after days of research I found a solution which worked for me.
I decided to make a small 'tutorial' about how to get your WhatsApp password.

I've used an iPhone 6 with iOS 8.1.2 (latest version at the moment of writing) 
You have to jailbreak your iPhone, I did it with this tutorial: http://www.iphonehacks.com/2014/12/how-to-jailbreak-ios-8-1-2-taig.html
Which worked perfectly for me. (Less than 10 minutes)

After that is done, you have to install openssh via Cydia.
Now, go to settings on your iPhone and connect to your wi-fi network, if you're connected then click on the network name which should show you some info which includes your iPhone IP address.

On your computer open terminal and connect to that IP adres (like 192.168.1.xx) with username: root and password: alpine (default password) 
Run `cd /` so you're in the root of your iPhone.
run `find -iname pw.dat`
and you should return one line, something like `./private/var/mobile/Containers/Data/Application/xxxxx/Library/pw.dat'
Copy it to /Library (cut /pw.dat off)
And run a new command: cd [paste]
When you run the command `ls` you see a folder `Caches` and a file `pw.dat`
Run `cd Caches/net.whatsapp.Whatsapp`
Run `ls` and you should see several files:
`Cache.db`, `Cache.db-shm`, `Cache.db-wal` and others which aren't important right now.
Delete `Cache.db` (`rm -rf Cache.db`) and `Cache.db-wal` (`rm -rf Cache.db-wal`)
Then restart your WhatsApp app, it should say that you have to verify your phone number.
Now you can register your new (test) phone number with WhatsApp.
After you done that you should get a text message with the code, fill in the verification code and WhatsApp should work with the new number or your phone.

But we want to have it work with the API, right?
@mgp25 has created a python script which downloads pw.dat and the Cache.db-wal file from your iPhone.

**extractPW.py:**
```
# -*- coding: utf-8 -*-
import sqlite3
import paramiko
import os, sys, time

def find_between( s, first, last ):
    try:
        start = s.index( first ) + len( first )
        end = s.index( last, start )
        return s[start:end]
    except ValueError:
        return ""

def getPath(username, host, password):
    dssh = paramiko.SSHClient()
    dssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    dssh.connect(host, username=username, password=password)
    cmd1 = "find /var/mobile/Containers -iname pw.dat"
    print "> "+cmd1
    stdin, stdout, stderr = dssh.exec_command(cmd1)
    res = stdout.read()
    res = res.split("\n")
    print res[0]
    dssh.close()
    return res[0]

def getDB(username, host, password):
    remotePath = "/var/mobile/Containers/Data/Application/" + WAPath[6] + "/Library/Caches/net.whatsapp.WhatsApp/Cache.db-wal"
    pwFile = "/var/mobile/Containers/Data/Application/" + WAPath[6] + "/Library/pw.dat"
    transport = paramiko.Transport((host, 22))
    transport.connect(username = username, password = password)
    sftp = paramiko.SFTPClient.from_transport(transport)
    sftp.get(remotePath, 'Cache.db-wal')
    sftp.get(pwFile, 'pw.dat')
    sftp.close()
    transport.close()
    print "\n\n- Cache.db-wal downloaded!"
    print "- pw.dat downloaded!"

def getData():
    conn = sqlite3.connect('Cache.db-wal')

    cursor = conn.cursor()

    cursor.execute("SELECT request_key FROM cfurl_cache_response")
    request_key = cursor.fetchall()
    request_key = request_key[0]

    cc = find_between(request_key[0], "cc=", "&")
    pn = find_between(request_key[0], "in=", "&")
    id = find_between(request_key[0], "id=", "&")
    lg = find_between(request_key[0], "lg=", "&")
    lc = find_between(request_key[0]+".", "lc=", ".")

    print "cc: "+cc
    print "pn: "+pn
    print "id: "+id
    print "lg: "+lg
    print "lc: "+lc
    print "\nRequest url: "+request_key[0]

    cursor.execute("SELECT receiver_data FROM cfurl_cache_receiver_data")
    receiver_data = cursor.fetchall()
    receiver_data = receiver_data[0]
    status = find_between(str(receiver_data[0]), "status\":\"", "\"")
    login = find_between(str(receiver_data[0]), "login\":\"", "\"")
    pw = find_between(str(receiver_data[0]), "pw\":\"", "\"")
    type = find_between(str(receiver_data[0]), "type\":\"", "\"")
    expiration = find_between(str(receiver_data[0]), "expiration\":", ",")
    kind = find_between(str(receiver_data[0]), "kind\":\"", "\"")

    print "\nstatus: "+status
    print "login: "+login
    print "pw: "+pw
    print "type: "+type
    print "expiration: "+expiration
    print "kind: "+kind

print '''
###########################################
#                                         #
#    WA Password and Identity Extractor   #
#              for iPhone                 #
#                                         #
###########################################

Author: @_mgp25 - github.com/mgp25 - mgp25.com

''' 

if len(sys.argv) < 4:
    sys.exit("Usage: python extractPW.py <username> <host> <password>\n")
time.sleep(2)
username = sys.argv[1]
host = sys.argv[2]
password = sys.argv[3]
WAPath = getPath(username, host, password)
WAPath = WAPath.split("/")
# Get Whatsapp cache ID 
print WAPath[6]
getDB(username, host, password)
print "\n- Extracting data...\n"
getData()
```

Of course all credits for this script goes to @mgp25 :)

Run it like this on your terminal:
`extractPW.py root <iPhone's IP> alpine`

It takes a while to download the files and it could return an error.
You can ignore the error, we have to do manually some work.
On the location of extractPW.py you should see 2 files: `pw.dat` and `Cache.db-wal` 

Open `Cache.db-wal` with your editor and you should see some requests to v.whatsapp.net (`https://v.whatsapp.net/v2/exist?cc=`)

Copy the whole link till the end (`&lc=zz`)
And go to http://requestmaker.com
By Request URL you fill in that URL.
And you should add 4 headers (content-type header which is default filled in can be removed)

Accept-Encoding: gzip
User-Agent: 
Accept-Language:
Accept: */*

I left User-Agent and Accept-Language blank, because that's different on each phone.
In Cache.db-wal you see several requests to v.whatsapp.net
In the file search for `Accept-Encoding`
The first result is something like `#��������#��������ˇˇˇˇˇˇˇˇSGET‘_Accept-EncodingZUser-Agent_Accept-LanguageVAccept]gzip, deflate_0WhatsApp/2.11.14 iPhone_OS/8.1.2 Device/iPhone_6Uen-usS*/*��`
(That was what I did get)

You can see your User Agent here (from WhatsApp to /iPhone_6)
(Not the Uen-usS*/*)
Also the language which stands behind the U and before the S (en-us in my case)
That 2 values (user agent and language) can you fill in with the other headers.

Now, when you click on submit on requestmaker.com you should see a return with something like
`{"status": "ok", "login":"phonenumber", "pw":"YOUR PASSWORD"`

Tada, that's your new WhatsApp password, you can use it with the PHP WhatsApi (`$w->loginWithPassword('your password')`

And that's pretty much it.
If you have Android, I'm sure there is a way to download the Cache.db-wal file from your Android device (pw.dat is not necessary) 

If you have any questions, please contact me by mail: jesse@reitsma.co, Twitter: [@JesseReitsma](https://twitter.com/JesseReitsma) or comment on this issue

Regards,
Jesse

PS: If you see any mistakes I made, please tell me. I will fix it :)

**Comment by nephilim1973** [comment]
Hi jessereitsma, thanks for this workaround.
I just wonder, why "mgp25" always mentioned, that the "no_routes" error in the WhatsAPI is caused by a WhatsApp server side problem and otherwise I can register the same SIM card with yowsup perfectly...

https://github.com/tgalal/yowsup

Here is a "screenshot" of successful registration process:

    $ yowsup-cli registration -m 262 -n 007 -p 491767624xxxx -C 49 -r sms
    
    status: sent
    retry_after: 1805
    length: 6
    method: sms
    
    --> incomming SMS with registration code to my SIM card, success!
    
    $ yowsup-cli registration -d -m 262 -n 007 -p 491767624xxxx -C 49 -R 234-442
    
    status: ok
    kind: free
    pw: ljsG2FggHdSrT4Z8tQ9awI+b164=
    price: 0,89 €
    price_expiration: 1423887354
    currency: EUR
    cost: 0.89
    expiration: 1452347364
    login: 491767624xxxx
    type: new

Works like charm.
So probably, "mgp25" could explain ????

Regards

**Comment by mgp25** [comment]
Its explained in there wiki

Regards

**Comment by jessereitsma** [comment]
I couldn't find anything that works?

**Comment by nephilim1973** [comment]
Why mgp25 has deleted my post ???
