### ISSUE TITLE
onGroupisCreated Fired for several

### ISSUE THREAD

**Issue by phpjoker** [mgp25/WhatsAPI-Official#275]
Hi, sometimes, When exits or removes a participant from group  `onGroupsParticipantsRemove` fired for 5-10 times.
also there is this problem for `onGroupsParticipantsAdd`.

Thanks a lot.

**Comment by mgp25** [comment]
@phpjoker provide PHP code and debug log.

Regards

**Comment by mgp25** [comment]
@phpjoker i just tried it, and its working fine. If you are still facing this issue you can contatc with me via mail, but evrything is working 100% fine :)

Regards
