### ISSUE TITLE
Error retriving Password

### ISSUE THREAD

**Issue by morettolss** [mgp25/WhatsAPI-Official#276]
Hi,

i install bluestack and whatsapp here, send the confirmation code to the smartphone throught the app and try to verify it with exampleRegister.php (i read that the confirmation code is not sent throught php file).

I set for username: CountryCodePhoneNumber
for identity: e807f1fcf82d132f9bb018ca6738a19f
and a nickname.

i comment line: $w->codeRequest('sms');

and insert in the code

$code = 'xxxxxx';
$res = $w->codeRegister($code);
print_r($res);

but i receive this error:

Notice: Undefined property: stdClass::$retry_after in C:\xampp\htdocs\www\whatsapp\WhatsAPI-Official-master\src\whatsprot.class.php on line 289
Array ( [cc] => XX [in] => XXXXX [id] => XXXX [code] => XXX [lg] => ro [lc] => RO [network_radio_type] => 1 ) stdClass Object ( [status] => fail [reason] => missing ) 
Fatal error: Uncaught exception 'Exception' with message 'An error occurred registering the registration code from WhatsApp.' in C:\xampp\htdocs\www\whatsapp\WhatsAPI-Official-master\src\whatsprot.class.php:295 Stack trace: #0 C:\xampp\htdocs\www\whatsapp\WhatsAPI-Official-master\examples\exampleRegister.php(78): WhatsProt->codeRegister('XXXXXX') #1 {main} thrown in C:\xampp\htdocs\www\whatsapp\WhatsAPI-Official-master\src\whatsprot.class.php on line 295

Any solution on how to get the password?

**Comment by CODeRUS** [comment]
you cannot use code requested with other application. request sms using register tool.
