### ISSUE TITLE
stdClass Object ( [status] => fail [reason] => no_routes [retry_after] => 3600 )

### ISSUE THREAD

**Issue by moosaviamir** [mgp25/WhatsAPI-Official#277]
Hi
While using the latest (as far as i could tell) 1.7.2.0 Wart to request a code i've got an error message going like this:
Could not request code using either sms or voice.
```
SMS: {"status":"fail","reason":"no_routes"."retry_after":3600
Voice:{"status":"fail","reason":"no_routes"."retry_after":3600}
```
tried from several computers using several numbers - same error repeats.
this is not my first time or number registering trough wart,usually, if i get into an error it is because my version is not up to date, and right now i can't tell what's wrong ...
please, I would really use of some help
thank you

edit:
even after trying to manually register using api scripts (typing my own mnc and mcc) got the same output
```
stdClass Object ( [status] => fail [reason] => no_routes [retry_after] => 3600 )
```

**Comment by morettolss** [comment]
Please read: https://github.com/mgp25/WhatsAPI-Official/issues/273

**Comment by mgp25** [comment]
This is not WART repo, sorry.

Regards
