### ISSUE TITLE
Correct Connect/reconnect script?

### ISSUE THREAD

**Issue by m-derevyanko** [mgp25/WhatsAPI-Official#278]
I've wrote some program with this API. So, first what im always trying to check in network scripts - connection stability. I did `onClose` handler (and used all other connection-close-events with it). After event is fired i'm just trying to call `$whatsApi->connect();` and after connection all login procedures. So i run the script, all works just fine. Than i've turned off wi-fi on my notebook and start watching. onClose event (and either close-connection-events) didn't hurry to fire. I've been waiting for 5-7 minutes and turned on wi-fe again. Wow, almost recently `onClose` was fired and it looks just fine, BUT `$whatsApi->connect()` didn't return my cdript online in whatsapp. 

By the way, after connection success i do this. It keeps nofiring 
```php
$this->getApi()->eventManager()->bind('onConnect', \Closure::bind(function( $mynumber, $socket ) {
            $this->getApi()->loginWithPassword($this->getPassword());
        }, $this, $this));

        $this->getApi()->eventManager()->bind('onLogin', \Closure::bind(function( $mynumber ){

            $this->setOnline(true);

            $this->getApi()->sendGetServerProperties(); // Obtenemos las propiedades del servidor
            $this->getApi()->sendClientConfig();
        }, $this, $this));
```

So, my question is, how shud i reconnect the script after connection crashes? Thanx

**Comment by m-derevyanko** [comment]
By the way, after connection success i do this. It keeps nofiring 

$this->getApi()->eventManager()->bind('onConnect', \Closure::bind(function( $mynumber, $socket ) {
            $this->getApi()->loginWithPassword($this->getPassword());
        }, $this, $this));

        $this->getApi()->eventManager()->bind('onLogin', \Closure::bind(function( $mynumber ){

            $this->setOnline(true);

            $this->getApi()->sendGetServerProperties(); // Obtenemos las propiedades del servidor
            $this->getApi()->sendClientConfig();
        }, $this, $this));

**Comment by mgp25** [comment]
```php
while (1) 
{
if (!$w->isConnected())
{
           $w->connect();
           $w->loginWithPassword("s0naTO4R1N8sfjbSg5nveDm1uUc=");
}
// More stuff
}
```

**Comment by m-derevyanko** [comment]
Its not working. Check by yourself, there is no onClose event, there is no false on osConnect at any moment

**Comment by mgp25** [comment]
@m-derevyanko i didn't try onClose nor onConnect, im just telling you that use this code instead:

```php
$w->isConnected()
```

That check wether the user is connected or not. When we finish with axolotl implementation we will rewrite the API and do a major improvement of this stuff.

Regards
