### ISSUE TITLE
How to distinguish error messages

### ISSUE THREAD

**Issue by maikeldus** [mgp25/WhatsAPI-Official#279]
So I use and lastSeen call for two Whatsapp users, and one of them has the privacy option on which means that `onError` is called instead of `onLastSeenRecieve`.

The dataset at the function onError is:
```php
$mynumber,
$id, //    (in the format: lastseen- (epoch time) -1 (random code?)
$data //(in the format: error code 405 and text: not-allowed)
```

But there is no way to retrieve the actual phone number which caused the call of `onError`? How can I distinguish the whatsapp users by having their privacy option enabled?

**Comment by mgp25** [comment]
Fixed: https://github.com/mgp25/WhatsAPI-Official/commit/740d3ac71e6b8d981d6f028e238f6028bcf724de

Regards
