### ISSUE TITLE
no-routes error " [status] => fail [reason] => no_routes [retry_after] => 3600"

### ISSUE THREAD

**Issue by ajay1989** [mgp25/WhatsAPI-Official#280]
I am getting no_routes error from today . i dont know whether whatsapp has changed its registration routine or not because the same code was working fine till 10th jan .. 
Please resolve this no-routes error .. i have even tried to run exampleRegister.php in multiple server but still i am facing same no_routes problem

**Comment by mgp25** [comment]
@ajay1989 This is a duplicate issue, you can search the closed ones for more info.

If you want contact me via email and i can explain you.

Regards
