### ISSUE TITLE
networkinfo.csv Header

### ISSUE THREAD

**Issue by archergod** [mgp25/WhatsAPI-Official#281]
can I have header for all column in `networkinfo.csv` file please. thanks.

**Comment by mgp25** [comment]
@archergod what do you mean by header

**Comment by archergod** [comment]
Well, I cannot make what column is what, 

for this first line


289	649	088	2191	ab	Abkhazia	7	A-Mobile

what is 289, 649? etc .. basically first four columns are not clear.

PS: BTW I know PHP and saw you need some help from php developer, if I can be of any use.

**Comment by mgp25** [comment]
mcc \ not required \ mnc \ not required \ lg \ Country \ Country Code \ Carrier

Regards

**Comment by archergod** [comment]
thanks.
