### ISSUE TITLE
Registration fail: no_routes

### ISSUE THREAD

**Issue by AlvaroOlivencia** [mgp25/WhatsAPI-Official#282]
Last weeks many have reported this (I'm having the same issue), could you please explain us what's failing ? I'm using the registerTool.php

Thanks !

**Comment by Bahrain2000** [comment]
There is a bad situation.
All this for money.

**Comment by mgp25** [comment]
WhatsApp is banning people that are doing many requests from the same IP, so the result of that is the `no_routes`. For example, i try with my number in home and gives `no_routes`, but in my university works fine.

Thats the explanation. It's an IP issue, thats way sometimes works and sometimes doesn't.

If you have any other question, let me know.

Regards

**Comment by jessereitsma** [comment]
How come that on a clean IP i didn't get it worked? I get the same no_routes error on an IP address which is never used for WhatsApp or WhatsApi..

**Comment by dopeamon** [comment]
With all due respect to @mgp25, we will be coming up with a solution soon..stay tuned!

**Comment by AlvaroOlivencia** [comment]
Ok... I'll try again today (my IP is dynamic, I get a new each 12 hrs) and let you know.... I tried it yesterday like 4 times always failing, but I only realized about *no_routes* error on the last one so I cannot judge what was the reason why failed previously.

**Comment by robocop249** [comment]
@mgp: With a 'non-clean' ip you can request a code through the normal app.
Through WhatsApi it does not work.

**Comment by jessereitsma** [comment]
@robocop249 indeed, so what's the different between the normal WhatsApp and the WhatsApi? 
If there is any, why not implement this in WhatsApi? Then it isn't a WhatsApp server issue what @mgp25 say all the time. But something that's not implemented in WhatsApi (yet)

**Comment by robocop249** [comment]
Why do you keep deleting the discussions, mgp? Whats the problem?
________________________________
Von: Jesse<mailto:notifications@github.com>
Gesendet: ‎13.‎01.‎2015 14:23
An: mgp25/WhatsAPI-Official<mailto:WhatsAPI-Official@noreply.github.com>
Cc: robocop249<mailto:robocop249@outlook.com>
Betreff: Re: [WhatsAPI-Official] Registration fail: no_routes (#282)

@robocop249 indeed, so what's the different between the normal WhatsApp and the WhatsApi?
If there is any, why not implement this in WhatsApi? Then it isn't a WhatsApp server issue what @mgp25 say all the time. But something that's not implemented in WhatsApi (yet)

---

**Comment by jessereitsma** [comment]
+1 @robocop249

**Comment by robocop249** [comment]
Again, why do you keep deleting comments?

**Comment by robocop249** [comment]
We are trying to solve an issue here and what you say is just wrong!
It is not (only) ip related.
It is the combination of ip & tokens used here, of that I am sure.
So you could have said "Maybe it is solved when we have encryption solved and can use the exact same token as the app again".

Again, if I get a no routes error and I use the same number from the same ip via WLAN e.g. there is no error. Same ip, using same number via WhatsApi there is the error.

So the answer should be:

"WhatsApp is banning people using WhatsApi that are doing many requests from the same IP, so the result of that is the no_routes."
