### ISSUE TITLE
Remove broadcast list?

### ISSUE THREAD

**Issue by domingopa** [mgp25/WhatsAPI-Official#285]
Hello, is there any function to delete list of broadcast? or to remove / add a contact from a list?

Thanks for helping

**Comment by 0xTryCatch** [comment]
Take a look at sendDeleteBroadcastLists()

Adding and removing contacts is done on the phone, not on the WA server

**Comment by CODeRUS** [comment]
on server broadcast list are updated only when you sending message.

**Comment by domingopa** [comment]
thank you very much
