### ISSUE TITLE
Cant get group ID

### ISSUE THREAD

**Issue by ashtm** [mgp25/WhatsAPI-Official#286]
Hello, Whatsapi is working good but I dont know how to send messages to group. I can create group but sending messages require group id. Where can I get group id. If i create a group i get bunch of texts as result like:

```xml
tx  <iq id="creategroup-xxxxxxx-1" type="set" xmlns="w:g" to="g.us">
tx    <group action="create" subject="JJ"></group>
tx  </iq>
```

how can i extract group id from the result? :)

**Comment by mgp25** [comment]
@ashtm You need to use `onGroupCreate`event to capture that data.

```php
onGroupCreate( $mynumber, $groupId )
```

There is an explanation in the wiki. Using events: https://github.com/mgp25/WhatsAPI-Official/wiki/WhatsAPI-Documentation#using-events
