### ISSUE TITLE
Not sending to iPhone 

### ISSUE THREAD

**Issue by cooler-farmer** [mgp25/WhatsAPI-Official#287]
The messages I sent got received on Android phones, but not on iPhones. I'm using whatsapi net

**Comment by cooler-farmer** [comment]
I'll post more details when I'm home.

**Comment by CODeRUS** [comment]
whatsapi net and posting here? really?

**Comment by cooler-farmer** [comment]
On whatsapi net is jo issue tab

**Comment by mgp25** [comment]
@cooler-farmer https://github.com/perezdidac/WhatsAPINet

Regards
