### ISSUE TITLE
Text Message not received

### ISSUE THREAD

**Issue by enzolarosa** [mgp25/WhatsAPI-Official#289]
Hello i don't receive text message

debug resutl

```xml


rx  <message from="393897953142@s.whatsapp.net" id="1421426308-45" retry="1" offline="1" type="text" t="1421428373" notify="Vincenzo">
rx    <enc v="1" type="pkmsg" av="Android/2.11.476">3è”ä!¨'¿$MLˆœ â&¬ïíR¤DÆDÂé²™¯Ê—‹-!¡puÉW¹6©æc§›ÒÙ `‡=š¶g—š±üI^ÎÏv"B3 !NV»¿&¨G8P×@dH”ÂÞÃçêÕ‡5Ÿºz*o°@ "{a!— ¬¸öbý4¢(ËÑfK(ÂÜÃ 0</enc>
rx  </message>

```

how i can resolve?

**Comment by CODeRUS** [comment]
You can read this: https://github.com/mgp25/WhatsAPI-Official/issues/109

**Comment by enzolarosa** [comment]
problem born from one minute to another without my having touched the code ... up to me ?? I've already read that ticket but can not find a solution

**Comment by CODeRUS** [comment]
Because there are no solution

**Comment by enzolarosa** [comment]
Should I change the number? or try to redo the recording of the account? or I have to keep everything well? :(

**Comment by mgp25** [comment]
@enzolarosa its because whatsapp encryption. Delete account, register it again and only use it with the API, if you are still facing this issue, use another number or wait until we bring libaxolotl to php

regards

**Comment by enzolarosa** [comment]
by bees as I can elimanre account?

proceed directly with the new recording?
