### ISSUE TITLE
bad_parms

### ISSUE THREAD

**Issue by kareem289** [mgp25/WhatsAPI-Official#290]
i got a new error response when i register by  registerTool.php
when register with american number ,

tis is the output 

-----------------------------------
```
Username (country code + number without + or 00): ***

Nickname: Mohammed

Carrier:


Type sms or voice: voice
Array
(
    [in] => ***
    [cc] => 1
    [id] => v∙x╟╓♣كّ≈7;zزُ:'╔h
    [lg] => en
    [lc] => US
    [mcc] => 000
    [mnc] => 000
    [sim_mcc] => 310
    [sim_mnc] => 150
    [method] => voice
    [reason] => self-send-jailbroken
    [token] => 56b9943c2924709d9ddddb7768e6f3bd
    [network_radio_type] => 1
)
stdClass Object
(
    [status] => fail
    [reason] => bad_param
    [param] => number
)
There was a problem trying to request the code.
```
-------------------------------------------

but if i put my number or any number i know , it's worked fine 
that's done only today , it all past week like a charm 
please help with this new issue

**Comment by CODeRUS** [comment]
You didn't selected carrier

**Comment by mgp25** [comment]
@kareem289 that error is caused because massive registrations.
