### ISSUE TITLE
Contact sync necessary before sending each broadcast

### ISSUE THREAD

**Issue by phpcoder345** [mgp25/WhatsAPI-Official#291]
Hi
I have a database of users that I send Broadcast to. These are people that have sent me messages and thus "had" me as their contact at some point in time. 

Now, do I need to do a contact sync each time I broadcast to them ? While doing that, I am getting the back off error and thus wonder if its needed.

**Comment by CODeRUS** [comment]
you need to sync each contact once

**Comment by mgp25** [comment]
@phpcoder345 You need to sync contact once each login.

More info in the wiki: https://github.com/mgp25/WhatsAPI-Official/wiki

**Comment by CODeRUS** [comment]
@mgp25 each login? are you crazy man? :D
