### ISSUE TITLE
What does pollMessage() actually do?

### ISSUE THREAD

**Issue by maikeldus** [mgp25/WhatsAPI-Official#292]
So i'm listening for a big set of Events (eg. `PresenceSubscription`) and because this all happens async the behaviour of my script is rather strange.

I have the following code at the end of my script:
```php
while(true) {
        $wa->pollMessage();
	sleep(1);
}
```
It waits for any changes of the state of a user. However, when i use sleep(60..20..10..5) it does not always detect the change (even if the user is 2 times the time online as the sleep delay). This ofcourse gives some very unsatisfying results (very inaccurate data). I tried the while(true) loop without any sleep() but here it got even stranger. This somehow delayed to loop to 1 second, but after a while it would go superfast (100% cpu usage, like I expect it to run).

Anyway, i've looked at the sourcecode and the pollMessage only seems to look at the incoming socket, thus not sending any extra requests to the whatsapp server. Is my idea of this setup correct? I can live with a timer of one second, but I don't want to be banned for spamming the whatsapp server.

Any thoughts on this?

**Comment by mgp25** [comment]
@maikeldus You should use it without the `sleep(x);`

```php
while(true) {
        $wa->pollMessage();
       // more stuff
}
```

And you are correct, it doesn't send any extra request, only queue messages and look incoming data. The most correct way will be like calling always `pollMessage` in background but in php multithread is not supported, i know there is pthread but i didn't try it yet, thats why we use the `while(1)` loop.

If you have any other doubt let me know :)

Regards

**Comment by maikeldus** [comment]
Thanks for your fast response mpg! 

But I'm still having some doubts about the while loop without any sleep. I've run my PHP script in the command line overnight. At first it does one loop per second, but after a while the while loop goes full speed (which causes 100% CPU usage of one core). Ofcourse 100% CPU usage isn't really desired either.

I'm not sure what is causing this, it's looks like the pollMessage has an 1 second delay in it? But it looks only this is the case if there is nothing to read from the socket (not sure btw, the behaviour is very inconsistant).

**Comment by mgp25** [comment]
@maikeldus i'll check it, i have never experienced that.
