### ISSUE TITLE
Error during Broadcast

### ISSUE THREAD

**Issue by phpcoder345** [mgp25/WhatsAPI-Official#293]
I get the following error at times. Not sure if this happening earlier. Any ideas  

```
Fatal error: Uncaught exception 'Exception' with message 'Tree length did not match received length (buff = 122 & treeLength = 324)'

Stack trace:
#0 .../whatsprot.class.php(583): WhatsProt->readStanza()
#1 ../index.php(45): WhatsProt->pollMessage()
```

**Comment by mgp25** [comment]
@phpcoder345 Post debug and code.

**Comment by phpcoder345** [comment]
@mgp25  : I will get the code now. Not sure how to capture the debug :-(

**Comment by mgp25** [comment]
@phpcoder345 

```php
$debug = true;
```

Run your script in terminal/command line if possible, and post the output.

**Comment by mgp25** [comment]
@phpcoder345 It's working i just try it. Use latest WhatsAPI Official code
