### ISSUE TITLE
Sending massive messages that is not spam

### ISSUE THREAD

**Issue by alexmaie** [mgp25/WhatsAPI-Official#295]
Hello,

Before killing this question, let me explain the use case. We have a client that wants to easily confirm his appointments with the patients. Before actually sending out appointment confirmations, we would ask the user if he wants to get this service.   I have read this page http://www.whatsapp.com/legal/ , but couldn't find anything that would state that this is a violation of terms.

Am I on the safe side here?

**Comment by mgp25** [comment]
Sending massive messages is a system abuse, and thats against WhatsApp EULA, we don't support massive messages too.

Sending massive messages is considered spam for WhatsApp. And sending messages to semi-random users will cause a block of your number.

Regards

**Comment by alexmaie** [comment]
Hi,

Thanks for the answer and quick abuse confirmation :)

Cheers
