### ISSUE TITLE
unusual message

### ISSUE THREAD

**Issue by iffifan** [mgp25/WhatsAPI-Official#296]
normally i get this when a new text message is received:
```
<message from="*****@s.whatsapp.net" id="1421661740-10" type="text" t="1421666457"   notify="NAME">
 rx    <body>Gdg</body>
 rx  </message>
```

but today I got this on one particular number when i sent a message:

```
rx  <message from="******@s.whatsapp.net" id="1421661740-9" type="text" t="1421666434" notify="NAME">
rx    <enc v="1" type="pkmsg" av="Android/2.11.498">3ºÛÝ!Rë?œäòšåH'M€Ë}E&„rr‡U³™–?¯°!*,N‡¬E•oYÂë›õ6¯·Uã«ÁÒz	HaE"B3
!iÀïÞ‡B,˜ö ƒÃ¹×^”¾Ë[lÛ§÷˜IJ~"pW}ïÜüº<0àÂèâÿÆõ_°ŸlÈÏ¢(ÏÉÁm0</enc>
rx  </message>
```

after message is sent it does not reply with receipt also it output this :
```
rx  <stream:error>
rx    <ack></ack>
rx  </stream:error
```

and sign out.

**Comment by CODeRUS** [comment]
Read this: https://github.com/mgp25/WhatsAPI-Official/issues/109

**Comment by mgp25** [comment]
@iffifan if you download latest code, the disconnection issue because of encrypted messages is fixed. You still receiving encrypted messages but it won't disconnect.
