### ISSUE TITLE
Ability to avoid using file to store identity.

### ISSUE THREAD

**Issue by ivanbaldo** [mgp25/WhatsAPI-Official#298]
It should be possible somehow to avoid using the .dat file to store the identity.
A base64 or urlencoded string should suffice and the property should be made public or have a getter.
What do you think?

BTW I don't understand the `checkIdentity()` method, it most certainly will return false always, what I am missing? :-/

Thanks!

**Comment by ivanbaldo** [comment]
BTW I don't understand the checkIdentity() method, it most certainly will return false always, what I am missing? :-/

**Comment by mgp25** [comment]
`checkIdentity()` checks if the identity has 16 bytes (old format) or 20 bytes (new format). The identity stored in the `.dat` file its urlencoded. So check identity only urldecode it and check if is 16 or 20 bytes, otherwhise its a bad identity.

```php
    protected function checkIdentity($identity)
    {
    	if (file_exists($identity.".dat"))
		  {
        $id = urldecode(file_get_contents($identity.'.dat'));
        if (($id == 20) || ($id == 16))
        {
          return true;
        }
    	}
    	else
    	{
    		return false;
    	}
    }
```

The reason we are storing identity in a file its because this is more secure generation way, its better to the user (privacy-security). We generate 20 random bytes using:

```php
$bytes = openssl_random_pseudo_bytes(20);
```

When you set `$identity = "something";`, a file called `something.dat` will be generated storing the identiy.

If you have any doubt, tell me.

Regards

**Comment by ivanbaldo** [comment]
Isn't there a bug in that code?, because I don't see any strlen(), so I think it always returns false as I said above.
But the API user should be able for example to store it in a database instead of a file, of course thats my opinion only...
Both methods (check and build identity) are simple and I could override them, but I cannot override the constructor because its a bit more complex and will certainly change in the future and maintaining it in sync with your version will hurt :-(.
Did I convince you? :-)
If yes then I could try to implement it and do a pull request so you can review it and apply when you think is good.
Let me know!
Thanks a lot for your time!!!

**Comment by mgp25** [comment]
@ivanbaldo yes, you are right, im going to fix it now :) and i agree with you that its better to store it in a database, but we are going to do that once we hace libaxolotl php working fine with the API.

Regards and thanks for telling me the error.

Regards

**Comment by mgp25** [comment]
@ivanbaldo fixed https://github.com/mgp25/WhatsAPI-Official/commit/a69ad8d1834c30bd41ca2cc373771cf044584b56

**Comment by ivanbaldo** [comment]
Excellent!!! Thanks a lot!
I will try to implement a way to detect if it is a file or the data directly so we can satisfy both ways of using it, maybe wednesday but not promises :-).
Thanks again!!!

**Comment by mgp25** [comment]
@ivanbaldo Updated: https://github.com/mgp25/WhatsAPI-Official/commit/cd9d1b4b56ffa7e1e01cdb8db48b6967796accbc

Thanks
