### ISSUE TITLE
Upon confirmation code appears mismatch error

### ISSUE THREAD

**Issue by allaga** [mgp25/WhatsAPI-Official#299]
Hello!
```
Array
(
    [cc] => 79
    [in] => ***
    [id] => g╖╦gОх&lt;Г*▒:▐_xieп1
    [code] => ######
    [lg] => ru
    [lc] => RU
    [network_radio_type] => 1
)

stdClass Object
(
    [status] => fail
    [reason] => too_many_guesses
    [retry_after] => 86432
)
```
```
Fatal error: Uncaught exception 'Exception' with message 'An error occurred registering the registration code from WhatsApp.' in C:\OpenServer\domains\localhost\src\whatsprot.class.php on line 295

Exception: An error occurred registering the registration code from WhatsApp. in C:\OpenServer\domains\localhost\src\whatsprot.class.php on line 295
```

p.s. my phone number 7968******* (Beeline, Russia)

p.s.s. Prior to that, to another phone number (+796*******, Beeline, Russia) successfully generate passwords

**Comment by mgp25** [comment]
@allaga this `too_many_guesses` is caused when you tried many times to request sms code and voice code to the same number.

Now you have to wait to the `retry_after`. In your case `86432` seconds = 24 hours (1 day), and then you can try to request code again. But if you try with other number will work.

If you have any doubt tell me.

Regards

**Comment by CODeRUS** [comment]
just one thing: too_many_guesses means you tried to register with wrong confirmation code. when you trying to request code too much you will receive too_many

**Comment by mgp25** [comment]
@allaga @CODeRUS is right, i was thinking about `too_many_all_methods` :smile:

**Comment by allaga** [comment]
I have entered the correct code, which came via SMS, this is what I made for myself ######

**Comment by mgp25** [comment]
@allaga If you received 123-456, you should do:

```php
$w->codeRegister('123456');e 
```

Make sure the identity you used to request the code its the same as the registration. Update your code, yesterday we pushed a bug fix for `checkIdentity()`.

Regards

**Comment by allaga** [comment]
Did exactly the same, but did not succeed. Then registered another phone number, turned out.
