### ISSUE TITLE
Failed to read stanza header

### ISSUE THREAD

**Issue by phpjoker** [mgp25/WhatsAPI-Official#301]
I get this error for times.
Failed to read stanza header
```
Tree length did not match received length (buff = 5837 & treeLength = 6875)
Tree length did not match received length (buff = 4013 & treeLength = 6626)
```
Please guide me for this.
Thanks a lot

**Comment by 0xTryCatch** [comment]
Are you using the latest version of WhatsAPI? Is it happening when syncing contacts or during what other action?

**Comment by mgp25** [comment]
Related to #293 

That was patched and its working. Download latest WhatsAPI Official code.

**Comment by phpjoker** [comment]
I use latest WhatsAPI Official code.

**Comment by mgp25** [comment]
@phpjoker provide debug and the code you are using then.

**Comment by phpjoker** [comment]
my debug is very big
email or put here?

**Comment by mgp25** [comment]
@phpjoker here and your script code too

**Comment by 0xTryCatch** [comment]
I think it is related to a bad internet connection where not all data can be received in time. Also:

    Failed to read stanza header

and

    Tree length did not match received length ...

are two different errors and occur only when not all data was read.

**Comment by phpjoker** [comment]
My API is member in 500 group with 20000 participants.
is it related to or not!?

**Comment by mgp25** [comment]
@phpjoker yes, and that is considered spam too.

**Comment by phpjoker** [comment]
No any spam.
It's only a server for educational context.

**Comment by mgp25** [comment]
@phpjoker then try do delete un-used groups and participants. That is caused when a lot of data has to be processed

**Comment by phpjoker** [comment]
My server have 128 GB ram and 2 xeon 2.1 and 2TB SCSi HDD
Could not enough?

**Comment by mgp25** [comment]
@phpjoker its not because of your server, its because the socket and WhatsApp limitations.

Regards

**Comment by phpjoker** [comment]
Is not or no any way to improve it?

**Comment by mgp25** [comment]
@phpjoker maybe, but is not our first priority. Try to remove unused groups.
