### ISSUE TITLE
Register Tool Says self-send-jailbroken

### ISSUE THREAD

**Issue by sisodiakaran** [mgp25/WhatsAPI-Official#303]
got following result:

    Array
    (
        [in] => 0000000000
        [cc] => 91
        [id] => <some hash>
        [lg] => hi
        [lc] => IN
        [mcc] => 000
        [mnc] => 000
        [sim_mcc] => 404
        [sim_mnc] => 011
        [method] => sms
        [reason] => self-send-jailbroken <---- May Be this is problem
        [token] => <some token>
        [network_radio_type] => 1
    )
    stdClass Object
    (
        [status] => fail
        [reason] => no_routes
        [retry_after] => 3600
    )

Am I doing something wrong?

**Comment by mgp25** [comment]
@sisodiakaran you are using an outdated version of WhatsAPI Official. Update and try again.

Regards

**Comment by sisodiakaran** [comment]
@mgp25 thanks for quick reply. I just cloned https://github.com/mgp25/WhatsAPI-Official.git but same issue.

**Comment by mgp25** [comment]
@sisodiakaran `no_routes` error its caused when WhatsApp can`t connect with your mobile operator, if you are using a virtual number its likely that this error will appear.

Also `no_routes` its caused when doing massive registrations. WhatsApp bans your IP and when trying to register will show that.

**Comment by mgp25** [comment]
@sisodiakaran I was my fault with yesterday commit. I just fix it: https://github.com/mgp25/WhatsAPI-Official/commit/f70917d770ca5dc0c9927972b3ad5469d54a3bad

Regards
