### ISSUE TITLE
whatsapi time

### ISSUE THREAD

**Issue by allaga** [mgp25/WhatsAPI-Official#304]
Hi!

Time for Russia is not displayed properly

Departure time visitors to Russia is wrong. We now have the winter. If I send a message at 19:00, then the time will be 18:00.

**Comment by mgp25** [comment]
@allaga try to write in a language everybody knows, at least i dont know russian, i had to change the name issue.

And thats its not a WhatsAPI feature. You can change timezone using php.

http://php.net/manual/en/function.date-default-timezone-set.php
