### ISSUE TITLE
Whatsapp Web launched

### ISSUE THREAD

**Issue by blaazetech** [mgp25/WhatsAPI-Official#306]
Visit, http://web.whatsapp.com/ scan your code with latest version of whatsapp on your phone, please note your phone need to be in sync for this to work, also, am thinking of this can be much more easier to build a wrapper API around it.

@mgp25 reach me out, lets build something for this atleast, its been many days we are stuck here without the luck with decryption of messages.

**Comment by CODeRUS** [comment]
What is your question regarding this project exactly?

**Comment by blaazetech** [comment]
My point is very simple, as we couldn't get hold of encryption and
decryption of messages, it will be easier for us to just make this web
version of what'sapp as api and use it for existing numbers.

**Comment by mgp25** [comment]
@blaazetech Messages are being sent thorught the device not through the web client. So libaxolotl is still required.
