### ISSUE TITLE
Status: are you able to connect/send/rcv?

### ISSUE THREAD

**Issue by RVN-BR** [mgp25/WhatsAPI-Official#309]
as of today we are apparently blocked for 24h on all accts with the API. Is anyone being able to access?

#301 is a similar issue but was locked before any healthy discussion could be established. Id urge this not be locked prematurely.

**Comment by RVN-BR** [comment]
Ops, #305 i meant

**Comment by mgp25** [comment]
@RVN-BR Only spammers are blocked. Im using it like always.

**Comment by domingopa** [comment]
@RVN-BR I'm not locked. everything ok

**Comment by RVN-BR** [comment]
Its back working... Very weird... We are mostly receiving so no bulk sending/random sending...

**Comment by mgp25** [comment]
@RVN-BR WhatsApp can detect us in many ways, the API mimic mostly the official client but not all. If you are not a spammer then dont need to worry nothing about

**Comment by RVN-BR** [comment]
I understand and mostly agree, my only worry is since their announcement of yesterday (and action) to block all non-official clients like Whatsapp+, dont you think they would do that (block) arbitrarily to all api clients?
