### ISSUE TITLE
Alternative for socket_select()

### ISSUE THREAD

**Issue by M3nn0123** [mgp25/WhatsAPI-Official#310]
Hey,

I am getting this error when I use `pollMessage()` (or even when logging in):

`Warning: socket_select()`: You must recompile PHP with a larger value of `FD_SETSIZE`. It is set to `1024`, but you have descriptors numbered at least as high as `1676`. `--enable-fd-setsize=2048` is recommended, but you may want to set it to equal the maximum number of open files supported by your system, in order to avoid seeing this error again at a later date. 

This is on line `621` in `whatsprot.class.php`
I know it is only on a specific webserver because I tried it somewhere else and it works there.
So my question is, is there any alternative for `socket_select()` because I really want to use it on this server.

Thanks

**Comment by DeeZone** [comment]
This question appears to be more about your server configuration than about the `WhatsAPI-Official` library. Even the question about an alternative to `socket_select()` is a PHP question. I suspect you'll have more luck looking for support in those specific communities.

In short, I suspect you'll make the most progress by reconfiguring your server:
http://serverfault.com/questions/48717/practical-maximum-open-file-descriptors-ulimit-n-for-a-high-volume-system
