### ISSUE TITLE
Sending Image Fails

### ISSUE THREAD

**Issue by Silikowski** [mgp25/WhatsAPI-Official#313]
I am trying to send an image using the API (/examples/whatsapp.php). No image appears at the mobile device.

Without message text, nothing arrives. If i add some text, the text arrives, the image not.

Are there any restrictions? Imagesize ore something else?

Also tried
```php
$target = '***';
$pathToImg = "http://path/to/2image.jpg"; 
$w->sendMessageImage($target, $pathToImg);
```
same result. contact is online, offline again, no message/image.

is there a way to debug this?

**Comment by mgp25** [comment]
If you want to see debug set `$debug = true;`

You can make your own script like this:

```php
<?php

require_once('/src/whatsprot.class.php');

$debug = false;

$username = '';               
$identity = 'identity';
$password = '';

$nickname = 'Test';

$w = new WhatsProt($username, $identity, $nickname, $debug);

$w->connect();

$w->loginWithPassword($password);


$target = '';
$pathToImg = "http://path/to/2image.jpg"; 
$w->sendMessageImage($target, $pathToImg);


$w->pollMessage();
$w->pollMessage();

$w->disconnect();
```

I recommend you reading the wiki: https://github.com/mgp25/WhatsAPI-Official/wiki

**Comment by Silikowski** [comment]
Strange things happen.
This script worked well.

THX!
