### ISSUE TITLE
sendGetGroupsParticipants - bad request

### ISSUE THREAD

**Issue by kazhual** [mgp25/WhatsAPI-Official#314]
When using `sendGetGroups` the sockets retrieves all groups including the participants. The event `onGetGroups` only gets the Groups, participant are not provided ofcourse.

The function `SendGetGroupsParticipants()` fails to load the group list:
```php
  $w->sendGetGroups();
  $w->sendGetGroupsParticipants('31610366951-1392569237');
```
```xml
tx  <iq id="getgroupparticipants-1422003852-2" type="get" xmlns="w:g2" to="31610366951-1392569237@g.us">
tx    <groups></groups>
tx  </iq>


rx  <iq from="31610366951-1392569237@g.us" id="getgroupparticipants-1422003852-2" type="error">
rx    <error code="400" text="bad-request"></error>
rx  </iq>
```

I tried changing some Node values, but with no luck

Full Log: http://pastebin.com/CByWJdNC

Is there any way i can monitor it live, like a proxy?

**Comment by clintoncheuk** [comment]
Maybe you can try ```$w->sendGetGroups();```?

**Comment by kazhual** [comment]
Thats what i did, but the evenlisteren is only providing the groups. ( upper part of image ).
Changing the main class for this could be an option but i prefer to find the solution.

**Comment by mgp25** [comment]
`sendGetGroupV2Info($gjid)

**Comment by 0xTryCatch** [comment]
tx  <iq id="getgroupparticipants-1422003852-2" type="get" xmlns="w:g2" to="31610366951-1392569237@g.us">
    tx    <groups></groups>
    tx  </iq>

It seems to me this is not a node from WhatsAPI since I cannot find it. Like @mgp25 said, use sendGetGroupV2Info() to get all participants in a group.

**Comment by kazhual** [comment]
the node is from WhatsAPI
https://github.com/mgp25/WhatsAPI-Official/blob/master/src/whatsprot.class.php#L933-947

the function "sendGetGroupV2Info" is sending data but not returning anything

**Comment by mgp25** [comment]
@kazhual post debug

**Comment by kazhual** [comment]
You closed it so i opened a new one:
https://github.com/mgp25/WhatsAPI-Official/issues/315
