### ISSUE TITLE
sendGetGroupV2Info - not waiting for server

### ISSUE THREAD

**Issue by kazhual** [mgp25/WhatsAPI-Official#315]
sendGetGroupV2Info
https://github.com/mgp25/WhatsAPI-Official/blob/master/src/whatsprot.class.php#L901-914

The function is actually sending DATA but not waiting for the server to respond.
This must be added after Line913
$this->waitForServer($msgId);

The following is node "sendGetGroupsParticipants" is not from WhatsAPI?
https://github.com/mgp25/WhatsAPI-Official/issues/314#issuecomment-71169947

If it should not be used ( Fails and deprecated at this moment ) then the following should be removed?
https://github.com/mgp25/WhatsAPI-Official/blob/master/src/whatsprot.class.php#L933-947
https://github.com/mgp25/WhatsAPI-Official/blob/master/src/events/AllEvents.php#L63
https://github.com/mgp25/WhatsAPI-Official/blob/master/src/events/MyEvents.php#L31

**Comment by kazhual** [comment]
Original:
[GetGroups] Loaded GroupsChats
tx  <iq id="get_groupv2_info-1422007869-2" xmlns="w:g2" type="get" to="31610366951-1392569237@g.us">
tx    <query request="interactive"></query>
tx  </iq>


[Disconnect] 31634127635 is disconnected!

With "$this->waitForServer($msgId);"Added to whatsprot.class.php:
[GetGroups] Loaded GroupsChats
tx  <iq id="get_groupv2_info-1422007974-2" xmlns="w:g2" type="get" to="31610366951-1392569237@g.us">
tx    <query request="interactive"></query>
tx  </iq>


rx  <iq from="31610366951-1392569237@g.us" id="get_groupv2_info-1422007974-2" type="result">
rx    <group id="31610366951-1392569237" creator="31610366951@s.whatsapp.net" creation="1392569237" subject="Keepers" s_t="1392569237" s_o="31610366951@s.whatsapp.net">
rx      <participant jid="31655101312@s.whatsapp.net"></participant>
rx      <participant jid="31615481621@s.whatsapp.net"></participant>
rx      <participant jid="31634127635@s.whatsapp.net"></participant>
rx      <participant jid="31610366951@s.whatsapp.net" type="admin"></participant>
rx    </group>
rx  </iq>


31634127635[Disconnect] 31634127635 is disconnected!

**Comment by kazhual** [comment]
Original:
[GetGroups] Loaded GroupsChats
tx  <iq id="get_groupv2_info-1422008015-2" xmlns="w:g2" type="get" to="31610366951-1392569237@g.us">
tx    <query request="interactive"></query>
tx  </iq>


[Disconnect] 31634127635 is disconnected!


With "$this->waitForServer($msgId);" added:
[GetGroups] Loaded GroupsChats
tx  <iq id="get_groupv2_info-1422007974-2" xmlns="w:g2" type="get" to="31610366951-1392569237@g.us">
tx    <query request="interactive"></query>
tx  </iq>


rx  <iq from="31610366951-1392569237@g.us" id="get_groupv2_info-1422007974-2" type="result">
rx    <group id="31610366951-1392569237" creator="31610366951@s.whatsapp.net" creation="1392569237" subject="Keepers" s_t="1392569237" s_o="31610366951@s.whatsapp.net">
rx      <participant jid="31655101312@s.whatsapp.net"></participant>
rx      <participant jid="31615481621@s.whatsapp.net"></participant>
rx      <participant jid="31634127635@s.whatsapp.net"></participant>
rx      <participant jid="31610366951@s.whatsapp.net" type="admin"></participant>
rx    </group>
rx  </iq>


31634127635[Disconnect] 31634127635 is disconnected!

**Comment by mgp25** [comment]
Add `$w->pollMessage();` after that. It wasnt neccessary to open a new issue...
