### ISSUE TITLE
Receiving messages

### ISSUE THREAD

**Issue by moshere** [mgp25/WhatsAPI-Official#316]
Hi,
I'm moving from WhatsAPI4J to the official WhatsAPI and I might have some questions. Thank you for your help.

I would like to listen and read messages and after I read them once not to see them again. I wrote the following code but I keep getting the message again and again.  How can I implement it that after reading the message it won't appear again.

```php
require_once('whatsapp_whatsapi_config.php');

function onGetMessage( $mynumber, $from, $id, $type, $time, $name, $body )
{
    echo "Message from $name:\n$body\n\n";
}

$w = new WhatsProt($userPhone, $userIdentity, $userName, $debug);
$w->Connect();
$w->eventManager()->bind("onGetMessage", "onGetMessage");
$w->LoginWithPassword($password);
$w->pollMessage();
```

**Comment by mgp25** [comment]
Change this:
```php
$w->eventManager()->bind("onGetMessage", "onMessage");
```

I recommend you reading the wiki: https://github.com/mgp25/WhatsAPI-Official/wiki

Regards

**Comment by moshere** [comment]
Hi @mgp25 ,
Thank you.
I implemented the change but still every time I'm calling this it returns me the message and not removing it.
Although I read the Wiki I couldn't find the answerr

**Comment by mgp25** [comment]
@moshere is you are using out code (WhatsAPI Official), that is done automatically.

You can do this:
```php
$w->pollMessage();
$w->pollMessage();
$w->pollMessage();

$w->disconnect();
```

Or a loop polling messages.

**Comment by salehbakir** [comment]
Thank u  how i can downloud whatsapi

**Comment by mgp25** [comment]
@salehbakir https://github.com/mgp25/WhatsAPI-Official/archive/master.zip
