### ISSUE TITLE
Image Received Event for groups

### ISSUE THREAD

**Issue by sisodiakaran** [mgp25/WhatsAPI-Official#317]
Is there any callback for Group Images Received event? Or any way to get Group Received Images/Media?

Thanks in advance...

**Comment by mgp25** [comment]
`    onGetImage( $mynumber, $from, $id, $type, $time, $name, $size, $url, $file, $mimeType, $fileHash, $width, $height, $preview, $caption )`

All the info can be found in the wiki: https://github.com/mgp25/WhatsAPI-Official/wiki

Regards
