### ISSUE TITLE
Registration works only after second time?

### ISSUE THREAD

**Issue by dahansi** [mgp25/WhatsAPI-Official#318]
Hi there,

I'm trying to register a new number.
I get the code by sms. 

If I enter the code and try to register it with `$w->codeRegister('123456');` it won't work. After 30 minutes, when I request the code again, I receive the same code as before, but this time it works.
I tried it with 5 different numbers, everytime it works only the second time.

Do u know what I'm doing wrong?

Thanks!

**Comment by rodrigofaillace** [comment]
at the first moment I comment that line (codeRequest) and did only the request for a code.

when the code arrives I comment the CodeRequest and uncomment and replace the 123456 by the sms I received...

That works for me. Anyway, try using RegisterTool.php.

regards!

**Comment by mgp25** [comment]
@dahansi try registerTool.php, for further support post your debug log.

Regards

**Comment by dahansi** [comment]
Ok, its working fine now.
I did a little script with a POST-Field to register the numbers, so i dont have to comment/uncomment the lines.
It seems that my browser cached the pages and didnt use the right paramters. After setting a timestamp for a GET-Parameter, each time a unique url is opend and it works.

Thanks! :)
