### ISSUE TITLE
Registration not working?

### ISSUE THREAD

**Issue by ChiefHornacek** [mgp25/WhatsAPI-Official#319]
Just running in throubles to register a new number in Whatsapp. The strange thing is that I'm using exactly the facilities you provide in "examples" folder and it is not working!

It is, downloaded the .zip from here, installed on apache, edited `exampleRegister.php`. Just changed the number for a real one (country code 54 for Argentina), set identity to a void string (may it bring problems?) and set a fancy nickname. It looks like:
```php
$username = '54xxxxxx';
$identity = '';
$nickname = 'Nickname';
```

and just left the line to request an SMS  code. 

Navigated to the page using a browser and everything runs ok, in seconds I received a SMS with the validation code. Then, this part that doesn't work.

Just wen to php file, commented out the line to request the code, uncommented the last line to validate the number, set there the code received (without "-", just the 6 numbers) and ran the page again.

I got :  `[status] => fail [reason] => mismatch [retry_after] => 2`

Obviously, I double checked the code sent, and it is ok (common, just six numbers, can't fail with that :) )

How can it fail? May it be related that I didn't set any value at `$identity` var?

If I look at the webfolder, I see that it created a file called ".dat", Since identity is void, the file doesn't have a name, but inside I have an identity value generated by WhatsAPI. Also tried modified the php code and setting in `$identity` the value inside the .dat file, and also created a file "%identity_value_found_in_the_file%.dat", just for testing, and again the same.

Could someone help me with this problem?

By the way, I can provide you the numbers/identity/etc. to test by yourself if you need it.

**Comment by CODeRUS** [comment]
same here? https://github.com/mgp25/WhatsAPI-Official/issues/318

**Comment by ChiefHornacek** [comment]
Exaclty that. Just requested the code again and tried and it worked!

Ok, no second problem. Just went to exampleFunctional.php, set number, password and target number (identity set to void).

When I ran the page got:

Warning: array_key_exists() expects parameter 2 to be array, boolean given in C:\xampp\htdocs\whats\examples\exampleFunctional.php on line 10

Warning: array_key_exists() expects parameter 2 to be array, boolean given in C:\xampp\htdocs\whats\examples\exampleFunctional.php on line 10
[] Logging in as 'Jack Lamota' (541165195349) tx <stream:features>
tx <readreceipts></readreceipts>
tx <groups_v2></groups_v2>
tx <privacy></privacy>
tx <presence></presence>
tx </stream:features>

tx <auth mechanism="WAUTH-2" user="541165195349"></auth>

rx <start from="s.whatsapp.net"></start>

rx <stream:features></stream:features>

rx <challenge>`#.��.��#�s�!|��Q!</challenge>

tx <response>�{���� ��1��A���]݊)Ŭw#‑⋭g%~ 
</response>

rx <failure>
rx <not-authorized></not-authorized>
rx </failure>


Fatal error: Uncaught exception 'Exception' with message 'Login Failure' in C:\xampp\htdocs\whats\src\whatsprot.class.php:2276 Stack trace: #0 C:\xampp\htdocs\whats\src\whatsprot.class.php(603): WhatsProt->doLogin() #1 C:\xampp\htdocs\whats\examples\exampleFunctional.php(70): WhatsProt->loginWithPassword('2GbltWM0SlTfA3g...') #2 {main} thrown in C:\xampp\htdocs\whats\src\whatsprot.class.php on line 2276

I read somewhere that <not-authorized> is returned when WhatsApp consider you an spammer, but in this case it is just a new number and haven't sent any number before.

I have tried previously on another computer, got same error when sending the message, and I thought that my IP was blocked thinking was spamming (since couldn't get it working tried many things and so I thought that may be banned me).

But now, with a new number and a new IP, cannot understand why it is not logging on.

Note: First time I tried to send a message, the target number wasn't in the source's name contact list. It failed and target number added source to its contact list. tried again and got the same error.

Thanks for your advices

**Comment by mgp25** [comment]
@ChiefHornacek you can set the identity name here:

```php
$username = '54xxxxxx';
$identity = 'myIdentity'; // it will create a file called myIdentity.dat
$nickname = 'Nickname';
```

It`s explained in the wiki, i recommend you to read it: https://github.com/mgp25/WhatsAPI-Official/wiki

Use `registerTool.php` to register your numbers.

Sometimes new numbers takes some time to be able to login, so try again later, also it happens when you are using a wrong password.

Regards

**Comment by ChiefHornacek** [comment]
@mgp25 just tried again today, waiting for the number to be approved. Again, I got the password correctly (problem was issue #318) and with the new password tried again. Didn't work. This time the debug dump just wrote 

```
```xml

tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

 tx  <auth mechanism="WAUTH-2" user="541165195349"></auth>

 rx  <start from="s.whatsapp.net"></start>

 rx  <stream:features></stream:features>

 rx  <challenge>q��4�`v�bGTì����</challenge>

 tx  <response>����X" �!��?,���Y�y aΒ�@9!g�Y</response>
```
```

Couldn't send any message yet with WhatsAPI, despite I just followed the step mentioned on the examples. Can you imagine what happenning?

**Comment by mgp25** [comment]
@ChiefHornacek It seems the number is blocked, try to log in again and send debug code.

Regards

**Comment by ChiefHornacek** [comment]
@mgp25 Just found the error. I was not including one number in the phone number. It worked for registration but not to send messages. Now everything works like a charm. Sorry for the drawbacks
