### ISSUE TITLE
How can we avoid the message encryption until there will be a fix?

### ISSUE THREAD

**Issue by yniv** [mgp25/WhatsAPI-Official#320]
Hi all,
Currently, as far as I know, there is no fix for the message encryptions. So, how can we avoid it
meanwhile?
Is it related to the version we send to whatsapp? 
I used the 2.11.301 version and did not got encrypted messages but suddenly i got not-authorized... like they blocked this version. and then i switched to 426 and started to get encryption messages....
Someone knows what is the last safe version?

**Comment by CODeRUS** [comment]
you can use WP7-2.11.634-443 resource for login.

**Comment by yniv** [comment]
What is WP7? also are you sure these versions(634-443) doesn't support the encryptes messages?

**Comment by clintoncheuk** [comment]
Windows Phone 7

**Comment by yniv** [comment]
Oh, I See. Thanks, I'll try it

**Comment by yniv** [comment]
When i try the WP7-2.11.634-443 versions as @CODeRUS mentioned I'm getting stream:error errors after approx 1 minute. Currently the only version that works for me is: Android  2.11.351 but I get message encoding from some clients. Any Ideas? Suggestions?

**Comment by CODeRUS** [comment]
S40-2.12.61-443

**Comment by yniv** [comment]
@CODeRUS Seems working. Thanks! Let's hope it'll continue to work for a long time :)
