### ISSUE TITLE
Some functions not working for me

### ISSUE THREAD

**Issue by rohit49khatri** [mgp25/WhatsAPI-Official#322]
I've tried most of the functions of this api only few of the functions are working.. i would like to list some of the non working functions.
```
sendMessageVideo
sendMessageImage
sendVcard
getMessage
sendGetProfilePicture
sendStatusUpdate
sendBroadcastMessage
```

When i use these functions i don't receive anything. Please help me out.

Thanks

**Comment by Silikowski** [comment]
Got the same Problem with SendMessageImage (https://github.com/mgp25/WhatsAPI-Official/issues/313) - copied the supplied code from there: image received.

I found the issue now: curl was not installed on the machine. installed php5-curl, workd well! Maybe thats it. System needs to fetch the data from the url.

**Comment by mgp25** [comment]
@rohit49khatri send debug log. Be sure to add `$w->pollMessage();` after that. It's explained in the wiki: https://github.com/mgp25/WhatsAPI-Official/wiki

**Comment by rohit49khatri** [comment]
When i tried broadcasting a message i received this debug log but i did not receive message on any number and for image and video i was not using pollmessage but now it's working like charm thanks.
Just help me out with broadcasting messages.



tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="91xxxxxxxxxx">iáû91xxxxxxxxxxKŠ7¼[1»Õ^x…üì©T1422284909WhatsApp/2.12.60 S40Version/14.26 Device/Nokia302 MccMnc/404011</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>º`hïWŒÛ´pì8 ç,åm†8</challenge>

tx  <response>”„Ÿanþ³‹{%N\#ê¿ºèF~[‰(Ãh¸ oþµ3IÎ</response>

rx  <success t="1422284910" props="4" kind="free" status="active" creation="1422189340" expiration="1453725340">¿´¶’5ö­Ñ­YëŠ˜`Š¯</success>

tx  <presence name="Rohit Khatri"></presence>

tx  <presence type="subscribe" to="91xxxxxxxxxx@s.whatsapp.net"></presence>

tx  <message to="1422284910@broadcast" type="text" id="broadcast-1422284910-1">
tx    <body>This is a testing message for sendBroadcastMessage function!</body>
tx    <broadcast>
tx      <to jid="91zzzzzzzzzz@s.whatsapp.net"></to>
tx      <to jid="91yyyyyyyyyy@s.whatsapp.net"></to>
tx    </broadcast>
tx  </message>

rx  <presence from="91xxxxxxxxxx@s.whatsapp.net"></presence>

**Comment by mgp25** [comment]
@rohit49khatri remember that in order to receive messages, numbers must be synced (saved in the contact list), if not, you wont receive any message

**Comment by rohit49khatri** [comment]
Can you tell me how to sync number so that i can broadcast message ?

**Comment by mgp25** [comment]
@rohit49khatri the numbers you are sending the messages to, must have your number saved in their contact list.

**Comment by rohit49khatri** [comment]
But i receive messages from people who are not in my contact list in phone. Does this feature only work in whatsapp official app ?

**Comment by mgp25** [comment]
@rohit49khatri You can receive messages from people you havent in your contact list, but you cant receive broadcast messages from people you dont have added

**Comment by rohit49khatri** [comment]
@mgp25 I tried using only one contact in sendBroadcastMessage numbers array and the number is in my contact list but still i did not receive text though when i send message using simple sendMessage it works fine. Why this is happening with broadcast function ?

**Comment by mgp25** [comment]
@rohit49khatri read my previous comment.

**Comment by rohit49khatri** [comment]
Got it.

Is there any way to register some contacts on my logged in account in this api and then create a broadcast list and send message to them ?

**Comment by mgp25** [comment]
@rohit49khatri Remember that is the number that receive the message the ones who need to add your number, not the one that sends the message.

Everything its explained in the wiki: https://github.com/mgp25/WhatsAPI-Official/wiki

**Comment by rohit49khatri** [comment]
Ohk thanks for you help..!!
