### ISSUE TITLE
Making a group member admin

### ISSUE THREAD

**Issue by dovfrank** [mgp25/WhatsAPI-Official#324]
Hi,
I was looking for a way to make other members of the whatsapp group admins.
In the Whatsapp iPhone app , if you are the group admin - you can make other members to be admins as well. I was looking through the documentation and did not see how it can be done.
Is it possible to do that or not?

**Comment by mgp25** [comment]
@dovfrank Hi, i'll that to documentation tonight.

Use this function:

```php
sendPromoteParticipants($gId, $participants)
```

Regards
