### ISSUE TITLE
Legality question

### ISSUE THREAD

**Issue by rcetrangolo** [mgp25/WhatsAPI-Official#326]
I suppose this question has been answered several times but I need an update.
The question is simple, is totaly legal to use WhatsAPI?
Is there some kind of arrangement with WhatsApp? or they approve WhatsAPI?

I know the spam is ilegal, but we can use WhatsAPI in order to receive a message and then start an authomatic chat? this could be consider ilegal too?

Thank you very much for your time and great work.

Best regards.

**Comment by mgp25** [comment]
WhatsApp EULA: http://www.whatsapp.com/legal/?l=en

**Comment by rcetrangolo** [comment]
Yes, I've read de EULA, I think there are two things they care about:
1 - Spam (obviously)
2 - Use of 'robots'

Point number 1 is out of discussion but if we send outbound messages to people that have our number as a contact and the messages are personalized for every user, it is not spam, right?
Point number 2 is much complicated but again, if we don't struggle WA server is enough, isn't it?

By the way, I want to know if you had some official contact with WA and what they said, what about an arrangement or oficial approval?

Thanks for your quick answer!!

**Comment by CODeRUS** [comment]
3. WhatsApp Access

**Comment by rcetrangolo** [comment]
CODeRUS, the WA EULA is quite gray, in my opinion.
What do YOU think? it is legal or not to use WhatsAPI? they (WA) told you something some time?

I repeat, we want to do two things:
- send messages to a finite list of users with different messages
- to 'wait' for a key word and then start a little chat with a real user

thank you again

can they consider this as ilegal?

**Comment by CODeRUS** [comment]
yes WA EULA is grey because WA is the only holder of WA service and can do anything they want in any moment they want.

**Comment by mgp25** [comment]
*sigh*

3. WhatsApp Access

A. Subject to your compliance with these Terms of Service, WhatsApp hereby grants you permission to use the Service, provided that: (i) your use of the Service as **permitted is solely for your personal use**, and you are not permitted to resell or charge others for use of or access to the Service, or in any other manner inconsistent with these Terms of Service;

**Comment by rcetrangolo** [comment]
Nobody will charge others for use the service and as we need a real phone number in order to register in WA server, that number is 'personal'.

One more time, has WA contacted you before? (yes or no please =)

thank you

**Comment by mgp25** [comment]
@rcetrangolo personal usage is personal usage, to contact with your friends or your parents or chatting with yourself, but not business. I think it's clear in WhatsApp EULA.

Regards

**Comment by domingopa** [comment]
Hi @mgp25 , congratulations on as manage this repository
I'm seeing some examples of using whatsapp that may violate EULA.
-Talk Working with my company.
-Ask An appointment at the hairdresser.

Or what makes an airport in Brazil with the explicit support of WA:
http://wwwhatsnew.com/2014/12/15/ya-se-puede-usar-whatsapp-para-consultar-vuelos-de-aeropuerto-en-brasil/

-Listen To my political party:
http://www.psoe.es/ambito/whatsapp/news/index.do?action=View&id=766882
It is considered personal or not?

I think everything changes very fast and not know what lies ahead .. but we have to be happy

;-)

What do you think @mgp25 ?

regards

**Comment by mgp25** [comment]
Its not personal usage and may violate WhatsApp EULA, im not responsible of the usage users do with this API, if one day you find that all your numbers are blocked its your problem and not of WhatsApp or this software.

**Comment by domingopa** [comment]
Of course ... do not know if using this api or another ..
are just a few examples I've seen browsing.
besides the BBC or 4News.

regards
