### ISSUE TITLE
Does PollMessage(); mark the messages as read?

### ISSUE THREAD

**Issue by Silikowski** [mgp25/WhatsAPI-Official#327]
I do a 
```php
$w->PollMessage();
```
and print the array i get back. The message in Whatsapp still shows as "unread" and i can Poll it again and again.

**Comment by CODeRUS** [comment]
hell yeah!

**Comment by Silikowski** [comment]
yay sry i hit the wrong button.
took me some time to find the edit button on mobile!

**Comment by mgp25** [comment]
@Silikowski Are you using WhatsApp Official code? If you are not, then upgrade it.

Can you post your debug log? Also keep in mind that you have to keep `polling messages` until you disconnect.

**Comment by Silikowski** [comment]
Yeah official code (3 Days old maybe).

<?php

require_once('wa/src/whatsprot.class.php'); 
require('wa/src/events/MyEvents.php');

$debug = false; 
$username = "username"; 
$identity = "identity"; 
$nickname = "Nick"; 
$password = "*****"; 

$w = new WhatsProt($username, $identity, $nickname, $debug); 

$events = new MyEvents($w);

$w->connect();
$w->loginWithPassword($password);


        $w->pollMessage();
        $data = $w->getMessages();
        if(!empty($data)) print_r($data);
        $w->pollMessage();   
$w->disconnect();


This is the code. Gives me the Output i need, but message is not marked in WA (double ticked in blue) and the script shows it every time i open it.

**Comment by mgp25** [comment]
@Silikowski try this:

<?php

require_once('wa/src/whatsprot.class.php'); 
require('wa/src/events/MyEvents.php');

$debug = false; 
$username = "username"; 
$identity = "identity"; 
$nickname = "Nick"; 
$password = "*****"; 

$w = new WhatsProt($username, $identity, $nickname, $debug); 

$events = new MyEvents($w);

$w->connect();
$w->loginWithPassword($password);

$w->pollMessage();
$data = $w->getMessages();
if(!empty($data)) print_r($data);
$i = 0;
for($i; $i < 6; $i++)
{
     $w->pollMessage();
} 
$w->disconnect();

**Comment by Silikowski** [comment]
Is there any special sense behind it or does pollMessage not mark the messages reliable so a set of pollMessage will work better?

copying it for 4,5,6 times would do the same job?

**Comment by mgp25** [comment]
@Silikowski becuase you only `pollMessage` once and then disconnect. Ideally you need to `pollMessage`everytime (in background), as php is not multithread its better to keep `pollingMessages` for a while so you can receive the data from the server.

Yes that will work too.

If your issue is solved, you can close the issue :)

Regards

**Comment by Silikowski** [comment]
Ill try it later and close it!

Thanks!

**Comment by Silikowski** [comment]
Worked! Thanks!

**Comment by harishannam** [comment]
@mgp25 Used the code which you gave in the above comment. But If I send 3 messages to the number and run this code, It just displays the latest one message in the response but marks read on all three messages
