### ISSUE TITLE
emojis...

### ISSUE THREAD

**Issue by jesussales** [mgp25/WhatsAPI-Official#328]
Hi!, how can I catch emojis and replace with images when pollmessage?

**Comment by mgp25** [comment]
Emojis are shown automatically.

Regards

**Comment by jesussales** [comment]
Me no. ... try to fin d .... the problem

**Comment by deizepi** [comment]
The following function solves your problem (in most cases), was unable to convert emojis that have separation ("_"):

    function parseEmojiForHTML($message){

        $message = mb_convert_encoding($message, "HTML-ENTITIES", "UTF-8");

        $matches = null;
        preg_match_all('/&#(.*?);/', $message, $matches, PREG_SET_ORDER);
        if (is_array($matches)) {
            foreach ($matches as $emoji){
                $html = "<img class='emoji emoji-".strtoupper(dechex($emoji[1]))."' />";
                $message = str_replace($emoji[0], $html, $message);
            }
        }
        return $message;
    }

**Comment by SikiFn** [comment]
I have written the following function, just define and bind it. Send only one emoji per message to the API and it will give you the HTML code

```php
function processReceivedEmoji($phone, $from, $id, $type, $time, $name, $data) {
	$data = mb_convert_encoding($data, 'HTML-ENTITIES', 'UTF-8');
	$data = str_split($data, 9);
	$ret = "";
	foreach($data as $d) {
	    $d = str_replace('&#', '', $d);
	    $d = str_replace(';', '', $d);
		$ret .= '##' . dechex($d) . '##';
	}
	echo $ret;
}
	
$w->eventManager()->bind("onGetMessage", "processReceivedEmoji");
```
