### ISSUE TITLE
Can't register code

### ISSUE THREAD

**Issue by glennadva** [mgp25/WhatsAPI-Official#329]
After several attempts, I managed to get the 6-digit code via sms.

When trying to register the code (via `$w->codeRegister('XXXXXX');`), I get the following message:
`stdClass Object ( [status] => fail [reason] => stale` )

I'm using the `examples/exampleRegister.php` script for the registration process.

Any idea what's the solution to this problem?

**Comment by mgp25** [comment]
Use `examples/registerTool.php`

Regards

**Comment by glennadva** [comment]
Hello mgp25,

Thank you very much for your reply.

How am I supposed to use this script; I am not familiar with trim(fgets(STDIN));
For example, do I need to replace $option = fgets(STDIN); with $option = "sms";
