### ISSUE TITLE
How to check the valid whatsapp number before sendmessage?

### ISSUE THREAD

**Issue by techcare2u** [mgp25/WhatsAPI-Official#331]
Hi..I am new here also new to php..i can `sendMessage` and use `contactsync` but i don't know how to combine this 2. I am prefer function `onSyncResult` can send a true or false before i start `sendmessage`. Any guru can help me? thanks a lot

**Comment by mgp25** [comment]
```php
$numbers = array('123456789',987654321');

$w->sendSync($numbers);

$w->sendMessage($numbers[0]);
```

Also a valid thing is:

```php
function onSyncResult($result)
{
foreach ($result->existing as $number) {
    // Send message here
}
foreach ($result->nonExisting as $number) {

}
die();
}
```

Regards
