### ISSUE TITLE
Only first message displayed

### ISSUE THREAD

**Issue by Silikowski** [mgp25/WhatsAPI-Official#334]
I tried to receive all messages in line (2 messages sent to the account, not read)

Tried the code found at https://github.com/mgp25/WhatsAPI-Official/issues/321 but i just get the first message in line. Next time no message is left to show.

Is there any sample like used in the whatsapp example? showing all received messages in line?

**Comment by mgp25** [comment]
@Silikowski i recommend you to read the wiki: https://github.com/mgp25/WhatsAPI-Official/wiki

And follow the examples we provide: https://github.com/mgp25/WhatsAPI-Official/tree/master/examples

Everything its explained there. The code im posting below its explained in the wiki.

```php
<?php

require_once('whatsprot.class.php');


function onMessage($mynumber, $from, $id, $type, $time, $name, $body)
{
    echo "Message from $name:\n$body\n\n";
}


$username = "";
$identity = "myIdentity";
$nickname = "Test";
$debug = "false";

$password = "";

$w = new WhatsProt($username, $identity, $nickname, $debug);
$events = new MyEvents($w);
$w->eventManager()->bind("onGetMessage", "onMessage");

$w->Connect();
$w->LoginWithPassword($password);

while(1)
{
  $w->pollMessage();
  //Something to break loop
}

$w->disconnect();
?>
```
