### ISSUE TITLE
how to pay the whatsapp and receive the password?

### ISSUE THREAD

**Issue by jacoboliveira** [mgp25/WhatsAPI-Official#335]
this is my question how do I get the password to pay whatsapp?

**Comment by CODeRUS** [comment]
https://www.whatsapp.com/payments/google.php?phone=PHONE&cksum=md5(PHONE+"abc")&sku=1
https://www.whatsapp.com/payments/paypal.php?phone=PHONE&cksum=md5(PHONE+"abc")&sku=1

**Comment by mgp25** [comment]
@jacoboliveira there is a function called:

`function generatePaymentLink($number, $sku)`

Just call it like this:

```php
$w->generatePaymentLink($number, $sku);
```

Regards

**Comment by jacoboliveira** [comment]
thank you I will try
