### ISSUE TITLE
Encoding accented letters

### ISSUE THREAD

**Issue by NicolaConnect** [mgp25/WhatsAPI-Official#336]
Hello,
How can I encode accented letters to send them via sendMessage()?

When I try to send "è", I get something like "�".

Thanks!

**Comment by 0xTryCatch** [comment]
Sounds like a character issue. Make sure you set PHP and your editor to use utf-8:

    mbstring.internal_encoding = utf-8

**Comment by NicolaConnect** [comment]
Thanks for your time! It works now.

I tried
```php
mb_internal_encoding("UTF-8");
```
but it didn't work properly.
