### ISSUE TITLE
Performance and need to pollMessage?

### ISSUE THREAD

**Issue by Silikowski** [mgp25/WhatsAPI-Official#337]
Hi,

how long does it take to connect to WA and send a Message?

I get a array of numbers from mysql, looping sendMessageImage() for each individual recip. closing the connection after the loop is done.

Mysql-Query takes 1,5 sek (Remote Server). Whole Script (15 recipients) needs about 100 sec. to finish.

Is that normal or are there ways to improve speed? 

2nd: Do i need to pollMessage() while looping in order to sendMessageImage()? I don't want to receive the Messages sent to me. Im doing this manually on demand with another script.

**Comment by mgp25** [comment]
@Silikowski 3 seconds more or less to connect and send a message.

Add pollMessage after you send the image.

We don't support massive messages.

Regards

**Comment by Silikowski** [comment]
ok thx. 
maybe the performance of the server is a bit crappy (running it on a raspberry :D).

what exactly do you mean with massive message? i am not sending spam messages. users registered and provided their mobilenumer to get notified via W/A. Im opening the connection, then sending´an imagee to every single user inside a while loop, disconnecting after it.

does that count as massive/spam?

**Comment by ahumblenerd** [comment]
I am trying to create a whatsapp based radio service where users can register and get details about a particular topic. To give real time updates can we enhance the speed some way ?

**Comment by Silikowski** [comment]
I moved my project from my homebased raspberry to a small vserver. 30 imageMessages now take only about 35 secons insteaf of 150! (single message, no broadcast!)
