### ISSUE TITLE
onSyncResult don't return syncId any more

### ISSUE THREAD

**Issue by ExpressArab** [mgp25/WhatsAPI-Official#338]
i am trying to print the `$result` object in this method `onSyncResult` i got the `syncId = 0` as shown below  
```
[syncId] => 0
```
any idea why it not returned as usual.

**Comment by mgp25** [comment]
https://github.com/mgp25/WhatsAPI-Official/commit/6d88e609e580c04d0a9f7ae9c0ee25a53c5891c8

**Comment by ExpressArab** [comment]
thanks @mgp25 for support
