### ISSUE TITLE
 block a number using whatsapi 

### ISSUE THREAD

**Issue by Abtab** [mgp25/WhatsAPI-Official#339]
hi
How to  block a number using whatsapi sending me message.

Thanks in advance
Regards

**Comment by clintoncheuk** [comment]
You won't know whether that number is using api to send you message, so there is no method to block i think. But you can use ```$w->sendSetPrivacyBlockedList($number);``` to block someone..

**Comment by CODeRUS** [comment]
he just asking "how to block some number (which sending me a message) using whatsapi" :D
