### ISSUE TITLE
Registration does not work

### ISSUE THREAD

**Issue by vkronik** [mgp25/WhatsAPI-Official#341]
```json
{"status":"fail","reason":"no_routes","retry_after":3600}
```

Please update token generator function

**Comment by ajay1989** [comment]
facing the same problem ..

**Comment by Pudins** [comment]
I have the same problem!

**Comment by mgp25** [comment]
We can't do nothing right now, it's not an API issue/bug. Don't use virtual phone numbers, if you try with your personal number it will work.

Regards

**Comment by vkronik** [comment]
I try wih my personal number and it is not work!

**Comment by mgp25** [comment]
@vkronik send debug log

**Comment by vkronik** [comment]
( [in] => 672809974 [cc] => 79 [id] => HDhЊДХНYeћ:&ФV [lg] => ru [lc] => RU [mcc] => 000 [mnc] => 000 [sim_mcc] => 250 [sim_mnc] => 028 [method] => sms [reason] => self-send-jailbroken [token] => 2d31c1d3f6dcd2f5b2689222470d16b0 [network_radio_type] => 1 ) stdClass Object ( [status] => fail [reason] => no_routes [retry_after] => 3600 )

**Comment by mgp25** [comment]
@vkronik what carrier do you have

**Comment by vkronik** [comment]
Bee Line GSM

**Comment by mgp25** [comment]
@vkronik researching, i'll give you a response as soon as i know something

Regards

**Comment by vkronik** [comment]
thanks, i'll be waiting

**Comment by Pudins** [comment]
@mgp25 Here in Brazil I'm also enfrentenado problems following debug code.

 [in] => 11995801670
 [cc] => 55 
[id] => x.��$��	�ft�ujy��� 
[lg] => pt
[lc] => BR
 [mcc] => 000
 [mnc] => 000 [
sim_mcc] => 724 
[sim_mnc] => 000
 [method] => sms 
[reason] => self-send-jailbroken 
[token] => 3dba3479b421a83cec6b09b457582375
 [network_radio_type] => 1 
stdClass Object (
 [status] => fail
[reason] => no_routes 
[retry_after] => 3600 )

I thank you that want help

**Comment by aesedepece** [comment]
@mgp25 Yowsup and Coseme users are getting ```no_routes``` since yesterday, just like before the last token update, so we should assume that ```"WhatsApp/2.12.60 S40Version/14.26 Device/Nokia302``` UA has been already banned.

**Comment by mgp25** [comment]
@aesedepece it could be, i dont know yet. I will try with latest token, as soon as try ill answer you.

Regards

**Comment by mgp25** [comment]
It doesn't seem to be a token problem (I just updated the token https://github.com/mgp25/WhatsAPI-Official/commit/e53886c4b190a245e12b26e81c399b5e6b04be9a), maybe a service downtime, we'll wait a while and if this persist i'll do a further reseach, anyway i'll leave this issue open meanwhile.

Regards

**Comment by castler** [comment]
+1

**Comment by mgp25** [comment]
[UPDATE]: As far as i know, its a identity problem, we are researching.

Once we have found this problem, we'll update code.

Regards

**Comment by jesussales** [comment]
On wart 1 7 3  work fine.... i don't know if that help you

**Comment by mgp25** [comment]
@jesussales We already know it, we are working on it.

Regards

**Comment by jesussales** [comment]
Ok. ... this morning i tried to register a number on watools,  voice Mode,
but not make a call and not display error on web. .. after register by SMS
on wart and works fine

**Comment by mgp25** [comment]
Fixed: https://github.com/mgp25/WhatsAPI-Official/commit/dfa2a8d436a37d0c0b7056a0d753c02415046bc5

**Comment by aesedepece** [comment]
@mgp25 You just overtook me, as I was about to make the PR with the same fix aahahaha.
Good job! :+1:

**Comment by dcardosoa** [comment]
I get this error:

Enter the received code: 596902
Array
(
    [cc] => 55
    [in] => ZZ9XXXXUUUU
    [id] => hqüþqê%8¯áãrä(ü2$
    [code] => XXXYYY
    [lg] => pt
    [lc] => BR
    [network_radio_type] => 1
)
stdClass Object
(
    [status] => fail
    [reason] => missing
)
An error occurred registering the registration code from WhatsApp.

Anybody have this problem?

**Comment by mgp25** [comment]
Try the latest commit: https://github.com/mgp25/WhatsAPI-Official/commit/588455111cd781e6ca8100f096e0476d270e8f11

**Comment by dcardosoa** [comment]
Works.

thks

**Comment by fcarstensen** [comment]
Hi mgp25,

I don't want to start a new issue, because I have exactly the same problem. I received the SMS with the code by using $r->codeRequest('sms')  and then I run into this issue. 
After $r->codeRegister($code) it returns:

```
Array
(
    [cc] => 49
    [in] => a_real_mobile_number
    [lg] => de
    [lc] => DE
    [id] => ▒▒wf▒s▒`0▒tk$▒xٻd
    [mistyped] => 6
    [network_radio_type] => 1
    [simnum] => 1
    [s] =>
    [copiedrc] => 1
    [hasinrc] => 1
    [rcmatch] => 1
    [pid] => 9216
    [rchash] => 3976017b76cd387685607dfa5e9c654c92d741536d32bf84e40df60aa5dc1052
    [anhash] => ed201c1836fb230e32a2d945dbe1d043
    [extexist] => 1
    [extstate] => 1
    [code] => 282811
)
stdClass Object
(
    [status] => fail
    [reason] => missing
)
```

What can I do? Any ideas?

**Comment by fcarstensen** [comment]
Hi mgp25,

I don't want to start a new issue, because I have exactly the same problem. I received the SMS with the code by using $r->codeRequest('sms')  and then I run into this issue. 
After $r->codeRegister($code) it returns:

```
Array
(
    [cc] => 49
    [in] => a_real_mobile_number
    [lg] => de
    [lc] => DE
    [id] => ▒▒wf▒s▒`0▒tk$▒xٻd
    [mistyped] => 6
    [network_radio_type] => 1
    [simnum] => 1
    [s] =>
    [copiedrc] => 1
    [hasinrc] => 1
    [rcmatch] => 1
    [pid] => 9216
    [rchash] => 3976017b76cd387685607dfa5e9c654c92d741536d32bf84e40df60aa5dc1052
    [anhash] => ed201c1836fb230e32a2d945dbe1d043
    [extexist] => 1
    [extstate] => 1
    [code] => 282811
)
stdClass Object
(
    [status] => fail
    [reason] => missing
)
```

What can I do? Any ideas?
