### ISSUE TITLE
number blocked after sid update applied

### ISSUE THREAD

**Issue by faisalcse** [mgp25/WhatsAPI-Official#342]
I try to send 4 messages to my friends but it blocked. It happened after applying sid update.

**Comment by mgp25** [comment]
@faisalcse Its already updated. See latest commit

**Comment by faisalcse** [comment]
Latest commit where?

**Comment by mgp25** [comment]
https://github.com/mgp25/WhatsAPI-Official/commit/6d88e609e580c04d0a9f7ae9c0ee25a53c5891c8

Please, see repo, wiki and commit before opening new issue

Regards

**Comment by faisalcse** [comment]
I saw. I have Applied but after send to 4 number it will help

**Comment by faisalcse** [comment]
I saw. I have Applied but after send to 4 number then block

**Comment by mgp25** [comment]
@faisalcse WhatsAPI its blocking user that does bulk/massive sending, so probably you are sending to users that they dont have your number added into their contact list

Regards

**Comment by faisalcse** [comment]
They are already in my contact list. After I send to 4 numbers it blocked after I applied updates in whatsaport

**Comment by mgp25** [comment]
@faisalcse not you, the ones who receive the messages. For example, you are sending to 123456789, that number must have your number in his contact list.

**Comment by faisalcse** [comment]
He already has my number.

**Comment by mgp25** [comment]
Then it should work fine to you
