### ISSUE TITLE
Receiving No Routes on codeRequest

### ISSUE THREAD

**Issue by pentatonicfunk** [mgp25/WhatsAPI-Official#345]
Im Receiving 
``` {"status":"fail","reason":"no_routes","retry_after":3600} ```

on codeRequest

Log Request
``` https://v.whatsapp.net/v2/code?in=89670XXXXX&cc=62&lg=id&lc=ID&mcc=000&mnc=000&sim_mcc=510&sim_mnc=001&method=sms&reason=self-send-jailbroken&token=bfa738c249ea4b97467caf90d8d6b184&network_radio_type=1&id=%c4%f3%12q%00f%f8%93%de%8XXXXXX ```

tried on another public ip, another computer, still same usually its good.

**Comment by mgp25** [comment]
Please, before opening a new issue, check if there is already an open one.

Duplicate: #341
