### ISSUE TITLE
Hello, my 2 cents..

### ISSUE THREAD

**Issue by thetitoo** [mgp25/WhatsAPI-Official#348]
Thanks for your work guys,
If I may input my modest contribution:

1. in: wiki/WhatsAPI-Documentation#list-of-all-events,

`onGetLocation( $mynumber, $from, $id, $type, $time, $name, $name, $longitude, $latitude, $url, $preview )`

Shouldn't it be - I'm bothered with the double $name

`onGetLocation( $mynumber, $from, $id, $type, $time, $name, $nameLocation, $longitude, $latitude, $url, $preview )`

2. in: \src\whatsprot.class.php Line#1041
PhpStorm cries for $null - variable not defined (I didn't go further than that)

Cheers,
Chris.

**Comment by mgp25** [comment]
Wiki fixed too

$null var fixed: https://github.com/mgp25/WhatsAPI-Official/commit/79a298bcd49edd292c08761fc1d0d8457b3183ed

Regards
