### ISSUE TITLE
Invalid media download request 

### ISSUE THREAD

**Issue by deizepi** [mgp25/WhatsAPI-Official#351]
Hello, the onMediaMessageSent() event returns the URL of the sent media. Through the Web Whatsapp could see that lack a folder to be able to access this media.

URL of the event: https://mmi211.whatsapp.net/d/AilaqkJgQ3UlNsItFDxAbA2YZdnMLTLWuilrhZ4UkRfV.jpg
URL Web WhatsApp: https://mmi211.whatsapp.net/d/w8K4j9S4sm2uqgfKteEyaFTNN3I/AilaqkJgQ3UlNsItFDxAbA2YZdnMLTLWuilrhZ4UkRfV.jpg

Is possible to know this folders? (in this case: "w8K4j9S4sm2uqgfKteEyaFTNN3I")

Thanks.
(Sorry for the bad english)

**Comment by 0xTryCatch** [comment]
No. I think this part of the URL is different for each recipient.

**Comment by mgp25** [comment]
When sending a media file you have something like this:
```xml
tx  <iq id="upload-1417220276-2" to="s.whatsapp.net" type="set" xmlns="w:m">
tx    <media hash="PTlogULv9Y8gw0fiYtGnKa41mZVTGgPeamckvRmCGuE=" type="image" size="38672"></media>
tx  </iq>

rx  <iq from="s.whatsapp.net" id="upload-1417220276-2" type="result">
rx    <media url="https://mmi232.whatsapp.net/u/KAThfmZKqjsFcYCjquBhEAX2XncABQj0TwJsGw/AgzG9XZGxMYjaU_70bFMChRBL2x9l4Hz1pVwoPWGaCby" ip="***"></media>
rx  </iq>

tx  <message to="***@s.whatsapp.net" type="media" id="message-1417220278-4" t="1417220278">
tx    <media xmlns="urn:xmpp:whatsapp:mms" type="image" url="https://mmi232.whatsapp.net/d/AgzG9XZGxMYjaU_70bFMChRBL2x9l4Hz1pVwoPWGaCby.jpg" file="830f8934d01d6d07a1275f6d8499bcb9.jpg" size="38672" hash="PTlogULv9Y8gw0fiYtGnKa41mZVTGgPeamckvRmCGuE="> 12024 byte data</media>
tx  </message>
```

In the receiver side, you will receive:
```xml
rx <message from="***@s.whatsapp.net" id="message-1417266176-4" type="media" t="1417266176" notify="Test">
rx       <media type="image" url="https://mms894.whatsapp.net/d/u4bkb25phMz6NbDN7P3s61R5xAAABQj-_wXqdQ/AgzG9XZGxMYjaU_70bFMChRBL2x9l4Hz1pVwoPWGaCby.jpg" encoding="raw" file="25bd6d88453041c7d113a108f1bf6c89.jpg" size="38672" caption="" ip="***" mimetype="image/jpeg" filehash="PTlogULv9Y8gw0fiYtGnKa41mZVTGgPeamckvRmCGuE=" width="1200" height="800">
```

You will only receive the right url only in the receiver side, not in the sender side.

**Sender side:**
https://mmi232.whatsapp.net/d/AgzG9XZGxMYjaU_70bFMChRBL2x9l4Hz1pVwoPWGaCby.jpg

**Receiver side:**
https://mms894.whatsapp.net/d/u4bkb25phMz6NbDN7P3s61R5xAAABQj-_wXqdQ/AgzG9XZGxMYjaU_70bFMChRBL2x9l4Hz1pVwoPWGaCby.jpg

Related issue: #101
