### ISSUE TITLE
Tree length did not match received length!

### ISSUE THREAD

**Issue by phpjoker** [mgp25/WhatsAPI-Official#352]
```
Tree length did not match received length (buff = 18 & treeLength = 2647)
Tree length did not match received length (buff = 7815 & treeLength = 41295)
Tree length did not match received length (buff = 79 & treeLength = 162)
```

**Comment by mgp25** [comment]
@phpjoker thats because you are managing a lot of groups, delete the unused ones.

Regards

**Comment by phpjoker** [comment]
Its happend after internet problem.

**Comment by mgp25** [comment]
@phpjoker then you have answered yourself

Regards

**Comment by phpcoder345** [comment]
Is there a way to retain the number of groups and still manage without the error

**Comment by kharchenkodenis** [comment]
i have a new number and jusy regiterring

Fatal error</b>:  Uncaught exception 'ConnectionException' with message 'Tree length did not match received length (buff = 19 &amp; treeLength = 25)' ...whatsprot.class.php:3716

how it fix?
