### ISSUE TITLE
How to get to know whether a number is using WhatsApp or not

### ISSUE THREAD

**Issue by rayidi** [mgp25/WhatsAPI-Official#353]
Hi,

I'm developing a project which needs to show a number is actually using WhatsApp account or not!
I can't find any related functions in the app.

However tried to get the sendGetRequestLastSeen didn't working.

Please help me to understand it better.
Thanks in advance.

**Comment by mgp25** [comment]
Please, read the wiki and FAQ before opening a new issue, most of the documentation and frequently asked questions are there.

Wiki: https://github.com/mgp25/WhatsAPI-Official/wiki
FAQ: https://github.com/mgp25/WhatsAPI-Official/wiki/Frequently-asked-questions

Regards
