### ISSUE TITLE
Sending bulk message by whatsappAPI

### ISSUE THREAD

**Issue by srimantacode** [mgp25/WhatsAPI-Official#354]
I am trying to send bulk messages by whatsappAPI using php.
First of all, Please let me know whether it is possible to send massive messages or not.
If Yes, then please send me a step by step process so that I can handle this in my PHP based application.

**Comment by castler** [comment]
@srimantacode read the wiki!

**Comment by jonnywilliamson** [comment]
@sirmantacode 

Yes!! Lots of us would love to help you send bulk messages using whatsapp! No problem. 

In fact to help us get started why don't you post the phone number you want to use to send the messages. 

Also if you post us your address, some of us might live near by and we could meet up and help you program it!!

**Comment by srimantacode** [comment]
The number is still not be fixed and it would be an Indian number. But could you please let me know whether it is possible to send bulk message from one number to n numbers of contacts by using whatsappAPI?

**Comment by mgp25** [comment]
It's explained in the FAQ: https://github.com/mgp25/WhatsAPI-Official/wiki/Frequently-asked-questions

**Comment by krishnavenii** [comment]
iam the beginner of php.i want to send messages from my web application to whatsapp. i am not able to solve the following error "There was an error with the AJAX request. XML/Json format is bad".i want to know why it occured and how to use the whtsapp api..will u please help me .?
