### ISSUE TITLE
Libaxolotl-php

### ISSUE THREAD

**Issue by rcetrangolo** [mgp25/WhatsAPI-Official#355]
Any news about encryption over PHP?

And what about .net?

thank you!

**Comment by CODeRUS** [comment]
https://github.com/mgp25/libaxolotl-php

**Comment by rcetrangolo** [comment]
I don't understand.

Libaxolotl PHP is finished? I don't see it inside WhatsAPI.

thanks

**Comment by 0xTryCatch** [comment]
It is under construction. Once finished it will be integrated in WhatsAPI

**Comment by rcetrangolo** [comment]
Great, that was what I want to know.

Thank you very much.

Best regards

**Comment by chattopadhyaysantanu** [comment]
how to decrypt the received message from whatsapp?

**Comment by WHAnonymous** [comment]
@chattopadhyaysantanu 



#891
#893
#899
