### ISSUE TITLE
sendSetGroupSubject not working for existing groups

### ISSUE THREAD

**Issue by phpcoder345** [mgp25/WhatsAPI-Official#356]
I tried `sendSetGroupSubject` and it doesn't work.

`sendSetGroupPicture` works fine.

Any pointers. Any of the group members are able to change the subject using their phones.

**Comment by emarketingw** [comment]
Hi phpcoder345

could you please call us via skype
my account on skype (emarketingw)

**Comment by phpcoder345** [comment]
calling now

**Comment by mgp25** [comment]
@phpcoder345 it is working fine, for further support post full debug-log.
