### ISSUE TITLE
" [status] => fail [reason] => stale" issue

### ISSUE THREAD

**Issue by Mohammad75** [mgp25/WhatsAPI-Official#357]
Hello mgp25 
using last upate of your API when I try to register a code I get this msg
```
[status] => fail [reason] => stale
debug log : 
Array ( 
[cc] => 1 
[in] => ********** 
[id] => oû2?â[/_y„rˆbï#v·ÖŸ 
[code] => 523309 
[lg] => en 
[lc] => CA 
) 
stdClass Object ( 
[status] => fail 
[reason] => stale 
)
```
An error occurred registering the registration code from WhatsApp.

and many time gives `[reason] => mismatch`

and it's working on wart

**Comment by mgp25** [comment]
This should fix that: https://github.com/mgp25/WhatsAPI-Official/commit/6f7e88e1f3d8cffbddd20bd0d661c06134a69af6

Regards

**Comment by Mohammad75** [comment]
@mgp25  Didn't fix it, still mismatch error

**Comment by mgp25** [comment]
@Mohammad75 Mismatch error its because you are trying to register a number with a different code that you received or a different identity.

**Comment by CODeRUS** [comment]
initialy stale means you trying to register with old code from previous sessions. whatsapp server sent this code time ago and it's no longer accepted.

**Comment by Mohammad75** [comment]
@mgp25   No I just received the code right now and I'm sure of the code and tried many many number and it's the same. what is  the problem if it's not wrong code?
thank you for your concern and time

@CODeRUS now it's mismatch error ^_^ thank you

**Comment by CODeRUS** [comment]
you probably requesting code with one id, and sending registration message with different.

**Comment by Mohammad75** [comment]
@CODeRUS   yes you are write. thank you ^_^

**Comment by cardoso243** [comment]
Success, connect the whatsapp . Very good.
