### ISSUE TITLE
Cant login

### ISSUE THREAD

**Issue by cromvuack** [mgp25/WhatsAPI-Official#362]
Hey guys

i've been trying to login to the wa service but cant get the successfull tag, can you please help, this is the log:

```
[] Logging in as 'Test User no. 2' (5255********)
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>


tx  <auth mechanism="WAUTH-2" user="5255xxxxxxxx"></auth>


rx  <start from="s.whatsapp.net"></start>


rx  <stream:features></stream:features>


rx  <challenge>	T����5���S.�&����"e</challenge>


tx  <response>TG��Q�A3�@ԍ.?xp�	�P�V:��E��k�
e��</response>



Fatal error: Uncaught exception 'Exception' with message 'Login Failure' in /var/www/vhosts/viko_playground/httpdocs/whatsapp/src/whatsprot.class.php:2282
Stack trace:
#0 /var/www/vhosts/viko_playground/httpdocs/whatsapp/src/whatsprot.class.php(605): WhatsProt->doLogin()
#1 /var/www/vhosts/viko_playground/httpdocs/whatsapp/examples/exampleFunctional1.php(76): WhatsProt->loginWithPassword('XXXXXXX')
#2 {main}
  thrown in /var/www/vhosts/viko_playground/httpdocs/whatsapp/src/whatsprot.class.php on line 2282
```

**Comment by 0xTryCatch** [comment]
It looks like your number is blocked. Use checkCredentials() to check that.

**Comment by cromvuack** [comment]
this is what i get when i run checkCredentials:
Array
(
    [cc] => 52
    [in] => 5561347102
    [id] => ��juy6��ri*�t@5�
    [lg] => es
    [lc] => MX
    [network_radio_type] => 1
)
stdClass Object
(
    [status] => fail
    [reason] => incorrect
    [sms_length] => 6
    [voice_length] => 6
)

**Comment by mgp25** [comment]
You need to use `checkCredentials` with the same identity you used to register the number, if not, you can't use `checkCredentials`. You can register your number again and it will work.

The error you posted above could be caused because of connectivity issues or bugged/banned number.

Regards

**Comment by cromvuack** [comment]
Array
(
    [cc] => 52
    [in] => 5561347104
    [id] => �>���{h�f�g*v:�[ʥ�
    [lg] => es
    [lc] => MX
    [network_radio_type] => 1
)
stdClass Object
(
    [status] => fail
    [reason] => incorrect
    [sms_length] => 6
    [voice_length] => 6
)
There was a problem trying to request the code.

is it possible to know if i have a good identity, im using the same one that i use when i register

**Comment by mgp25** [comment]
It doesnt seem like you are using the same identity, but dont worry, use `registerTool.php` register your number again and everything will work fine.

Regards

**Comment by cromvuack** [comment]
i can register successfully, the sms is received on the phone, and from there i cant create the password, also the .dat file is generated, but when i try exampleRegister.php the exception i get is Login Failure im using $identity = $username;. Im using brand new sims, i dont know what else to do :(

**Comment by mgp25** [comment]
@cromvuack contact with me via mail, ill try to help you

**Comment by cromvuack** [comment]
great!!!! thank you so much!
