### ISSUE TITLE
reset pass

### ISSUE THREAD

**Issue by jesussales** [mgp25/WhatsAPI-Official#364]
there a way to reset a password with new one?  i see in wiki but not find anything...

**Comment by CODeRUS** [comment]
use code request and then register, or check credentials in case you remember your registration id

**Comment by jesussales** [comment]
Can you say me the The Registration id format? ? I have some data from
registration,  but I don't know if any is the registration id

Thanks a lot

**Comment by CODeRUS** [comment]
it's bytes format

**Comment by jesussales** [comment]
Ok I'll look for.... I wait have good luck

**Comment by mgp25** [comment]
@jesussales if you have your number registered from previous WhatsAPI versions, copy your identity, ie: `%13%11%E3%AB%09%5D%B5%FCj%A4%88%EE%3Dq%07%96%0A%FD%FC%22` and copy it in the name file you have set in your identity name file, `$identity = 'myId`;`,  in this example you need to paste your identity in `myId.dat` file.

If you registered your number with the latest code, you need the same file that was generated to call `checkCredentials` and get a new password.

Regards
