### ISSUE TITLE
Trouble with Broadcasts

### ISSUE THREAD

**Issue by theArch2** [mgp25/WhatsAPI-Official#365]
Hi,

until today a was just a reader which followed the issues, today i have one :(
Some things at first:
- i'm doing no spam (as most of issues which containing the keyword "broadcast" will be closed immediately)
- all recipients have my number in their list, guaranteed. 
- yesterday everything was fine

today not: 
I send a broadcast once per day (sometimes two, sometimes none) to exactly 43 Numbers.
Since today it worked without problem, today about 60% of the recipients do not recieve the message. 

I send the broadcast with 
```php
sendBroadcastMessage($targets, $message)
```
In response i get 

```xml
<message to="1423560532@broadcast" type="text" id="broadcast-1423560532-142">
tx    <broadcast>
tx      <to jid="49XXXXXXX@s.whatsapp.net"></to>
tx      <to jid="49XXXXXXX@s.whatsapp.net"></to>
tx      <to jid="49XXXXXXX@s.whatsapp.net"></to>
tx      <to jid="49XXXXXXX@s.whatsapp.net"></to>
tx      <to jid="49XXXXXXX@s.whatsapp.net"></to>
tx      <to jid="49XXXXXXX@s.whatsapp.net"></to>

[,,,]

</broadcast>
tx    <x xmlns="jabber:x:event">
tx      <server></server>
tx    </x>
tx    <body>The message i send</body>
tx  </message>

```

and some 
```xml
rx  <ack from="1423560532@broadcast" id="broadcast-1423560532-142" class="message" count="15" t="1423560533"></ack>
```

And some 
```xml
<receipt from="1423560532@broadcast" id="broadcast-1423560532-142" participant="49XXXXXXX@s.whatsapp.net" t="1423560535"></receipt>

```

As i can see, i get not for every participant the ack and reciept. 

Is there a change in the protocol or a WA-Bug? 

Regards,
theArch2

**Comment by mgp25** [comment]
@theArch2 You are using an outdated code, use latest code.

The node should be something like this:
```xml
<message to="1423560532@broadcast" type="text" id="broadcast-1423560532-142">
tx    <broadcast>
tx      <to jid="49XXXXXXX@s.whatsapp.net"></to>
tx    </broadcast>
tx    <body>The message i send</body>
tx  </message>
```

If the user hasnt received or read the message you dont get an ack. Make sure all the contacts have your number synced.

Its working fine, i just try it, and there were no changes.

Regards

**Comment by theArch2** [comment]
Hi,

i updated to latest code now. Same problem. If i send a broadcast to just two people it runs perfectly.
I noticed also that i got no response from server, just
```
tx  <message to="1423588064@broadcast" type="text" id="broadcast-1423588064-79">
tx    <body>Testmessage</body>
tx    <broadcast>
tx      <to jid="49XXXXX@s.whatsapp.net"></to>
tx      <to jid="49XXXXX@s.whatsapp.net"></to>
tx    </broadcast>
tx  </message>

```

As i said in my first post, all contacts have my number synced.

**Comment by mgp25** [comment]
Post the full debug log, its the only way i can help you. Full with all details, but it seems contacts are not synced, anyway send full debug log.

Regards

**Comment by mgp25** [comment]
check solution #371

**Comment by theArch2** [comment]
i tested it the same way, with just one or two numbers it runs perfectly, more numbers not. I noticed that if i send 4-5 broadcasts in short time less numbers recieve the message...maybe there is a new limitation by whatsapp? :/

**Comment by mgp25** [comment]
It could be, remember thats WhatsApp is trying to avoid users abusing their system, so if you try to send multiple broadcast it could affect to you.

The limit is 50 users per broadcast.

```php
rx      <prop name="broadcast" value="50"></prop>
```

**Comment by theArch2** [comment]
I know that limit...hm, at monday everything works perfect, its since yesterday morning.

**Comment by theArch2** [comment]
I can reproduce this with official wa-client. There is defintitly a bug/limitation on whatsapp-side :(

**Comment by mgp25** [comment]
Ill try to help you, contact me via mail

**Comment by mgp25** [comment]
@theArch2 If you are using a foreign number, remember to save in your contact list the number with '+', otherwise wont work.

Regards

**Comment by dennobaby** [comment]
It's a problem at WhatsApp:
http://www.hna.de/netzwelt/deutschlandweite-stoerung-whatsapp-4727056.html?cmp=defrss

**Comment by theArch2** [comment]
@dennobaby: i dont see your comment here, but i received the mail from github. Thanks for that, this confirmed my assumption that this is a problem of whatsapp...

**Comment by mos041184** [comment]
where to use this code in android device tell its step please i have a rooted note 3
