### ISSUE TITLE
Problem with registration

### ISSUE THREAD

**Issue by nthommen** [mgp25/WhatsAPI-Official#366]
I've tried to register my recieved registration code but always get the following error:

```
Array ( 
[cc] => 41 
[in] => 79UUXXXUU 
[id] => &þ m•wêìÕ¸ >î¤þ5 
[code] => 979057 
) stdClass Object ( 
[status] => fail 
[reason] => missing 
) 
An error occurred registering the registration code from WhatsApp.
```

Already saw the other closed issue regarding the same problem. I'm using the newest version. What am I doing wrong?

**Comment by mgp25** [comment]
@nthommen Are you using `registerTool.php`. Post here the full debug log.

Regards

**Comment by Ixtalo** [comment]
I cannot complete the registration process either.
I am using exampleRegister.php.

Error:
```
PHP Notice:  Undefined property: stdClass::$retry_after in /mnt/ramdisk/WhatsAPI-Official/src/whatsprot.class.php on line 291
PHP Fatal error:  Uncaught exception 'Exception' with message 'An error occurred registering the registration code from WhatsApp.' in /mnt/ramdisk/WhatsAPI-Official/src/whatsprot.class.php:297
Stack trace:
#0 /mnt/ramdisk/WhatsAPI-Official/examples/exampleRegister.php(81): WhatsProt->codeRegister('xxx-yyy')
#1 {main}
  thrown in /mnt/ramdisk/WhatsAPI-Official/src/whatsprot.class.php on line 297
```

**Comment by nthommen** [comment]
Yes I used the `registerTool.php` but changed it a bit so I could use it without the cli and directly with all the variables filled in and splitted in two files (getting the sms and getting the password). I didn't get any other output than the array. I did now use the android app to extract the password directly from the device which is working for now. But still the other way didnt work for me. thanks in advance

**Comment by mgp25** [comment]
@Ixtalo Read the wiki, its explained there. You have to put the code like xxxyyy not like xxx-yyy.

@nthommen If you want send me the number to my mail, ill try myself, once you got the code send it back to me, and ill tell you if i can register it successfuly.

Regards

**Comment by nthommen** [comment]
For now I will use the extract password method. Will come back if I need it differently. Thanks though! :-)

Best Regards :+1:
