### ISSUE TITLE
Number registration not work

### ISSUE THREAD

**Issue by IronGeiv** [mgp25/WhatsAPI-Official#367]
When i use exampleRegister.php, or registerTool.php, I always get the same error: 

```
[status] => fail 
[reason] => no_routes 
[retry_after] => 3600
```

I used your Api before, for two or three month, everything was fine until last two days, it stop working.
Can you help me please?

**Comment by mgp25** [comment]
@IronGeiv are you using the latest code and `registerTool.php`. Post the full debug log here.

Regards

**Comment by IronGeiv** [comment]
Yes, i am using last of your code.
Log:
Array ( 
[in] => 987721536 
[cc] => 380 
[id] => %92%32%B4%E6%45%3C%CB%0C%3E%AE%4A%DE%3A%15%88%0A 
[lg] => uk 
[lc] => UA 
[mcc] => 255 
[mnc] => 001 
[sim_mcc] => 255 
[sim_mnc] => 001 
[method] => sms 
[token] => g5RuOHr0ztHNZVcp2yv7Lka0%2B0w%3D 
[network_radio_type] => 1 ) 
stdClass Object ( [status] => fail [reason] => no_routes [retry_after] => 3600 ) 
Fatal error: Uncaught exception 'Exception' with message 'There was a problem trying to request the code.' in /Applications/AMPPS/www/WhatsAPI/src/whatsprot.class.php:420 Stack trace: #0 /Applications/AMPPS/www/WhatsAPI/examples/exampleRegister.php(25): WhatsProt->codeRequest('sms') #1 {main} thrown in /Applications/AMPPS/www/WhatsAPI/src/whatsprot.class.php on line 420

**Comment by mgp25** [comment]
@IronGeiv You are using an outdated code, download again and use `registerTool.php`, it will work, i`ll wait for your feedback

Regards.

**Comment by IronGeiv** [comment]
Ok, i will try right now.

**Comment by IronGeiv** [comment]
Hm, it's strange, i downloaded your code yesterday and it not working... Now it works! Thank you for your help!

**Comment by mgp25** [comment]
Great, you are welcome!
