### ISSUE TITLE
Add emoji for caption in images and videos

### ISSUE THREAD

**Issue by deizepi** [mgp25/WhatsAPI-Official#368]
Please, add 
```php    
$caption = $this->parseMessageForEmojis($caption);
```
for `sendMessageImage` and `sendMessageVideo` methods.

Thanks.

**Comment by mgp25** [comment]
Added.

Commit: https://github.com/mgp25/WhatsAPI-Official/commit/bdecbec293ec70226c6b9b884f0c6bdc5901be74

Regards

**Comment by everyusernameistaken123** [comment]
I am sorry for fetching this closed issue, but it seems like I am blind?
Where is the "parseMessageForEmojis" method?
I was interested how it works (how to send emoticons?)?

**Comment by mgp25** [comment]
@everyusernameistaken123 https://github.com/mgp25/Chat-API/wiki/Frequently-asked-questions#how-can-i-send-emojis

**Comment by everyusernameistaken123** [comment]
Thank you, I was thinking about the issues but not about the FAQs, shame on me :(
Yesterday I also tried to "revert" this method: https://github.com/mgp25/Chat-API/issues/482 which also did work.
