### ISSUE TITLE
TokenMap is messed up

### ISSUE THREAD

**Issue by poma** [mgp25/WhatsAPI-Official#372]
This issue is for `WhatsAPINet` repository. It doesn't have an issue tracker so I'll post it here.

The read receipts cause an exception. It looks like

    <receipt from="request" preview="digest" s.us="order" digest="name" s.whatsapp.net="id"></receipt>

instead of

    <receipt from="123@s.whatsapp.net" id="1425789830-0" retry="2" offline="2" t="1445750671"></receipt>

I tried to replace `TokenMap.cs` and `BinTreeNodeWriter.cs` from @shirioko's fork and it started to work correctly. The bug is narrowed down so it should take little time to fix it.

STR: 
1. Send a message from WhatsTest
2. As soon an recipient receives it the program will throw an exception

**Comment by CODeRUS** [comment]
https://github.com/perezdidac/WhatsAPINet/issues
