### ISSUE TITLE
how do I get the return function

### ISSUE THREAD

**Issue by aldisseia** [mgp25/WhatsAPI-Official#375]
```php
function GetGroups($mynumber, $groups) {
/* $i = 0;
$grupos = "";
foreach ($groups as $gg) {
$grupos .= $i."°)".
'IDG: '. $gg['id'].'
'.
'ID: '. $gg['owner'].'
'.
'Criado em: '.date("d/m/Y G:i:s", $gg['creation']).'
'.
'Nome: '. $gg['subject'].'
'.
's_t: '. $gg['s_t'].'
'.
's_o: '. $gg['s_o'].'

'; 
}
echo utf8_decode($grupos); //show*/
return ($grupos) //get the return???
}

$w->eventManager()->bind("onGetGroups", "GetGroups");
$w->Connect();
$w->LoginWithPassword($password);
$w->sendGetGroups();

print_r(return function????);
```

**Comment by mgp25** [comment]
@aldisseia this is not an API issue/question, its related to PHP.

Anyway, you can do it like this:
```php
function GetGroups($mynumber, $groups) {
     return ($groups);
}

$w->eventManager()->bind("onGetGroups", "GetGroups");
$w->Connect();
$w->LoginWithPassword($password);
$result = $w->sendGetGroups();

print_r($result);
```

**Comment by phpjoker** [comment]
@mgp25 Are you sure!?
$w->sendGetGroups() does not return any result, only NULL!!!
it's only send a request to whatsapp server...
please guide me better.

Regard.

**Comment by mgp25** [comment]
Please guide me better? Wtf man.... im getting very tired of this shit.

Post your debug log

**Comment by phpjoker** [comment]
this function works fine: $w->sendGetGroups()
but return variable in this function
```
function GetGroups($mynumber, $groups) {
     return ($groups);
}
```
Where is assigned?

**Comment by mgp25** [comment]
@phpjoker can you please send debug log?

**Comment by phpjoker** [comment]
```
function GetGroups($phone, $groups)
{
	     return ($groups);
}

$w = new WhatsProt($username, $identity, $nickname, $debug);
$w->eventManager()->bind("onGetGroups","GetGroups");
$w->Connect();
$w->LoginWithPassword($password);
$w->sendGetPrivacyBlockedList();
$w->sendClientConfig();
$w->sendGetServerProperties();
$w->sendGetHasVoipEnabled($contacts);
$result= $w->sendGetGroups();
var_dump($result);
```
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="xxxxxx">ƒhC989011248415{pç…ے¢$گ–nwi–7i}«1424009639WhatsApp/2.12.61 S40Version/14.26 Device/Nokia302 MccMnc/432001</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>ڑغu½=ه S
V¥ط_W}cO«	</challenge>

tx  <response>„½£غ6ي{¦XJrئ8w¥™اھكRo"ّشلج¥w],A؛s</response>

rx  <success t="1424009638" props="4" kind="free" status="active" creation="1423312330" expiration="1454848330">ز‍Kd'سو"سïRـچ¼\>[}w</success>

tx  <presence name="xxxx"></presence>

tx  <iq id="getprivacy-1424009639-1" xmlns="jabber:iq:privacy" type="get">
tx    <query>
tx      <list name="default"></list>
tx    </query>
tx  </iq>

rx  <ib from="s.whatsapp.net">
rx    <offline count="0"></offline>
rx  </ib>

rx  <presence from="xxxx@s.whatsapp.net"></presence>

rx  <iq from="xxxx@s.whatsapp.net" id="getprivacy-1424009639-1" type="error">
rx    <error code="404" text="item-not-found"></error>
rx  </iq>

tx  <iq id="config-1424009640-2" type="set" xmlns="urn:xmpp:whatsapp:push" to="s.whatsapp.net">
tx    <config platform="none" lc="CA" lg="en"></config>
tx  </iq>

tx  <iq id="getproperties-1424009640-3" type="get" xmlns="w" to="s.whatsapp.net">
tx    <props></props>
tx  </iq>

tx  <iq id="voip_-1424009640-4" xmlns="voip" type="get" to="s.whatsapp.net">
tx    <eligible>
tx      <user jid="xxx@s.whatsapp.net"></user>
tx      <user jid="xxx@s.whatsapp.net"></user>
tx      <user jid="xxx@s.whatsapp.net"></user>
tx      <user jid="xxx@s.whatsapp.net"></user>
tx    </eligible>
tx  </iq>

tx  <iq id="getgroups-1424009640-5" type="get" xmlns="w:g2" to="g.us">
tx    <participating></participating>
tx  </iq>

rx  <presence from="xxx@s.whatsapp.net"></presence>

rx  <presence from="xxx@s.whatsapp.net"></presence>

rx  <iq from="s.whatsapp.net" id="config-1424009640-2" type="result"></iq>

rx  <iq from="s.whatsapp.net" id="getproperties-1424009640-3" type="result">
rx    <props version="4">
rx      <prop name="timeout" value="300"></prop>
rx      <prop name="location" value="0"></prop>
rx      <prop name="readreceipts" value="1415214000"></prop>
rx      <prop name="qr" value="0"></prop>
rx      <prop name="groups_v2" value="1"></prop>
rx      <prop name="lists" value="1"></prop>
rx      <prop name="library" value="0"></prop>
rx      <prop name="audio" value="1"></prop>
rx      <prop name="checkmarks" value="0"></prop>
rx      <prop name="newmedia" value="0"></prop>
rx      <prop name="image_max_kbytes" value="5120"></prop>
rx      <prop name="image_quality" value="80"></prop>
rx      <prop name="image_max_edge" value="1280"></prop>
rx      <prop name="media" value="16"></prop>
rx      <prop name="broadcast" value="50"></prop>
rx      <prop name="max_subject" value="25"></prop>
rx      <prop name="max_participants" value="101"></prop>
rx      <prop name="max_groups" value="9999"></prop>
rx    </props>
rx  </iq>

rx  <iq from="g.us" id="getgroups-1424009640-5" type="result">
rx    <groups>
rx      <group id="xxx-1394918866" creator="xxx@s.whatsapp.net" creation="1394918866" subject="ًxxx" s_t="1422217662" s_o="xxx@s.whatsapp.net" type="locked">
rx        <participant jid="xxx@s.whatsapp.net"></participant>
rx        <participant jid="xxx@s.whatsapp.net"></participant>
rx        <participant jid="xxx@s.whatsapp.net"></participant>
rx        <participant jid="xxx@s.whatsapp.net" type="admin"></participant>
rx        <participant jid="xxx@s.whatsapp.net"></participant>
rx        <participant jid="xxx@s.whatsapp.net" type="admin"></participant>
rx        <participant jid="xxx@s.whatsapp.net"></participant>
rx      </group>
rx      <group id="xxx-1403778040" creator="xxx@s.whatsapp.net" creation="1403778040" subject="xxx" s_t="1416603103" s_o="xxx@s.whatsapp.net" type="locked">
rx        <participant jid="xxx@s.whatsapp.net"></participant>
rx        <participant jid="xxx@s.whatsapp.net" type="admin"></participant>
rx        <participant jid="xxx@s.whatsapp.net"></participant>
rx        <participant jid="xxx@s.whatsapp.net"></participant>
rx      </group>
rx    </groups>
rx  </iq>

NULL
```

**Comment by mgp25** [comment]
As you can see, its working perfectly:

```xml
<iq from="g.us" id="getgroups-1424009640-5" type="result">
rx    <groups>
rx      <group id="xxx-1394918866" creator="xxx@s.whatsapp.net" creation="1394918866" subject="ًxxx" s_t="1422217662" s_o="xxx@s.whatsapp.net" type="locked">
rx        <participant jid="xxx@s.whatsapp.net"></participant>
rx        <participant jid="xxx@s.whatsapp.net"></participant>
rx        <participant jid="xxx@s.whatsapp.net"></participant>
rx        <participant jid="xxx@s.whatsapp.net" type="admin"></participant>
rx        <participant jid="xxx@s.whatsapp.net"></participant>
rx        <participant jid="xxx@s.whatsapp.net" type="admin"></participant>
rx        <participant jid="xxx@s.whatsapp.net"></participant>
rx      </group>
rx      <group id="xxx-1403778040" creator="xxx@s.whatsapp.net" creation="1403778040" subject="xxx" s_t="1416603103" s_o="xxx@s.whatsapp.net" type="locked">
rx        <participant jid="xxx@s.whatsapp.net"></participant>
rx        <participant jid="xxx@s.whatsapp.net" type="admin"></participant>
rx        <participant jid="xxx@s.whatsapp.net"></participant>
rx        <participant jid="xxx@s.whatsapp.net"></participant>
rx      </group>
rx    </groups>
rx  </iq>
```

Your code should be this one:

```php
function GetGroups($phone, $groups)
{
         var_dump($groups);
}

$w = new WhatsProt($username, $identity, $nickname, $debug);
$w->eventManager()->bind("onGetGroups","GetGroups");
$w->Connect();
$w->LoginWithPassword($password);
$w->sendGetPrivacyBlockedList();
$w->sendClientConfig();
$w->sendGetServerProperties();
$w->sendGetHasVoipEnabled($contacts);
$w->sendGetGroups();
```

This is a PHP question, not API related, im not longer to answer PHP related questions, only API related, you can find also information using google

Regards

**Comment by phpjoker** [comment]
Thanx, I know this but you say in previous post: $result= $w->sendGetGroups();
In any case, thank you for all your hard work
