### ISSUE TITLE
Get all existing messages

### ISSUE THREAD

**Issue by IronGeiv** [mgp25/WhatsAPI-Official#376]
Hi again!! =)
I had such question, can i get all of the messages from chat of one user? 
When i using  <code>$w->pullMessage()</code> i get only last messages and only once, if they market as "read" then i can't get them, can i recieve all messages at once from one number?

**Comment by CODeRUS** [comment]
whatsapp not keeping your chat history, only unread messages not delivered to you since you last offline. you should store your messages yourself.

**Comment by IronGeiv** [comment]
@CODeRUS Ok. Thank you.
