### ISSUE TITLE
Problem with Extraction on Nexus one

### ISSUE THREAD

**Issue by srikumar101** [mgp25/WhatsAPI-Official#377]
Hi, 

First of all congratualtions. as this is now official.. 

I am trying to get it working (The WA password extractor apk) on HTC Nexus one.. when I click on "Extract" button it throws and error saying - "couldn't find 'su' command. Are you root?" 

My first guess was I haven't rooted my device properly.. when I checked this link - http://forums.androidcentral.com/google-nexus-one-rooting-roms-hacks/57228-how-root-your-nexus-one.html

It says.. we only need to unlock Nexus one and no need to root it.. Can you please help me on getting this working on HTC nexus one?

**Comment by mgp25** [comment]
Read carefully, is says:

```
Choose YES to unlock your phone and void your warranty, and you're done. At this point you can install a custom recovery and/or a custom ROM with root enabled.
```

You still need to install a custom ROM witn root enabled. Or root your phone.

Once you have it rooted it will work.

Regards
