### ISSUE TITLE
Whats is the difference between sendPing and sendPing?

### ISSUE THREAD

**Issue by rayidi** [mgp25/WhatsAPI-Official#378]
Hi Guys,

I can understand `sendPong()` function will `* Sends a pong to the whatsapp server. I'm alive!`
But i don't understand what `sendPing()` function will do?

Whats was the difference beween these two?

**Comment by CODeRUS** [comment]
sendPing is sending ping message to server. sendPong is sending reply to server when we receiving ping from server, and it shuoldn't be called manually.
