### ISSUE TITLE
sendGetGroupV2Info Error

### ISSUE THREAD

**Issue by moosaviamir** [mgp25/WhatsAPI-Official#379]
Hello all
I want to get group participants so when i run the following code:
```php
$username = "***************"; 
$password = "*************************************;
$w = new WhatsProt($username, 0, "****", true);
$w->sendGetGroupV2Info("****************-**********");

for($i = 0; $i < 5; $i++) {
    $w->pollMessage();
}
```
I get this response:
```xml
tx  <iq id="get_groupv2_info-1423830351-1" xmlns="w:g2" type="get" to="**************-*********@g.us">
tx    <query request="interactive"></query>
tx  </iq>


Fatal error: Uncaught exception 'ConnectionException' with message 'Connection Closed!' in C:\xampp\htdocs\WAO\src\whatsprot.class.php:617 Stack trace: #0 C:\xampp\htdocs\WAO\src\t2.php(21): WhatsProt->pollMessage() #1 {main} thrown in C:\xampp\htdocs\WAO\src\whatsprot.class.php on line 617
```
please help me.

**Comment by mgp25** [comment]
Update the whole code... Not only the whatsprot.class.php...

Regards

**Comment by moosaviamir** [comment]
I did update the whole code!!! this error is from new WhatsAPI-Official one.

**Comment by mgp25** [comment]
@moosaviamir post your code

**Comment by moosaviamir** [comment]
```
<?php
require_once("./whatsprot.class.php");
 
$username = "********************"; 
$password = "**********************************";

$w = new WhatsProt($username, 0, "a", true);
$w->sendGetGroupV2Info("*****************-***********");

for($i = 0; $i < 5; $i++) {
    $w->pollMessage();
}

?>
```

**Comment by mgp25** [comment]
@moosaviamir you need to login!

```php
$w = new WhatsProt($username, $identity, $nickname, $debug);
$w->connect();
$w->loginWithPassword($password);
```

**Comment by moosaviamir** [comment]
:(((((((((( I'm very sorry to make such a fool mistake! thank you! 
But how can i get group participants ???

**Comment by mgp25** [comment]
```php
sendGetGroupsParticipants($gjid)
```

Please all this information can be found in the wiki: https://github.com/mgp25/WhatsAPI-Official/wiki

**Comment by moosaviamir** [comment]
Dear mpg25:
Didn't you just tell me : 
"(sendGetGroupsParticipants($gjid))that function you are using is deprecated."
In [This Issue](https://github.com/venomous0x/WhatsAPI/issues/1105#issuecomment-74236450) and then redirected me to this function "sendGetGroupV2Info".
Now your telling me using sendGetGroupsParticipants?

**Comment by mgp25** [comment]
@moosaviamir use `sendGetGroupV2Info` and `onGetGroupV2Info` event.

`onGetGroupV2Info( $mynumber, $creator, $creation, $subject, $participants, $admin )`
