### ISSUE TITLE
how to delete contact list??

### ISSUE THREAD

**Issue by aldisseia** [mgp25/WhatsAPI-Official#380]
use this to pick up groups:

function GetGroups($mynumber, $groups) {}
function onMessageg($mynumber, $from_group_jid, $from_user_jid, $id, $type, $time, $name, $body) {}
w->eventManager()->bind("onGetGroups", "GetGroups");
$w->eventManager()->bind("onGetGroupMessage", "onMessageg")
w->Connect();
$w->LoginWithPassword($password);
while ($w->sendGetGroups());

and to get contacts?

**Comment by CODeRUS** [comment]
contacts are not saved on server. you need to store them yourself localy.

**Comment by aldisseia** [comment]
So I have to make a sync this data, how do it?

**Comment by CODeRUS** [comment]
you should store your contacts yourself in any format

**Comment by aldisseia** [comment]
so, how do I get this data?
one ves with the data I can put in bd ...
you have an example?

**Comment by CODeRUS** [comment]
what data do you want to get?

**Comment by aldisseia** [comment]
my contacts

**Comment by CODeRUS** [comment]
should i know what contacts you want to send a messages?

**Comment by aldisseia** [comment]
as well as have the list of groups, I have a contact list on WhatsApp, how do I handle it?

**Comment by CODeRUS** [comment]
whatsapp server not keeping your contacts list.

**Comment by aldisseia** [comment]
using onGetSyncResult existe a possibilidade de pegar o nome da pessoa?

**Comment by mgp25** [comment]
No, its not possible to get the contacts name, it will only appear in the `notify`field when you receive a message only.

Regards

**Comment by aldisseia** [comment]
Thank!
