### ISSUE TITLE
pollMessage

### ISSUE THREAD

**Issue by androidworldbh** [mgp25/WhatsAPI-Official#381]
Hi everybody .. I'm facing a problem really don't know how to solve it  .. all what i want is to receive messages, but i got nothing .. there's no errors .. just blank page ..     here d code and what's wrong with it? 
```php
<?php

require_once '../src/whatsprot.class.php';
require '../src/AllEvents.php';
date_default_timezone_set('Asia/Bahrain');
$username = "789789";                      
$password = "***************";
$identity = "identitycodeshits";     
$nickname = "anything";
$target = "123456";
$debug = true;                           

function onMessage($mynumber, $from, $id, $type, $time, $name, $body)
{
    echo "Message from $name:\n$body\n\n";
}

$w = new WhatsProt($username, $token, $nickname, false);
$w->eventManager()->bind("onGetMessage", "onMessage");
$w->Connect();
$w->LoginWithPassword($password);
for($i = 0; $i < 10; $i++)
{
    $w->pollMessage();

}
```

**Comment by fermino** [comment]
Are you using the latest version?

**Comment by androidworldbh** [comment]
yes definitely

**Comment by fermino** [comment]
AllEvents.php doesn't exists in /src/.
Please write error_reporting(E_ALL); before your code and post the output.

**Comment by androidworldbh** [comment]
I've added this file .. it just contains functions

**Comment by androidworldbh** [comment]
here it is AllEvents.php

<?php
abstract class AllEvents
{
    protected $eventsToListenFor = array();
    protected $whatsProt;
    public function __construct(WhatsProt $whatsProt)
    {
        $this->whatsProt = $whatsProt;
        return $this;
    }
    /**
     * Register the events you want to listen for.
     *
     * @param array $eventList
     * @return AllEvents
     */
    public function setEventsToListenFor(array $eventList)
    {
        $this->eventsToListenFor = $eventList;
        return $this->startListening();
    }
    /**
     * Binds the requested events to the event manager.
     * @return $this
     */
    protected function startListening()
    {
        foreach ($this->eventsToListenFor as $event) {
            if (is_callable(array($this, $event))) {
                $this->whatsProt->eventManager()->bind($event, array($this, $event));
            }
        }
        return $this;
    }

   
    
    //Adding to this list? Please put them in alphabetical order!
    public function onClose($mynumber, $error){}
    public function onCodeRegister( $mynumber, $login, $password, $type, $expiration, $kind, $price, $cost, $currency, $price_expiration ){}
    public function onCodeRegisterFailed( $mynumber, $status, $reason, $retry_after ){}
    public function onCodeRequest( $mynumber, $method, $length ){}
    public function onCodeRequestFailed( $mynumber, $method, $reason, $param ){}
    public function onCodeRequestFailedTooRecent( $mynumber, $method, $reason, $retry_after ){}
    public function onCodeRequestFailedTooManyGuesses( $mynumber, $method, $reason, $retry_after ){}
    public function onConnect( $mynumber, $socket ) {}
    public function onConnectError( $mynumber, $socket ){}
    public function onCredentialsBad( $mynumber, $status, $reason ){}
    public function onCredentialsGood( $mynumber, $login, $password, $type, $expiration, $kind, $price, $cost, $currency, $price_expiration ){}
    public function onDisconnect( $mynumber, $socket ) {}
    public function onDissectPhone( $mynumber, $phonecountry, $phonecc, $phone, $phonemcc, $phoneISO3166, $phoneISO639, $phonemnc ) {}
    public function onDissectPhoneFailed( $mynumber ){}
    public function onGetAudio( $mynumber, $from, $id, $type, $time, $name, $size, $url, $file, $mimeType, $fileHash, $duration, $acodec ){}
    public function onGetBroadcastLists( $mynumber, $broadcastLists ){}
    public function onGetError( $mynumber, $from, $id, $data ){}
    public function onGetExtendAccount( $mynumber, $kind, $status, $creation, $expiration ){}
    public function onGetFeature( $mynumber, $from, $encrypt ){}
    public function onGetGroupMessage( $mynumber, $from_group_jid, $from_user_jid, $id, $type, $time, $name, $body ){}
    public function onGetGroupParticipants( $mynumber, $groupId, $groupList ){}
    public function onGetGroups( $mynumber, $groupList ){}
    public function onGetGroupsInfo( $mynumber, $groupList ){}
    public function onGetGroupV2Info( $mynumber, $creator, $creation, $subject, $participants, $admin ){}
    public function onGetGroupsSubject( $mynumber, $group_jid, $time, $author, $name, $subject ){}
    public function onGetImage( $mynumber, $from, $id, $type, $time, $name, $size, $url, $file, $mimeType, $fileHash, $width, $height, $preview, $caption ){}
    public function onGetGroupImage( $mynumber, $from_group_jid, $from_user_jid, $id, $type, $time, $name, $size, $url, $file, $mimeType, $fileHash, $width, $height, $preview, $caption ){}
    public function onGetGroupVideo( $mynumber, $from_group_jid, $from_user_jid, $id, $type, $time, $name, $url, $file, $size, $mimeType, $fileHash, $duration, $vcodec, $acodec, $preview, $caption ){}
    public function onGetKeysLeft( $mynumber, $keysLeft){}
    public function onGetLocation( $mynumber, $from, $id, $type, $time, $name, $name, $longitude, $latitude, $url, $preview ){}
    public function onGetMessage( $mynumber, $from, $id, $type, $time, $name, $body ){    echo "Message from $name:\n$body\n\n";
    
    }
    public function onGetNormalizedJid( $mynumber, $data ){}
    public function onGetPrivacyBlockedList( $mynumber, $data ){}
    public function onGetProfilePicture( $mynumber, $from, $type, $data ){}
    public function onGetReceipt( $from, $id, $offline, $retry ){}
    public function onGetRequestLastSeen( $mynumber, $from, $id, $seconds ){}
    public function onGetServerProperties( $mynumber, $version, $props ){}
    public function onGetServicePricing( $mynumber, $price, $cost, $currency, $expiration ){}
    public function onGetStatus( $mynumber, $from, $requested, $id, $time, $data ){}
    public function onGetSyncResult( $result ){}
    public function onGetVideo( $mynumber, $from, $id, $type, $time, $name, $url, $file, $size, $mimeType, $fileHash, $duration, $vcodec, $acodec, $preview, $caption ){}
    public function onGetvCard( $mynumber, $from, $id, $type, $time, $name, $vcardname, $vcard ){}
    public function onGroupCreate( $mynumber, $groupId ){}
    public function onGroupisCreated( $mynumber, $creator, $gid, $subject, $admin, $creation ){}
    public function onGroupsChatCreate( $mynumber, $gid ){}
    public function onGroupsChatEnd( $mynumber, $gid ){}
    public function onGroupsParticipantsAdd( $mynumber, $groupId, $jid ){}
    public function onGroupsParticipantsRemove( $mynumber, $groupId, $jid){}
    public function onLogin( $mynumber ){}
    public function onLoginFailed( $mynumber, $data ){}
    public function onAccountExpired( $mynumber, $kind, $status, $creation, $expiration ){}
    public function onMediaMessageSent( $mynumber, $to, $id, $filetype, $url, $filename, $filesize, $filehash, $caption, $icon ){}
    public function onMediaUploadFailed( $mynumber, $id, $node, $messageNode, $statusMessage ){}
    public function onMessageComposing( $mynumber, $from, $id, $type, $time ){}
    public function onMessagePaused( $mynumber, $from, $id, $type, $time ){}
    public function onMessageReceivedClient( $mynumber, $from, $id, $type, $time ){}
    public function onMessageReceivedServer( $mynumber, $from, $id, $type, $time ){}
    public function onPaidAccount( $mynumber, $author, $kind, $status, $creation, $expiration ){}
    public function onPing( $mynumber, $id ){}
    public function onPresence( $mynumber, $from, $status ){}
    public function onProfilePictureChanged( $mynumber, $from, $id, $time ){}
    public function onProfilePictureDeleted( $mynumber, $from, $id, $time ){}
    public function onSendMessage( $mynumber, $target, $messageId, $node ){}
    public function onSendMessageReceived( $mynumber, $id, $from, $type ){}
    public function onSendPong( $mynumber, $msgid ){}
    public function onSendPresence( $mynumber, $type, $name ){}
    public function onSendStatusUpdate( $mynumber, $txt ){}
    public function onStreamError( $data ){}
    public function onUploadFile( $mynumber, $filename, $url ){}
    public function onUploadFileFailed( $mynumber, $filename ){}
}

**Comment by androidworldbh** [comment]
I've tried this code and eventually i got something but can't be read .. encrypted msgs .. so the next step .. how to solve this issue again ? .. I'm bad in PHP by d way .. 

$w = new WhatsProt($username, $identity, $nickname, $debug); 

//$events = new MyEvents($w);

$w->connect();
$w->loginWithPassword($password);

$w->pollMessage();
$data = $w->getMessages();
if(!empty($data)) print_r($data);
$i = 0;
for($i; $i < 2; $i++)
{
     $w->pollMessage();
} 
$w->disconnect();
?>

**Comment by mgp25** [comment]
@androidworldbh post your debug log.

**Comment by androidworldbh** [comment]
tx  <stream:features></stream:features>

tx  <auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="WAUTH-2" user="12139159391">¢ðŠÍ12139159391ÜDi:6yƒówìö`	ÜÓÈ“ñ1423927581WhatsApp/2.11.378 Android/4.3 Device/GalaxyS3 MccMnc/310001</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>­ jŽ¿^ÐpR­>:0©^Ç</challenge>

tx  <response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">¥…]m0FFï¨PcìÃf730öâ9~¨Þö	Þh¢ Œv</response>

rx  <success t="1423927582" props="4" kind="free" status="active" creation="1423315335" expiration="1454851335"> 
tx  <presence name="AndroidWorldBH"></presence>

rx  <message from="97332224585@s.whatsapp.net" id="1423890149-4" retry="3" offline="3" type="text" t="1423891481" notify="ðŸ˜¶">
rx    <enc v="1" type="pkmsg" av="Android/2.11.520">3­Ü!ùÈºî—Ô)ÒYTH„xµi¥)?ÉÌ–:[ñ62,!ááˆ„ZðÈÏ0ÜS9¼frÛ%st×7ƒîZ•–í/"B3 !»‡î{;¯Q ÿ)*òùñï#òÅ A»¿_Øv= "§¨)¨9Û¡€Ó'ÉëÈ¼| 4xž{(¾öÒF0</enc>
rx  </message>

rx  <receipt from="97332003350@s.whatsapp.net" id="message-1423871317-6" offline="0" t="1423894747"></receipt>

rx  <receipt from="97332003350@s.whatsapp.net" id="message-1423871681-6" offline="0" t="1423894747"></receipt>

rx  <receipt from="97332003350@s.whatsapp.net" id="message-1423871681-6" offline="0" t="1423894754">
rx    <list>
rx      <item id="message-1423871317-6"></item>
rx    </list>
rx  </receipt>

rx  <receipt from="97338889317@s.whatsapp.net" id="message-1423871190-6" offline="0" t="1423898471">
rx    <list>
rx      <item id="message-1423871555-6"></item>
rx    </list>
rx  </receipt>

rx  <receipt from="97332003350@s.whatsapp.net" id="message-1423901514-4" offline="0" t="1423901514"></receipt>

rx  <receipt from="97332003350@s.whatsapp.net" id="message-1423901514-4" offline="0" t="1423901521"></receipt>

rx  <receipt from="97333221616@s.whatsapp.net" id="message-1423901518-5" offline="0" t="1423902708"></receipt>

rx  <receipt from="97333221616@s.whatsapp.net" id="message-1423901518-5" offline="0" t="1423902907"></receipt>

rx  <receipt from="966557688853@s.whatsapp.net" id="message-1423871559-7" offline="0" t="1423908173">
rx    <list>
rx      <item id="message-1423871195-7"></item>
rx    </list>
rx  </receipt>

rx  <presence from="12139159391@s.whatsapp.net"></presence>

**Comment by androidworldbh** [comment]
Http://www.androidworldbh.com/Screenshot.jpg

**Comment by androidworldbh** [comment]
```php

tx  <stream:features></stream:features>

tx  <auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="WAUTH-2" user="12139159391">¢ðŠÍ12139159391ÜDi:6yƒówìö`	ÜÓÈ“ñ1423927581WhatsApp/2.11.378 Android/4.3 Device/GalaxyS3 MccMnc/310001</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>­ jŽ¿^ÐpR­>:0©^Ç</challenge>

tx  <response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">¥…]m0FFï¨PcìÃf730öâ9~¨Þö	Þh¢ Œv</response>

rx  <success t="1423927582" props="4" kind="free" status="active" creation="1423315335" expiration="1454851335"> 
tx  <presence name="AndroidWorldBH"></presence>

rx  <message from="97332224585@s.whatsapp.net" id="1423890149-4" retry="3" offline="3" type="text" t="1423891481" notify="ðŸ˜¶">
rx    <enc v="1" type="pkmsg" av="Android/2.11.520">3­Ü!ùÈºî—Ô)ÒYTH„xµi¥)?ÉÌ–:[ñ62,!ááˆ„ZðÈÏ0ÜS9¼frÛ%st×7ƒîZ•–í/"B3 !»‡î{;¯Q ÿ)*òùñï#òÅ A»¿_Øv= "§¨)¨9Û¡€Ó'ÉëÈ¼| 4xž{(¾öÒF0</enc>
rx  </message>

rx  <receipt from="97332003350@s.whatsapp.net" id="message-1423871317-6" offline="0" t="1423894747"></receipt>

rx  <receipt from="97332003350@s.whatsapp.net" id="message-1423871681-6" offline="0" t="1423894747"></receipt>

rx  <receipt from="97332003350@s.whatsapp.net" id="message-1423871681-6" offline="0" t="1423894754">
rx    <list>
rx      <item id="message-1423871317-6"></item>
rx    </list>
rx  </receipt>

rx  <receipt from="97338889317@s.whatsapp.net" id="message-1423871190-6" offline="0" t="1423898471">
rx    <list>
rx      <item id="message-1423871555-6"></item>
rx    </list>
rx  </receipt>

rx  <receipt from="97332003350@s.whatsapp.net" id="message-1423901514-4" offline="0" t="1423901514"></receipt>

rx  <receipt from="97332003350@s.whatsapp.net" id="message-1423901514-4" offline="0" t="1423901521"></receipt>

rx  <receipt from="97333221616@s.whatsapp.net" id="message-1423901518-5" offline="0" t="1423902708"></receipt>

rx  <receipt from="97333221616@s.whatsapp.net" id="message-1423901518-5" offline="0" t="1423902907"></receipt>

rx  <receipt from="966557688853@s.whatsapp.net" id="message-1423871559-7" offline="0" t="1423908173">
rx    <list>
rx      <item id="message-1423871195-7"></item>
rx    </list>
rx  </receipt>

rx  <presence from="12139159391@s.whatsapp.net"></presence>


```

**Comment by mgp25** [comment]
@androidworldbh You are using outdated code, update it and register your number again with the updated code in order to receive unencrypted messages.

**Comment by jesussales** [comment]
Are there solution for enc messages ?? Libxtool is just working? ?

**Comment by mgp25** [comment]
@jesussales yes, no.

Update to latest code and register your number again, that will prevent message encryption.

Regards

**Comment by androidworldbh** [comment]
You mean i sould register my number using the api?

And how to? .. i couldn't understand the wiki t be honest my English is not
that good

So is there any step by step instructions?

**Comment by mgp25** [comment]
@androidworldbh Yes, everything its explained step by step in the wiki: https://github.com/mgp25/WhatsAPI-Official/wiki

Number registration: https://github.com/mgp25/WhatsAPI-Official/wiki/WhatsAPI-Documentation#number-registration

Use `registerTool.php`

**Comment by androidworldbh** [comment]
Thaanks .. gonna try it tonight :D
