### ISSUE TITLE
Simple CLI not working properly

### ISSUE THREAD

**Issue by nesttle** [mgp25/WhatsAPI-Official#382]
Dear sir

I'm testing the example files, and some functions are not working:
```php
            switch ($command) {
                case "/query":
                    $dst = trim(strstr($line, ' ', FALSE));
                    echo "[] Interactive conversation with $contact:\n";
                    break;
                case "/lastseen":
                    echo "[] Last seen $target: ";
                    $w->sendGetRequestLastSeen($target);
                    break;
                default:
                    $w->sendMessage($target , $line);
                    break;
            }
```
When I type `/query` in cmd and type some text, nothing happens!

Some tips?

Thanks and keep this good work!

**Comment by mgp25** [comment]
When you type `/query` it will only print the contact you are chatting with.

Regards

**Comment by nesttle** [comment]
Done, example functional working nice, can talk via command prompt!

One more thing sir (don't want to flood this section opening new topics):

How can I get group list? sendGetGroupsFiltered or getGroupList? 

Can't find any example :(

Gracias crack! :+1:

**Comment by mgp25** [comment]
You have to code `sendGetGroups` function. All the documentation is in the wiki: https://github.com/mgp25/WhatsAPI-Official/wiki

using events: https://github.com/mgp25/WhatsAPI-Official/wiki/WhatsAPI-Documentation#using-events

**Comment by nesttle** [comment]
sendGetGroups already exists sir!

File: whatsprot.class.php
    public function sendGetGroups()
    {
        $this->sendGetGroupsFiltered("participating");
    }
    /**
     * Send the getGroupList request to Whatsapp
     * @param  string $type Type of list of groups to retrieve. "owning" or "participating"
     */
    protected function sendGetGroupsFiltered($type)
    {
        $msgID = $this->createMsgId("getgroups");
        $child = new ProtocolNode($type, null, null, null);
        $node = new ProtocolNode("iq", array(
            "id" => $msgID,
            "type" => "get",
            "xmlns" => "w:g2",
            "to" => "g.us"
                ), array($child), null);
        $this->sendNode($node);
        $this->waitForServer($msgID);
    }

But can't show results on command prompt :(

**Comment by mgp25** [comment]
@nesttle Please read the wiki! you need to code the binded function to the event! 

When you are doing this:

```php
$w->eventManager()->bind("onGetGroups", "sendGetGroups");
```

You are telling that when `onGetGroups` occurs then a function named `sendGetGroups` will be called, so in your own script you need to code a function named like that. if you do this:


```php
$w->eventManager()->bind("onGetGroups", "whatever");
```

You will need to code the function `whatever`

Please, everything its explained in the wiki and how to manage and use events.

Regards

**Comment by nesttle** [comment]
Gotcha! :+1: :)

Will try today, if I have some issues I'll be bothering you a bit (again)

Thanks!
