### ISSUE TITLE
Doc/src incoherence about number registration

### ISSUE THREAD

**Issue by realtebo** [mgp25/WhatsAPI-Official#383]
I'm reading the doc here: https://github.com/mgp25/WhatsAPI-Official/wiki/WhatsAPI-Documentation#number-registration

About this command

    $w = new WhatsProt($username, $identity, $nickname, $debug);

    Identity: The name of the file where is going to be saved the identity. This string is used for retrieving a new password.

Am I uderstanding well? It's a file name? So must I choose a 'blablabla.txt' as file name?

I was thinking in this way, until I reached the source code at exampleRegister.php whwre $identity is commented as

     // Obtained during registration with this API or using MissVenom

And so? Can I obtain identity using only the api or not? 

PS: Please, just a suggestion: don't call $username a phone number variable. It's not good

**Comment by mgp25** [comment]
@realtebo Use the information found on the wiki, some examples may have outdated information, ill update right now.

Yes, when you set `$identity = "identity";` a file called `identity.dat` will be created and your identity will be stored in there. This info can be found in the wiki.

Actually the username its our phone number, so it makes sense, its how WhatsApp works.

I'll update the info.

Regards
