### ISSUE TITLE
Mark group message as read/delivered.

### ISSUE THREAD

**Issue by viniciusjarina** [mgp25/WhatsAPI-Official#384]
Hello @mgp25 thank you very much for this awesome library.

I was trying to read messages from the group, but I couldn't find a way to mark the message group as read/delivered.

The XMPP documentation is quite different from the WhatsApp protocol in this part.

Reading the tx/rx debug I've noticed the receipt node contains a "participant" attribute, but even adding the participant attribute to the messageHash in sendMessageReceived didn't work.

You have any idea how to mark a group message as read/delivered ?

Thank you.

**Comment by mgp25** [comment]
Call `$w->pollMessage();` and it will automatically send a read receipt.

**Comment by viniciusjarina** [comment]
Hi @mgp25 

This seems to work only for regular messages, and not for the "Group Messages", 

Even after pollMessage().

Any other alternatives I could check?

Thank you.

**Comment by mgp25** [comment]
I'll check the code tomorrow and do some tests, maybe i forgot to add it. Tomorrow ill tell you.

Regards

**Comment by viniciusjarina** [comment]
Great!

Thank you @mgp25.

Let me know if you need any help.

**Comment by mgp25** [comment]
@viniciusjarina Fixed.

https://github.com/mgp25/WhatsAPI-Official/commit/602be31d39dddcdf268bfeb157ab1ed2c7c9f2f2

Regards

**Comment by viniciusjarina** [comment]
Fantastic!

Thank you @mgp25 :smile:
