### ISSUE TITLE
How to get message id for message sent using sendMessageImage()

### ISSUE THREAD

**Issue by rayidi** [mgp25/WhatsAPI-Official#385]
Hi,

I'm getting message id for a text message which can check for delivery & read receipts.
However if I want to get message id for a image message using `sendMessageImage` function how will i get?

Please suggest some sample code, I'm unable to find on wiki.

**Comment by mgp25** [comment]
You can use this evet:
`onMediaMessageSent( $mynumber, $to, $id, $filetype, $url, $filename, $filesize, $filehash, $caption, $icon )`

It's in the wiki: https://github.com/mgp25/WhatsAPI-Official/wiki/WhatsAPI-Documentation#list-of-all-events


Regards

**Comment by rayidi** [comment]
Hi, is there any other way to get the media message id instantly right after sending the image?
`$msg_id = sendMessageImage($mobile, $url);`

**Comment by mgp25** [comment]
@rayidi nope, you have to use that event, you can find documentation about managing events.

Regards
