### ISSUE TITLE
Documentation error for onGroupisCreated?

### ISSUE THREAD

**Issue by dovfrank** [mgp25/WhatsAPI-Official#387]
Hi,
I was trying to use onGroupisCreated.
according to the documentation, it should be called as "onGroupisCreated( $mynumber, $creator, $gid, $subject )"
But It fails for me. Looking at the abstract definition (at AllEvents.php), I saw that it is "onGroupisCreated( $mynumber, $creator, $gid, $subject, $admin, $creation ){}"

When changing to the method signature with all the parameters to be as in AllEvents.php - everything works fine.
Am I doing something wrong? Starting PHP 5.4, signatures of the methods must match.

**Comment by mgp25** [comment]
It was recently updated:

```
onGroupisCreated( $mynumber, $creator, $gid, $subject, $admin, $creation, $members = array()){}
```

Im going to update the documentation now.

Regards
