### ISSUE TITLE
Socket - connection broke

### ISSUE THREAD

**Issue by rootshell-do** [mgp25/WhatsAPI-Official#395]
Hi, sometimes when the Internet goes down, the connection to server broke, but the
script don't recreate the socket and reconnect.

I think this is the solution:
```php
    protected function sendData($data)
    {
        if($this->socket != null)
        {
            if (socket_write($this->socket, $data, strlen($data)) === false) {
            	
            	$this->disconnect();
				$this->connect();
            	
            }
        }
    }
```

**Comment by mgp25** [comment]
```php
while (1) {
  if (!$w->isConnected()) {
      $w->connect();
      $w->loginWithPassword($myPassword);
  }
  // More stuff
}
```

Not the `connect()` function retuns `true` if connected or `false` if disconnected.

Regards

$w->pollMessage();
//$w->disconnect();
}

**Comment by rootshell-do** [comment]
Maybe I'm wrong, but if the Internet connection goes down, the socket will be still open on the side of the server, so it will be still connected, but the write won't work.

So $this->socket will not be false, but socket_write will return error:
Warning: socket_write(): unable to write to socket [32]: Broken pipe

Happened to me :)

**Comment by mgp25** [comment]
Here you have: https://github.com/mgp25/WhatsAPI-Official/commit/35bda846ab4aaa031d0263b505ef8471b58c2d57

Regards
