### ISSUE TITLE
Whats limit for send?

### ISSUE THREAD

**Issue by over12** [mgp25/WhatsAPI-Official#397]
there is a limit number to send messages a day? or phone number?

**Comment by mgp25** [comment]
No, there is not, but if you abuse WhatsApp system or spam, WhatsApp will block you.

**Comment by jesperveldhuizen** [comment]
Is the following situation called 'spam':

User adds our number to their contact list. Then the user send us a message, like 'news on'. We then start sending messages once a week to every user which send us that particular message.

When the users sends 'news off' we will not send messages anymore. We will also not send messages if the users deletes our number from their contact list.

**Comment by 0xTryCatch** [comment]
It is not allowed by WhatsApp so your number will be blocked. Also you cannot detect if a user removed you from there contact list.

**Comment by jesperveldhuizen** [comment]
OK thanks!

"Also you cannot detect if a user removed you from there contact list."

Ah, I misunderstood the sync function. All clear now.

**Comment by gadhiamitul41** [comment]
Is the following situation called 'spam':

What if some one message me "news" and I want to reply them instantly with latest news from respective websites.

**Comment by jesperveldhuizen** [comment]
No, this API is for personal use.

We tried and got banned.

**Comment by 0xTryCatch** [comment]
You were warned ;)

**Comment by jwelmac** [comment]
Can I use it to interact with a php script to enable users to set an appointment or see a FAQ about my business?

**Comment by marijnkortstra** [comment]
@0xTryCatch @jesperveldhuizen ; if you want to achieve something like Jesper said, what would be the appropriate way to do so? In the Netherlands we have a newspaper (NRC Q, see http://www.nrcq.nl/2014/09/19/volg-en-deel-nrc-q-nu-ook-via-whatsapp) which does exactly what Jasper says. I'm curious how they sent thousand of messages per day, without getting blocked by Whatsapp. The company http://www.wireless-services.nl developed this for NRC Q.
