### ISSUE TITLE
Login Failure

### ISSUE THREAD

**Issue by Davit21** [mgp25/WhatsAPI-Official#398]
Hi guys,
I am using whatsapp app oficial

I used it one week everything was going good but today when i try to log in it is only connected but the login failur 
please explain the raeson and how can i solve this problem

http://joxi.ru/xAeJEPpF5gxNry

**Comment by mgp25** [comment]
You are temporary blocked, if you see the `retry=38258` that means, that you have to wait 38258 seconds = 637 minutes = 10 hours

You can see more info in the F.A.Q: https://github.com/mgp25/WhatsAPI-Official/wiki/Frequently-asked-questions

Regards
