### ISSUE TITLE
sync fails

### ISSUE THREAD

**Issue by theArch2** [mgp25/WhatsAPI-Official#399]
Hi,

first point: the wiki for syncing contacts is deprecated. 

The second thing: 

i get 
```xml
rx  <iq from="49XXXXXXX@s.whatsapp.net" id="sendsync_-1424369906-25" type="error">
rx    <error code="501" text="feature-not-implemented" backoff="3600"></error>
rx  </iq>

```

if i try to sync my contacts with:
```php
$sublist = array("49123456789", "49987654321", "49585646456", ...);
$w->sendSync($sublist, null, 4);
```

the header of the node is:
```xml
tx  <iq id="sendsync_-1424370436-11" xmlns="urn:xmpp:whatsapp:sync" type="get">
tx    <sync mode="delta" context="background" sid="130688476360000000" index="0" last="true">
```

Thanks for advise

**Comment by mgp25** [comment]
@theArch2 It is working fine:

Code:
```php
$sync = array("123456789");
$w->sendSync($sync);
```


Result:
```xml
rx  <iq from="**@s.whatsapp.net" id="sendsync_-*1916-3" type="result">
rx    <sync index="0" sid="*491160000000" last="true" version="1423687402713596">
rx      <in>
rx        <user jid="123456789@s.whatsapp.net">+123456789</user>
rx      </in>
rx    </sync>
rx  </iq>
```

Please, check your code and make sure you use latest WhatsAPI Official code.

Regards

**Comment by theArch2** [comment]
Did you try it with more than one number? I use latest code.

**Comment by mgp25** [comment]
@theArch2 i dont remember, but it worked sometime ago, use it like i did above :)

**Comment by theArch2** [comment]
i tested it also with no more params, just the array like you. Same error :(

**Comment by mgp25** [comment]
@theArch2 post the full code here.

**Comment by theArch2** [comment]
I think that's it. I try to sync my complete contact-list (maybe just 150 of them have whatsapp, but i have to sync all numbers to see). 
Do you know where the maximum is? Or do i have to use the "chunked"-sync?

**Comment by 0xTryCatch** [comment]
It probably means you are syncing too often, 150 contacts is not a problem.

**Comment by theArch2** [comment]
i have more than 150 numbers to sync. i said that 150 of all contacts have maybe whatsapp. But to know it really i have to sync all my contacts.

**Comment by sirwallo** [comment]
Hello,

I have the same problem, could solve

This is what brings me the debug
<iq id="sendsync_-1424777885-1" xmlns="urn:xmpp:whatsapp:sync" type="get">
	<sync mode="full" context="registration" sid="1.3069255085E+17" index="0" last="true">
		<user>+34XXXXXXXX1</user>
		<user>+34XXXXXXXX2</user>
	</sync>
</iq>

<iq from="34XXXXXXXXX@s.whatsapp.net" id="sendsync_-1424777885-1" type="error">
	<error code="501" text="feature-not-implemented" backoff="3600"></error>
</iq>

**Comment by sirwallo** [comment]
I've been trying and if I try after 60 minutes working properly.

From what I've read no limit contacts to sync?

**Comment by mgp25** [comment]
@sirwallo You are using an outdated code, download WhatsAPI Official code and try again

Regards

**Comment by sirwallo** [comment]
@mgp25 The version I'm using is updated has today, has sometimes works and sometimes not, if I run it twice in less than two minutes, if I run 60 minutes after working correctly.

Can be a restriction Whassapp?

**Comment by blaazetech** [comment]
```
rx  <iq from="91xxxxxxxxxx@s.whatsapp.net" id="sendsync_-1425040978-1" type="error">
rx    <error code="501" text="feature-not-implemented" backoff="3600"></error>
rx  </iq>
```
Am also facing the same when using 
```
$w->sendSync($numberarray, $mode="delta",$context="background",$index=0,$last=true);
```
