### ISSUE TITLE
Limitation the number of sending messages

### ISSUE THREAD

**Issue by hdbrave101** [mgp25/WhatsAPI-Official#401]
I'm working on a complete WhatsAPI project..
when the counter of sending messages reach around 1200 messages, there is no more messages send.

I'm using broadcast, and at the fourth broadcast the API can't send any more messages.

Is it a public problem from Whatsapp? or another problem?

Note: this problem appear from 9/2/2015, and before this date the sending messages work correctly, and the API sends messages to all broadcast I have.

Thank you.

**Comment by mgp25** [comment]
There is no limitation sending messages. If you abuse the system or send massive messages WhatsApp will block you.

Regards

**Comment by hdbrave101** [comment]
The system has been working for 2 months .. and still working now but for limit number of sending broadcast messages.

Thank you.

**Comment by jesussales** [comment]
We don't support to spam

**Comment by theArch2** [comment]
#371 
#365 
I have the same issue, but not so many contacts. It also appears from time to time with broadcasts with only 2 recipients. I see this behavior since 10/2/2015
Last week this behavior was also seen in official client. 
@mgp25 you could say what you want, but this IS a bug at whatsapp or there is something changed...

**Comment by SikiFn** [comment]
it is NOT a bug.. It is a new policy Mr. Mark Zuckerburg decided to set!
When you send a BIG number of messages (around 1000 to 1200) broadcasts, the rest will not be delivered at all.
Then you have to wait for an amount of time on order to be able to send again!

**Comment by qoronfola** [comment]
Same here.. any clue the time needed to wait before you can continue broadcast again?

P.S: Broadcast lists ARE NOT SPAM , the receiver must have you in his contact list.

**Comment by SikiFn** [comment]
They did it from their side, you can contact WhatsApp Inc. but they usually ignore the clients.

**Comment by qoronfola** [comment]
still trying guys , tried pullmessage and pong , waited different interval of times but still broadcasts are not delivered to all lists.

Did any one find a way around?

**Comment by 0xTryCatch** [comment]
There is no way around it. Mass broadcasting is not possible anymore.

**Comment by rejath888** [comment]
I have almost 4000 people in my broadcast ie, like 16 lists. I have the same problem. When I broadcast to 5 broadcast list, i have to wait exactly 11 minutes to broadcast to the next 5 list. I have 16 lists now in total, and this is becoming hard for me. Is there anyway that we can overcome this? I have tried to contact Whatsapp, but they just ignore me.
