### ISSUE TITLE
Implementing WhatsAPI on Heroku

### ISSUE THREAD

**Issue by InsidiousMiss** [mgp25/WhatsAPI-Official#403]
I hope this is the right place to put this. When I run my app on my server, it runs beautifully. But when I deploy it to Heroku, it times out. It runs when I comment out
```php
$w->pollMessage();
```
Has anyone been able to use WhatsAPI on Heroku?

**Comment by mgp25** [comment]
@InsidiousMiss i dont know what Heroku is, but for sure there is info in internet :) if you find something you can come back and post your solution.

Regards
