### ISSUE TITLE
AJAX example

### ISSUE THREAD

**Issue by nesttle** [mgp25/WhatsAPI-Official#404]
Hi sir,
there is some working example of AJAX controller/script?

The one included in the package is not working anymore :(

Thanks in avance

**Comment by mgp25** [comment]
@nesttle there is the ajaxDemo, if it isnt working, then we havent any more examples, but there is a lot of examples in internet about how to use ajax.

Regards

**Comment by SikiFn** [comment]
Well it was so easy to fix! https://github.com/mgp25/WhatsAPI-Official/commit/3e6d3252ecbed7cb15d22e09bc0698f24c0f15ee

**Comment by nesttle** [comment]
@SikiFn :+1:  Thanks dude! :)
