### ISSUE TITLE
the test script relies on non existing WhatsAppEventListenerProxy.php

### ISSUE THREAD

**Issue by ducch** [mgp25/WhatsAPI-Official#409]
title speaks for itself.

it also calls for undefined variables, such as [$imei](https://github.com/mgp25/WhatsAPI-Official/blob/master/tests/whatsapp.php#L43)

**Comment by ducch** [comment]
it also calls for undefined variables, such as [$imei](https://github.com/mgp25/WhatsAPI-Official/blob/master/tests/whatsapp.php#L43)

**Comment by mgp25** [comment]
https://github.com/mgp25/WhatsAPI-Official/commit/d7ba1e58fb8dee1623218911b44ae2fb52decd6d
https://github.com/mgp25/WhatsAPI-Official/commit/1df003f70c2eaa3053bb9995b451119abae90642

Regards
