### ISSUE TITLE
mnc not correct

### ISSUE THREAD

**Issue by moutazhodhod** [mgp25/WhatsAPI-Official#412]
Hello,
codeRequest() => detectMnc() function return "Only Sometimes" MNC as 000 and return correct MCC
i was tried anather numbers on the same provider , and its return both mcc & mnc correctly ,

**Comment by mgp25** [comment]
@moutazhodhod it's explained in the wiki, there are set a default data in order to make it work with all numbers of all carriers.

More information about registration in the wiki: https://github.com/mgp25/WhatsAPI-Official/wiki/WhatsAPI-Documentation#number-registration

Regards
