### ISSUE TITLE
Reconnect

### ISSUE THREAD

**Issue by railton** [mgp25/WhatsAPI-Official#417]
Hi
I'm doing some tests if the application is disconnect happens the following problem
```php
// Loop code
while (true) {

  try {

      if (!$w->isConnected()) {
          $w->connect()
          $w->loginWithPassword($password);
      }

        while($w->pollMessage());

        sleep(30);
        $w->disconnect();
    }
    catch(Exception $e) {
       $w->disconnect();
    }

}
```

MyEvents 
```php
public function onConnect($mynumber, $socket)
    {
        echo "Connected\n";
    }

    public function onLogin( $mynumber ){
        echo "Login success\n";
    }

    public function onDisconnect($mynumber, $socket)
    {
        echo "Disconnect\n";
    }
```

- Response

Connected
Login success
Disconnect
Connected
Disconnect
Connected
Disconnect

The first time he logs in, but after disconnecting it not run more login
Any?

**Comment by ducch** [comment]
I had the same thing myself a while ago, see #169.
However, none of the solutions provided at the time helped so I ended up using crontab to relaunch the script upon death.

**Comment by railton** [comment]
public function disconnect()
    {
        if (is_resource($this->socket)) {
            @socket_shutdown($this->socket, 2); // add this line
            @socket_close($this->socket); // add @ to remove warning
            $this->socket = null;
            $this->loginStatus  = static::DISCONNECTED_STATUS; // add new status
            $this->eventManager()->fire("onDisconnect",
                array(
                    $this->phoneNumber,
                    $this->socket
                )
            );
        }
    }

now
Connected
Login success
Disconnect
Connected
Login success
Disconnect
Connected
Login success
Disconnect

**Comment by mgp25** [comment]
Added: https://github.com/mgp25/WhatsAPI-Official/commit/e2b44f8791e00807f3765e26515e61edbfdd9381

Regards
