### ISSUE TITLE
Problems with Break lines

### ISSUE THREAD

**Issue by aldisseia** [mgp25/WhatsAPI-Official#420]
Problems with Break lines, to send message tried \ n \ n \ r \ r nothing works
[cod]
$mesg='Test \n \n\r \r kkkkk';
$w->sendMessage(!fone, $mesg);
[/cod]
Display: 'Test \n \n\r \r kkkkk

**Comment by SikiFn** [comment]
You should use: $mesg="Test \n \n\r \r kkkkk"; (with double quotes).. Everything between single quotes is not parsed!

**Comment by aldisseia** [comment]
I go to work after 00H, thank you had not seen the quotes ...
