### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by DarkAllMan** [mgp25/WhatsAPI-Official#422]
Can anyone steer me in the correct direction. Suddenly got this message:
`Uncaught exception 'Exception' with message 'Login Failure' in whatsprot.class.php:1640`

DEBUG:
```xml
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="31615239471">AI|U31615239471‹íe6jí¤t ªkÖiÐÞ¸Éb«—1424688844WhatsApp/2.12.61 S40Version/14.26 Device/Nokia302 MccMnc/204004</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>zØþ@VC0ßŽÄ“œ)Øƒæ ÝX</challenge>

tx  <response>vï]Pu>äc2E¿JQ¢b›ñ8ªl?'V4kEœzÝ€</response>
```

**Comment by ducch** [comment]
update your code.

**Comment by DarkAllMan** [comment]
And what if I did? How can I check if I'm running the latest update?

**Comment by ducch** [comment]
the latest version clearly has no throw at line 1640.

**Comment by DarkAllMan** [comment]
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="31615239471">���"31615239471Ї��  
���͞  
�� %��R1424694601WhatsApp/2.12.61 S40Version/14.26 Device/Nokia302 MccMnc/204004</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>L��T� �¬n Q� X:�~W</challenge>

tx  <response>�� x ᨔ���� ���Y��<�br�� �RX HP��</response>

PHP Fatal error:  Uncaught exception 'Exception' with message 'Login Failure' in /var/www/vhosts/lievelabels.nl/wa.lievelabels.nl/whatsapp-master/whatsprot.class.php:2308
Stack trace:
#0 /var/www/vhosts/lievelabels.nl/wa.lievelabels.nl/whatsapp-master/whatsprot.class.php(561): WhatsProt->doLogin()
#1 /var/www/vhosts/lievelabels.nl/wa.lievelabels.nl/send_whatsapp.php(20): WhatsProt->loginWithPassword('uc23mKusKqFbysd...')
#2 {main}
  thrown in /var/www/vhosts/lievelabels.nl/wa.lievelabels.nl/whatsapp-master/whatsprot.class.php on line 2308

**Comment by DarkAllMan** [comment]
I really do'nt understand whats going on

**Comment by thiagosantos** [comment]
I had a similar problem.
One of my bots was running smoothly over a month, but on last Saturday I
got a socket close and I couldn't login again.

I will try to register again to try save this number.

bests,

Thiago Santos
http://thiagosantos.com

**Comment by DarkAllMan** [comment]
I will disable my crontab to give the number some "rest" See what happens later on!

**Comment by mgp25** [comment]
@DarkAllMan Seems a connection error, if you get a `not-authorized` tag means your number is blocked, if you don't get this tag, then its a connection issue.

If you have any other doubt just tell me.

Regards

**Comment by phpjoker** [comment]
When I try to register a blocked number , it response  [status] => fail [reason] => blocked 
But today one of my numbers get a not-authorized tag but when register it again say :
```
 [status] => fail [reason] => no_routes [retry_after] => 3600
```

**Comment by SikiFn** [comment]
@phpjoker well, this happened to me yesterday.. Three of my numbers were unexpectedly unable to login.. I thought they were blocked, but I re-registered them successfully.. After few hours they were permanently blocked!

It seems a new action WhatsApp is taking in order to block the numbers.. Dunno

**Comment by phpjoker** [comment]
another my number unable to login.
for a while Login Failure without any ' not-authorized tag' but after several login attemp  'not-authorized tag' appear.

**Comment by phpjoker** [comment]
```
<system: error>
    <system-shutdown></system-shutdown>
</system:error>
```

**Comment by rodrigofaillace** [comment]
what is it, @phpjoker ?

**Comment by phpjoker** [comment]
Last error that causes login failure  and block all numbers!!! :(

**Comment by phpjoker** [comment]
@mgp25 Please Help
Another number blocked....
```
function onGetMessage($mynumber, $from, $id, $type, $time, $name, $body){
$from=ExtractNumber($from);
$w->sendSync($from);
usleep(100000);
$message='.........';
$w->sendBroadcastMessage($from,$message);
}
```
WHY!????

Thanks a lot.

**Comment by phpjoker** [comment]
exactly on this codes:
```
$w->sendSync($from);
$w->sendBroadcastMessage($from,$msgwelcome);
$w->sendBroadcastVcard($from,$Subject,$VCard));
```
first broadcast sent and received but on second broadcast script stoped and then restart it , login failed.

**Comment by ducch** [comment]
why do you broadcast to 1 destination? :O

**Comment by mgp25** [comment]
@phpjoker because of your sending message behaviour, that could be considered spam to WhatsApp

**Comment by phpjoker** [comment]
Ok, say me how do it?

**Comment by ruchirkakkad** [comment]
Guys please help me.. Where to get the whatsapp password.. I am getting the Login failure error.

**Comment by mgp25** [comment]
@ruchirkakkad its explained in the wiki: https://github.com/mgp25/WhatsAPI-Official/wiki

Regards

**Comment by ruchirkakkad** [comment]
Thank you... It helped me and solved my problem.

**Comment by jacksparao** [comment]
The code is still working if share any one share the clone here please.....
