### ISSUE TITLE
Using Twilio number

### ISSUE THREAD

**Issue by pedrommone** [mgp25/WhatsAPI-Official#424]
I dont know what Im doing wrong. Im registering a number, verifying it. I got all my stuff done but it giveme always a `Login fail` exception

```php
$username = "14XX7001374";
	$identity = "";
	$nickname = "Vai ter agua";
	$password = "**";
	$debug = true;

	// Create a instance of WhastPort.
	$w = new WhatsProt($username, $identity, $nickname, $debug);

	$w->connect(); // Connect to WhatsApp network
	$w->loginWithPassword($password); // logging in with the password we got!

	$w->sendMessage("number" , "Eae babaca.");
```

this is how Im making the send procedure.

**Comment by mgp25** [comment]
Post debug log

Regards

**Comment by catch2patch** [comment]
I have "reason: bad param" when registering with Twilio or Textplus number. Why?

**Comment by mgp25** [comment]
@catch2patch post full debug log

Regards

**Comment by mgp25** [comment]
@catch2patch some virtual numbers doesnt work with WhatsApp anymore.

@pedrommone your code is good, you have a login issue. It could be a connectivity issuem you can try again. If you receive a `not-authorized` tags, means that your number is blocked and you will need a new one.

If you want more help or have doubts tell me, but remember to post the debug log too.

Regards
