### ISSUE TITLE
In last seen i am not able to get that 

### ISSUE THREAD

**Issue by jayeshsoni** [mgp25/WhatsAPI-Official#425]
this is my code how do i get date 

```php
 public function onGetRequestLastSeen($mynumber, $from, $id, $seconds )
{
	  echo "Last seen of $id: ".gmdate("H:i:s", $seconds);
}
```

**Comment by mgp25** [comment]
@jayeshsoni its explained in the wiki: https://github.com/mgp25/WhatsAPI-Official/wiki/WhatsAPI-Documentation#requesting-last-seen-and-profile-picture

Regards

**Comment by miki143** [comment]
yes but it gives second not the perfect date..

**Comment by miki143** [comment]
how can we check the date and time of last seen.

**Comment by mgp25** [comment]
@miki143 use this function with the binded event:

```php
 public function onGetRequestLastSeen($mynumber, $from, $id, $seconds )
{
      echo "Last seen of $id: ".gmdate("H:i:s", $seconds);
}
```

Please read the wiki, its explained there
