### ISSUE TITLE
Prevent Getting Blocked

### ISSUE THREAD

**Issue by pentatonicfunk** [mgp25/WhatsAPI-Official#426]
Is there any way to make the number getting blocked ?

i tried to use this behavior : https://github.com/mgp25/WhatsAPI-Official/wiki/WhatsAPI-Documentation#whatsapp-workflow

but my number always getting blocked
 
is there any good tips, the number not sending a lot of messages, just 2 or 3 per hour, to different target

thank you

**Comment by mgp25** [comment]
Its explained in the FAQ: https://github.com/mgp25/WhatsAPI-Official/wiki/Frequently-asked-questions

Regards
