### ISSUE TITLE
Undefined property: stdClass::$retry_after

### ISSUE THREAD

**Issue by Padrio** [mgp25/WhatsAPI-Official#429]
When calling code register im getting following error:
``Undefined property: stdClass::$retry_after``

Which refferes to line 266:
https://github.com/mgp25/WhatsAPI-Official/blob/master/src/whatsprot.class.php#L266

Btw, it looks like the mobile number is banned, so that could be the reason.
Edit: An print_r told me that the code must be without the "-" - otherwise you will get the error.

**Comment by mgp25** [comment]
Its working from here, if you have any doubt just tell me.

Regards

**Comment by Padrio** [comment]
So, if the code is wrong, there is no $retry_after variable in the object.
Or if you try it too often, it's missing too - and that causes the warning.
