### ISSUE TITLE
Receiving message multiple times

### ISSUE THREAD

**Issue by Elektroniikka** [mgp25/WhatsAPI-Official#430]
Hi!

I have a cronjob which runs my whatsapi script every half a second `(* * * * * php script.php and * * * * * sleep 30; php script.php)`. I did add this new "feature" in my script. It adds every group message to my database.

```php
$qr = $connection->prepare("INSERT INTO messages (phonenumber, message, time) VALUES (?, ?, ?)");
$qr->connection(array($phonenumber, $body, $time));

$phonenumber is str_replace("@s.whatsapp.net", "", $from_user_jid).
```

When I send a message to the group with my personal phone, it adds my message, time and phone number correctly, but after 30 secs it adds again it and then after 30secs it adds third time it! So there is total of 3 same messages. Same time, phone number and message. I am trying to prevent spam in my group. (look if there is multiple messages inside x time by y person) If I could fix this bug it would work perfectly, but it bans the user too quickly. EX. if there is 9 messages in 3 seconds by x player ban it. when I message 3 messages in a row it will ban me, because in database there is 9 entries ( 3 x 3 ).

Sorry for bad english.
`onGetGroupMessage` gots one same message 3 times. Using cronjob to run script every 30 seconds.

**Comment by deizepi** [comment]
Which event are you using to write the message in the database?

**Comment by mgp25** [comment]
@Elektroniikka there is a built in option to save directly messages in a SQLite database.

Wiki: https://github.com/mgp25/WhatsAPI-Official/wiki/WhatsAPI-Documentation#saving-messages-in-db

**Comment by Elektroniikka** [comment]
Hi mgp25!

Thanks for that link. I am using MySQL, but looks like Sqlitemessagestore.php is easy to edit for MySQL. Couple questions: will this receive Group messages? And second: Does ongetgroupmessage listener work after that? (Receives all messages) Because this "supervisor" has also commands and other features.

**Comment by mgp25** [comment]
@Elektroniikka that will save all messages, the groups messages too. It doesnt use events for that, so you can still use events to do other stuff ot whatever, so yes, it will work the listener.

Regards

**Comment by Elektroniikka** [comment]
Any idea why this isn't working? (replaced this into sqlitemessagestore.php)

´´´php
<?php
interface MessageStoreInterface
{
    public function saveMessage($from, $to, $txt, $id, $t);
}
class MysqlMessageStore implements MessageStoreInterface
{
    private $db;
    public function __construct($host, $dbname, $usern, $passw) {
        $this->db = new PDO("mysql:host=" . $host . ";dbname=" . $dbname, $usern, $passw, array(PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC, PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION));
    }
    public function saveMessage($from, $to, $txt, $id, $t) {
        $sql = 'INSERT INTO messages (`from`, `to`, message, id, t) VALUES (:from, :to, :message, :messageId, :t)';
        $query = $this->db->prepare($sql);
        $query->execute(
            array(
                ':from' => $from,
                ':to' => $to,
                ':message' => $txt,
                ':messageId' => $id,
                ':t' => $t
            )
        );
    }
}
´´´

´´´php
$w = new WhatsProt($username, $identity, $nickname, $debug);
$w->setMessageStore(new MysqlMessageStore("localhost", "whatsapp", "root", $mysql_password));
$w->eventManager()->bind("onGetGroupMessage", "onMessage");
$w->Connect();
$w->LoginWithPassword($password);
$w->pollMessage();
while(1) {
   $w->pollMessage();
}
´´´

no errors in logs and no rows added.

**Comment by Elektroniikka** [comment]
Actually is that function sended messages? Cause it added sended messages, not received (adds from sendMessage). I need received messages.

**Comment by moersoft** [comment]
@Elektroniikka : 
Please change this script :         
        $query->execute(
            array(
                ':from' => $from,
                ':to' => $to,
                ':message' => $txt,
                ':messageId' => $id,
                ':t' => $t
            )
        );
with : 
        $query->bindParam(':from', $from);
        $query->bindParam(':to', $to);
        $query->bindParam(':message', $txt);
        $query->bindParam(':messageId', $id);
        $query->bindParam(':t', $t);
        $query->execute();
it's work...

**Comment by golge666** [comment]
i also tryed to save messageson mysql ..
try to edit Myevent.php ,

<code>
public function onGetMessage( $mynumber, $from, $id, $type, $time, $name, $body )
{< br/>
    echo "Message from $name:\n$body\n\n";
    echo '<br>';
    /*$kaydet = mysql_query("INSERT INTO 'g_msj' ('phone', 'from', 'wid', 'type', 'time', 'name', 'data') VALUES ('$phone', '$from', '$id', '$type', '$time', '$name', '$data')");
    if ($baglan->query($sql) === TRUE) {
    echo "New record created successfully";
} else {
    echo "Error: " . $sql . "<br>" . $bglan->error;
}
</code>
i didnt get any mesaj .. any one ?

**Comment by hpatel4u** [comment]
Hope you register the onGetMessage event before you logged in to whatsapp.

$this->wa->eventManager()->bind('onGetMessage', array($this, 'processReceivedMessage'));

I may be wrong in syntax, as i am .net developer.

**Comment by golge666** [comment]
i m sorry for my poor english. i ment ;
actualy i m getting messages as well but i m fail to add them to mysql =( .

**Comment by shirkeshriram** [comment]
Try this code  It's working 

<?php

interface MessageStoreInterface 
{
    public function saveMessage($from, $to, $txt, $id, $t);
}
class SqliteMessageStore implements MessageStoreInterface 
{
    const DATA_FOLDER = 'wadata';
    public function saveMessage($from, $to, $txt, $id, $t) {
        echo 'adjhakjshskjdasdj'.$from.'-'.$to.'-'.$txt.'-'.$id.'-'.$t;
        $con = mysql_connect("localhost", "root", "");
        if (!$con) {
            die('Could not connect: ' . mysql_error());
        }
        mysql_select_db("save", $con);
        $sql = 'INSERT INTO messages (`from`, `to`, `message`, `id`, `t`) VALUES ("'.$from.'", "'.$to.'", "'.$txt.'", "'.$id.'", "'.$t.'")';
        $query = mysql_query($sql);
    }
}

**Comment by shirkeshriram** [comment]
Try this code. it's working    

      <?php
     interface MessageStoreInterface
      { 
      public function saveMessage($from, $to, $txt, $id, $t);
      }

     class SqliteMessageStore implements MessageStoreInterface 
      {
      const DATA_FOLDER = 'wadata';
      public function saveMessage($from, $to, $txt, $id, $t) 
      {
        echo 'adjhakjshskjdasdj'.$from.'-'.$to.'-'.$txt.'-'.$id.'-'.$t;
        $con = mysql_connect("localhost", "root", "");
        if (!$con) {
            die('Could not connect: ' . mysql_error());
        }
        mysql_select_db("save", $con);
        $sql = 'INSERT INTO messages (`from`, `to`, `message`, `id`, `t`) VALUES ("'.$from.'", "'.$to.'", "'.$txt.'", "'.$id.'", "'.$t.'")';
        $query = mysql_query($sql);
    }

}
?>
