### ISSUE TITLE
Doubt: Avoid "Connection closed"

### ISSUE THREAD

**Issue by deizepi** [mgp25/WhatsAPI-Official#432]
How best to imitate WhatsApp Mobile? My question is in receipt of messages, I'm doing this Receive via AJAX that is rotated every 3 minutes (put a long time thinking that would avoid the `close connection`), but even so, after AJAX run sometimes without receiving or sending any message, I get "connection closed".

Anyone know how this should be done?
The `close connection` only occurs when `pollMessages` not get return for a few consecutive times.

Now, I would like to thank and congratulate all those responsible for this incredible API and also apologize for bad English.

**Comment by mgp25** [comment]
@deizepi Are you using WhatsAPI Official code? There is only 'pollMessage`not `pollMessages` and it should work fine, because it answer automatically the ping request from WA server, fi you you can always `sendPing()` to keep it alive.

Regards

**Comment by deizepi** [comment]
Okay, thank you.
