### ISSUE TITLE
Accounts blocked by WhatsApp

### ISSUE THREAD

**Issue by Udirley** [mgp25/WhatsAPI-Official#433]
Hello everybody
Yesterday forth had 6 accounts blocked by WhatsApp.
I make it clear that we are not using WhatsApp to make advertisements, these accounts are used by radio stations to receive musical requests of its listeners and also receive feedback on how they are transit visa by listeners.
Highlight some accounts use the Yowsup and others use the WhatsAPI-Official and had locks on both.
Is there anything we can do to prevent this?
I thank the attention.

**Comment by mgp25** [comment]
@Udirley If you have a normal workflow you shouldnt have any issue. If you only use WhatsApp to receive messages there isnt any problem with it, and if you send messages remember to sync them and the numbers you send the messages to, should have your number in their contact list too.

Many accounts have been "blocked" but if you registered again you can make them to work again (in some cases).

All the information can be found in the wiki. For more information you need to post your day activity and debug so we know what is the block nature.

Regards

**Comment by yniv** [comment]
@mgp25 What did you mean by "remember to sync them and the numbers you send the messages to" do I need to do something or if my number is in the user contacts its ok?

**Comment by phpjoker** [comment]
Please Help
Another number blocked....
```
function onGetMessage($mynumber, $from, $id, $type, $time, $name, $body){
$from=ExtractNumber($from);
$w->sendSync($from);
usleep(100000);
$message='.........';
$w->sendBroadcastMessage($from,$message);
}
````
WHY!????

Please Help Me!

Thanks a lot.

**Comment by mgp25** [comment]
@yniv yes, it must be in your contact addess list

**Comment by yniv** [comment]
@mgp25 how do I add a number to my contacts through code??

**Comment by Udirley** [comment]
This is where I was going. Adding contacts in the phonebook using the code?
I believe that this is the reason why I am being blocked. All my clients have my number on their agendas but I do not because they do not know how to attach them on the agenda using the code.
Thank attention.
