### ISSUE TITLE
Broadcasting a message

### ISSUE THREAD

**Issue by ahumblenerd** [mgp25/WhatsAPI-Official#434]
I tried creating a broadcast.
```xml
[*] Connected to WhatsApp
tx  <message to="1424888929@broadcast" type="text" id="broadcast-1424888929-1">
tx    <body>Hi This is my first broadcast test</body>
tx    <broadcast>
tx      <to jid="+***@s.whatsapp.net"></to>
tx      <to jid="+***@s.whatsapp.net"></to>
tx      <to jid="+***@s.whatsapp.net"></to>
tx      <to jid="+***@s.whatsapp.net"></to>
tx      <to jid="+***@s.whatsapp.net"></to>
tx    </broadcast>
tx  </message>

tx  <iq id="get_lists_-1424888929-2" xmlns="w:b" type="get" to="s.whatsapp.net">
tx    <lists></lists>
tx  </iq>
```

This is the debug output I got . But the messae is not going through. 

I also tried the jidversion without + infront.

**Comment by jessereitsma** [comment]
Do those number have the number you are sending from in their contact list? Thats a must for broadcast messages to prevent spam :)

**Comment by mgp25** [comment]
The numbers you are sending to, must have your number in their contact list.

Regards

**Comment by ahumblenerd** [comment]
@mgp25  Yes they have my number in their contact list and i also synced every number with sync method
