### ISSUE TITLE
How To unblock my blocked Contacts

### ISSUE THREAD

**Issue by Abtab** [mgp25/WhatsAPI-Official#435]
Hi
How To unblock my blocked Contacts using whatsapi.

Regards
Abtab

**Comment by mgp25** [comment]
```php
$blockedNumbers = array(num1, num2);

$w->sendSetPrivacyBlockedList($blockedNumbers);
```

If you just want to unblock the number, just remove it from the array. That will keep yours numbers blocked except the one you want.

```php
$blockedNumbers = array(num1);

$w->sendSetPrivacyBlockedList($blockedNumbers);
```

Regards
