### ISSUE TITLE
Cant receive Group text messages

### ISSUE THREAD

**Issue by Abtab** [mgp25/WhatsAPI-Official#436]
Hi

I cant receive group text messages and receiving audio video and Photos. Thanks in advance

Best Regards

**Comment by mgp25** [comment]
If you dont post your code and debug log i cant help you. ALWAYS post code and debug

**Comment by Abtab** [comment]
Thanks for reply. I will post debug log.

**Comment by Abtab** [comment]
Sorry . My mistake  i have not created event OnGetGroupMessage .  Appreciate your initiation. Thanks very much.
