### ISSUE TITLE
Broadcasts

### ISSUE THREAD

**Issue by dahansi** [mgp25/WhatsAPI-Official#438]
Hi there,

while I was trying to send broadcasts to i.e. 60 people (= 3 broadcasts), sometimes some messages were never delivered. 
`onSendMessage` says, that they were sent, but `onServerReceived` returned false.

I found this function in the whatsprot.class.php `$this->waitForServer($msgId);`.

My Question is: If I add this function after `$this->sendNode($messageNode)` in the sendBroadcast(...)-function, will it always wait until the broadcast is delivered? Is this the solution that the broadcasts will be sent?
Why isnt it added there by default?

Thanks so much!

**Comment by mgp25** [comment]
@dahansi only people who have your number added in their contact list, will get your messages, otherwise not.

**Comment by dahansi** [comment]
I know that. Everybody I sent the message to, has my number in the contact list.

It seems like sometimes the server is "busy". If I wait for 5 minutes and try to send the same broadcast to the same people it is delivered correctly.
That's why I want to add waitForServer to the sendBroadcast-Function.

**Comment by mgp25** [comment]
Oks, if you want send a pull request.

**Comment by dahansi** [comment]
Ok, I have no idea how to send a pull request o_O

**Comment by mgp25** [comment]
Already added in latests commits.

Regards
