### ISSUE TITLE
Can We implement Proxy For Connection.

### ISSUE THREAD

**Issue by miki143** [mgp25/WhatsAPI-Official#440]
@mgp25  Now how can we implement proxy into this... before i am able to connect via proxy but in this new connect function not able to do that .can u please suggest the way ..

**Comment by mgp25** [comment]
@miki143 Sorry, wont implement that, the API works perfectly without proxy, so is not required, or are you trying to hide something?

Regards

**Comment by miki143** [comment]
yes if we send more then there is a problem of blocking..

**Comment by mgp25** [comment]
@miki143 if you send messages to people that have your number in their contact list then you dont have to worry about nothing. If you are trying to send spam, sorry we dont give support.
