### ISSUE TITLE
Number got Blocked, but I never sent a message?

### ISSUE THREAD

**Issue by dahansi** [mgp25/WhatsAPI-Official#441]
Hi there,

yesterday I updated to the new Version of WhatsApi.
Right after that some of my numbers got blocked. Even numbers that never sent a message! There was no spamming. It worked for month with no problems at all.

Thats what I get, when I try to login:
```
Fatal error: Uncaught exception 'Exception' with message 'Login Failure' in /.../src/whatsprot.class.php:2294 Stack trace: #0 /.../src/whatsprot.class.php(561): WhatsProt->doLogin() #1 /.../incs/class.inc.php(373): WhatsProt->loginWithPassword('...') #2 /.../incs/class.inc.php(64): MyWA->login(Array) #3 /.../cron1.php(54): MyWA->doAll(...) #4 {main} thrown in /.../src/whatsprot.class.php on line 2294
```

And when I try to get new credentials:
```xml
Array
(
    [cc] => 12
    [in] => 123456
    [id] => ...
    [lg] => de
    [lc] => DE
    [network_radio_type] => 1
)
stdClass Object
(
    [status] => fail
    [reason] => blocked
)
```

Is this a temporary block or is it for ever? How can it happen for accounts that never send a message and after it worked fine for more than 3 month. 

Thanks for your help!

**Comment by mgp25** [comment]
@dahansi if you have other numbers and with those numbers you have sent lots of messages, WhatsApp also blocks iP, so all numbers in the network, get blocked.

Also the block could happen because of a bad behaviour or massive requests.

It seems to be blocked, not temporary.

Regards

**Comment by dahansi** [comment]
Ok, that sounds not good :(
I will try to contact WhatsApp, maybe they can unblock the numbers.

3 numbers that didnt send any message yesterday got blocked, though they had their own IP. Really strange.


Another question: I receive all my Broadcasts by calling onBroadcastLists and then I delete them (sendDeleteBroadcastLists) and create new Broadcasts to keep it clean. Is this a got solution or shouldn't I delete broadcasts?

**Comment by mgp25** [comment]
@dahansi it doesnt matter if you delete broadcasts lists, WhatsApp knows everything about the number as they can track everything.

If you didnt send anything, you can try sending an email to WhatsApp support

Regards
