### ISSUE TITLE
Blocked. How to find out why?

### ISSUE THREAD

**Issue by Silikowski** [mgp25/WhatsAPI-Official#445]
I used the api (without any problems) for about  a month now.

Im sending about 30 messages to 30 users (one per user) per day with a script like this:

1. get users-numbers from database -> write to array
open connection to whatsapp
3. start loop (while) {
4. send image to user_from_array)
5. end loop
6. poll message (few times)
7 close connection to whatsapp.

all that happens in 16 seconds.

it worked for over a month now, now issues.
yesterday i got no message. checking the debug/serverlog shows me  not authorized.

is there a way to find out if i was blocked caused by to many messages or sending them to fast?

do you know any restrictions (numer of messaged sent once, delay time)?

**Comment by mgp25** [comment]
30 messages to different users in 16 seconds? No way! Thats not the way you should do it! 

You have to think the same as you were using the device app. And remember to have synced in both ways

**Comment by Silikowski** [comment]
so adding a delay of 3 seconds after each message should look more realistic to the servers and be more safe?

what do you mean snc both ways??

**Comment by Pudins** [comment]
All my numbers are being blocked when they receive a message they are blocked then.
Someone can tell me what is happening?

**Comment by miki143** [comment]
Mine is also blocked no idea why it is blocking ?

**Comment by patatje368** [comment]
I use my own function for sending messages with a delay. Works perfect. It sends a 'Typing...' message to the receiver first for a while (depending on the length of the message) and after the delay, the message is send. You can make a method liek this yourself for images.

You should also add the receivers to your contact list.

```php
function sendMessageWithTypingDelay(WhatsProt $w, $target, $message) {
    $w->sendMessageComposing($target);
    
    $time = ceil(strlen($message)/10)*150000;
    if($time >= 2000000 && $time < 7500000) {
        usleep($time);
    }
    else {
        usleep(5000000);
    }
    $w->sendMessage($target, $message);
}
```

Example:
```php
$w = new WhatsProt();
sendMessageWithTypingDelay($w, 'numberhere', 'message to send');
```

**Comment by patatje368** [comment]
I use my own function for sending messages with a delay. Works perfect. It sends a 'Typing...' message to the receiver first for a while (depending on the length of the message) and after the delay, the message is send. You can make a method liek this yourself for images.

You should also add the receivers to your contact list.

```php
function sendMessageWithTypingDelay(WhatsProt $w, $target, $message) {
    $w->sendMessageComposing($target);
    
    $time = ceil(strlen($message)/10)*150000;
    if($time >= 2000000 && $time < 7500000) {
        usleep($time);
    }
    else {
        usleep(5000000);
    }
    $w->sendMessage($target, $message);
}
```

Example:
```php
$w = new WhatsProt();
sendMessageWithTypingDelay($w, 'numberhere', 'message to send');
```

**Comment by mgp25** [comment]
All the information about block its in the WhatsApp EULA, read the wiki please.

Regards
