### ISSUE TITLE
I need a tip on how to receive messages

### ISSUE THREAD

**Issue by Pudins** [mgp25/WhatsAPI-Official#448]
Personnel Today I use a loop to see if someone sent a message to my number and answer automatically as an answering machine, however I believe you are not doing the right way because my number is not online all the time, it is only when running the command $ w-> pollMessage ();
Does anyone have an alternative to keep the number online all the time?

**Comment by mgp25** [comment]
@Pudins the number is always online, you probably are doing or coding something wrong.

Regards

**Comment by Pudins** [comment]
I am doing so:

function receiveMsg($username, $nickname, $password){
		$username = $username;
		$identity = "/dats/".strtolower(urlencode(sha1($username, true)));
		//$identity = "../dats/".strtolower(urlencode(sha1($username, true)));
		$nickname = $nickname;
		$password = $password;
		$debug = false;
		$w = new WhatsProt($username, $identity, $nickname, $debug);
		$events = new MyEvents($w);
		$w->eventManager()->bind("onGetMessage","answersMsg");
		$w->connect();
	    $w->loginWithPassword($password);
	    while($w->PollMessage());
}

We perform this function within the loop, do you think there's something wrong here?

**Comment by mgp25** [comment]
@Pudins 

As i said above, it should be this: 

```php
function receiveMsg($username, $nickname, $password){
        $debug = false;
        $w = new WhatsProt($username, $nickname, $debug);
        $events = new MyEvents($w);
        $w->eventManager()->bind("onGetMessage","answersMsg");
        $w->connect();
        $w->loginWithPassword($password);
        while($w->PollMessage());
}
```

**Comment by Pudins** [comment]
@ mgp25 Thanks for the help and sorry for the inconvenience!
