### ISSUE TITLE
sendMessage not sending messages all the time

### ISSUE THREAD

**Issue by Elektroniikka** [mgp25/WhatsAPI-Official#451]
Hi!

My problem is now, that when I do foreach loop and inside that loop there is $w->sendMessage($num, $msg); it does message just couple users, usually the first ones.

This code is custom voting system which sends every user her/his custom link to vote. This is for school class, which has 24 people. Phone numbers and hashes comes from external site (whatsapp bot in one server, voting in another). I've checked that this page gets all phone numbers and correct hashes. So it's something about whatsapp...?

My code:

```php
function objectToArray($d) {
	if (is_object($d)) {
		$d = get_object_vars($d);
	}
	if (is_array($d)) {
		return array_map(__FUNCTION__, $d);
	} else {
 		return $d;
 	}
}
$rtn = objectToArray(json_decode(file_get_contents("http://site.com/startVoting.php?starter=" . $phonenumber . "&question=" . $question)));
foreach($rtn as $ele) {
$w->sendMessage($ele['phone'], "Hi! You can vote in here: http://site.com/vote.php?hash=" . $ele['hash']);
//tried also this: sleep(1);
}
```

No errors returned in apaches error.log(s).

**Comment by zionnite** [comment]
hello pls did were u able to debugs the error

**Comment by Elektroniikka** [comment]
Hi!

I tried to get debug information, but somehow I didn't get anything.

**Comment by zionnite** [comment]
please i really do need ur help.... am participating  in Google summer of
code and sending message from pho script to whatsapp contact is one of my
project......
please i would love u to support me with any information and what to do
please i beg u

**Comment by mgp25** [comment]
Read the wiki:

```php
$w = new WhatsProt($username, $nickname, $debug);
```

**Comment by Elektroniikka** [comment]
Hi! I know this sounds like spam, but I can promise you it is not. This message is rarely sent. I could send straw poll link to our WhatsApp group, but then we wouldn't know who voted and what. Only group admins can start voting. If you still think this is spam, you don't need to response. I can understand this, because here is a lot spammers. And my code was like: $debug = true and just before new WhatsProt there was $debug = false, so thats why there wasn't any debug info. Here is all what I got:

```
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="pnumber">ÿíA358440285007ÏšŠ«½Ó,)hQ¿‡‘[P1425139517WhatsApp/2.12.61 S40Version/14.26 Device/Nokia302 MccMnc/244005</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>random</challenge>

tx  <response>random</response>

rx  <success t="time" props="4" kind="free" status="active" creation="time" expiration="time">random</success>

tx  <presence name="Supervisor"></presence>

rx  <ib from="s.whatsapp.net">
rx    <offline count="0"></offline>
rx  </ib>

rx  <presence from="number@s.whatsapp.net"></presence>

rx  <presence from="number@s.whatsapp.net"></presence>

rx  <message from="gjid@g.us" id="id" participant="group_admin_phonenumber@s.whatsapp.net" type="text" t="time" notify="admins name">
rx    <body>!startvoting Questionhere</body>
rx  </message>
```
