### ISSUE TITLE
Missing messages

### ISSUE THREAD

**Issue by moshere** [mgp25/WhatsAPI-Official#453]
Hi,
I'm running the following code from command line.
Once command line to send messages (below) and the second to retrieve.
I've lock file in order to make sure not to login and connect twice.
However in most of the cases while sending and receiving several messages (~30) about 3 or 4 are missing. 
I get no error, just missing messages. I looked into it for a day now without identifying the issue.
I really thank you if you can look into it and tell what's wrong.

Thank you in advance,
Moshe

Send messages:
#!/usr/bin/php
<?php

// This file is part of a tutorial on the blog of Philipp C. Heckel, July 2013
// http://blog.philippheckel.com/2013/07/07/send-whatsapp-messages-via-php-script-using-whatsapi/

require_once('whatsapp_whatsapi_config.php');

$w = new WhatsProt($userPhone, $userIdentity, $userName, $debug);
$w->Connect();
$w->LoginWithPassword($password);
$w->sendMessage($argv[1], $argv[2]);
$w->Disconnect();
?>

Receive messages
#!/usr/bin/php
<?php

require_once('whatsapp_whatsapi_config.php');

function escapeJsonString($value) {
    # list from www.json.org: (\b backspace, \f formfeed)    
    $escapers =     array("\\",     "/",   "\"",  "\n",  "\r",  "\t", "\x08", "\x0c");
    $replacements = array("\\\\", "\\/", "\\\"", "\\n", "\\r", "\\t",  "\\f",  "\\b");
    $result = str_replace($escapers, $replacements, $value);
    return $result;
  }

$w = new WhatsProt($userPhone, $userIdentity, $userName, $debug);
$w->Connect();
$w->LoginWithPassword($password);
 

    while ($w->pollMessage());
    $msgs = $w->GetMessages();
    foreach ($msgs as $m) {
		$from = str_replace("@s.whatsapp.net", "", $m->getAttribute("from"));
		$name = $m->getAttribute("notify");
		$time = $m->getAttribute("t");
		if($m->getChild("body"))
		{
        $messagebody = $m->getChild("body")->getData();
        $messagebody = escapeJsonString($messagebody);
		$from = escapeJsonString($from);
		$name = escapeJsonString($name);
		
		}
		echo "json: {\"from\":\"$from\", \"name\":\"$name\", \"time\":\"$time\", \"message\":\"$messagebody\"}\n";
		}

$w->Disconnect();

?>

**Comment by mgp25** [comment]
@moshere read the wiki, that link and the code you are using are outdated

Regards

**Comment by moshere** [comment]
@mgp25 Thank you.
I'm doing it wrong.
My requirement is to have one command line to send messages and one command to receive new messages.
Can you guide me what to do using the new code?

Moshe

**Comment by mgp25** [comment]
@moshere examples and code in the wiki

Regards

**Comment by moshere** [comment]
@mgp25 Thank you.
Sorry to bother you.
I looked into Wiki 
https://github.com/mgp25/WhatsAPI-Official/wiki/WhatsAPI-Documentation#sending-messages

And looked into the code and the issue is that part of sendMessage code contains waitForServer which will pollMessage.
So during sending messages the received message will be vanished.

Moshe

**Comment by mgp25** [comment]
@moshere you can store received messages, you can find all the info in the wiki

Regards

**Comment by moshere** [comment]
@mgp25 Thank you. I've seen this option in Wiki.
However I couldn't find explanation on how to read the messages from db. What is the structure of the messages?

Thank you,
Moshe
