### ISSUE TITLE
Mark message as read?

### ISSUE THREAD

**Issue by Padrio** [mgp25/WhatsAPI-Official#455]
After polling the messages using the `pollMessage()` method the `onGetMessage` event will be fired successfully - and my messages will be send back perfectly.
But when im calling the method a second time - the `onGetMessage` event will be fired a second time.
Like the messages wont get marked as "read" after polling them.

```php
$whatsProt->eventManager()->bind('onGetMessage', function ($myNumber, $from, $id, $type, $time, $name, $body) use ($whatsProt, $command, $account) {

    $to = $this->getCleanMobile($from);

    $command->info('Received message from: ' . $to);

    $whatsProt->sendMessageComposing($to);
    $whatsProt->sendMessage($to, '...');

});

// ### Poll messages for current account
$whatsProt->pollMessage();
```

To show what i mean my log
![Console Log](http://puush.padrio.de/WcP2.png)

Hope you understand what i mean, if not - just tell me.

**Comment by railton** [comment]
Use onMessageReceivedClient event

2015-03-01 15:11 GMT-04:00 Pascal Krason <notifications@github.com>:

> After polling the messages using the pollMessage() method the onGetMessage
> event will be fired successfully - and my messages will be send back
> perfectly.
> But when im calling the method a second time - the onGetMessage event will
> be fired a second time.
> Like the messages wont get marked as "read" after polling them.
>
> $whatsProt->eventManager()->bind('onGetMessage', function ($myNumber, $from, $id, $type, $time, $name, $body) use ($whatsProt, $command, $account) {    $to = $this->getCleanMobile($from);    $command->info('Received message from: ' . $to);    $whatsProt->sendMessageComposing($to);    $whatsProt->sendMessage($to, '...');});// ### Poll messages for current account$whatsProt->pollMessage();
>
> To show what i mean my log
> [image: Console Log]
> <https://camo.githubusercontent.com/5f29156159f422b79db37e6f2fef5304c4850990/687474703a2f2f70757573682e70616472696f2e64652f576350322e706e67>
>
> Hope you understand what i mean, if not - just tell me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mgp25/WhatsAPI-Official/issues/455>.
>



-- 
Railton Nepomuceno

**Comment by Padrio** [comment]
Now i dont receive any message

**Comment by railton** [comment]
Uncomment event onMessageReceivedClient and implement

public function onMessageReceivedClient($mynumber, $from, $id, $type,
$time) {
            echo "$mynumber, $from, $id, $type, $time\n";
}

type changed to read after contact read message.


2015-03-01 17:27 GMT-04:00 Pascal Krason <notifications@github.com>:

> Now i dont receive any message
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mgp25/WhatsAPI-Official/issues/455#issuecomment-76631847>
> .
>



-- 
Railton Nepomuceno

**Comment by mgp25** [comment]
@Padrio the message is set automatically as read when you poll the message, so you shouldnt receive any duplicate message, try a simple script listening with debug true and check if you receive duplicates.

Regards
