### ISSUE TITLE
How to Get Privacy Blocked List

### ISSUE THREAD

**Issue by Abtab** [mgp25/WhatsAPI-Official#457]
Hi.
I know that that we have to call `$wa.SendGetPrivacyBlockedList` and to receive it we have to bind it with event `$wa.OnGetPrivacyBlockedList($mynumber, $data)`

But How to extract blocked jids from `$data`.

Thanks in advance

**Comment by mgp25** [comment]
@Abtab its not an API issue, this type of questions you should search it in google or php sites.

Use `var_dump($data)` to see `$data` content, or do a loop printing all the numbers or whatever you want to do.

Regards

**Comment by Abtab** [comment]
But I am getting NULL In data and i have list of blocked people. thats why i am sakung
