### ISSUE TITLE
ffmpeg

### ISSUE THREAD

**Issue by ducch** [mgp25/WhatsAPI-Official#458]
WhatsAPI currently spits errors and warnings when trying to determine if ffmpeg is present or not.
I personally think it's inefficient to test for ffmpeg's existence every time we upload a video, and it
just might be better to statically define settings regarding ffmpeg (if it's there or not, paths, etc.).

**Comment by tugmaks** [comment]
https://github.com/tony2001/ffmpeg-php

**Comment by mgp25** [comment]
We are trying to find an easy solution for this, if anyone knows send a pull request.

Thanks.

Regards

**Comment by mgp25** [comment]
@ducch for now we are going to keep that as its the easiest way (i kown), if you find a better solution send a pull request and ill merge it.

Thanks for your efforts

Regards
