### ISSUE TITLE
Impossible to use own folder for identites?

### ISSUE THREAD

**Issue by tugmaks** [mgp25/WhatsAPI-Official#459]
How to set own folder for identities?
in WhatsProt constructor it uses predefined class constant?
i wanna to set my own, like it was in previous version
 public function __construct($number, $identity, $nickname, $debug = false)

**Comment by mgp25** [comment]
Right now, you cant, all data related to the API will be saved in a folder called `wadata` this is the best solution for now, everything its organized and stored in there.

Regards
