### ISSUE TITLE
Not showing PrivacyBlockedList

### ISSUE THREAD

**Issue by Abtab** [mgp25/WhatsAPI-Official#460]
Hi
 I am getting NULL In data and i have list of blocked people.

Or If  i am doing something incorrect... Please guide me how i can get list of blocked contacts. 
I tried everything. there is no error and its showing NULL to me.
Thanks in advance

**Comment by mgp25** [comment]
Fixed: https://github.com/mgp25/WhatsAPI-Official/commit/4219ff4a4754980b7c1d55b5c2ceb75de13f7153
