### ISSUE TITLE
Image Sending Bad Request: 400

### ISSUE THREAD

**Issue by archergod** [mgp25/WhatsAPI-Official#461]
I was trying to send image, here is the request node
```xml
    tx  <iq id="upload-1425298174-11" to="s.whatsapp.net" type="set" xmlns="w:m">
    tx    <media hash="47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=" type="image"  size="7914"></media>
    tx  </iq>
``` 
Here is response node
```xml
     rx  <iq from="s.whatsapp.net" id="upload-1425298174-11" type="error">
     rx    <error code="400" text="bad-request"></error>
     rx  </iq>
```

When I run this script from my local machine, it is sending the same image from same source phone to same destination phone, but when I run it from online server it give BAD request ... I check server disk space it is more than 10 GB free, text messages are going through well. Not sure what else I should check. 

EDIT:
Just before `sendNode` call in`whatsport.class.php` in `sendRequestFileUpload` function I put file_exists to check if file exists, and it return true. I am trying to send a Image from URL (it doesn't redirect), 
Also, I didn't find downloaded image in `wadata\media` folder after successful send from local machine. do we delete URL images after sending?

**Comment by mgp25** [comment]
@archergod images arent stored automatically, you will have to set a function to save the images or media files. And no, the API doesnt delete anything.

Regards

**Comment by archergod** [comment]
@mgp25  Thanks, yes I figured out that images aren't automatically stored, just was confirming. 

here is my code to sent the image 

    if(!empty($url)) {
			elog("Sending image $url");
			$w->sendMessageComposing($target);
			sleep(rand(1,3));
			$w->sendMessagePaused($target);
			$w->sendMessageImage($target, $url, false);
    }

thanks.

**Comment by mgp25** [comment]
@archergod remember that some url address may cause some problem sending images, try with an image stored in your server and try sending it, if it works, it means the problem its in the url address

Regards

**Comment by archergod** [comment]
I agree with you and even the official app on my Phone sometime didn't send few images as they never get uploaded to server. But why I wrote a issue is that same URL (I try with 3-4 url) works from local machine but not from server and node is generating fine (as I understand as it got hash), so thought there might be something I am missing.

I will test image saved on server now, will result soon.

**Comment by archergod** [comment]
I just try to send image saved on server here is request

    tx  <iq id="upload-1425310275-2" to="s.whatsapp.net" type="set" xmlns="w:m">
    tx    <media hash="DJGtrVtNZ/eqg6QAmb4Rxx4PhDJ2cjKMJYLxVudkaR0=" type="image" size="293830"></media>
    tx  </iq>

here is response

    rx  <iq from="s.whatsapp.net" id="upload-1425310275-2" type="result">
    rx    <media url="https://mmi104.whatsapp.net/u/uopXoEIRDc1NQFgqgWA7-HJ1VEwABRBP6Kz0Lw/Ah2203nZpdSlhHHayc5Xx-kuZw92jjGTtq5kEdLosH0B" ip="173.193.230.122"></media>
    rx  </iq>

though it looks like the Image is uploaded fine, but I haven't recieved on phone I sent to...

**Comment by mgp25** [comment]
Post full debug log

**Comment by archergod** [comment]
Here is complete log,

    	tx  <stream:features>
	tx    <readreceipts></readreceipts>
	tx    <groups_v2></groups_v2>
	tx    <privacy></privacy>
	tx    <presence></presence>
	tx  </stream:features>

	tx  <auth mechanism="WAUTH-2" user="972543836111">tŸ§972543836111âj-Ç„¹Ç¯gÔÀ{ý3ÃŒ€œb1425359522WhatsApp/2.12.61 S40Version/14.26 Device/Nokia302 MccMnc/425001</auth>

	rx  <start from="s.whatsapp.net"></start>

	rx  <stream:features></stream:features>

	rx  <challenge>ÃÖ¦ÏŠ×‹ÚŸ·Öä.	Ú@…</challenge>

	tx  <response>(ÛZ@HSµu¨.˜ÿGÚ%^qÜZçO´šéq>—ùà Þ</response>

	rx  <success t="1425359522" props="4" kind="free" status="active" creation="1422268777" expiration="1453804777">Ì0­q$Û}‡…h±ÆP7Z{úÝ</success>

	tx  <presence name="Sim Sum"></presence>


	tx  <iq id="sendsync_-1425359522-1" xmlns="urn:xmpp:whatsapp:sync" type="get">
	tx    <sync mode="delta" context="background" sid="130698367220000000" index="0" last="true">
	tx      <user>+911234567890</user>
	tx    </sync>
	tx  </iq>

	rx  <ib from="s.whatsapp.net">
	rx    <offline count="0"></offline>
	rx  </ib>

	rx  <presence from="972543836111@s.whatsapp.net"></presence>

	rx  <iq from="972543836111@s.whatsapp.net" id="sendsync_-1425359522-1" type="result">
	rx    <sync index="0" sid="130698367220000000" last="true" version="1425309543746024">
	rx      <in>
	rx        <user jid="911234567890@s.whatsapp.net">+911234567890</user>
	rx      </in>
	rx    </sync>
	rx  </iq>


	tx  <presence type="subscribe" to="911234567890@s.whatsapp.net"></presence>

	rx  <presence from="911234567890@s.whatsapp.net" type="unavailable" last="1425318609"></presence>


	Sending image http://images.all-free-download.com/images/graphicmedium/thinking_monkey_191286.jpg
	tx  <chatstate to="911234567890@s.whatsapp.net">
	tx    <composing></composing>
	tx  </chatstate>

	tx  <chatstate to="911234567890@s.whatsapp.net">
	tx    <paused></paused>
	tx  </chatstate>


	URL is saved
	Array
	(
		[url] => http://images.all-free-download.com/images/graphicmedium/thinking_monkey_191286.jpg
		[filesize] => 14066
		[filemimetype] => image/jpeg
		[fileextension] => jpg
		[filepath] => /var/www/vhosts/cashanywhere.co.il/httpdocs/whats2/includes/whatsapp/wadata/media/WHAsNQRYP
	)

	File Exists ? bool(true)

	tx  <iq id="upload-1425359544-2" to="s.whatsapp.net" type="set" xmlns="w:m">
	tx    <media hash="47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=" type="image" size="14066"></media>
	tx  </iq>

	rx  <iq from="s.whatsapp.net" id="upload-1425359544-2" type="error">
	rx    <error code="400" text="bad-request"></error>
	rx  </iq>


Not sure if I should email it :).

**Comment by mgp25** [comment]
@archergod are you using latest version of WhatsAPI? If you disconnect to fast, you wont get the message, recently we added a `waitForMsgId` so the message will arrive .

Also i see you save the image here:

`/var/www/vhosts/cashanywhere.co.il/httpdocs/whats2/includes/whatsapp/wadata/media/WHAsNQRYP`

with no extensions like `.jpg` that could be the error.

Regards

**Comment by archergod** [comment]
I will update the version today again, I update it the same day I start this ticket. 

On missing extension, I have no idea about saving it is "default" behaviour of API, as I just gave URL to it and API download and save it, probably for some reason it fails there?

**Comment by archergod** [comment]
doesn't make a difference with latest version.

**Comment by mgp25** [comment]
@archergod i just try it in my webserver, works perfectly. Check:

```xml
tx  <iq id="upload-1425686884-3" to="s.whatsapp.net" type="set" xmlns="w:m">
tx    <media hash="4Rg3WNjdCKSkydPeEXrB8ISOXVCRLE2udV/2OJCNq1E=" type="image" size="9553"></media>
tx  </iq>

rx  <iq from="s.whatsapp.net" id="upload-1425686884-3" type="result">
rx    <duplicate url="https://mmi201.whatsapp.net/d/AvsY_kBHQhhhoHSPCH0XWhB41TdZBiEkRxUzZ3RFlhss.jpg" size="9553" mimetype="image/jpeg" filehash="4Rg3WNjdCKSkydPeEXrB8ISOXVCRLE2udV/2OJCNq1E=" type="image" width="313" height="234"></duplicate>
rx  </iq>

tx  <message to="**@s.whatsapp.net" type="media" id="message-1425686884-5" t="1425686884">
tx    <media type="image" url="https://mmi201.whatsapp.net/d/AvsY_kBHQhhhoHSPCH0XWhB41TdZBiEkRxUzZ3RFlhss.jpg" encoding="raw" file="AvsY_kBHQhhhoHSPCH0XWhB41TdZBiEkRxUzZ3RFlhss.jpg" size="9553"> 4003 byte data</media>
tx  </message>
```

Code:

```php
$w->sendMessageImage($num, 'https://upload.wikimedia.org/wikipedia/commons/8/8c/JPEG_example_JPG_RIP_025.jpg');
```

Regards

**Comment by archergod** [comment]
I am using same code and same scripts work on my local machine, but not on server. I read other thread where they found the server has no disk space, but that is not true for me, I give full 777 permission on complete chain and it still didn't work on server for image sending. So, my concern is for some reason data transmission is not smooth and there is some error coming in transmission. Is there any way you can suggest I can debug this.
