### ISSUE TITLE
Is there a method to check if the number is valid Whatsapp user?

### ISSUE THREAD

**Issue by booker0108** [mgp25/WhatsAPI-Official#466]
Is there a method to check if the number is valid Whatsapp user?

**Comment by archergod** [comment]
add the number to your number, using SendSync and if that return positive response than he requested number is valid else not.

**Comment by mgp25** [comment]
@booker0108 as @archergod said, use senSync, check the wiki for more info.

Wiki: https://github.com/mgp25/WhatsAPI-Official/wiki

Regards
