### ISSUE TITLE
Time Out on Upload Proccess

### ISSUE THREAD

**Issue by phpjoker** [mgp25/WhatsAPI-Official#467]
When we upload a large file, It takes more than 30 seconds and cause time out connection.
How solve it?

**Comment by mgp25** [comment]
@phpjoker check your interner connection or if the media files has a big size.

Try with a small image instead for testing.

Regards

**Comment by phpjoker** [comment]
small file no problem,
with large file connection time out.
whatsapp on device how do it?

**Comment by phpjoker** [comment]
Its possible file uploading run in other tread!!!?

**Comment by phpjoker** [comment]
This function:
public function uploadFile($file) 
 what does it do!?
