### ISSUE TITLE
Best way to reconnect after disconnection

### ISSUE THREAD

**Issue by fermino** [mgp25/WhatsAPI-Official#468]
I have some questions about how to reconnect the API. 
After <https://github.com/mgp25/WhatsAPI-Official/pull/374> and <https://github.com/mgp25/WhatsAPI-Official/issues/417>

Can I do something like

```php
while(true)
{
    if ($w->connect())
    {
        // Do something
    }
}
```

without instantiating WhatsProt again?

**Comment by mgp25** [comment]
@fermino you can do it like this:

```php
if (!$w->isConnected()) {
   $w->connect();
    $w->loginWithPassword($password);
 }
```

Or just use on disconnect event, and reconnect again, this was already fixed.

Regards

**Comment by fermino** [comment]
Thanks!
