### ISSUE TITLE
on using checkCredentials

### ISSUE THREAD

**Issue by thiagosantos** [mgp25/WhatsAPI-Official#469]
Hello,

I was reading the code and I saw a warning about WhatsApp change the password when using "checkCredentials" method. As a return object there are a few parameters, but two got my attention, first was the "password" and the second the "expiration".

Did anyone have your password changed using "checkCredentials", or changed automatically, even not using "checkCredentials"?
What is the "expiration" parameter ?

Is it possible that this last wave of numbers blocked happened because WhatsApp changed the numbers passwords on the fly?

**Comment by 0xTryCatch** [comment]
WA will not change passwords by itself. The checkCredentials **will** change the password, that's how WA implemented it. The expiration is just your own account expiration (when you have to start paying for WhatsApp).

The blocked numbers are because those numbers violated the WA EULA.

**Comment by tauseefahmed** [comment]
I used WART-1.8.2.2 to get password, now when i used checkCredentials function it returned the password but when i try to login it it throw exception any idea how can i prevent this ?

**Comment by mgp25** [comment]
@tauseefahmed open a new issue, post debug log, show more info, etc etc etc

**Comment by phpjoker** [comment]
probably your ip is blocked!
