### ISSUE TITLE
virtual numbers

### ISSUE THREAD

**Issue by Kson2** [mgp25/WhatsAPI-Official#471]
I can't seem to register with virtual numbers anymore, can anyone offer any insight on how to get around this? How do the servers even know that its a virtual number?
Thanks

**Comment by thetitoo** [comment]
Whatsapp will search by operator - If you use Google Voice, the operator is not registered and Whatsapp won't let you register (you can try to request it from customer service - I tried 2 months ago without reply).
I'm using a number from Twillio (you can create one for free)

**Comment by Kson2** [comment]
How can they search by operator? Wouldn't that mean the need access to all Carrier DBs?

**Comment by thetitoo** [comment]
Seems like: https://github.com/mgp25/WhatsAPI-Official/blob/master/src/networkinfo.csv

**Comment by Kson2** [comment]
Hmm i'm not so sure, any other ideas?

**Comment by CODeRUS** [comment]
Yes whatsapp servers have access to carriers dbs and checking if virtual number or not.

**Comment by Kson2** [comment]
Would you mind if i ask how you know this is what they do? I'm not doubting you but i'm curious since i was able to register a land line phone number which they would also block (Since the official client can't work there) if there had such access

**Comment by Kson2** [comment]
Never mind, if searchbug.com can do it, obviously so can they and clearly there is no way around it short of actually adding the number to a carrier network. Thanks for your responses!

**Comment by Kson2** [comment]
So are we stuck using only our personal mobile number (meaning it can't be on our phones) or is there a way to register using another number?

**Comment by archergod** [comment]
You just need to recieve single SMS/TEXT from whatsapp with auth code. Once you get that you don't need your number to be active on device so buy a new number get the SMS and remove number from device.

**Comment by Kson2** [comment]
@archergod true but then you'd be spending ~$20 on a number that may only work until someone else uses the number to install whatsapp. 

I was hoping to find a way to use a free (or at least cheaper than at&t) number from someone like Google voice, twilio, etc.

**Comment by mgp25** [comment]
You can try with your personal number, you can extract your password (explained in the wiki).

Regards
