### ISSUE TITLE
[Question] - Receiving messages from multiple sender.

### ISSUE THREAD

**Issue by kampit** [mgp25/WhatsAPI-Official#472]
https://github.com/mgp25/WhatsAPI-Official/blob/master/examples/Simple%20CLI%20client.php

Good to start & working example.

There have a clue how to run this `CLI` to get messages from any number?

**Comment by thetitoo** [comment]
Sorry, I didn't get your question.
This CLI example is working and is parsing any new message from any number.

**Comment by mgp25** [comment]
@kampit its a CLI script, you will neeed to run it in terminal / cmd / shell

Regards
