### ISSUE TITLE
new line msg

### ISSUE THREAD

**Issue by brunowcs** [mgp25/WhatsAPI-Official#475]
How can I send message as a new line? I realized that it is possible only after a while, would send or decrease the timeout of each new message, I'm using the API to monitor my environment and accurate records the schedule of sending each message, it will only be possible if you can send to my number each message per line.

**Comment by mgp25** [comment]
`"Your Message \n New line"`

Regards

**Comment by brunowcs** [comment]
for whatsapp it sends the new line, but appears on the same schedule message block, would like a new line showing your receipt schedule, I realize that this behavior only works after a very wide range and shipping.
