### ISSUE TITLE
Best practices

### ISSUE THREAD

**Issue by rodrigofaillace** [mgp25/WhatsAPI-Official#476]
Hello @mgp25 and all whatspi-official team.

We are now migrating from nodejs (hidespb) to php (mgp25) repository due to many blocks we had recently (last 7 days).

Our App works only in a passive way, just answering received messages. 

I have checked your whatsapp flow (in your wiki) and I noticed that SendSync, SendMessageComposing we were not using. Also, we stayed connected 24 hours a day.

As we are not (yet) php specialists we produced this code below based on your examplefunctional.php.

Do you think that the code below shows the best practices in order to mitigate blocked numbers? And about our connection time (24h is required), the way it is implemented (sendPing in less then 5 minutes)?

```php
<?php
require_once '../src/whatsprot.class.php';
//Change to your time zone
date_default_timezone_set('Europe/Madrid');

$username = "552197600****";                      // Telephone number including the country code without '+' or '00'.
$password = "XXX";     // Use registerTool.php or exampleRegister.php to obtain your password
$nickname = "test";                          // This is the username (or nickname) displayed by WhatsApp clients.
$target = "***";                   // Destination telephone number including the country code without '+' or '00'.
$debug = false;                                           // Set this to true, to see debug mode.
///////////////////////////////////////////////////////////

echo "[] Logging in as '$nickname' ($username)\n";

//Create the whatsapp object and setup a connection.
$w = new WhatsProt($username, $nickname, $debug);
$w->eventManager()->bind("onGetMessage", "onGetMessage");

$w->connect();

$numbers = array('5521999999999','5521888888888');

function onGetMessage($phone, $from, $messageid, $type, $time, $name, $message) {
	global $w;
	global $numbers;
	
	echo "[*] onGetMessage \n";	
	
	if ( ! in_array($from, $numbers) ) {
		array_push($numbers, $from);
		$w->sendSync($numbers);
	}
	
	if ($message && ($message == "5" || trim($message) == "5")) {
        $w->sendMessageComposing($from);
		sleep(1);
		$w->sendMessage($from, "Congratulations you guessed the right number!");
    }
    elseif (ctype_digit($message)) {
        if ((int)$message != "5"){
			$w->sendMessageComposing($from);
			sleep(1);
			$w->sendMessage($from, "I'm sorry, try again!");
		}
    }
}

$w->loginWithPassword($password);
echo "[*] Connected to WhatsApp\n\n";

$time = 0;
while (1) {
	$w->pollMessage();
	
	$time++;	
	if($time >= 110){
		echo "PING \n";
		
		$w->sendPing();
		$time = 0;
	}	
	echo " $time \n";
}

```

Thanks for your project and attention!

**Comment by mgp25** [comment]
@rodrigofaillace You can find real WhatsApp client workflow here: https://github.com/mgp25/WhatsAPI-Official/wiki/WhatsAPI-Documentation#whatsapp-workflow

Then you can add them or not, its up to you. If you are in a passive mode, then its not required to sync and that stuff. And yes, it seems fine.

It has a 3 minutes timeout, the WA server does automatically a ping every 3 minutes, then we answer the server, so we keep alive, anyway you can send ping to server whenever you want.

You can find most of the documentation in the wiki: https://github.com/mgp25/WhatsAPI-Official/wiki

Regards
