### ISSUE TITLE
get the list of broadcasts in whatsapp

### ISSUE THREAD

**Issue by sant527** [mgp25/WhatsAPI-Official#477]
How to get the broadcastlists i have. I have whatsapp on mobile. I had some broadcast lists in it already before i started using this scripts.

So i tried:
```
`$username = "91xxxxxxxxx9";
$nickname = "sxxxx";
$debug = false;
$w = new WhatsProt($username,null, $nickname, $debug);
$w->connect();
$w->loginWithPassword('sdsdsdsdkjdskdjskdj'); 
$w->sendGetBroadcastLists();
$w->disconnect();
```
But it does not list any. It only shows realted to broadcast.
```
tx  <iq id="get_lists_-1425560439-1" xmlns="w:b" type="get" to="s.whatsapp.net">
tx    <lists></lists>
tx  </iq>
```

**Comment by mgp25** [comment]
You are disconnecting too fast. Add pollMessage after the get request, then you will get the result


Regards

**Comment by sant527** [comment]
Thank you. It solved.
