### ISSUE TITLE
How to use broadcast id instead of multiple numbers

### ISSUE THREAD

**Issue by sant527** [mgp25/WhatsAPI-Official#478]
In the below code  can i use Broadcast is instead of list of phone numbers array.
```php
$w->sendBroadcastImage($targets, "./media7.jpg")
```

Is there any way  i can make a broadcast list and keep adding and removing numbers from that list. .Just like in the app.

**Comment by mgp25** [comment]
@sant527 Nope, is not implemented.

Regards
