### ISSUE TITLE
Whatsapp now permanently bans users using third-party apps

### ISSUE THREAD

**Issue by glennadva** [mgp25/WhatsAPI-Official#479]
See the original article on
http://www.myce.com/news/whatsapp-now-permanently-bans-users-using-third-party-apps-75246/

Will this affect WhatsAPI-Official?

**Comment by mgp25** [comment]
Only people who use it for non personal usage

Regards

**Comment by CODeRUS** [comment]
WhatsApp+ and WhatsappMD are banned because it violates WhatsApp inc. trademark name. These cases have nothing similar with WhatsAPI users bans. As @mgp25 said you can be banned only if WHatsApp detects you using it for not personal usage.

**Comment by glennadva** [comment]
Thank you @mgp25 and @CODeRUS !

Could you maybe elaborate on this a bit more, are there any guidelines for what personal/non-personal usage is?

**Comment by CODeRUS** [comment]
@glennadva nobody knows exactly about criteria. WhatsApp is proprietary platform and they are not telling how checking process is happening :)
