### ISSUE TITLE
Error al realizar registro

### ISSUE THREAD

**Issue by jmcortacero** [mgp25/WhatsAPI-Official#480]
He intentado realizar un registro con el último API y registerTool.php y no funciona correctamente.

Enter the received code: 496-729
PHP Notice:  Undefined property: stdClass::$retry_after in /root/WAD/tmp/WhatsAPI-Official/src/whatsprot.class.php on line 269
Array
(
    [cc] => 34
    [in] => 619757610
    [id] => d.▒i▒▒▒+▒▒▒▒j
    [code] => 496-729
)
stdClass Object
(
    [status] => fail
    [reason] => bad_param
    [param] => code
)
An error occurred registering the registration code from WhatsApp.

**Comment by mgp25** [comment]
First, write in english
Second, read the wiki, this is explained in the wiki

The code its without '-'

Regards
