### ISSUE TITLE
Any difference to officlal Whatsapp in terms of message exchange ?

### ISSUE THREAD

**Issue by mylover80** [mgp25/WhatsAPI-Official#481]
Is there any difference between officlal Whatsapp and Whatsapi that can be spotted by the server ?
If yes, then this can be a clue to ID ban mechanism, and can this difference be eliminated through code change ?

**Comment by CODeRUS** [comment]
oh, we never thought about it, thank you!

**Comment by mgp25** [comment]
Sarcastic @CODeRUS xD

@mylover80  we already know this, but its the easiest way we have managing results to identify them. Anyway, if you use it for your own, WhatsApp wont block you.

Regards

**Comment by mylover80** [comment]
@mgp25 I cannot login since a few days ago (not authorised), though I can re-register again and use the official whatsapp.  As I have not changed the code and version number for many months, it seems that whatsapp server is nowing checking "new things".  I have tried changing the version number to the latest, but still get the same response, so what can be the new things ?

**Comment by mgp25** [comment]
@mylover80 use WhatsAPI Official code, if still appear there are 2 possible ways: 

- Your IP have been blocked, so better you try in other IP
- Your number its blocked

Make sure you are using the number and password correctly

Regards

**Comment by mylover80** [comment]
@mgp25 As I said, I can use my old account in official apk.  That means the account itself is not blocked, but only login message exchange content is incorrect suddenly, or the checking of login content is changed just few days ago.
