### ISSUE TITLE
Question about emojis

### ISSUE THREAD

**Issue by julianobd** [mgp25/WhatsAPI-Official#482]
When I receive a message I insert in the database, but the emojis appear as question marks "??" there is some function to convert unicode to string or something else?

**Comment by mgp25** [comment]
@julianobd you can't you need to store in unicode and once you get that string from the database, parse the unicode to show the emoji. You can search more about this in google, there are many answers already :smile:

Regards

**Comment by kampit** [comment]
Add this function 

		function isEmoji($txt)
		{
			$txt = mb_convert_encoding($txt, 'HTML-ENTITIES', 'UTF-8');
			$matches = null;
			preg_match_all('/\&\#(.+?)\;/', $txt, $matches, PREG_SET_ORDER);
			if (is_array($matches)) {
				foreach ($matches as $emoji) {
					$txt = str_ireplace($emoji[0], '<div class="emoji emoji-'.dechex($emoji[1]).'"></div>', $txt);
				}
			}
			return mb_convert_encoding($txt, 'UTF-8', 'HTML-ENTITIES');
		}

Then `onGetMessage` or `$caption` call the function `isEmoji($body)` and it will store something like this

    <div class="emoji emoji-1f44d"></div>

Copy paste css & image in folder `examples/emoji` to display the emoji.

Other : Switch MySQL to `utf8mb4`

**Comment by julianobd** [comment]
thank you kampit and mgp25! :+1:
