### ISSUE TITLE
Login not possible (new number registered)

### ISSUE THREAD

**Issue by Silikowski** [mgp25/WhatsAPI-Official#484]
Just registered a new number using registerTool.php

got this Output on CLI:

####################################
#                                  #
#           WA CLI CLIENT          #
#                                  #
####################################

====================================
[] logging in as '' ()
PHP Fatal error:  Uncaught exception 'Exception' with message 'Login Failure' in                                                                                                                        /var/www/wa/src/whatsprot.class.php:2297
Stack trace:
#0 /var/www/wa/src/whatsprot.class.php(564): WhatsProt->doLogin()
#1 /var/www/wa/examples/Simple CLI client.php(58): WhatsProt->loginWithPassword(                                                                                                                       '')
#2 {main}
  thrown in /var/www/wa/src/whatsprot.class.php on line 2297

is it blocked or another problem?

**Comment by mgp25** [comment]
@Silikowski you havent set any password or number, if you dont edit the script it wont never work

Regards
