### ISSUE TITLE
getting stream error and server dies

### ISSUE THREAD

**Issue by sant527** [mgp25/WhatsAPI-Official#486]
Many times whatapps server dies giving the following message.
```xml
rx  <stream:error>
rx    <conflict></conflict>
rx    <text>Replaced by new connection</text>
rx  </stream:error>
```
How to ensure i reconnect and send the message

**Comment by thetitoo** [comment]
This will happen when you login from somewhere else. 
I had this problem when I had my Infinite loop running and I tried to send a message seperately in my script.

**Comment by sant527** [comment]
Can explain what you meant by logging from some where else. Also i am not running an infinite loop

**Comment by mgp25** [comment]
Post your code
