### ISSUE TITLE
Register a new Number via Webform

### ISSUE THREAD

**Issue by jonny0303** [mgp25/WhatsAPI-Official#487]
How it's possible to register a new number (request code, register, echo $pw) via a PHP-Webscript?

Requesting the code works without any problems but I can't register the number with this 6-digit code... :(

I tried it already, for more information (and code) check [StackOverflow](http://stackoverflow.com/q/28880035/1133346) please.

**Comment by mgp25** [comment]
@jonny0303 use `exampleRegister.php` and `registerTool.php` for help, its just normal php coding. If you use latest updates, that constructor isnt use it anymore, see wiki to compare your code.

Regards
