### ISSUE TITLE
Something like internal Spam

### ISSUE THREAD

**Issue by atfo90** [mgp25/WhatsAPI-Official#489]
Guys, I have a problem:

Our system registers internal alerts on a table in the database.

A routine in PHP sends this message to the email of employees.
However, my boss would like this routine to send a notice to the Whatsapp of each, because checking email takes longer.

We have about 50 employees, and after 10 messages, my number is blocked.

Can someone help me avoid that?

For each database number, I am using this function:
(I've tried with `connect();` and `sendSync();` outside `foreach()` )
```php
foreach ($numbers as $number) {
    $w->connect ();
    $w->loginWithPassword($WA_PASSWORD);
    
    $phoneListPlus[0] = '+'.$​​target;
    $w->sendSync($phoneListPlus);

    $w->pollMessage();

    sleep(rand(4,6)); // Random pause

    $w->sendPresenceSubscription($target);
    $w->sendMessageComposing($target);

    sleep(rand(4,6)); // Random pause

    $w->pollMessage();
    $w->sendMessagePaused($target);

    $newMessage = '('. Rand(0, 9999).')'.PHP_EOL.$message; // To avoid same message

    if ($withImage == true) {
        $w->sendMessageImage($target, $filepath, false, 0, '', $newMessage);
    } else {
        $w->sendMessage($target, $newMessage);
    }

    $w->disconnect();
                
    sleep(rand(4,6)); // Random pause

}
```

**Comment by fermino** [comment]
You can maybe use a broadcast message.

**Comment by mgp25** [comment]
@atfo90 numbers must be synced, and the employees must have the number added in their contact list too. It should work better is a passive mode, like the user requesting for updates. You don't need to reconnect each time to send a new message.

Anyway, all kind of non-personal activities are being blocked by WhatsApp, for more information, you can check WhatsApp EULA: http://www.whatsapp.com/legal/?l=en

Regards
