### ISSUE TITLE
Adding support for handling incoming WhatsApp Voice Calls

### ISSUE THREAD

**Issue by Tirzono** [mgp25/WhatsAPI-Official#490]
Since the release of calling with WhatsApp, it seems like a good plan to implent some functions to receive (or decline) calls or even send calls. Since iPhone clients cannot receive calls yet, I suggest to change:

    const WHATSAPP_DEVICE = 'iPhone';                                                        // The device name.
    const WHATSAPP_VER = '2.11.14';                                                          // The WhatsApp version.

to:

    const WHATSAPP_DEVICE = 'Android';                                                        // The device name.
    const WHATSAPP_VER = '2.11.555';                                                          // The WhatsApp version.

**Comment by CODeRUS** [comment]
lolwhat? lolwhy?

**Comment by mgp25** [comment]
We arent going to implement voice calls

Regards

**Comment by matteocontrini** [comment]
Just for curiosity: has someone found how WhatsApp handles calls? Do they use FunXMPP for incoming calls notifications perhaps? :smiley:

**Comment by CODeRUS** [comment]
sure
