### ISSUE TITLE
Help me to optimize my procedure

### ISSUE THREAD

**Issue by dahansi** [mgp25/WhatsAPI-Official#491]
Hi there,

I am still getting blocked with some of my numbers. I just received Messages from various friends (I'm in their contact list and they are in mine).

So here is my script:
```php
new WhatsProt(nr,nick,false);
Connect();
bindEvents();
LoginWithPassword(pw);
sendGetPrivacyBlockedList();
sendClientConfig();
sendGetServerProperties();
sendGetHasVoipEnabled($allUsers);
sendGetGroups();
sendGetBroadcastLists();
if(FirstTimeLogin)
       sendSetProfilePicture($img);
sendSync($allNumbers);
sendPing();
if(FirstTimeLogin)
     sendStatusUpdate('thestatus');

while(asLongAsImLoggedIn){
pollMessage()
sendBulkWelcomeToNewFriends() //Sends a Welcome message  to new contacts, 10 minutes after they send me a message. Waits for at least 2 contacts to send the bulk
sendBulks() //If i have a normal Bulk it is send here
sendPresence() 
pollMessage()
sendChatMsg(nr,msg) // If i send a normal message it is done here
sendPresence()
pollMessage()
}


//Sending a message:
sendChatMsg(nr,msg){
sendPresenceSubscription(nr);
sendMessageComposing($nr);
usleep(mt_rand(100000,5000000));
sendMessagePaused($nr);
sendMessage($nr, $msg);
}
//If somebody adds me and sends me a message who is not yet in my contact list:
processReceivedMessage(...){
...
sendSync($allUsers,null,'delta')    //Synchronising all users again (old + new)
...
}
```

So, after sending a bulk the scripts wait between 4 und 9 seconds to send the next one. 
All Bulks have min 2 and maximum 20 users.

The strange thing is I dont even need to send a message out to get blocked. I have a maximum of 500 users for one number. Some numbers have 500 users and are not blocked. Some numbers get blocked after just 20 to 50 users.

I can't find my mistake. -.-

Can somebody help me?

Thanks a lot!

**Comment by mgp25** [comment]
We dont support bulk sending

**Comment by dahansi** [comment]
As is said, this happens if I dont even send any message. You can skip the bulk-sending part if you want...
