### ISSUE TITLE
Register not working, no_routes error

### ISSUE THREAD

**Issue by zvermephi** [mgp25/WhatsAPI-Official#494]
Hello!
I tried to register new number today, and everytime I got "no_routes" error.
Also I tried different phone numbers, connect from different IPs - still get this error.
Please, help.

**Comment by mgp25** [comment]
@zvermephi if you dont post debug log, we cant help you. Post debug log.

**Comment by zvermephi** [comment]
Debug log:

####################
#                  #
# WA Register Tool #
#                  #
####################


Username (country code + number without + or 00): 79263231312


Type sms or voice: sms
Array
(
    [in] => 263231312
    [cc] => 79
    [id] => v!m▒<y▒▒0▒1▒b1tf(>
    [lg] => ru
    [lc] => RU
    [sim_mcc] => 250
    [sim_mnc] => 000
    [method] => sms
    [token] => 22e786a235221692b7866192d3517644
)
stdClass Object
(
    [status] => fail
    [reason] => no_routes
    [retry_after] => 3600
)
There was a problem trying to request the code.

Thanks!

**Comment by mgp25** [comment]
@zvermephi Its a virtual phone number?

**Comment by zvermephi** [comment]
No, phone number is "real", sim is in my phone now.

**Comment by mgp25** [comment]
@zvermephi If you are using it in your phone, instead of registering it, extract the password from your device: https://github.com/mgp25/WhatsAPI-Official/wiki/Extracting-password-from-device

**Comment by zvermephi** [comment]
Well, unfortunately I can't do It, because there is no WhatsApp client for nokia 3210 ((

**Comment by mgp25** [comment]
@zvermephi i just sent you an sms, send me back the code by mail and ill send you back the password.

Regards

**Comment by zvermephi** [comment]
880-481, thanks.
But what should I do, if will be necessary to register another number or lost my password?
There is some bug in WhatsApi with registration, or I am doing something wrong?

**Comment by mgp25** [comment]
@zvermephi i have your password send me an email and ill send you the password.

Regards
