### ISSUE TITLE
Send a file with different duplicate file hash and size!

### ISSUE THREAD

**Issue by phpjoker** [mgp25/WhatsAPI-Official#497]
```xml
tx  <iq id="upload-1425888369-17" to="s.whatsapp.net" type="set" xmlns="w:m">
tx    <media hash="LzoNj5NDdPp95n/jb7hUNzfEL0R8cXAjx1QlF5jjWwA=" type="video" size="2563221"></media>
tx  </iq>

rx  <iq from="s.whatsapp.net" id="upload-1425888369-17" type="result">
rx    <duplicate url="https://mmv206.whatsapp.net/d/At6oGKSnNIac8BWWm1VQL6HDrrvDmItaNhGs7CJZrcC0.mp4" size="4154431" mimetype="video/mp4" filehash="OZ8l5rSlBWQWvO6luG6gGfgQJfAOiPr2NxsxtTTtPiM=" duration="127" type="video" vcodec="h264" width="480" height="270" fps="25" vbitrate="193" acodec="aac" asampfreq="44100" asampfmt="flt" abitrate="63"></duplicate>
rx  </iq>

tx  <message to="xxxxx-1425473855@g.us" type="media" id="message-1425888369-19" t="1425888369">
tx    <media type="video" url="https://mmv206.whatsapp.net/d/At6oGKSnNIac8BWWm1VQL6HDrrvDmItaNhGs7CJZrcC0.mp4" encoding="raw" file="At6oGKSnNIac8BWWm1VQL6HDrrvDmItaNhGs7CJZrcC0.mp4" size="4154431"> 4985 byte data</media>
tx  </message>
```

**Comment by CODeRUS** [comment]
okay, what is your question?

**Comment by phpjoker** [comment]
Why file hash and size different in upload and duplicate ?

**Comment by mgp25** [comment]
@phpjoker i dont know, its that a problem?

**Comment by phpjoker** [comment]
yes, i want checking database which file uploaded! with unique size and hash

**Comment by mgp25** [comment]
@phpjoker its a WhatsApp result, i dont know why its different, maybe to avoid something, i dont know, but i dont see any problem on that. Use the size and hash you got, and try with which ones works, and that it.

Regards

**Comment by phpjoker** [comment]
In this case when i send a video file for example , my contact receive another video file!!

**Comment by mgp25** [comment]
@phpjoker post here your code and the event you use to capture the size and hash

**Comment by phpjoker** [comment]
I check it now, size of sended clip is "2563221" but received clip size is "4154431"
but both clip are the same with different size and hash!!

**Comment by CODeRUS** [comment]
whatsapp encoding/decoding media on server
