### ISSUE TITLE
Unable to set profile pic using sendSetProfilePicture()

### ISSUE THREAD

**Issue by rayidi** [mgp25/WhatsAPI-Official#498]
Hi I'm unable to set photo using `$w->sendSetProfilePicture($pic);` where $pic has full http URL of the logo.
`
[Mon Mar 09 17:35:32 2015] [error] [client 183.XX.XXX.XX] PHP Fatal error:  Uncaught exception 'ConnectionException' with message 'Connection Closed!' in /var/www/meriawaazapp.in/whatsapp/src/whatsprot.class.php:616\nStack trace:\n#0 /var/www/meriawaazapp.in/whatsapp/src/whatsprot.class.php(2042): WhatsProt->pollMessage()\n#1 /var/www/meriawaazapp.in/whatsapp/src/whatsprot.class.php(3937): WhatsProt->waitForServer('setphoto-142592...')\n#2 /var/www/meriawaazapp.in/whatsapp/src/whatsprot.class.php(1848): WhatsProt->sendSetPicture('12362372031', 'http://www.what...')\n#3 /var/www/meriawaazapp.in/app/admin/newChannel.php(76): WhatsProt->sendSetProfilePicture('http://www.what...')\n#4 {main}\n  thrown in /var/www/meriawaazapp.in/whatsapp/src/whatsprot.class.php on line 616
`

Please help me

**Comment by mgp25** [comment]
Post your code
