### ISSUE TITLE
changing destination number error

### ISSUE THREAD

**Issue by shermund** [mgp25/WhatsAPI-Official#500]
Dear sir,

I have been testing it for a week, all works fine but i cannot change destination number on the fly.

which means i have coded 2 lines to change the $dst or $target variables. it seemed to only work when i hard code it in the script instead of being able to change during CLI session in the console/cmd.

please advise. i am a novice programmer so dont mind me asking silly questions like this.

```php
            case "/chatwith":
                echo "[] chatwith: ";
                $handle = fopen ("php://stdin","r");
                $target = fgets($handle);
                $sync = array($target);
                $w->sendSync($sync); 
                $w->sendPresenceSubscription($target);
                $w->sendGetRequestLastSeen($target);
                break;
```

this is the part where i have added in the CLI.

this is the result
![capture](https://cloud.githubusercontent.com/assets/4609054/6569869/5c0f716c-c72c-11e4-8fcb-74e8de5b8a32.PNG)

It seemed to me that the target number isnt picked up somewhere in between, where i have cant check last seen and all sorts.

**Comment by shermund** [comment]
Is this something to do with jabberid/token?

**Comment by mgp25** [comment]
@shermund check this example: https://github.com/mgp25/WhatsAPI-Official/blob/master/examples/Simple%20CLI%20client.php

The solution its in there.

Regards

**Comment by shermund** [comment]
I have gone through it for the past 1 week, what i meant is changing the destination after the login, what i am seeing in the script is determining the destination number via arguments while firing up the script.

sorry for the inconvenience.
