### ISSUE TITLE
Print all contacts and their last message

### ISSUE THREAD

**Issue by TriPSs** [mgp25/WhatsAPI-Official#507]
Is there a way to print all the contacts you have and the last message from them
like the whatsapp web client?

Do i have the get all the contacts from a db? and then get all the messages?
And is there a easy way to get all new incoming messages with there number?

I'm sorry if i'm asking the obvious or that i'm missing something.

Thanks in advanced.

**Comment by 0xTryCatch** [comment]
Contacts must be stored by you. These are not stored by WhatsAPI. If you store them in the same database as the WhatsAPI messages you can easily query that database to get the info you want.

**Comment by TriPSs** [comment]
Oke, but what if i get a message from some one that i don't have stored in my db? How will i know that number send me a mssg?

**Comment by 0xTryCatch** [comment]
You can use the events for that: https://github.com/mgp25/WhatsAPI-Official/wiki/WhatsAPI-Documentation#list-of-all-events
