### ISSUE TITLE
Always get blocked (Burned 3 SIMs now)

### ISSUE THREAD

**Issue by Silikowski** [mgp25/WhatsAPI-Official#508]
Hi mgp25,

sorry for asking again.

I startet with a script like this here:

```
Get Numbers
while loop {
Login
Send Image to Number[x]
Logout
}
```

Took about 35 Seconds for 30 Images to send. Worked well for a month.

Then i updated to
```
Get Numbers
Login
while loop {
Send Image to Number[x]
}
Logout
```

Took just 15 Seconds for 30 images to send.

Worked a few days -> blocked.

Now i made it "more human":

```
Get Numbers
Login
while loop {
Send Image to Number[x]
sleep(3);
}
Logout
```

Blocked again.

Using official code, last update.

I know: read the wiki and the WA EULA for the reasons beeing blocked.

I just want to know, if there is any tip on how to perform. I dont want to spam. I just need to send an image to users registered to the website (they want it!)

Even if the script runs 10 Minutes, its no problem. I just dont want to get blocked all the time.

How do you perform on your tests when you're sending hundreds of messages???

Thank you so much!

**Comment by mgp25** [comment]
@Silikowski because i only send messages to myself, i use it for personal usage only.

You can't send massive messages even if you make it more realistic, why? because its easy to detect the API, its really easy.

WhatsApp its banning 3rd party apps, and they are blocking every user that uses this API not only for spamming, abusing their sytem too, and yes, they think sending massive messages (even if you need to send to registered users), and it will get blocked.

According to WhatsApp EULA, you can use this API, only for personal usage, if you use it in other way, they have no responsability, with this i mean, they can block you whenever they want.

So my recommendatio is the following one: Only answer the number that requests the information, otherwise, WhatsApp will block your number.

Regards

**Comment by robocop249** [comment]
This does not apply.
I made an "autoresponder" for a dentist.
Replying on incoming messages does not save you from being banned.

Just realize, that WhatsApi is just nothing for more than experimenting yourself a bit around,
Not for use in any professional environment.

**Comment by nikfariz** [comment]
using whatsapi is against their EULA. period. u will get banned no matter how big or small ur list is. 

if you're thinking of using whatsapi for other than messaging ur friends whom u know personally (who have added ur number to their contact list), then its no longer personal.

but then, u're better off using Whatsapp Web for that matter. It's an official web app from Whatsapp and you will not be banned if u use it like a human do.

Why do we want to waste time and resources using WhatsApi when at the end of the day, its no better than using the official whatsapp? 

What do you guys use Whatsapi for? 

- as an autoresponder? blocked
- as a mass messenger? blocked
- as a personal messenger? (maybe u wont be blocked, but why use whatsapi when u can use official whatsapp web?)

Can anyone tell me what you use whatsapi for and your number does not get blocked?

**Comment by robocop249** [comment]
That's the point. There is no point anymore.

**Comment by robocop249** [comment]
I also ask myself, why my comments get deleted?
I am just speaking the truth?
This api ist not for a professional use, it is for personal use which means not much more than experimenting.

@mgp25 why do you keep deleting my comments?

**Comment by nikfariz** [comment]
maybe.. just maybe its because whatsapi-official is mgp25's baby...

he worked hard to maintain it..

and yet there are people like you (and me) that is trying to proof that whatsapi is a time-waster (or probably to upgrade some skills (aka experiment)).. which in the end, will cause the majority of us to lose steam and forget whatsapi...

maybe...

**Comment by jonnywilliamson** [comment]
@robocop249 @nikfariz 

Couldn't agree more. So if you're not a spammer, and you want to be able to send messages to other people who are prepared to receive them and you want to avoid any risk of being blocked....I came to only one conclusion:


Telegram
https://github.com/vysheng/tg
(Use this to build an executable that you can run as a daemon 24/7 on your server)


And using this wrapper it can be easily used for PHP.
https://github.com/zyberspace/php-telegram-cli-client


Been using this for weeks and it's been fantastic. SO thank you whatsapi, it's been fun, but you're just not work the hassle or risk anymore.

**Comment by nikfariz** [comment]
@jonnywilliamson  oh how i can not love u?

**Comment by jonnywilliamson** [comment]
@nikfariz a handshake it just fine thanks :)

Anyway, the hard part is getting the executable built, but once that is done it is just fantastic.

Disclaimer - I have nothing to do with Telegram. I have heard that there may be an issue at the moment with regards registering a new number using the telegram-cli....purely down to the fact that telegram have changed their registration servers ip numbers....once that gets updated in the code it'll be back to business.

Telegram is like a breath of welcoming fresh air! They want you to use them!

That's not to say @mgp25 we don't appreciate your efforts, it's just that it seems, in the long run, it's going to be in vain.

**Comment by robocop249** [comment]
Cool! Thanks for the hints.

@nikfariz yes, this could be the problem.
I can understand him. It has been really work for years for free.
It was used by thousands of developers.
As soon as it stops working or gets in trouble everybody just turns around and sais "bye".

I would like to say thanks before saying bye!
Thank you @mgp25!!!
Much appreciated!

**Comment by robocop249** [comment]
@jonnywilliamson are there binaries for windows?

**Comment by jonnywilliamson** [comment]
It's not fair to continue discussion on another project here on whatsapi.

You should head over there.

(I don't know, I run linux on my server)

**Comment by robocop249** [comment]
You're right. Cheers, see you there ;)

**Comment by mgp25** [comment]
@nikfariz @robocop249 @jonnywilliamson WhatsAPI was NEVER meant to be used for commercial purposes. It only work for personal usage ONLY for personal usage.

If you use it in other way it obiously NOT going to work, as easy as that.

**Comment by jonnywilliamson** [comment]
@mgp25 Agreed.

So I use it to send messages to ME, from my server, to update me on various things. I couldn't take the risk anymore of blocking numbers etc. So I don't need to...

I just move to a project that wants me to use their service. I get to relax knowing it's going to be working tomorrow, next week, next month without fear of having to update code.

I don't mind installing a new app on my phone. My wife/friends I set up with this too don't mind. It's a win win.

Don't take any of this as an negative on this project. Your support has been **amazing** here over the past number of months - its hard to know how you kept so cool among so many help requests!!

 But it has to be said....for those NON spammers who want to use a messaging service, whatsapi is not a reliable long term solution.

If whatspp ever change their EULA, I'll be back.

**Comment by jonnywilliamson** [comment]
@0xTryCatch . I fail to see how removing previous comments on this thread is of benefit to anyone. It was a civilized conversation.

A bit of a "smell" starting to emulate if I'm honest with regards that type of action...
