### ISSUE TITLE
Event when a number is removed from a group

### ISSUE THREAD

**Issue by PHPian** [mgp25/WhatsAPI-Official#512]
Is there any event fired when the number is removed from a group. Something similar to "onGroupisCreated" but just the opposite.

**Comment by mgp25** [comment]
Yes, read the wiki, its in the event list

`    onGroupsParticipantsRemove( $mynumber, $groupId, $jid )`

**Comment by PHPian** [comment]
Thank you. I had seen that but was unaware of what it does. Is it possible for us to get a 1 line description for these events please.
