### ISSUE TITLE
Register twilio number

### ISSUE THREAD

**Issue by moshere** [mgp25/WhatsAPI-Official#514]
Hi,
I'm trying to register twilio number and get the following. Please assist.
Thank you

code
$w = new WhatsProt('15***44016', '359845054972786', 'true');
$w->codeRequest('sms'); // could be 'voice' too

output

C:\Users\mosher>c:\kms\php\php.exe c:\kms\WhatsAPI-Official-master\src\whatsapp_whatsapi_register.php
MIB search path: c:/usr/share/snmp/mibs
Cannot find module (IP-MIB): At line 0 in (none)
Cannot find module (IF-MIB): At line 0 in (none)
Cannot find module (TCP-MIB): At line 0 in (none)
Cannot find module (UDP-MIB): At line 0 in (none)
Cannot find module (HOST-RESOURCES-MIB): At line 0 in (none)
Cannot find module (SNMPv2-MIB): At line 0 in (none)
Cannot find module (SNMPv2-SMI): At line 0 in (none)
Cannot find module (NOTIFICATION-LOG-MIB): At line 0 in (none)
Cannot find module (UCD-SNMP-MIB): At line 0 in (none)
Cannot find module (UCD-DEMO-MIB): At line 0 in (none)
Cannot find module (SNMP-TARGET-MIB): At line 0 in (none)
Cannot find module (NET-SNMP-AGENT-MIB): At line 0 in (none)
Cannot find module (DISMAN-EVENT-MIB): At line 0 in (none)
Cannot find module (SNMP-VIEW-BASED-ACM-MIB): At line 0 in (none)
Cannot find module (SNMP-COMMUNITY-MIB): At line 0 in (none)
Cannot find module (SNMP-FRAMEWORK-MIB): At line 0 in (none)
Cannot find module (SNMP-MPD-MIB): At line 0 in (none)
Cannot find module (SNMP-USER-BASED-SM-MIB): At line 0 in (none)
Cannot find module (SNMP-NOTIFICATION-MIB): At line 0 in (none)
Cannot find module (SNMPv2-TM): At line 0 in (none)
Array
(
    [in] => 5***44016
    [cc] => 1
 ·♠▼-Ü╢q┤ ∩rm·↑πδα°
    [lg] => en
    [lc] => US
    [sim_mcc] => 310
    [sim_mnc] => 260
    [method] => sms
    [token] => 5517114d916144195be04664399f3d3b
)
stdClass Object
(
    [status] => fail
    [reason] => bad_param
    [param] => number
)
PHP Fatal error:  Uncaught exception 'Exception' with message 'There was a problem trying to request the code.' in C:\KMS\WhatsAPI-Official
Stack trace:
#0 C:\KMS\WhatsAPI-Official-master\src\whatsapp_whatsapi_register.php(18): WhatsProt->codeRequest('sms')
#1 {main}
  thrown in C:\KMS\WhatsAPI-Official-master\src\whatsprot.class.php on line 399

**Comment by mgp25** [comment]
https://github.com/mgp25/WhatsAPI-Official/wiki/Frequently-asked-questions#registration-no_routes-and-bad_param-issue
