### ISSUE TITLE
Ability to use a single connection

### ISSUE THREAD

**Issue by Udirley** [mgp25/WhatsAPI-Official#516]
Hello staff.
It is possible to stay connected permanently to receive messages and use another script to send messages without dropping the connection already established?
I would like to use the same connection for all scripts.
If this is not possible, the fact of having to reconnect every time I answer or send a message can be a problem?
Now I thank you for your attention.

**Comment by mgp25** [comment]
Yes, its possible, you can check this example: https://github.com/mgp25/WhatsAPI-Official/tree/master/examples/ajaxDemo

For further support you will need to search in google.

And why do you want to disconnect to send a message? You can listen and answer at the same time, check this example: https://github.com/mgp25/WhatsAPI-Official/blob/master/examples/exampleFunctional.php

Regards
