### ISSUE TITLE
Check if a number is registrated @ WA

### ISSUE THREAD

**Issue by hey-there** [mgp25/WhatsAPI-Official#519]
hello,

any idea how i can check if a number is using whatsapp?

greetings

**Comment by hansrouge** [comment]
It is in the wiki:
```php
onSyncResult($result){
	    foreach ($result->existing as $number) {
	       echo "$number does exist<br />";
	    }
	    foreach ($result->nonExisting as $number) {
	       echo "$number does not exist<br />";
	    }
	}
```

**Comment by hey-there** [comment]
How i have to do it? I have added 

        foreach ($result->existing as $number) {
           echo "$number does exist<br />";
        }
        foreach ($result->nonExisting as $number) {
           echo "$number does not exist<br />";
        }

to the Event for onSyncResult (at)AllEvents.php 
And then i have synced with:

$this->waContainer->sendSync($number);

But i get no echo if the user is exist or not. 
any idea?

**Comment by mgp25** [comment]
@hey-there check contactsync example in examples folder

**Comment by hey-there** [comment]
I don´t know what is wrong. I added to my WhatsApp-Trait for my project. 

$this->waContainer->eventManager()->bind('onGetSyncResult', '$onSyncResult');

On my init function before i login & connect to the whatsapp server. 
in the trait is 

		public function onSyncResult($result)
		{
			foreach ($result->existing as $number) {
				echo "$number exists<br />";
			}
			foreach ($result->nonExisting as $number) {
				echo "$number does not exist<br />";
			}
			die();
		}

available. Then i send the sync request:

return $this->waContainer->sendSync($number);

But i only get this warning:

call_user_func_array() expects parameter 1 to be a valid callback, function '$onSyncResult' not found or invalid function name

But i don´t know why they can not access to this function ...

**Comment by jesussales** [comment]
The function haven't $

**Comment by mgp25** [comment]
@hey-there read the wiki, check how to use events, and check the examples.

Regards

**Comment by hey-there** [comment]
Without $ the same error:
Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'onSyncResult' not found

	trait whatsapp {
		
		public function waÌnit($number, $password, $name = "WhatsInfo", $debug = false) {
			$this->waContainer = new WhatsProt($number, $name, $debug);
			$this->waContainer->eventManager()->bind('onGetSyncResult', 'onSyncResult');
			$this->waContainer->connect();
			$this->waContainer->loginWithPassword($password);
		}
		
		public function onSyncResult($result)
		{
			foreach ($result->existing as $number) {
				echo "$number exists<br />";
			}
			foreach ($result->nonExisting as $number) {
				echo "$number does not exist<br />";
			}
			die();
		}

		public function isWaUser($number) {
			return $this->waContainer->sendSync($number);
		}
		
		
	}

**Comment by mgp25** [comment]
@hey-there read the wiki! you arent even using the correct constructor.

**Comment by mkwsra** [comment]
Same Error here, and his constructor is the same as yours along with mine! What is the problem?

```
ErrorException in WhatsApiEventsManager.php line 15:
call_user_func_array() expects parameter 1 to be a valid callback, function 'onSyncResult' not found or invalid function name
```

I've read all the wiki, this is [Legacy Event](https://github.com/WHAnonymous/Chat-API/wiki/WhatsAPI-Documentation#legacy-events) doesn't seem to work!

**Comment by 0xTryCatch** [comment]
@mkwsra The error message is quite obvious!

**Comment by mkwsra** [comment]
@0xTryCatch I've `'onSyncResult'` function and I made sure it's the same name, now its working only using  the first way of handling events `MyEvents.php`.

**Comment by Bou3ou** [comment]
Hi @mkwsra i'm new in this community can you explain me please how you call the function onSyncResult to have an idea if the contact has a whatsapp app or not ?
