### ISSUE TITLE
Best practices to sync contacts in order to avoid block

### ISSUE THREAD

**Issue by yniv** [mgp25/WhatsAPI-Official#520]
I'm using the api to let contacts consult with managers. I never send messages to someone who have not contacted me first.
Currently, I call sync users with Delta and Background params every 10 minutes with all the new contacts that contacted me since the last sync. 
Is it a good practice or do I need to do something else to avoid block? 
thanks!

**Comment by mgp25** [comment]
Only sync at login

**Comment by yniv** [comment]
@mgp25 but if my process is always connected and there are always new users who contact me then i will never sync them... also, do i need to sync with Delta and Background or something else?
