### ISSUE TITLE
Login Fail

### ISSUE THREAD

**Issue by SmokiinTreez** [mgp25/WhatsAPI-Official#521]
Hi ive been using your API for a few weeks now with no problems at all (Great Code)
Today i was trying to login and sync some contacts, But i am facing a error 

[code]
Uncaught exception 'Exception' with message 'Login Failure'
WhatsProt->doLogin() #1 
WhatsProt->loginWithPassword('XXXXXXXXXXX...') #2
whatsprot.class.php on line 1640
[/code]

i have tried by registering 2 new numbers but i cant login to send or sync ?

is there a new issue as of today ?

Things i have tried....
1. New Numbers 
2. New hosting
3. Simple Sync 1 Contact 
4. Simple Send Message

**Comment by mgp25** [comment]
Post debug log

**Comment by SmokiinTreez** [comment]
[code]
Fatal error: Uncaught exception 'Exception' with message 'Login Failure' in /home/calculat/public_html/wapp/src/whatsprot.class.php:1640 Stack trace: #0 /home/calculat/public_html/wapp/src/whatsprot.class.php(474): WhatsProt->doLogin() #1 /home/calculat/public_html/wapp/testwasher.php(86): WhatsProt->loginWithPassword('xxxxxxxxxxxxxxxxxxxxxx...') #2 {main} thrown in /home/calculat/public_html/wapp/src/whatsprot.class.php on line 1640
[/code]

**Comment by SmokiinTreez** [comment]
Sorry i dont think that is debug you wanted ?
Can you explain ?

Thanks

**Comment by mgp25** [comment]
@SmokiinTreez your password is wrong or your number has been blocked. I recommend you to read the wiki and follow some examples.

Regards

**Comment by SmokiinTreez** [comment]
I have registered 2 new numbers password is base64 format i believe everything is correct, Also i have followed examples on this issue by simply send 1 message to my number and simply sync 1 contact.

Ok thanks anyway
