### ISSUE TITLE
id file creation error

### ISSUE THREAD

**Issue by felipecorrea9** [mgp25/WhatsAPI-Official#522]
I just created my password that it contains this char "/".

That causes this:
`
PHP Warning:  file_put_contents(/var/www/html/dir/whatsapp/src/wadata/id.SK/wuVSxVMfkubfrB8OuIXxkbaM=.dat): failed to open stream: No such file or directory in /var/www/html/dir/whatsapp/src/whatsprot.class.php on line 2334
`
Anything I can do?

Regards!

**Comment by mgp25** [comment]
@felipecorrea9 post the code you are using..
