### ISSUE TITLE
Is there any way to get about Update Notification and Emulate Temporary Block

### ISSUE THREAD

**Issue by assegaf** [mgp25/WhatsAPI-Official#525]
In Official we get information about when there is update and when expired current version some days from now. Is there any notification info from whatsapi about that ?

and official client also has introduce temporary block, but so far whatsapi never get it, is there any way to produce that temporary block ?

**Comment by mgp25** [comment]
@assegaf Yes, when its outdated you will receive a node saying something like that.

Also if you are temporary blocked you will receive a not-authroized node with a retry and expire params

Regards

**Comment by assegaf** [comment]
@mgp25 
yeah, thanks, in which node ?, since its only happen not sure in time.

yeah is there any activity to produce that not-authroized temporary using the api ?

**Comment by hansrouge** [comment]
@mgp25 please reopen.

WA blocked me and changed my password, too. If I use $w->codeRequest('sms') I dont get the new password by sms. It is shown directly in the response node.
It would be great to have this implemented, because it makes those password changes a lot easier.

Thanks!

**Comment by CODeRUS** [comment]
you should post debug log

**Comment by mgp25** [comment]
@hansrouge as @CODeRUS said get used to post debug log.

**Comment by assegaf** [comment]
I think the question is not about that, the question is how to get "temporary block" like we use whatsapp++ or whatsapp MD , mod of whatsapp.

**Comment by 0xTryCatch** [comment]
@assegaf the debug log is necessary to see what kind of block happened (if any)

**Comment by hansrouge** [comment]
@mgp25 I will post the code as soon as it happens again :)

@0xTryCatch Some of them maybe 1,5 months ago, some last week. Does that matter? Does WhatsApp change the password if I didn't log me in for a longer time?

**Comment by hansrouge** [comment]
@mgp25 here you go:

Yesterday the number got blocked, today I just called "$code = $w->codeRequest('sms');" and thats the return. I didnt receive any sms, the new code is shown directly in the code. I did not call checkCredentials.

```php
Array
(
    [in] => xxx
    [cc] => xx
    [id] => xxx
    [lg] => de
    [lc] => DE
    [sim_mcc] => 262
    [sim_mnc] => 000
    [method] => sms
    [token] => e9037e29d82f7ec3d8fe15b574fdfa96
)
stdClass Object
(
    [status] => ok
    [login] => xxx
    [pw] => xxx
    [type] => existing
    [expiration] => 1455274163
    [kind] => free
    [price] => 0,89 €
    [cost] => 0.89
    [currency] => EUR
    [price_expiration] => 1429680738
)
object(stdClass)#6 (10) {
  ["status"]=>
  string(2) "ok"
  ["login"]=>
  string(13) "xxx"
  ["pw"]=>
  string(28) "xxx"
  ["type"]=>
  string(8) "existing"
  ["expiration"]=>
  int(1455274163)
  ["kind"]=>
  string(4) "free"
  ["price"]=>
  string(8) "0,89 €"
  ["cost"]=>
  string(4) "0.89"
  ["currency"]=>
  string(3) "EUR"
  ["price_expiration"]=>
  int(1429680738)
}
```
