### ISSUE TITLE
Login Failure

### ISSUE THREAD

**Issue by deepak-manwal** [mgp25/WhatsAPI-Official#526]
I am using this now but its not working for me. Has anyone tested this currently?

It was working before but now its not loging any Phone number. Is there any update or changes in whatsapp API?

**Comment by adpstore** [comment]
I think whatsapp blocked a lot of account working whit whatsAPI ..... mine is gone .... someone know how can i reactive the account???

**Comment by mgp25** [comment]
If you send massive messages or use it for commercial usage you will be blocked, as easy as that

**Comment by newuser10** [comment]
I am having the same issue. The numbers were working fine yesterday, but today i cannot login. The numbers are not blocked, i can still see them in whatsapp contact list on a device. I have not used checkCredentials() but it seems like password is changed. Could it be due the updated whatsapi code?

**Comment by 0xTryCatch** [comment]
@newuser10 Can you post a debug log of what is sent and received please.

**Comment by newuser10** [comment]
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="639436543702">kÃ¦å639436543702ºh¬Ûf¯Æ—wPA%¶*RÆü1426500267WhatsApp/2.12.61 S40Version/14.26 Device/Nokia302 MccMnc/515002</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>JDÜ‘©L˜{UŠ¬eH1~1Ñê</challenge>

tx  <response>nr^CÚÔ'·õ‚½knÌ?¨
rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>


i get the <not-authorized> node while trying to login.

**Comment by newuser10** [comment]
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="639436543702">kÃ¦å639436543702ºh¬Ûf¯Æ—wPA%¶*RÆü1426500267WhatsApp/2.12.61 S40Version/14.26 Device/Nokia302 MccMnc/515002</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>JDÜ‘©L˜{UŠ¬eH1~1Ñê</challenge>

tx  <response>nr^CÚÔ'·õ‚½knÌ?¨
rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>


I get the  <not-authorized> node when trying to login.

**Comment by 0xTryCatch** [comment]
Thanks. What happens when you call checkCredentials()?

**Comment by newuser10** [comment]
stdClass Object
(
    [status] => fail
    [reason] => incorrect
    [sms_length] => 6
    [voice_length] => 6
)


I guess this is because of the identity. The numbers were registered using a different identity. I don't know what caused this password change? This happened for all my numbers not just this one.

**Comment by 0xTryCatch** [comment]
How do you know the password was changed? Did you register again?

**Comment by mylover80** [comment]
Why this issue has been closed ?
I noticed that since this year there are many cases (including myself) reported login failed, and in most cases the reason is different from previous - not bulk send, not coding error - but blocked due to using "not the same official client".
I can imagine the battle just starts, and it will never end.  This thread is useful to track what must be done to avoid blocking - for each and every versions when the client gets updated.

**Comment by deepak-manwal** [comment]
Totally agree with @mylover80. I am still getting error and unable to login in API, its showing me "Login Failure" with any of the number.

How do i check is Number is blocked or not????

**Comment by 0xTryCatch** [comment]
The issue is closed because there is nothing we can do.

**Comment by CODeRUS** [comment]
@deepak-manwal checkCredentials()

**Comment by mylover80** [comment]
@0xTryCatch Why you say you cannot do anything.  If login failure is due to mis-use, yes, it is not your problem.  But what about if failure is due to wrong program code ? Or the code, though works, cannot behave fully in the same way as the server expects.

**Comment by CODeRUS** [comment]
@mylover80 developers doing their best. If you have something to contribute - just do it, if not - just use it as is. All misbehaves are wrong usage of api by your, not whatsapi developers.
