### ISSUE TITLE
Uncaught exception 'Exception' with message 'Login Failure'

### ISSUE THREAD

**Issue by mosqueiro** [mgp25/WhatsAPI-Official#530]
I get the sms and the password .
But when I try to run the following code I am getting the message below. I've done the test with several numbers .
```php
<?php
require '../src/whatsprot.class.php';

$nickname = "xxxxx"; // Your nickname
$sender =   "55xxxx"; // Number with country code
$imei =     ""; // Not used
$password =     "xxxxxxxxxx"; // Password you received from WhatsApp (Using WART, WhatsAPI...)
$dst = "55xxxxxxx"; // Number with country code (target to send a message)
$wa = new WhatsProt($sender, $imei, $nickname, TRUE);
$wa->connect();
$wa->loginWithPassword($password);

$wa->sendMessage($dst, "You have sent a message correctly, so you've connected to WhatsApp");

?>
```

```xml
PHP Deprecated:  Comments starting with '#' are deprecated in /etc/php5/cli/conf.d/ming.ini on line 1 in Unknown on line 0
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="55xxxxxxxx"></auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>??<F?+0:8W?????z</challenge>

tx  <response>?[??g?8??`??ڥ?|g???6|_?#jI???</response>

PHP Fatal error:  Uncaught exception 'Exception' with message 'Login Failure' in /var/www/whats/src/whatsprot.class.php:2304
Stack trace:
#0 /var/www/whats/src/whatsprot.class.php(562): WhatsProt->doLogin()
#1 /var/www/whats/examples/msg.php(14): WhatsProt->loginWithPassword('QlM4cUBYfIKqzy5...')
#2 {main}
  thrown in /var/www/whats/src/whatsprot.class.php on line 2304
```

**Comment by 0xTryCatch** [comment]
It seems you are blocked. Use <code>checkCredentials()</code> and post the result here

**Comment by mgp25** [comment]
@mosqueiro You are using an outdated constructor you should use this instead:

```php
$w = new WhatsProt($username, $nickname, $debug);
```

Try logging in again, if you receive a `not-authorized` node, you are blocked.

See the F.A.Q. for more information: https://github.com/mgp25/WhatsAPI-Official/wiki/Frequently-asked-questions

Regards

**Comment by TriPSs** [comment]
I had the same only mine also had the not-authorized node, if i login now if have it again only without the not-authorized node.

Is there a way to keep receving messages forever? I'm using now the ajax one from the example?
Or do have have to use a other one?
Because if i look in the issues every one is using more functions than i do?

Sorry for bad english.

**Comment by mgp25** [comment]
@TriPSs If you have received once the `not-authorized` node you are blocked, sometimes it doesnt appear, but if you retry, it will.

Yes, you can keep the connection alive, its explained in the wiki, if you want to implement in a webserver you will need to search in google how to config your server.

Regards

**Comment by mosqueiro** [comment]
Now receive :
```
stdClass Object
(
    [status] => fail
    [reason] => no_routes
    [retry_after] => 3600
)

```

**Comment by mgp25** [comment]
@mosqueiro its explained in the F.A.Q https://github.com/mgp25/WhatsAPI-Official/wiki/Frequently-asked-questions

**Comment by mosqueiro** [comment]
Is there a way to get the password of my Android device ? I tried the Pasword Extractor and no longer works.

**Comment by 0xTryCatch** [comment]
Also explained in the wiki. Do some homework please.

**Comment by mosqueiro** [comment]
Its ok !
I managed to extract the pass through the Android tool. But now the message does not reach the recipient ($dst) , follows the log, how come?

Code :
```
<?php
require '../src/whatsprot.class.php';

$nickname = "xxxxxxx"; // Your nickname
$sender =   "5xxxxxxxxxxxxx"; // Number with country code
$imei =     ""; // Not used
$password =     "xxxxxxxxx"; // Password you received from WhatsApp (Using WART, WhatsAPI...)

$dst = "55xxxxxxxx"; // Number with country code (target to send a message)

$wa = new WhatsProt($sender, $nickname, TRUE);
$wa->connect();
$wa->loginWithPassword($password);
$wa->checkCredentials();
$wa->sendMessage($dst, "hello : " . date('H:i'));
?>
```

```
PHP Deprecated:  Comments starting with '#' are deprecated in /etc/php5/cli/conf.d/ming.ini on line 1 in Unknown on line 0
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="557581278350">1M!d557581278350=B???ܻ??m???67v?+1426647308WhatsApp/2.12.61 S40Version/14.26 Device/Nokia302 MccMnc/724002</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>?XX?)?͎??߼??v/?</challenge>

tx  <response>??q?}??4????ܤ{?$?l?X&?O4㷃??O=??</response>

rx  <success t="1426647308" props="4" kind="free" status="active" creation="1421502713" expiration="1453038713">+`m?%?Pa?Zk?H??</success>

tx  <presence name="xxxxxxxx"></presence>
```

Use checkCredentials() :
```
Array
(
    [cc] => 55
    [in] => 75xxxxxxx
    [id] => ????d?)?y?-#=:%
    [lg] => pt
    [lc] => BR
    [network_radio_type] => 1
)
stdClass Object
(
    [status] => fail
    [reason] => incorrect
    [sms_length] => 6
    [voice_length] => 6
)

```

**Comment by 0xTryCatch** [comment]
I called WhatsApp about your problem and they said RTFW

**Comment by rodvan** [comment]
Im getting same issues.. This is driving me nuts, Ive used 4 different phones and I get the same error.
Also using the exampleFunctional.php

[] Logging in as 'mobiments' (52554465----)
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="52554465----"></auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>`?ݐ	????B?D???L5</challenge>

tx  <response>xW!>??s
                     ,?]HɊ?,?kG?Iq#?{f??/</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>

PHP Fatal error:  Uncaught exception 'LoginFailureException' in /Users/r0dvan/code/whatsapp/chatAPI/src/whatsprot.class.php:2273
Stack trace:
#0 /Users/r0dvan/code/whatsapp/chatAPI/src/whatsprot.class.php(551): WhatsProt->doLogin()
#1 /Users/r0dvan/code/whatsapp/chatAPI/examples/exampleFunctional.php(65): WhatsProt->loginWithPassword('hX5Lzwa1gxJLLqB...')
#2 {main}
  thrown in /Users/r0dvan/code/whatsapp/chatAPI/src/whatsprot.class.php on line 2273

Fatal error: Uncaught exception 'LoginFailureException' in /Users/r0dvan/code/whatsapp/chatAPI/src/whatsprot.class.php:2273
Stack trace:
#0 /Users/r0dvan/code/whatsapp/chatAPI/src/whatsprot.class.php(551): WhatsProt->doLogin()
#1 /Users/r0dvan/code/whatsapp/chatAPI/examples/exampleFunctional.php(65): WhatsProt->loginWithPassword('hX5Lzwa1gxJLLqB...')
#2 {main}
  thrown in /Users/r0dvan/code/whatsapp/chatAPI/src/whatsprot.class.php on line 2273

**Comment by mgp25** [comment]
@rodvan 

```xml
rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>
```

You are blocked, everything is explained in the wiki

**Comment by rodvan** [comment]
Thanks a lot.
How exactly can I unblock myself? Or are there some specific guidelines?

**Comment by 0xTryCatch** [comment]
It is not possible to unblock your number

**Comment by rodvan** [comment]
Ok, so I need to buy american numbers to not get blocked or what?

**Comment by vlnsnewton** [comment]
Hello All
@mgp25 i am using 9180102017** number 
firstly i am using this number with some password it is showing 
not-authorized 
node then i use blockchecker.php and it shows number is not blocked and show some password 
and now when i am using this password and typing to send message it is showing following nodes 
challenge
response
seccuss
presence 
nodes i am not able to find where is problem i am having 3 numbers and all numbers having same issue.

Thanx

**Comment by yultyyev** [comment]
Maybe it will be helpful for others. I have same issue, but all works fine if I use password from blockchecker.php
