### ISSUE TITLE
Sync existing contact and new contact

### ISSUE THREAD

**Issue by technocode** [mgp25/WhatsAPI-Official#531]
Hi

Just want to ask how real whatsp application sync existing contact daily. 
Do its sync full contact list every 1 hour or everytime we open whatsp application?
What `$mode` and `$context` use for sync full existing contacts?

And what $mode and $context it use for add new contact?

Thanks

**Comment by hansrouge** [comment]
After I received a message from a new user I call this:
```php
$this->w->sendSync($allUsers,null,4);
```

$allUsers is an array with all my Users.
But don't call it too often. I call it every more then 10 minutes. Some users just have to wait :)

**Comment by mgp25** [comment]
You can also use delta interactive for syncing only the new contact.

Regards

**Comment by hansrouge** [comment]
@mgp25 If I use delta interactive do I still need the array with all my users or is it enough to make an array with the new ones? (sometimes its just 1 new person).
