### ISSUE TITLE
how to I recover password

### ISSUE THREAD

**Issue by rajenpal033** [mgp25/WhatsAPI-Official#532]
Hello,

I noticed that if the password is wrong, the systems throws the exception Login Failure, but is there any way to recover the password or change the password ( checkCredinals function don't return the password now a days ). I know it can be done, there is another optional password which could be used to recover passwords, anyone here, know about this.

Thanks.

**Comment by 0xTryCatch** [comment]
<code>checkCredentials</code> should return your password. Post your output of that function

**Comment by rajenpal033** [comment]
The output is failed and reason invalid

**Comment by rajenpal033** [comment]
can you give a example how do I call this checkCredentials() function?

**Comment by rajenpal033** [comment]
stdClass Object ( [status] => fail [reason] => incorrect [sms_length] => 6 [voice_length] => 6 ) this happens for active numbers also

**Comment by CODeRUS** [comment]
you using incorrect identity

**Comment by rajenpal033** [comment]
please give me example code to call this function

**Comment by mgp25** [comment]
READ the WIKI and F.A.Q! https://github.com/mgp25/WhatsAPI-Official/wiki/Frequently-asked-questions
