### ISSUE TITLE
Receive Message

### ISSUE THREAD

**Issue by gateseee** [mgp25/WhatsAPI-Official#534]
Hello!

Normally, i understand all FAQ's or Wikis, but now i have problems, to read a incoming message.

Can someone give me a Code-Snippet to do this ? 
I only must read all incoming messages (Cron Job all 5 minutes.. ), and save it in any format in any way. Save the Results is no problem for me, but i only see that a message is incoming (Debug), but no body.

```
rx <receipt from="43660XXXXXXX-1396826091@g.us" id="message-1426696863-1"  participant="43664XXXXXXX@s.whatsapp.net" retry="1" offline="1" type="read" t="1426698206"
```
Can Someone Help me please?

**Comment by mgp25** [comment]
@gateseee What you have posted its an ack / receipt, not a message. 

Regards

**Comment by gateseee** [comment]
Yes, i know. Its from the Debug output. 
It's because i find no other way to display an incoming message.

**Comment by gateseee** [comment]
Closed, why ?

**Comment by mgp25** [comment]
@gateseee you are getting a ack / receipt node not a message node, you are NOT receiving a message.

**Comment by gateseee** [comment]
Okay. Then i quote the wrong Log. 
I'm definitly sending a few testmessages to the Number, but i dont know how to read it. 
I tried all code-snippets and the eventmanager but i dont know how to do.. please help me.

**Comment by ngethe** [comment]
You can hack all that data from processReceivedMessage() function
processReceivedMessage($phone, $from, $id, $type, $time, $name, $data)
