### ISSUE TITLE
Get receipt acknowledgement for a sent message

### ISSUE THREAD

**Issue by vishvodhay** [mgp25/WhatsAPI-Official#535]
Hello
I could not find a proper method that gives us a confirmation of delivery after the message has been sent. Couple of forums in google suggested WaitForReceipt() method and I could not find it in Whatsprot class

Any help is appreciated

Thanks

**Comment by mgp25** [comment]
@vishvodhay Please, read the wiki, everything its in there: https://github.com/mgp25/WhatsAPI-Official/wiki

Use this events:
```
onMessageReceivedClient( $mynumber, $from, $id, $type, $time )
onMessageReceivedServer( $mynumber, $from, $id, $type, $time )
```

Regards

**Comment by vishvodhay** [comment]
Thanks so much for your reply @mgp25 . I understand that calling events would let me notify via echo message. What I'm looking for is something like a call to a method somewhere in API which returns me a boolean value or some relevant string saying that message is delivered. 
What I need to do is to capture that value as a success or failure and store it into database table as success or failure again. 
I could do that my having relevant code in onMessageReceivedClient implementation, but is that a proper way to do that? I really wonder

Thanks
