### ISSUE TITLE
SendOfflineStatus

### ISSUE THREAD

**Issue by matthijsotterloo** [mgp25/WhatsAPI-Official#536]
Hi,

I'm wanting the following:

When I'm running the script, the bot shows as offline.
But as soon as someone sends a message, 
```php
function onGetMessage($phone, $from, $id, $type, $time, $name, $body) {
```
I want the bot the be shown as online, send a message and after that go offline again, what's the best way to do that? I already took a look at the Wiki

**Comment by matthijsotterloo** [comment]
Can u help me?

**Comment by mgp25** [comment]
Add inside of onGetMessage event SendOfflineStatus, you can send messages being in offline status if i remember well, you can add that function in the event onMessage.

You can also do this by modifiying the API code you have to always be connected but in offline status.

Regards

**Comment by matthijsotterloo** [comment]
No, I want to be shown offline, but as soon as I'm receiving a message it changes to online

**Comment by mgp25** [comment]
Then add this to the event `sendActiveStatus()`

**Comment by matthijsotterloo** [comment]
The following code:

function onGetMessage($phone, $from, $id, $type, $time, $name, $body) {
        sendActiveStatus();
        sendMessage($from, 'Hoi ' . $name . ', Het is niet mogelijk mij berichten te sturen.');
} 

Is giving: PHP Fatal error:  Call to undefined function sendActiveStatus() on line 16

**Comment by mgp25** [comment]
@matthijsotterloo ...

if your const is:

```php
$w = new WhatsProt($username, $nickname, $debug);
```

then

```php
$w->sendActiveStatus();
```

**Comment by matthijsotterloo** [comment]
That's giving: PHP Notice:  Undefined variable: w in  on line 16
PHP Fatal error:  Call to a member function sendActiveStatus() on a non-object on line 16

**Comment by mgp25** [comment]
@matthijsotterloo have you read my comment above? depends of the name you have assigned to the whatsprot object

**Comment by matthijsotterloo** [comment]
$w = new WhatsProt($username, $identity, $nickname, true);

**Comment by mgp25** [comment]
@matthijsotterloo first. Wrong constructor, i recommend you to read the wiki again and post your code script.

**Comment by matthijsotterloo** [comment]
I already did that a few times, but can't get it done.... 
This is my script:

#!/usr/bin/php
<?php
set_time_limit(0);
include $_SERVER['DOCUMENT_ROOT'].'../src/whatsprot.class.php';
date_default_timezone_set('Europe/Amsterdam');

$username = "31634455279";
$password = "1CaRmROZ6ZFQTu8009+j777wlBU=";
$identity = "HBL Roosterbot";
$nickname = "HBL Roosterbot";

$w = new WhatsProt($username, $identity, $nickname, true);
$messages = array();

function onGetMessage($phone, $from, $id, $type, $time, $name, $body) {
	$w->sendActiveStatus();
	sendMessage($from, 'Hoi ' . $name . ', Het is niet mogelijk mij berichten te sturen.');
} 


/* 	global $cursewords;
	$bad = false;
	$words = explode(' ', $message);
	
	foreach($words as $word) {
		if(in_array(strtolower($word), $cursewords)) {
			$bad = true;
		}
	}
	
	if($bad == true) {
		sendMessage($from, 'Niet schelden, ' . $name . '!');
	} 
} */

function sendMessage($to, $body) {
	global $messages;
	$message = array('to' => $to, 'body' => $body);
	array_push($messages, $message);
}


$w->eventManager()->bind("onGetMessage", "onGetMessage");
$w->connect();
$w->loginWithPassword($password);
//$update = "HBL Roosterbot BETA door Matthijs Otterloo (B2d) eventuele fouten voorbehouden";
//$w->sendStatusUpdate($update);
//$w->sendSetProfilePicture('hbl.jpg');
$w->sendOfflineStatus();
// $w->sendGetGroups();
//Change group title of B2D Chat
//$gjid = "31631185419-1372089209";
//$subject = "B2d💜";
//$w->sendSetGroupSubject($gjid, $subject);

//Print when the user goes online/offline (you need to bind a function to the event onPressence
//so the script knows what to do)
//$w->eventManager()->bind("onPresence", "onPresenceReceived");


//update your profile picture
//$w->sendSetProfilePicture("demo/venom.jpg");

//send picture
//$w->sendMessageImage($target, "demo/x3.jpg");

//send video
//$w->sendMessageVideo($target, 'http://techslides.com/demos/sample-videos/small.mp4');

//send Audio
//$w->sendMessageAudio($target, 'http://www.kozco.com/tech/piano2.wav');

//send Location
//$w->sendLocation($target, '4.948568', '52.352957');

//echo "\n\nYou can also write and send messages to $target (interactive conversation)\n\n> ";

//$target = ($gjid);
//$json = json_decode(file_get_contents('http://scherm.baarnschlyceum.nl/data.php'), true);
//$b2d = $json['changes']['classes']['today']['0']['B2d'];
//$replaced = str_replace(">",'wordt',$b2d);
//	if (empty($replaced)) {
//	$text = "Wijzigingen voor morgen: \r\n \r\n Er zijn morgen geen wijzigingen";
//	$w->sendMessage($target,$text);
//} else {
//	$text = "Wijzigingen voor morgen: \r\n \r\n";
//	foreach($replaced as $uur => $wijziging){
// 	$new = implode(",", $wijziging);
//  	$text .= $uur.": ".$new."\r\n";
//	}
//	$w->sendMessage($target,$text);
// }


while(true) {
	$w->PollMessage();
	sleep(1);
	foreach($messages as $key => $message) {
		$w->sendMessage($message['to'], $message['body']);
		unset($messages[$key]);
	}
}

**Comment by mgp25** [comment]
It should be like this...

```php
#!/usr/bin/php
<?php
set_time_limit(0);
include $_SERVER['DOCUMENT_ROOT'].'../src/whatsprot.class.php';
date_default_timezone_set('Europe/Amsterdam');

function onGetMessage($phone, $from, $id, $type, $time, $name, $body)
{
    $w->sendActiveStatus();
    $w->sendMessage($from, 'Hoi ' . $name . ', Het is niet mogelijk mij berichten te sturen.');
} 


function sendMessage($to, $body)
 {
    global $messages;
    $message = array('to' => $to, 'body' => $body);
    array_push($messages, $message);
}
//////// CONFIG
$username = "placeholder";
$password = "placeholder";
$nickname = "HBL Roosterbot";
//////////////////////

$w = new WhatsProt($username, $nickname, true);
$w->eventManager()->bind("onGetMessage", "onGetMessage");
$w->connect();
$w->loginWithPassword($password);
$w->sendOfflineStatus();

$messages = array();

while(true) {
    $w->PollMessage();
    sleep(1);
    foreach($messages as $key => $message) {
        $w->sendMessage($message['to'], $message['body']);
        unset($messages[$key]);
    }
}
```

**Comment by matthijsotterloo** [comment]
Still PHP Notice:  Undefined variable: w in on line 9

**Comment by mgp25** [comment]
@matthijsotterloo man, you need to learn how to debug for yourself, its not an API issue.

Use this instead for example (you need to adapt it to your path oc!):

```php
require_once('../src/whatsprot.class.php');
require '../src//events/MyEvents.php';
```

**Comment by matthijsotterloo** [comment]
Yes I know but i've been trying this for a long time now and it's still not working!
And again after replacing it with this code not working....

**Comment by mgp25** [comment]
@matthijsotterloo look, try with some easy ok? Try going step by step, the following code im going to post, its fully working:

```php
<?php

require_once('/Users/mgp25/Desktop/WhatsAPI-Official/src/whatsprot.class.php');
require '/Users/mgp25/Desktop/WhatsAPI-Official/src//events/MyEvents.php';

$username = 'YOUR NUMBER'; 
$password = 'YOUR PASSWORD';
$nickname = 'Test';      

$w = new WhatsProt($username, $nickname, true);

$w->connect();

$w->loginWithPassword($password);

while(1)
{
  $w->pollMessage();
}
?>
```

**Comment by matthijsotterloo** [comment]
Finally fixed it!

function onGetMessage($phone, $from, $id, $type, $time, $name, $body)
{
	global $w;
    $w->sendActiveStatus();
    sleep(1);
    sendMessage($from, 'Hoi ' . $name . ', Het is niet mogelijk mij berichten te sturen.');
    $w->sendOfflineStatus();
}
