### ISSUE TITLE
Getgroupv2info error

### ISSUE THREAD

**Issue by shermund** [mgp25/WhatsAPI-Official#537]
Dear sirs,

I seemed to have issues with sendgetgroupv2info

```xml
<iq from="60124460023-1426743408
@g.us" id="get_groupv2_info-1426745442-5" type="error">
error code="500" text="internal-server-error"></error>
```

this is the result.

Please kindly advise

**Comment by mgp25** [comment]
@shermund try again. As you can see in the node, its was an internal server error.

**Comment by shermund** [comment]
noted, i shall try it again.

**Comment by shermund** [comment]
hi sir, its still showing internal server error 500. any idea?

**Comment by 0xTryCatch** [comment]
Show us the debug log please

**Comment by shermund** [comment]
found the problem, i gave the @g.us in the STDIN, hence it doubles up in the query. after i removed that line and its working perfect now.

thank you so much.
