### ISSUE TITLE
ContactSync return not correct answer

### ISSUE THREAD

**Issue by rkazanova** [mgp25/WhatsAPI-Official#538]
Example: i want to check number 529931813442.
Whatsapp Server answer that 5219931813442@s.whatsapp.net exists.
But please look - it is other number (whatsapp added 1 after 52)

**Comment by mgp25** [comment]
Post your code

**Comment by rkazanova** [comment]
i used your example without changes

**Comment by CODeRUS** [comment]
use international number format and add + before your number to sync. use correct mcc and mnc values to let whatsapp servers detect international and local numbers correctly.

**Comment by 0xTryCatch** [comment]
This is why: *From outside Mexico, mobile numbers are reached by +52 1 before the area code and subscriber number, rather than +52 45*

WA is formatting the numbers for you.
