### ISSUE TITLE
sendGetGroupsParticipants is missed

### ISSUE THREAD

**Issue by mouhammad-zd** [mgp25/WhatsAPI-Official#539]
How can i get group particiapnts as old version the function sendGetGroupsParticipants do the trick but now as i can see that their is no longer function to get group participants.

Can i use the same old one or something is changed ! Please help !

**Comment by mgp25** [comment]
sendGetGroupV2Info($groupID)

**Comment by mouhammad-zd** [comment]
Thank you guy for fast reply ! Hope this is more clear in documentation !

**Comment by mgp25** [comment]
@mouhammad-zd you could search in the closed issues, this was answered many times before. There is a search bar in the issue, the more you know.
