### ISSUE TITLE
Uncaught exception 'Exception' with message 'Login Failure'

### ISSUE THREAD

**Issue by renanhenrique** [mgp25/WhatsAPI-Official#541]
Hi, i just registered a number and got the pw.
But when I try to use exampleFunctional.php i got this:

```xml

[] Logging in as 'Inedita Mobile' (***) 
tx  <iq id="getpicture-1426794855-1" type="get" xmlns="w:profile:picture" to="***@s.whatsapp.net">
tx    <picture type="image"></picture>
tx  </iq>

tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="***"></auth>


Fatal error: Uncaught exception 'Exception' with message 'Login Failure' in C:\xampp\htdocs\WPI\src\whatsprot.class.php:2304 Stack trace: #0 C:\xampp\htdocs\WPI\src\whatsprot.class.php(562): WhatsProt->doLogin() #1 C:\xampp\htdocs\WPI\examples\exampleFunctional.php(69): WhatsProt->loginWithPassword('sLAsw+6sBrlL7yj...') #2 {main} thrown in C:\xampp\htdocs\WPI\src\whatsprot.class.php on line 2304
```

Any help?

**Comment by mgp25** [comment]
Wrong password or blocked.

**Comment by renanhenrique** [comment]
Just ran exampleRegister.php again and got:

(
    [status] => ok
    [login] => 556599546918
    [pw] => the passwd
    [type] => existing
    [expiration] => 1458330071
    [kind] => free
    [price] => US$0.99
    [cost] => 0.99
    [currency] => USD
    [price_expiration] => 1429952896
)

So its not blocked, its a fresh number.

**Comment by mgp25** [comment]
@renanhenrique try logging in then, if you receive eventually `not-authorized` means blocked

**Comment by renanhenrique** [comment]
@mgp25 just tryed again and got this:

tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="556599546918"></auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>$‹J õAE‰%‚>8W*³FÑö</challenge>

tx  <response>b3¿Dp:·mDHs0Œƒ€ì.çJUÏy\3þ–ä?¶_</response>


Fatal error: Uncaught exception 'Exception' with message 'Login Failure' in C:\xampp\htdocs\WPI\src\whatsprot.class.php:2304 Stack trace: #0 C:\xampp\htdocs\WPI\src\whatsprot.class.php(562): WhatsProt->doLogin() #1 C:\xampp\htdocs\WPI\examples\teste.php(14): WhatsProt->loginWithPassword('dBXiSSbDGEPHE5C...') #2 {main} thrown in C:\xampp\htdocs\WPI\src\whatsprot.class.php on line 2304

**Comment by mgp25** [comment]
@renanhenrique send me an email if you want, and ill try to help you...

**Comment by renanhenrique** [comment]
Thanks @mgp25, i'll send now

**Comment by 0xTryCatch** [comment]
You are sending nodes before login, don't do that

**Comment by jaidruja** [comment]
I got a password from registertool and i am using whatsapp official api then also Error is like this 
[] Logging in as 'Cloyde' (919900248848)
tx  <iq id="getpicture-1428041514-1" type="get" xmlns="w:profile:picture" to="917353174373@s.whatsapp.net">
tx    <picture type="image"></picture>
tx  </iq>

tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="919900248848"></auth>

PHP Fatal error:  Uncaught exception 'LoginFailureException' in /home/druja-jai/whatsappofficial/src/whatsprot.class.php:2304

can any body help ?

**Comment by 0xTryCatch** [comment]
Post your debug log

**Comment by fa-deve** [comment]
i have same problem please help me ..
i have new number and used  exampleRegister.php
but got this 
Fatal error occurred
Message: Uncaught exception 'LoginFailureException' in \phpTestNumber\src\whatsprot.class.php:2262
Stack trace:
#0 F:\phpTestNumber\src\whatsprot.class.php(552): WhatsProt->doLogin()
#1 F:\phpTestNumber\index.php(25): WhatsProt->loginWithPassword('XC8xZ3NRm8ldZvV...'
#2 {main} thrown

**Comment by 0xTryCatch** [comment]
Did you try ```blockChecker.php```?

**Comment by fa-deve** [comment]
no, but i try with two new numbers and got the same LoginFailureException

**Comment by 0xTryCatch** [comment]
Give some more info. Are you using the latest API? Debug log? ```blockChecker.php``` result?

**Comment by fa-deve** [comment]
using this version https://github.com/WHAnonymous/Chat-API , got 
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>
tx  <auth mechanism="WAUTH-2" user="20xxxxxxx"></auth>
rx  <start from="s.whatsapp.net"></start>
rx  <stream:features></stream:features>
Fatal error: Uncaught exception 'LoginFailureException' in :\phpTestNumber\src\whatsprot.class.php on line 2262

**Comment by 0xTryCatch** [comment]
That debug log seems incomplete and try blockChecker.php

**Comment by fa-deve** [comment]
the output of  blockChecker.php :
  [status] => ok
  [login] => 20xxxxxxx
  [pw] => XC8xZ3NRm8ldZvVUvAxDiPFCQ/A=
  [type] => existing
  [expiration] => 1472666032
  [kind] => free
  [price] => 0.99 دولار امريكى
  [cost] => 0.99
  [currency] => USD
  [price_expiration] => 1444720560

**Comment by WHAnonymous** [comment]
@fa-deve 

- Remove your identity from `wadata` folder. If you don't know what you identity is, simply delete all contents inside `wadata` folder.
- Register your number again with `registerTool.php`. You should get an SMS.

- Use the following example to test your number:

```php
<?php

require_once('src/whatsprot.class.php');

$debug = true;
$nickname = 'Test';
$username = ''; // edit this with your number (country code included)
$password = ''; // Your WhatsApp password

$w      = new WhatsProt($username, $nickname, $debug);
try {
  $w->connect();
} catch (Exception $e) {
  echo 'Connection error: ' . $e->getMessage();
  exit(0);
}

try {
  $w->loginWithPassword($password);
  echo "Successful login";
} catch (Exception $e) {
  echo 'Login error: ' . $e->getMessage();
  exit(0);
}

$w->disconnect();
```

**Note:** Take the data `registerTool.php` outputs to you.

- In case this doesn't work, then your connection is being blocked, try somewhere else with a different IP or so.

Nothing more to add. There are also many answered issues like this one if you want to check them as reference

**Comment by fa-deve** [comment]
@WHAnonymous  Thanks , i followed  your steps and it working fine for sometime 
but .... now it back to the same problem and cannot login 
![untitled](https://cloud.githubusercontent.com/assets/14147885/9766374/d30f2588-5718-11e5-8fdd-3eb442d68a13.png)
 and the output of blockChecker.php :
  [status] => ok
  [login] => 20xxxxxxx
  [pw] => 9IANkfc05pf19ZnZNv+sKJ4SEAA=
  [type] => existing
  [expiration] => 1472666032
  [kind] => free
  [price] => 0.99 دولار امريكى
  [cost] => 0.99
  [currency] => USD
  [price_expiration] => 1444806560

**Comment by 0xTryCatch** [comment]
The debug log looks incomplete. Can you paste the full log?

**Comment by fa-deve** [comment]
this is full debug log of login code

**Comment by 0xTryCatch** [comment]
Your log is not complete so it may also be your connection is dropped

**Comment by fa-deve** [comment]
@0xTryCatch  what can i do ?? can you explain more

**Comment by fa-deve** [comment]
when i tracing the code of function loginWithPassword() i found that it check nextChallenge.xxx.dat file
but i don't have this file only have id.***.dat file in wadata folder .
why this file didn't generate by default from script ??

**Comment by Franpastoragusti** [comment]
I think i´m blocked, but i´m not sure. 
tx  <stream:features></stream:features>

tx  <auth user="34626919200" mechanism="WAUTH-2"></auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>193ea2a6ef81ae85ea528518a4f673800acc192f</challenge>

tx  <response>f99fa8d3496fae9fe4f36126244109905271ff06bd4d585e68fd4e8920a197c153
ff5a4e214f19fd15912c142b5c02ee8553c350be60143cf79e074ec9929f992d1ea8729a7cc2e498
419642c0</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>


Fatal error: Uncaught exception 'LoginFailureException' in C:\Source\tests-night
watch\Chat-API\src\Login.php on line 54

LoginFailureException:  in C:\Source\tests-nightwatch\Chat-API\src\Login.php on
line 54

Call Stack:
    0.0003     123944   1. {main}() C:\Source\tests-nightwatch\Chat-API\whatsapp
_whatsapi_send.php:0
    0.1508    1559432   2. WhatsProt->loginWithPassword() C:\Source\tests-nightw
atch\Chat-API\whatsapp_whatsapi_send.php:13
    0.1511    1560224   3. Login->doLogin() C:\Source\tests-nightwatch\Chat-API\
src\whatsprot.class.php:287


I´m 2 hour with this problem, if i´m blocked how can i unblock me?

**Comment by Franpastoragusti** [comment]
HERE IS THE FULL LOG
$ php ./whatsapp_whatsapi_send.php
tx  <stream:features></stream:features>

tx  <auth user="34626919200" mechanism="WAUTH-2"></auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>892f716e724257525478fbabf9122ab9df926be9</challenge>

tx  <response>96a634da42151703c18032fd81b27e8bd8e9b1d3a8d9e833fd828e42b1cca5433b
56caf7b00b3a62ab0a6d8301837683bd33191551eeda2451ebf984d456a3bf80d692edb045d802d6
be2d574e</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>


Fatal error: Uncaught exception 'LoginFailureException' in C:\Source\tests-night
watch\Chat-API\src\Login.php on line 54

LoginFailureException:  in C:\Source\tests-nightwatch\Chat-API\src\Login.php on
line 54

Call Stack:
    0.0002     123928   1. {main}() C:\Source\tests-nightwatch\Chat-API\whatsapp
_whatsapi_send.php:0
    0.1412    1559376   2. WhatsProt->loginWithPassword() C:\Source\tests-nightw
atch\Chat-API\whatsapp_whatsapi_send.php:13
    0.1415    1560168   3. Login->doLogin() C:\Source\tests-nightwatch\Chat-API\
src\whatsprot.class.php:287

Thanks for your quickly answers :)

**Comment by Franpastoragusti** [comment]
I have the same problem, here is the log

$ php ./whatsapp_whatsapi_send.php
tx  <stream:features></stream:features>

tx  <auth user="34626919200" mechanism="WAUTH-2"></auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>268ea24f3f9a01bd9d46d803ac7df976cc070650</challenge>

tx  <response>fbb2879010ee177c38c63fc6b188c18f6dcf051c6f9690c8179e003d2cff90834c
863daf15b5390eac3fcf13ac462215133a96b01f4354e7d8cff907eb43be189b817baf829930b92a
23b9d726</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>


Fatal error: Uncaught exception 'LoginFailureException' in C:\Source\tests-night
watch\Chat-API\src\Login.php on line 54

LoginFailureException:  in C:\Source\tests-nightwatch\Chat-API\src\Login.php on
line 54

Call Stack:
    0.0002     123928   1. {main}() C:\Source\tests-nightwatch\Chat-API\whatsapp
_whatsapi_send.php:0
    0.1262    1559376   2. WhatsProt->loginWithPassword() C:\Source\tests-nightw
atch\Chat-API\whatsapp_whatsapi_send.php:13
    0.1265    1560168   3. Login->doLogin() C:\Source\tests-nightwatch\Chat-API\
src\whatsprot.class.php:287
