### ISSUE TITLE
Using non existing "param" from WhatsApp server response

### ISSUE THREAD

**Issue by eliasjnior** [mgp25/WhatsAPI-Official#543]
Well, I tried to commit, but, I'm not good with Github, so, here is the problem.

Depeding of the server response, like blocked, or other things (discovered that because I was testing my friend number), in the line 397 of whatsprot.class.php, it set the $response->param, but, this param don't exists in JSON response. Thats cause a PHP notice.

So, I just changed that:

```php
$response->param
```

to:
```php
isset($response->param) ? $response->param : NULL
```

As I couldn't commit this change, I'm publishing here to @mgp25 change it :P

**Comment by viniciusjarina** [comment]
You need to create a Pull Request (PR) https://help.github.com/articles/creating-a-pull-request/
