### ISSUE TITLE
Some time block contacts some time not

### ISSUE THREAD

**Issue by Abtab** [mgp25/WhatsAPI-Official#544]
Hi @mgp25 

When using the function `sendSetPrivacyBlockedList` to block contacts. Sometime it blocks contacts and sometime not. when i send new list to block and after that when i check sync Result. It gives me previously blocked list
Thanks in advance

**Comment by CODeRUS** [comment]
as usual no debug log is posted, do we need to ask every time for debug log?

**Comment by Abtab** [comment]
@CODeRUS Sorry for not posting log and thanks for reply

But sometime it gives this behaviour.. Now i am Using iys giving righr result. Please dont close this issue.. i will post here log as problem will persist. Thanks
