### ISSUE TITLE
Necessity of onGroupParticipantsExit()

### ISSUE THREAD

**Issue by rayidi** [mgp25/WhatsAPI-Official#545]
Hi,

I'm working on a Groups App which able to create group with 2 participants.
Since there is a limitation for groups, I need to remove the group when the 2 participants left the group.

Hope this can be doable & better if we trigger an event if the event occurs.

Thanks in advance :-)

**Comment by mgp25** [comment]
Please, read code and wiki before opening an issue:

https://github.com/mgp25/WhatsAPI-Official/blob/master/src/whatsprot.class.php#L1369

Regards
