### ISSUE TITLE
Whatsapp is blocking when we send message

### ISSUE THREAD

**Issue by rohit49khatri** [mgp25/WhatsAPI-Official#546]
I tried 4 registered accounts when i sent first message it did not give Login failure but after that the number was blocked, then i tried to login with another number and it happened again so on.

**Comment by mgp25** [comment]
@rohit49khatri If you are trying to massive sending you will be blocked at the moment, if they have detected that, they could block your IP so all numbers you are running under the same IP are blocked.

Make sure your script does a good behaviour and the message you sent to, must have your number in the contact list, you also must have the number synced.

If you want more help, post your code and debug log.

Regards
