### ISSUE TITLE
how can i retrieve my phone user agent and token

### ISSUE THREAD

**Issue by abd65000** [mgp25/WhatsAPI-Official#548]
how can i get my phone user agent and token, and not to use your token...

thank you for your interesting project.

best regards

**Comment by CODeRUS** [comment]
useragent is easy part, isn't it? token is fixed for each version number, you can't use "your own" :D

**Comment by abd65000** [comment]
thank you for your quickly reply.

i mean how can i take it for the new version

**Comment by CODeRUS** [comment]
this one: https://github.com/mgp25/classesMD5-64

**Comment by abd65000** [comment]
thank you again,

i use the above, its great tool, i check the MD5 from there.

i want it for android, but when a new version appears, we change three strings as following:

user agent: "WhatsApp/2.12.68 S40Version/14.26 Device/Nokia302"
token:         "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1425519315543"
and MD5,

in your code you already update it each time with new data, last time you update it to Nokia302, i need the way to update it my self to my android data.

thank you for helping

**Comment by CODeRUS** [comment]
check git history when andriod is being used and learn  how to use android data. but android client is using text encryption which is not implemented in this api yet, you've been warned.

**Comment by mgp25** [comment]
Please, the wiki exists for something!! https://github.com/mgp25/WhatsAPI-Official/wiki/Token-Generation
