### ISSUE TITLE
Banned and Not Allowed

### ISSUE THREAD

**Issue by filipewan** [mgp25/WhatsAPI-Official#549]
Tks for de Whatsapp API. Is a very good API and has helped me a lot.

But recently my number was not authorized send message.

When I tried use the number on my cell, my suprise: my number was banned for 24 hours! Another number was not allowed to use whatsapp services.

I found this reasons:
https://www.whatsapp.com/faq/en/general/23154266
https://www.whatsapp.com/faq/en/general/28030003

There are any way to prevent this?

Tks a lot

**Comment by CODeRUS** [comment]
https://github.com/mgp25/WhatsAPI-Official/issues/546
https://github.com/mgp25/WhatsAPI-Official/issues/508
https://github.com/mgp25/WhatsAPI-Official/issues/492
https://github.com/mgp25/WhatsAPI-Official/issues/479
https://github.com/mgp25/WhatsAPI-Official/issues/473
https://github.com/mgp25/WhatsAPI-Official/issues/456
https://github.com/mgp25/WhatsAPI-Official/issues/445
https://github.com/mgp25/WhatsAPI-Official/issues/441
and so on
