### ISSUE TITLE
How to get the whatsapp password using the old whatsapp number? 

### ISSUE THREAD

**Issue by mrssam** [mgp25/WhatsAPI-Official#552]
How to get the whatsapp password using the old whatsapp number i have two mobile number and they are not blocked but i need to use on in my whatsapp api how i can get it Password ?

**Comment by mgp25** [comment]
@mrssam register the number to get the password, explained in there wiki

**Comment by mrssam** [comment]
but i register this mobile Number and i cant extract the password form mobile my mobile not rooted ? is any way

**Comment by mgp25** [comment]
@mrssam Read the wiki, eveything its explained there

**Comment by mrssam** [comment]
i read it i find only Number registration and other things is you mean by Number registration i can re register My old Mobile Number i try to do that and i find this  
Array ( [in] => 773377657 [cc] => 967 [id] => °Ï—>yirõ’äjªr+çç” [lg] => ar [lc] => YE [sim_mcc] => 421 [sim_mnc] => 000 [method] => sms [token] => afc2dabc103f77329ec69c9bbe7b2f63 ) stdClass Object ( [status] => fail [reason] => missing_param [param] => token )

**Comment by mrssam** [comment]
can you tell me please

**Comment by thetitoo** [comment]
You will receive the token, then you submit again.
Use
https://github.com/mgp25/WhatsAPI-Official/blob/master/examples/registerTool.php
as CLI

Read the wiki as well.

Christophe Hubert.
