### ISSUE TITLE
Profile photo refresh in phone when i click on it.

### ISSUE THREAD

**Issue by knk106** [mgp25/WhatsAPI-Official#553]
change Profile photo working fine but it doesn't refresh automatically. i have to tap on photo then i can see updated photo.

but when we change profile photo from official app it refresh automatically. 

why is it happening?

**Comment by mgp25** [comment]
@knk106 send debug log when setting profile picture.

Regards

**Comment by mgp25** [comment]
@knk106 Make sure you have GD ext installed.

https://github.com/mgp25/WhatsAPI-Official/wiki/WhatsAPI-Documentation#dependencies

Regards

**Comment by nephilim1973** [comment]
@knk106: on which device you can run the program ? Which script do you use and which GUI ?
