### ISSUE TITLE
password changes everytime

### ISSUE THREAD

**Issue by docsuleman** [mgp25/WhatsAPI-Official#554]
im using examples from code.. i made a new account using registertool.php. i received code and i got registered. but that password was incorrect according to whatsapp.php. now running blockchecker.php give me new password every time i run it. and every pass is incorrect if i use it in whatsapp.php. any one can help me?

**Comment by mgp25** [comment]
@docsuleman `blockChecker.php` reset your password and gives you a new one, try with an easier script like the ones you can find in `/examples` folder.

Regards

**Comment by docsuleman** [comment]
ohh thankss dear :) now its working..
