### ISSUE TITLE
Number lock to interact with contact!

### ISSUE THREAD

**Issue by Pudins** [mgp25/WhatsAPI-Official#562]
Good afternoon guys!
Had my number blocked today to receive a message!
The fact receive messages and respond also blockers?

**Comment by mgp25** [comment]
@Pudins No, if you receive a message and answer it, there shouldnt be any problem, maybe your script behaviour. There is information about that in the wiki

Regards

**Comment by Pudins** [comment]
It really can be something related to image send script or video, only informing url? What is the best way to send these medias? Remembering that I am using the command contained in the wiki just changing the url!
