### ISSUE TITLE
fixing the problem with sendSetProfilePicture($path)  function 

### ISSUE THREAD

**Issue by sohaibsleem** [mgp25/WhatsAPI-Official#565]
i faced a problem when i use `sendSetProfilePicture($path)` function to send my profile picture to the receiver,
the problem is: the function use the protected function sendSetPicture`( $this->phoneNumber,$path)` that take 2 parameters ,the first parameter `$to` must be the number of the receiver ,but  the API class use  `$this->phoneNumber` ,which is the number of the sender, so i fixed it in the API class by add an extra parameter to the function `sendSetProfilePicture($to,$path)` , and use $to in the function `sendSetPicture($to,$path)` instead of `sendSetPicture( $this->phoneNumber , $path)` ,
here is the code :

```php
  public function sendSetProfilePicture($to,$path)
    {
      //$this->sendSetPicture($this->phoneNumber, $path);
        $this->sendSetPicture($to, $path);
    }
```

**Comment by mgp25** [comment]
@sohaibsleem `sendSetProfilePicture` its to set your own profile picture, not for sending a picture.

Regards

**Comment by sohaibsleem** [comment]
@mgp25   i know  that ,it is clear from function's name that it set my profile picture not to send the pic to receiver, but my profile pic didn't appear to the user until i made these changes ,i tried it many time finally it works after my changes,thanks for reply

**Comment by mgp25** [comment]
@sohaibsleem you need to add `$w->pollMessage();`right after, try it

**Comment by sohaibsleem** [comment]
@mgp25 yes it works ,thanks alot
