### ISSUE TITLE
Send Image with caption

### ISSUE THREAD

**Issue by Abtab** [mgp25/WhatsAPI-Official#570]
Hi @mgp25 

I am facing a problem. I tried by myself but not got any success. Please see the issue below. 
https://github.com/mgp25/WhatsAPINet/issues/13
Thanks in advance

Regards

**Comment by mgp25** [comment]
@Abtab will look at it.

You can find the code here https://github.com/mgp25/WhatsAPI-Official/blob/master/src/whatsprot.class.php btw

**Comment by Abtab** [comment]
thanks for reply. Yes i can use this.. But I have done some work in c# and i want to proceed with that. 

Regards
