### ISSUE TITLE
How to correctly sync contactlist after adding one new contact

### ISSUE THREAD

**Issue by hansrouge** [mgp25/WhatsAPI-Official#571]
Hi there,

i know how i have to sync my contacts after my login.
But how do I sync my contactlist after adding one or two new contactc?

Do I have to sync all the contacts again or is it ok to just sync the new contacts?

For example:
```php
$w->login...
....
//First Sync:
$nrs = array(1,2,3,4,5,6);
$w->sendSync($nrs);
...
...
// I want to add a new one:
$new_number = array(7,8);
$w->sendSync($new_numbers,0,4);  

//or do I have to:
$allNumbes = array_merge($nrs,$new_numbers);
$w->sendSync($allNumbers,0,4);
```

Can you explain more detailed the difference between Delta Interactive (3) and Delta Background (4). Should I use Background or Interactive to sync only my new contacts?

The wiki does not explain it  enough.

Thanks very much!

**Comment by CODeRUS** [comment]
afaik interactive is you adding contact manually from your addressbook, background is automatically syncing new contact from your addressbook

**Comment by hansrouge** [comment]
Thank you! That sounds logic :)

So, can I just sync the new numbers with interactive?

Like this:
```php
$w->login...
....
//First Sync:
$nrs = array(1,2,3,4,5,6);
$w->sendSync($nrs);
...
...
// Adding two new numbers:
$new_number = array(7,8);
$w->sendSync($new_numbers,0,3); 
```

**Comment by CODeRUS** [comment]
yes you only delta sync new number

**Comment by nxccontrols** [comment]
i cant sync my google contact ..... showing authentication error

**Comment by yniv** [comment]
@CODeRUS is there a limit on how many interactive syncs i can send in a given time?

**Comment by CODeRUS** [comment]
if yes, then nobody know the actual numbers

**Comment by yniv** [comment]
Ok, I'll try and report here :)

**Comment by yniv** [comment]
Also, Is it required that every log-in i'll send all the passed synced contacts in my contact list?
or i can send only delta's for new ones?

**Comment by CODeRUS** [comment]
You send contacts only once, but i don;t know how official client works.

**Comment by hansrouge** [comment]
@yniv Maybe this helps you:

https://github.com/venomous0x/WhatsAPI/issues/821
https://github.com/venomous0x/WhatsAPI/issues/767

**Comment by momovil** [comment]
Hello, I have read that the android contact limit is 2000 contacts. I have made a 1500 contact sync with 700 existing numbers and it works fine.
