### ISSUE TITLE
Difference between (pollmessage , getmessage) and (onGetMessage) Event

### ISSUE THREAD

**Issue by moosavialeki** [mgp25/WhatsAPI-Official#572]
what is Difference between (`pollmessage` , `getmessage`) and (`onGetMessage`) Event?

It is necessary to build an online chat use `pollMessage` function?
Why not be use `pollmessage` function in the api example ?
https://github.com/mgp25/WhatsAPI-Official/blob/master/examples/whatsapp.php 
Can we polling in message Araay (`$messages` in above example) instead of calling continuing pollmessage function?

browser side:
```
jQuery=>send post request to php page=>action='poll'
```

in server side : 
method1: 
```php
if(inpute['action']=='poll'){
$w->pollMessage();
exit($message);
}
```
OR OR OR OR

method 2:
```php
if(inpute['action']=='poll'){
exit($message);
}
```

**Comment by mgp25** [comment]
```
    /**
     * Drain the message queue for application processing.
     *
     * @return ProtocolNode[]
     *   Return the message queue list.
     */
```
`getMessages()`

```
    /**
     * Fetch a single message node
```
`pollMessage`

`onGetMessage` and event that its launch when you receive a message.

You need to call `pollMessage` in order to receive nodes.

Regards

**Comment by moosavialeki** [comment]
Do not understand :(
What happens if we do not use ```pollMessage ```?
What is the difference between protocol Node and message Node?

How recive all message (without missing)(all message in when i offline and now)?
I want via AJAX to call a php code and receive new message to display every 2sec

**Comment by moosavialeki** [comment]
```getMessage``` return ```messageQueue```
and ```messageQueue``` fill in two line in code
1-in ```processInboundDataNode``` function when ```php if ($node->getTag() == "message") ```
2-in ```processInboundDataNode``` function when:
```php
if ($node->getTag() == "iq"
            && $node->getAttribute('type') == "result") 

if ($node->getChild("query") != null){... here ...}

```


onGetMessage fired in processInboundDataNode function and for receive message getmessage function not useful ! (when use getMessage() ?)

in below code messageQueue fill if tag is 'message'
but when fire 'onGetMessage' the messageQueue is not empty ! why ?!
after receive message with event messageQueue should be empty!
```php
if ($node->getTag() == "message") {
array_push($this->messageQueue, $node);
if ($node->hasChild('x') && $this->lastId == $node->getAttribute('id')) {
$this->sendNextMessage();
}
if ($this->newMsgBind && ($node->getChild('body') || $node->getChild('media'))) {
$this->newMsgBind->process($node);
}
if ($node->getAttribute("type") == "text" && $node->getChild('body') != null) {
$author = $node->getAttribute("participant");
if ($author == "") {
//private chat message
$this->eventManager()->fire("onGetMessage",
array(
$this->phoneNumber,
$node->getAttribute('from'),
$node->getAttribute('id'),
$node->getAttribute('type'),
$node->getAttribute('t'),
$node->getAttribute("notify"),
$node->getChild("body")->getData()
));
if ($this->messageStore !== null) {
$this->messageStore->saveMessage($node->getAttribute('from'), $this->phoneNumber, $node->getChild("body")->getData(), $node->getAttribute('id'), $node->getAttribute('t'));
}
} else {...}
```
and for pollMessage():
pollMessage call processInboundData and processInboundData call processInboundDataNode
and processInboundDataNode (fill queue) or (fire onGetMessage)

in doLogin function api called pollMessage function
 I want via AJAX to call a php code (example poll.php) and receive new message to display every 2sec

in poll.php i create a new whatsPort obj and call connect and login method
therefore pollMessage Called
Do I need to call?
