### ISSUE TITLE
Getting incoming msg mobile number and replying them individually

### ISSUE THREAD

**Issue by sphirelabs** [mgp25/WhatsAPI-Official#581]
Hi,

The script works great!! I am looking for an option to get incoming message numbers and reply to those numbers individually. Say, I am getting some msg from 34123456789 as "how are you" and from 34123456799 as "what is your name" and I want to reply to 34123456789 as"am fine" and to 34123456799 as "official api".

Any help is appriciated:)

**Comment by 0xTryCatch** [comment]
Use the events described in the Wiki.
