### ISSUE TITLE
Not Authorised Error while moving to server.

### ISSUE THREAD

**Issue by sphirelabs** [mgp25/WhatsAPI-Official#582]
Hi,

I made the required modifications, tested everything on my local machine and tried to move to server. But the issue starts, the debug result showed <not authorised>. Registered on server -> Got banned. Tried a new number register on openshift cloud, got blocked :(. Then I tired on azure Virtual machine with a dedicated IP, registered, but getting not authorised error.

Can someone what's wrong is going when am moving to server and suggest me some places where we can actually host it without banning:(

**Comment by mgp25** [comment]
WhatsApp can block IP, and your server seems to be block, there is no special place we can suggest you, WhatsApp knows if the server is doing massive request or bulk messaging and blocking everything directly.

Regards
