### ISSUE TITLE
Groups admin just one when their are multi

### ISSUE THREAD

**Issue by MoudiZd** [mgp25/WhatsAPI-Official#583]
Hello ! Before anything i have searched for the word "admins" in issues and cannot find what i search about , i decided to search documentation and also without any luck . so i decided to open it in a new issue .

I want to get all group admins as array if their are multiple admins or as string if their were just single admin .
I know that in the documentation their is instructions to get group admin (single admin)
But my real question is i want to get all admins of group
Can this be done like the client whatsapp application or this cannot be done via api ?

Best Regards !

**Comment by mgp25** [comment]
`sendGetGroups()` and `sendGetGroupV2Info($groupID)`

then you have to code your own function.

Regards
