### ISSUE TITLE
Number being blocked

### ISSUE THREAD

**Issue by kwiiby** [mgp25/WhatsAPI-Official#584]
Hey guys!

I have a problem, my numbers are being blocked (forever) after a few days. (I do not spam, just answer people).

I'm doing all right, synchronizing contacts, waiting time while the bot is typing, etc..

I do not know what to do, here is my code, please review and tell me if there is something wrong.

```php
<?php
require_once 'src/whatsprot.class.php';

$username = 'MY WHATSAPP NUMBER';
$password = 'MY WHATSAPP PASSWORD';
$nickname = "";
$target = $username;

echo "[] logging in as '$nickname' ($username)\n";
$w = new WhatsProt($username, $nickname, true);
$w->eventManager()->bind("onPresence", "onPresenceReceived");
$w->connect();
$w->loginWithPassword($password);
$w->sendGetServerProperties();
$w->sendClientConfig();
$w->pollMessage();
$w->sendPresenceSubscription($target);
$pn = new ProcessNode($w, $target);
$w->setNewMessageBind($pn);
while (1) {
	$w->pollMessage();
	$messages = $w->getMessages();
	foreach ($messages as $m) {
		sleep(rand(2, 6));
		$contactNumber = explode('@', $m->getAttribute("from"));
		if (!contactExistsInMyDatabase()) { // Abstract function
			echo "Syncing new contact (Name: ".$m->getAttribute('notify').", Number:".$contactNumber.")\n";
			$w->sendSync(array($contactNumber));
			$w->pollMessage();
			appendContactToMyDatabase(); // Abstract function
		}
		$w->sendMessageComposing($m->getAttribute('from'));
		sleep(rand(2, 6));
		$w->sendMessagePaused($m->getAttribute('from'));
		$answer = "Welcome to my bot! \n Message ID: ".generateRandomCode();
		$w->sendMessage($m->getAttribute('from'), $answer);
	}
}

class ProcessNode
{
	protected $wp = false;
	protected $target = false;

	public function __construct($wp, $target)
	{
		$this->wp = $wp;
		$this->target = $target;
	}

	public function process($node) {
		$notify = $node->getAttribute("notify");
		if ($node->getAttribute('type') == 'text') {
			$text = $node->getChild('body');
			$text = $text->getData();

			echo "\n- ".$notify.": ".$text."    ".date('H:i')."\n";
		} else {
			echo "\n- ".$notify." sent a message type ".$node->getChild("media")->getAttribute('type')."    ".date("H:i")."\n";
		}

	}
}

function onPresenceReceived($username, $from, $type) {
	$dFrom = str_replace(array("@s.whatsapp.net","@g.us"), "", $from);
	if ($type == "available")
		echo "<$dFrom is online>\n\n";
	else
		echo "<$dFrom is offline>\n\n";
}

// Generate a random code (to avoid sending same message hash)
function generateRandomCode() {
	return strtoupper(substr(md5(uniqid(mt_rand(), true)), 0, 10));
}
```

**Comment by mgp25** [comment]
If you are managing many requests, lets talk about 1k users or more, WhatsApp can detect if you are using the API and they can block you.

Regards

**Comment by kwiiby** [comment]
Ok, but it is like 30 users.. I don't understand, my code is ok? anything else that could be?

**Comment by mgp25** [comment]
@kwiiby the code seems fine to me

**Comment by kwiiby** [comment]
So, how could whatsapp detect and block? do I can sync without @s.whatsapp.net (look at the explode), could my IP be in blacklist? because it is not the first number that gets blocked. The number is Brazilian (+55) but the code is hosted in a USA VPS, could that be a problem?

**Comment by jesperveldhuizen** [comment]
Might be a little error in your code. Explode returns an array, and you are using it as a single string.

**Comment by kwiiby** [comment]
In my original code I'm using the index zero. Actually I removed some parts of the original code (and unintentionally took this line) to post here, you know, make it easier to understand.

**Comment by Edumatsu** [comment]
@kwiiby entra em contato comigo pelo meu e-mail de contato do github.

**Comment by jodinathan** [comment]
@Edumatsu, posta a resposta aqui por favor.

Please, post your answers here to help others.
Thanks

**Comment by jodinathan** [comment]
@kwiiby, I don't know if it is relevant, but one thing that helped me was to always end the script with a $w->pollMessages.

looking at your code, you can send a message to someone without calling the pollMessage().

**Comment by Edumatsu** [comment]
@jodinathan i don't have the answer, i only need talk with he.

**Comment by adelsjunior** [comment]
Good Night Guys, I can send image , video and text, but can only receive the encrypted message, someone help me ?
