### ISSUE TITLE
What value is price_expiration?

### ISSUE THREAD

**Issue by domingopa** [mgp25/WhatsAPI-Official#585]
The object that returns record

``  [status] => ok
    [login] => xxxxxxxx
    [pw] => RpSHxxxxxxxxxp6Sc2cje6n4=
    [type] => existing
    [expiration] => 1459957795
    [kind] => free
    [price] => 0,89 €
    [cost] => 0.89
    [currency] => EUR
    [price_expiration] => 1431226145
``

What value is price_expiration?

thanks for your support

**Comment by mgp25** [comment]
The date you have to pay agaiin subscription to WhatsApp `"Price_expiration"`

**Comment by domingopa** [comment]
And then expiration containing?

**Comment by CODeRUS** [comment]
expiration is available period, price_expiration is period when you can extend subscription with special price

**Comment by mgp25** [comment]
^

**Comment by domingopa** [comment]
Ok ;)
