### ISSUE TITLE
how to not print the log in the page?

### ISSUE THREAD

**Issue by foxpcteam** [mgp25/WhatsAPI-Official#587]
Hello,
how to not output this code when i include `whatsprot.class.php`

i create small plugin in wordpress to send text message true WhatsAPI

when i active the plugin i get this code that mess all the page.

how to prevent this code from be printed?

my code is simaple:
```php
require_once '/src/whatsprot.class.php';
$username = ""; //Mobile Phone prefixed with country code
$password = "";
$w = new WhatsProt($username, 0, "", true); //Application Name
$w->connect();
$w->loginWithPassword($password);
```

**Comment by mgp25** [comment]
@foxpcteam read the wiki please: https://github.com/mgp25/WhatsAPI-Official/wiki/WhatsAPI-Documentation#getting-started

Look how the whatsprot its initialized, everything its explained there

Regards
