### ISSUE TITLE
Get Hash code of Image and Video you just uploaded to whatsapp

### ISSUE THREAD

**Issue by davidgff** [mgp25/WhatsAPI-Official#588]
Hi, i just sent an image, and i know i'm going to send it again.

I know i can get the hash and filesize when i get an image, but this time, i want to know the hash of the image so i don't have to upload it again.

Is there a way?

Thanks

**Comment by mgp25** [comment]
You can use this event `onMediaMessageSent( $mynumber, $to, $id, $filetype, $url, $filename, $filesize, $filehash, $caption, $icon )`

Regards
