### ISSUE TITLE
Sync error

### ISSUE THREAD

**Issue by msrahmanian** [mgp25/WhatsAPI-Official#589]
Hi
Firstly I would like to thank you for developing WhatsApp API,
I have a problem with syncing contacts with WhatsApp, It can not sync and subscribe all of my contacts
I have a log file for that but whatsapp does not send any error for syncing result

**Comment by mgp25** [comment]
If you dont post debug log, we cant help

**Comment by mgp25** [comment]
https://github.com/mgp25/WhatsAPI-Official/blob/master/examples/contactsync.php

**Comment by msrahmanian** [comment]
Hi, This is the log for syncing error

tx  <iq id="sendsync_-1428901486-2" xmlns="urn:xmpp:whatsapp:sync" type="get">
tx    <sync mode="delta" context="background" sid="130733786860000000" index="0" last="true">
tx      <user>+CONTACT-NUM</user>
tx    </sync>
tx  </iq>

rx  <iq from="MY_ACCOUNT_NUM@s.whatsapp.net" id="sendsync_-1428901486-2" type="error">
rx    <error code="501" text="feature-not-implemented" backoff="3600"></error>
rx  </iq>

**Comment by mgp25** [comment]
@msrahmanian you are using way too much sync, you are getting a `backoff` you need to wait 3600 seconds = 1 hour

**Comment by belazaras** [comment]
A question here, if I keep trying to get contacts with this backoff, does my query reset it back to 3600 or does it keep going down until my query finally gives the correct result? Thanks.

**Comment by mgp25** [comment]
@belazaras resets back to 3600
