### ISSUE TITLE
Password changed

### ISSUE THREAD

**Issue by Quera** [mgp25/WhatsAPI-Official#592]
Hi,
every morning I have the same problem: I must use Wart to have new password to connect by WhatsAPI because login with old one fails.

Why does it happend?
What can I do?

**Comment by CODeRUS** [comment]
register with custom identity. someone is stealing your account :D

**Comment by mgp25** [comment]
@Quera or you are also logging with that number in your device, that also changed the password.

**Comment by Quera** [comment]
I use no device.... but what about register with custom identity?

**Comment by Quera** [comment]
I'm using a new SIM card

**Comment by mgp25** [comment]
If you register with WhatsAPI Official, the identity its automatically generated, if you use WART, you can use an optional word to generate the identity.

**Comment by Quera** [comment]
so you suggest me to register by WhatsAPI Official?
