### ISSUE TITLE
How to get info about message delivery

### ISSUE THREAD

**Issue by jumpdfu** [mgp25/WhatsAPI-Official#594]
Hello, can u please explain how does this events work? -
onMessageReceivedClient( $mynumber, $from, $id, $type, $time )
onMessageReceivedServer( $mynumber, $from, $id, $type, $time )

I whant to know, if friends reacived my message or no. Thx in advance;

**Comment by mgp25** [comment]
Its explained in the wiki

Regards

**Comment by jumpdfu** [comment]
Sorry for reopening this issue, but I haven't found any information about this functions. Can you please give a link to it?  And one more question, I can't get my id code, I reacived it but it doesn't looks normal. Here is exactly what I get - [id] => �m�<�6u��l@qt���zq�  I tried to change defferent charsets, I even downloaded autocharset detection tool. But no result. Hope for your help (((

**Comment by CODeRUS** [comment]
id is pseudo random bytes array. You not supposed to "read" it

**Comment by mgp25** [comment]
Read wiki, how to use events

Regards
