### ISSUE TITLE
Messages are not sent

### ISSUE THREAD

**Issue by peteralexandercb** [mgp25/WhatsAPI-Official#596]
Hi I downloaded the latest version of the sdk whatsapp for php.
but unfortunately the messages are not sent, do not understand the reason.

the server shows the following:

```xml
tx <stream: features>
tx <readreceipts> </ readreceipts>
tx <groups_v2> </ groups_v2>
tx <privacy> </ privacy>
tx <presence> </ Presence>
tx </ stream: features>

tx <auth mechanism = "WAUTH-2" user = "18099802999"> </ auth>

rx <start from = "s.whatsapp.net"> </ start>

rx <stream: features> </ stream: features>

rx <challenge> Ã ^ ÑXÖœÝ! "U $ Ò-D, 5 ÷÷ </ challenge>

tx <response> AECO @ ³ ¥ ª "å &: ÛÍDÀ¬Iì-Àê½? ¿? Or? Ã ??? Ã </ response>
```

only shows that.
the code is as follows:
```php
<? php
require_once '../src/whatsprot.class.php';
$ username = "18099802999"; // Mobile Phone prefixed with country code
$ password = "mypassword";
$ w = new WhatsProt ($ username, 0, "WhatsApp Messaging", true); // Name your application by Replacing "WhatsApp Messaging"
$ w-> connect ();
$ w-> loginWithPassword ($ password);
$ target = '18293473087'; // Target Phone, phone reciever
$ message = 'Your message comes here';
$ we-> Send Presence Subscription ($ target); // Let us first user to send Presence
$ w-> sendMessage ($ target, $ message); // Send Message
?>
```

**Comment by CODeRUS** [comment]
use code markdown please instead of your crappy "fixed" code
and your debug log is not full

**Comment by peteralexandercb** [comment]
better explicate, am new to github.
have some idea of the problem.
as to debug that's the only thing showing.

**Comment by CODeRUS** [comment]
https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks

**Comment by peteralexandercb** [comment]
I wonder if anyone has an idea of the problem.

I thought maybe whatsapp change its internal function.
because before everything worked well for me.

**Comment by CODeRUS** [comment]
as i said your debud log is not full, it does not contain server reply.

**Comment by peteralexandercb** [comment]
but if that's the answer that shows me the script and debug option is set to true.

**Comment by peteralexandercb** [comment]
only show this:

tx 
tx </ readreceipts>
tx </ groups_v2>
tx </ privacy>
tx </ Presence>
tx </ stream: features>

tx </ auth>

rx </ start>

rx </ stream: features>

rx Ã ^ ÑXÖœÝ! "U $ Ò-D, 5 ÷÷ </ challenge>

tx AECO @ ³ ¥ ª "å &: ÛÍDÀ¬Iì-Àê½? ¿? Or? Ã ??? Ã </ response>

**Comment by mgp25** [comment]
@peteralexandercb if thats the only debug you always get, seems there is a problem when your account, check with `blockChecker.php` the status of your number.

I also recommend you to add `$w->pollMessage();` right after `sendMessage`

Regards
