### ISSUE TITLE
LoginFailureException

### ISSUE THREAD

**Issue by bigjoevtrj** [mgp25/WhatsAPI-Official#599]
Whats is this Throw that not exists?
```xml
tx  <auth mechanism="WAUTH-2" user="5521XXXXXXXXX"></auth>
```
```
PHP Fatal error:  Uncaught exception 'LoginFailureException' in /Users/diogonunes/Google Drive/projetos/WhatsAPI-Official/src/whatsprot.class.php:2304
Stack trace:
#0 /Users/diogonunes/Google Drive/projetos/WhatsAPI-Official/src/whatsprot.class.php(562): WhatsProt->doLogin()
#1 /Users/diogonunes/Google Drive/projetos/WhatsAPI-Official/examples/sendMessage.php(69): WhatsProt->loginWithPassword('TtGZ7sQr6SQM/2G...')
#2 {main}

  thrown in /Users/diogonunes/Google Drive/projetos/WhatsAPI-Official/src/whatsprot.class.php on line 2304

Fatal error: Uncaught exception 'LoginFailureException' in /Users/diogonunes/Google Drive/projetos/WhatsAPI-Official/src/whatsprot.class.php:2304
Stack trace:
#0 /Users/diogonunes/Google Drive/projetos/WhatsAPI-Official/src/whatsprot.class.php(562): WhatsProt->doLogin()
#1 /Users/diogonunes/Google Drive/projetos/WhatsAPI-Official/examples/sendMessage.php(69): WhatsProt->loginWithPassword('TtGZ7sQr6SQM/2G...')
#2 {main}
  thrown in /Users/diogonunes/Google Drive/projetos/WhatsAPI-Official/src/whatsprot.class.php on line 2304
```

**Comment by mgp25** [comment]
@bigjoevtrj 

Use markdown and quote the debug and stack trace so we can check it easily.

It seems your account have some kind of problem, try using `blockChecker.php` to see if your number its blocked or its just a connection issue.

By the way, you can add `try` and `catch` statements:

```php
try{
    $w->loginWithPassword($password);
}
catch (Exception $e)
{
    echo $e->getMessage();
}
```

Regards

**Comment by bigjoevtrj** [comment]
i understand, but i've tried on phone and it worksi understand, but i've tried on phone and it works

**Comment by mgp25** [comment]
@bigjoevtrj you cant use your number at the same time with the API and with your device. If you get your WhatsApp password using the API, you have to request another code to your device, if you use WhatsApp in your device, the password you got before doesnt work and you will have to request a new one.

**Comment by bigjoevtrj** [comment]
i know this, i had uninstalled wa on phone, and got the sms code, after the login failure i've installed it again to check the block and it work fine....
