### ISSUE TITLE
2 scripts at the same time

### ISSUE THREAD

**Issue by davidgff** [mgp25/WhatsAPI-Official#602]
Hi, 
i have 2 scripts, one to check wich is always polling and the other is often use and it's just for sending messages and then the scripts dies...  when i use the second one,  the first one stops running and gives this error: 
Maximum execution time of 10 seconds exceeded

is there a way to make this so the first script doesn't get interrupted?

thanks in advance.

**Comment by thetitoo** [comment]
Hi,

You can't have 2 instances running at the same time.
Use the polling script to send messages as well (check the examples)

Christophe Hubert.

**Comment by jesperveldhuizen** [comment]
Is it possible to track when a instance has 'died' ?

**Comment by thetitoo** [comment]
This is more of a php question.
On the other hand you can find out if you are still connected using `isConnected()`

**Comment by jesperveldhuizen** [comment]
How can I break out the while loop (polling) when a new connection is created? `isConnected()` does not return false on this occasion, so `break` in the `else` statement does not work...

Small example:

```php
<?php
  
$wa = new WhatsappHandler($client);
$protocol = $wa->getProtocol();  // returns WhatsProt

while (true)
{
    // Are we connected? 
    if ($protocol->isConnected())
    {
        $protocol->pollMessage();
        $messages = $protocol->getMessages();  
        
        // And do some more things ...
    }

    // Break out the loop because of new connection. 
    else
    {
        break; 
    }
}

if ($protocol->isConnected())
{
    $protocol->disconnect();
}
  
?>
```

**Comment by jesperveldhuizen** [comment]
CC @mgp25 (maybe you got an idea?)

**Comment by jesperveldhuizen** [comment]
Sorry to spam this topic, but I have found a solution. I have modified `whatsprot.class.php` and added the following line after line 3259.

```php
        if ($node->getTag() == "stream:error" && $node->getChild(1)->getData() == 'Replaced by new connection')
        {
            $this->disconnect();    
        }
```

This code disconnects the socket when a new connection is create by a other instance. Now my code above works and the script stops.
