### ISSUE TITLE
Password changing every day

### ISSUE THREAD

**Issue by Quera** [mgp25/WhatsAPI-Official#605]
Hi,
I have still the same problem: every day I need to register my Whatsappa account because the password I used the day berfore is wrong.

I tried to register my account both with WART and with WhatsAPI Official Script but every day I have the same problem.

is WhatsApp trying to block my account?

**Comment by CODeRUS** [comment]
I don't think the password is wrong. I think you logged in with wrong nextChallenge data. Check how challenge is handled and saved between logins. You should not clear data saved by api.

**Comment by Quera** [comment]
here is my error message

Fatal error: Uncaught exception 'Exception' with message 'Login Failure' in /htdocs/public/www/WhatsAPI/src/whatsprot.class.php:2322 Stack trace: #0 /htdocs/public/www/WhatsAPI/src/whatsprot.class.php(566): WhatsProt->doLogin() #1 /htdocs/public/www/WhatsAPI/Tp_ver_01/downMsg.php(19): WhatsProt->loginWithPassword('JaVh1Jd3/fBN944...') #2 {main} thrown in /htdocs/public/www/WhatsAPI/src/whatsprot.class.php on line 2322

**Comment by Quera** [comment]
but I do nothing with nextChallenge data.
I simply run my php script every morning. 
First two week I had no problem, now without change anything I have this message

**Comment by CODeRUS** [comment]
check if script have write right to it directory and you have nextChallenge.*.dat file

**Comment by Quera** [comment]
Yes, it has

**Comment by Quera** [comment]
i have something like nextChallenge.<phonenumber>.dat

**Comment by CODeRUS** [comment]
@mgp25 check this please ^

**Comment by 0xTryCatch** [comment]
It is unrelated to nextChallenge. Please post a debug log when the login failure happens.

**Comment by Quera** [comment]
here is my log:
15-04-2015 16:02:39tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="??????????">B ÈÎ?????????j­ŸºX¸,ÁÙž š„^ô1429106559WhatsApp/2.12.61 S40Version/14.26 Device/Nokia302 MccMnc/222001</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>Æ-{Å(#ö!&ÛéRFôfÚJ</challenge>

tx  <response>KMHö"k«§
Fatal error: Uncaught exception 'Exception' with message 'Login Failure' in /htdocs/public/www/WhatsAPI/src/whatsprot.class.php:2322 Stack trace: #0 /htdocs/public/www/WhatsAPI/src/whatsprot.class.php(566): WhatsProt->doLogin() #1 /htdocs/public/www/WhatsAPI/Tp_ver_01/downMsg.php(19): WhatsProt->loginWithPassword('JaVh1Jd3/fBN944...') #2 {main} thrown in /htdocs/public/www/WhatsAPI/src/whatsprot.class.php on line 2322

**Comment by 0xTryCatch** [comment]
Please use markdown next time otherwise our eyes hurt ;)

It seems you are using an older version of WhatsAPI. Can you upgrade and try again?

**Comment by mgp25** [comment]
@Quera have you used `checkCredentials` or `login()`? Both of them resets your password.

Also, you markdown to quote your debug.

If you aren't using that functions, then you are logging in with that account in some device or somebody else has your identity and reset your password whenever he wants.

My recomendation:

1- Delete your identity from the `/wadata` folder.
2- Register it again.
3- Don't let anyone to have your new identity
4- Dont you the functions i told above.

Once you have done that, tell me if everything is right.

Regards

**Comment by Quera** [comment]
ok I will download API again and I will follow mgp25 instruction.
once I have done that I will inform.

Thanks

**Comment by qoronfola** [comment]
Hi , yes exactly same issue i am facing with two of my numbers , i have other working just fine.
@Quera Please tell us what your findings are.

**Comment by Quera** [comment]
@qoronfola what about "i have other working just fine"?
Do You solve your problem? How?

**Comment by qoronfola** [comment]
@mgp25 I understand you like to keep everything clean in the Issues homepage :)
But issue wasn't resolved yet maybe some one who've experience it can see the issue and respond to it

@Quera no i mean i have multiple numbers using same code , only two of them give me this error.

Another thing : requesting a new password return the password without asking for verification (SMS-Voice) which is troubling :S

**Comment by Atlyatuu** [comment]
@mgp25 , theirs a little more than a couple of us still experiencing the same issue. me is with all my numbers,  using the latest source.
My opinion is that this could have to do with the way the code is handing the challengeData? 
please advice.

Thanks

**Comment by 0xTryCatch** [comment]
Does the problem persist after you re-register the number?

**Comment by Atlyatuu** [comment]
@0xTryCatch , yes still persist; after successfully processing registrationTool..

**Comment by mgp25** [comment]
Delete your identiy from `/wadata` folder and register it again.

**Comment by Atlyatuu** [comment]
@0xTryCatch, @mgp25  , yes still persist after those two actions:

shedding a little more on the issue.
example/exampleFunction.php - throws op's exception
example/Simple CLI client.php - throws op's exception
example/registrationTool.php - successfully registers each time
example/blockChecker.php - returns a different pw each time* as number Not Blocked.

ps. Being apart of the community i know how much we all like and appreciate this code.
but i do suggest keeping this issue as [open],  We can collaborate and help find the solution for this issue, and im sure issues #521,#526, #554, #599 will appreciate it too.

Thank you guys,

**Comment by mgp25** [comment]
@Atlyatuu send me in an email, your number, password an identity, im going to register the number on my side, and check if tomorrow still working, because i never experienced that. Meanwhile i have the code, do not attempt to use it in any device.

Regards

**Comment by Atlyatuu** [comment]
Thanks, @mgp25.

**Comment by hansrouge** [comment]
Any news here?

**Comment by CODeRUS** [comment]
Any problems here?

**Comment by mgp25** [comment]
I helped other users in this, mostly IP issues not API related.

Regards

**Comment by hansrouge** [comment]
@mgp25 Ok, thank you :+1:

**Comment by Quera** [comment]
Hi,
Few days ago I installed new API version and I cleaned wadata direcotry.
So until today I have no problem, all seems work good.

**Comment by Alfafc** [comment]
Hi @mgp25, I was wondering what are the IP issues you helped to solve to other users.

I am facing the same problem, BTW I running it on a docker container (where I use to test this kind of stuff). Is that an issue? An IP related one?
