### ISSUE TITLE
Error: registration failed [a phone]: bad_param

### ISSUE THREAD

**Issue by hgc2002** [mgp25/WhatsAPI-Official#606]
I'm receiving constantly the response "bad_param" since couple of days. I've updated whatsapi this morning so i'm up to date.

Sometimes it works, but it's about 1 to 5 (4 failed!). I've tried mostly with +1 numbers from Canada. Currently i'm testing with USA numbers, but results are the same.

Do you have any idea why this can be happening?

Regards,
Herman.

**Comment by mgp25** [comment]
@hgc2002 Virtual phone numbers are being blocked by WhatsApp, dont use virtual phone numbers.

Regards

**Comment by hgc2002** [comment]
I know but that block happens AFTER registering and use the phone for login, not in the middle of registration process.

The reason for bad_param must be other.

**Comment by hgc2002** [comment]
by the way, this is happening mostly with numbers that comes from USA, when i'm in Europe. Could be something regarding with my IP???

**Comment by hgc2002** [comment]
tested: IP has something to do. using local IP from the country where the number come from helps to get it registered succesfully.
