### ISSUE TITLE
News Service

### ISSUE THREAD

**Issue by janpsx** [mgp25/WhatsAPI-Official#608]
Iam trying to use the API to send news from the city and the region. The recipient must be the first to write a message to me to activate this service. But I got blocked. Any idea how to fix that?

**Comment by CODeRUS** [comment]
you should sync everybody

**Comment by janpsx** [comment]
before each sending? Or on Login?

**Comment by CODeRUS** [comment]
for each contact you want to send message

**Comment by l043nz0** [comment]
I think that you have blocked from whatsapp because you send massive messages an not a real conversation.
I think that you must change number and type of service or call whatsapp customer care avoid blocking.

**Comment by janpsx** [comment]
@l043nz0 i would it not call "massive sending". Currently I have 37 users for this service and each User have to register for this service. In this Case I think it agrees with the terms and conditions. But what you mean with change the type of service?

**Comment by l043nz0** [comment]
@janpsx How many messages you send? How many messages received?
I mean that send "news" is not agrees with conditions of Whatsapp

**Comment by jodinathan** [comment]
Hi, please, what do you mean by "sync everybody" ?

**Comment by jesperveldhuizen** [comment]
Read the wiki friends :)

https://github.com/mgp25/WhatsAPI-Official/wiki/Sync

**Comment by janpsx** [comment]
@l043nz0 I have send about 32 Messages und received no message. In the conditions "News" is not mentioned. " You agree not to spam, or solicit for commercial purposes, any users of the Service."

**Comment by janpsx** [comment]
@jodinathan Read the Wiki https://github.com/mgp25/WhatsAPI-Official/wiki/Sync

**Comment by jodinathan** [comment]
Thank you very much. Very helpful.

2015-04-16 11:26 GMT-03:00 janpsx <notifications@github.com>:

> @jodinathan <https://github.com/jodinathan> Read the Wiki
> https://github.com/mgp25/WhatsAPI-Official/wiki/Sync
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mgp25/WhatsAPI-Official/issues/608#issuecomment-93747919>
> .
>



-- 
Jonathan Rezende

**Comment by l043nz0** [comment]
@janpsx But I think that this is a service like spam: Whatsapp doesn't understand that's news or spam
