### ISSUE TITLE
no_routes Error

### ISSUE THREAD

**Issue by markusvienna** [mgp25/WhatsAPI-Official#611]
hi, 

i try to Request a code for a number (in total 3 of them 2 Austrian / different networks and 1 Indian / Vodafone ) but all i get is no_routes error 
```
no_routes [retry_after] => 3600 
```
i tried also to add Network to Function according to the networkinfo.cvs 
```php
$w->codeRequest('sms',$network);
```
i also tried 
```php
$w->codeRequest('voice');
```

I didnt find something on the net or either in the fixed Issuses which helped me, is there anything hint link or information which can help me fixing this problem ?

all the best

**Comment by mgp25** [comment]
@markusvienna post one of your numbers here.

**Comment by markusvienna** [comment]
9109873013762
and i also tried
919873013762

91 is the indian Landcode i tried both of the Vodafone Carriers

thx for help

**Comment by mgp25** [comment]
It worked in my side. So it must be your IP.

```
Array
(
    [in] => 09873013762
    [cc] => 91
    [id] => t'tbo??c?t?o?yr
    [lg] => hi
    [lc] => IN
    [sim_mcc] => 404
    [sim_mnc] => 000
    [method] => sms
    [token] => 5a2ef4bb79c8dbc49ae2d8a5510cf5b5
)
stdClass Object
(
    [status] => sent
    [length] => 6
    [method] => sms
    [retry_after] => 1805
)
```

Regards
