### ISSUE TITLE
LoginFailureException

### ISSUE THREAD

**Issue by aki263** [mgp25/WhatsAPI-Official#613]
Example register works well but when i try exmple fuction it gives error. 

![i3mg](https://cloud.githubusercontent.com/assets/5713674/7211349/9abf4e50-e577-11e4-8be0-2bf39f1f4a98.png)

`examplefuction.php`
![img](https://cloud.githubusercontent.com/assets/5713674/7211351/9edb395e-e577-11e4-9711-67657929442a.png)

i am using xamp, i tied lot of `$this->DebugPrint()` to find issue but nothing helped. Also i am sure if nextChallenge file is created after successfull login or before because there is no nextChallenge file being created. I have checked permission and there are other files being created like id.919910423393.dat in wadata folder. So file creation permission is working well. 

How can i check if the login that that i am sending is correct and accepted by whatsapp.

**Comment by mgp25** [comment]
Try latest commit: https://github.com/mgp25/WhatsAPI-Official/commit/abff168ec6cc1edb36ca22e87b9f8b3c6fefe706

It was sending nodes even before logging in. If still happening, then, its your password, register it again and try logging in again.

Regards

**Comment by aki263** [comment]
Still same. No improvement. Generated new password also. 
How to track if login is success or not. Any way to confirm that password is correct or not

**Comment by mgp25** [comment]
@aki263 you can try this: http://www.watools.es/bloqueado.html

**Comment by aki263** [comment]
says account is locked but how is it possble, i get status ok every time i generate password

Array ( [in] => 1123210485 [cc] => 54 [id] => q���w/�����:\�bw�u [lg] => es [lc] => AR [sim_mcc] => 722 [sim_mnc] => 000 [method] => sms [token] => e32ffcaadfd8c990c6a0e0b8f377504b ) stdClass Object ( [status] => ok [login] => 5491123210485 [pw] => IAbUe4PZ0FkdDHwvdy7zAr7ytK4= [type] => existing [expiration] => 1460788637 [kind] => free [price] => US$0.99 [cost] => 0.99 [currency] => USD [price_expiration] => 1432501831 ) 

SMS CODE: 289496

**Comment by mgp25** [comment]
@aki263 are you using that number in a mobile device? You cant use it in the API at the same time. If you arent, ill research for this.

Regards

**Comment by aki263** [comment]
I wish i could use that number on mobile device 
http://prntscr.com/6v16s6

**Comment by aki263** [comment]
I wish i could use that number on mobile device 
http://prntscr.com/6v16s6

**Comment by aki263** [comment]
any update, is it working for you ..?
