### ISSUE TITLE
How to get the nickname by phone number

### ISSUE THREAD

**Issue by alexus37** [mgp25/WhatsAPI-Official#615]
Hi,
first I want to say thank you for the awesome api! 
But I am struggling to find a function to get the nickname of a given phone number.

Thanks for your advise

**Comment by mgp25** [comment]
@alexus37 That is not possible. You are the one who set the nickname in your device, so you should to create a database with the names and phone numbers if you want to get that.

What you can do, its getting the push nickname the user has when he send you a message. You can get it using the following event: `onMessage($mynumber, $from, $id, $type, $time, $name, $body)`

You can follow this: https://github.com/mgp25/WhatsAPI-Official/wiki/WhatsAPI-Documentation#legacy-events

Its explained in the wiki.

Regards

**Comment by alexus37** [comment]
oh okay thanks for the quick response!
