### ISSUE TITLE
Cant receive Group Participants

### ISSUE THREAD

**Issue by Abtab** [mgp25/WhatsAPI-Official#616]
Hi

I am sending  
```php
$w->sendGetGroupV2Info($gid);
 $w->eventManager()->bind("onGetGroupV2Info", "onGetGroupV2Info"); 
```
 But not retrieve anything in onGetGroupV2Info function

Following is debug Results:
```xml
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="86130255XXXXX">/ó˜R8613025531436Qn¶¸g5êôd…_à>.âA1429510989</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>qïl‰.FÉœ}˜2{®¶Ud</challenge>

tx  <response>›@-?[š üôÊ&eÎld ÁØ>2˜­#­Ëª Æëv</response>

rx  <success t="1429510991" props="4" kind="free" status="active" creation="1424589197" expiration="1456125197">ƒ'	ÕÖKþVí KUÉ'2ó5Q</success>

tx  <presence name="Rahi"></presence>

tx  <iq id="1" xmlns="w:g2" type="get" to="918054595391-1429466812@g.us">
tx    <query request="interactive"></query>
tx  </iq>

rx  <ib from="s.whatsapp.net">
rx    <offline count="0"></offline>
rx  </ib>
```

Thanks in Advance

**Comment by mgp25** [comment]
Its working perfectly:

```xml
tx  <iq id="3" xmlns="w:g2" type="get" to="***-1429523281@g.us">
tx    <query request="interactive"></query>
tx  </iq>

rx  <iq from="***-1429523281@g.us" id="3" type="result">
rx    <group id="***-1429523281" creator="***@s.whatsapp.net" creation="1429523281" subject="Test" s_t="1429523281" s_o="***@s.whatsapp.net">
rx      <participant jid="***@s.whatsapp.net"></participant>
rx      <participant jid="***@s.whatsapp.net" type="admin"></participant>
rx    </group>
rx  </iq>
```

Maybe you are not polling messages.

**Comment by Abtab** [comment]
My code is:

function onGetGroupV2Info($mynumber, $creator, $creation, $subject, $participants, $admin)
{
echo "fired";

$GList=$participants;
//var_dump($participants);

$_SESSION['GList']=$participants;

}


$w = new WhatsProt($number,$nickname, $debug);
 $w->eventManager()->bind("onGetGroupV2Info", "onGetGroupV2Info");                   
                            $w->connect();
              
 $w->loginWithPassword($password);


   $w->sendGetGroupV2Info($gid);
//$w->sendGetGroupsParticipants($gid);
//echo "sent";
$w->pollMessage(); 



Please guide me if anything is wrong

Regards

**Comment by mgp25** [comment]
@Abtab please, quote your code, its easy, so please do it, so people can easily read the code.

```php
while(1)
{
$w->pollMessage();
}
```

It is explained in the wiki...

**Comment by Abtab** [comment]
Ok . I will .. Thanks

**Comment by Abtab** [comment]
Sorry for asking @mgp25 . As per your reply i added while loop . Now following is Debug result:
```xml
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="8613025531436">-BN8613025531436Ò€©tzD¶EusV¥ç¾wTÏþ1429525819</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>Ù°«EX¨Pn4¬¹7ŠÜJÀŒÔMô</challenge>

tx  <response>/+G|e!s¶Ì?^FxOæ	Øfjzqá‘2kO¾çžgé</response>

rx  <success t="1429525821" props="4" kind="free" status="active" creation="1424589197" expiration="1456125197">0¢B˜Ô«f‹	|›I›ùóäk</success>

tx  <presence name="Rahi"></presence>

tx  <iq id="1" xmlns="w:g2" type="get" to="8613025531436-1429503325@g.us">
tx    <query request="interactive"></query>
tx  </iq>

rx  <ib from="s.whatsapp.net">
rx    <offline count="0"></offline>
rx  </ib>

rx  <presence from="8613025531436@s.whatsapp.net"></presence>

rx  <iq from="8613025531436-1429503325@g.us" id="1" type="result">
rx    <group id="8613025531436-1429503325" creator="8613025531436@s.whatsapp.net" creation="1429503325" subject="OneStepAhead" s_t="1429503325" s_o="8613025531436@s.whatsapp.net">
rx      <participant jid="918054595391@s.whatsapp.net"></participant>
rx      <participant jid="8613025531436@s.whatsapp.net" type="admin"></participant>
rx    </group>
rx  </iq>

firedstring(12) "OneStepAhead" rx  <stream:error>
rx    <conflict></conflict>
rx    <text>Replaced by new connection</text>
rx  </stream:error> 
```

**Comment by mgp25** [comment]
@Abtab `rx    <text>Replaced by new connection</text>`

You are trying to login with other device or other instance

**Comment by Abtab** [comment]
there is not any other connection and following exception i caught in error log:

[20-Apr-2015 11:11:13 UTC] PHP Notice:  Undefined index: groupcreate in /home/XXX/public_html/test/wa/includes/whatsapp/whatsprot.class.php on line 3042
[20-Apr-2015 11:11:13 UTC] PHP Notice:  Undefined index: endgroup in /home/XXX/public_html/test/wa/includes/whatsapp/whatsprot.class.php on line 3050
[20-Apr-2015 11:11:13 UTC] PHP Notice:  Undefined index: getgroups in /home/XXX/public_html/test/wa/includes/whatsapp/whatsprot.class.php on line 3058
[20-Apr-2015 11:11:13 UTC] PHP Notice:  Undefined index: get_lists in /home/XXX/public_html/test/wa/includes/whatsapp/whatsprot.class.php on line 3079

**Comment by CODeRUS** [comment]
@Abtab we're not idiots, and whatsapp server is not idiot also. There IS another connection. You running whatsapi multiple times.

**Comment by Abtab** [comment]
@CODeRUS .. I just post my situation. May I am idiot doing something wrong.  I will not disturb you people now. Thanks for reply . Closed

**Comment by mgp25** [comment]
@Abtab post your full code script, ill try to help you, but you need to provide me as much info as possible.

**Comment by Abtab** [comment]
ok. Please check code below . Its just simple code @mgp25, But confused with error :

```php

case 'a':
			
     $GList = NULL;
function onGetGroups($mynumber, $List)
{
$_SESSION['GList']=$List;
$_SESSION['mynumber']=$mynumber;
}

                  

				$w = new WhatsProt($number, $nickname, true);
             $w->eventManager()->bind("onGetGroups", "onGetGroups");
                         $w->connect();
 $w->loginWithPassword($password);


                      $w->sendGetGroups();
                           }
break;
case 'b':
function onGetGroupV2Info($mynumber, $creator, $creation, $subject, $participants, $admin)
{
echo "fired";

$GList=$participants;
var_dump($participants);
}
			
$w = new WhatsProt($number, $nickname, true);
                   $w->eventManager()->bind("onGetGroupV2Info", "onGetGroupV2Info");    
                         $w->connect();
 $w->loginWithPassword($password);

                     $w->sendGetGroupV2Info($gid);

while(1)
{
$w->pollMessage();                          
} 
     
$w->disconnect();

```

First  i am calling case 'a' to check all my groups and then calling case 'b'  to view participants in specific group  .

**Comment by mgp25** [comment]
@Abtab i need the full code script so i can see where the error is.

**Comment by CODeRUS** [comment]
I think logging on every case is a problem of replacing your connection with another one. but we need to ask our expert. @mgp25 what is your opinion? could it be a reason?

**Comment by mgp25** [comment]
@CODeRUS is right, you and logging in the 2 cases, with a result of a `replaced connection`

So you were doing it wrong.

In your case A, there is:
```php
$w->connect();
 $w->loginWithPassword($password);
```

And also appear in case B:
```php
$w->connect();
$w->loginWithPassword($password);
```

So... nothing more to say

**Comment by CODeRUS** [comment]
@Abtab you should login ONCE affter starting your script, and disconnect on quit.

**Comment by Abtab** [comment]
Thanks for your replies @mgp25  and @CODeRUS .  :+1:

**Comment by hassanalisalem** [comment]
its working only on debug mode and only with using of : sendGetGroups()
but you cannot get group list from sendGetGroups
but when you put it on debug mode you will see groups participants 
but how may I use it ???
