### ISSUE TITLE
Sync before send vs. backoff time

### ISSUE THREAD

**Issue by lc-ikrumov** [mgp25/WhatsAPI-Official#620]
Hello WhatsApi team,

After reading every issue about sync I have one remaining thing I am not clear about, I hope you can answer.

I have an app where external contacts can send messages to my number, registered via the API. After initiating a conversation I can respond to them. So I make sure the contacts have me in their address book. Now, as I understand, before sending a message to the contact I need to make sure I have the contact in my address book as well, otherwise I'm risking a ban.

So before I send a message to an unsynced number I use sendSync(number), and if the result is 'existing in WhatsApp' (duh) then I move on to sending and never sync the number again. I use delta background sync for that. My problem is that because many contacts can initiate a conversation and I need to respond to them quickly, and I want all of them to be synced, I need to sendSync frequently, and I can't because of the sync limit per hour. I can respond to the contact without syncing but I don't want a ban.

I want to know how the real Whatsapp app does it - as with it I can have multiple contacts adding me and I can chat with them instantly.

Should I allow sending before sync at all? And maybe sync unsynced contacts every few hours or so?
 
Thanks!

**Comment by phpjoker** [comment]
Unfortunately, in each case will be blocked.

**Comment by jodinathan** [comment]
Hi, is there a sync limit per hour?
couldn't find it at https://github.com/mgp25/WhatsAPI-Official/wiki/Sync

**Comment by mgp25** [comment]
@jodinathan 

If an user sendd you a message first, you can answer without syncing it. If you are going to send a message (without an started conversation), thrn you must sync it.

If you want to sync a single person, just do a sync with delta interactive.

And only sync with default params all contacts but not always.

And yes, there is a limit, i dont know how many request you can do, but if you exceed you will get a backoff error, and wait 1 hour.

Regards

**Comment by hansrouge** [comment]
Be careful about the auto-answer if the contacts are not synced. If you have a lot (like 500) you will be blocked. Thats whats happend to me.

I now sync about 25 contacts every few minutes with sendSync() and never get blocked again :)

**Comment by lc-ikrumov** [comment]
@mgp25 Thanks for the quick reply!
> And only sync with default params all contacts but not always.
I didn't get that. I thought you cannot pass all contacts to sendSync with the default params (delta backgound), because mode 'delta' is for new contacts only, not existing contacts.

What do you mean by 'not always'? I should mix default params sync (delta backgound) with some other sync type like delta interactive?

@hansrouge What sync type are you using? Every few minutes seems quite often.

**Comment by mgp25** [comment]
@lc-ikrumov delta interactive only for new contacts.

Do only `sendSync($numbers)` when syncing all numbers (only in login) and not always, for example sometimes you can login without resyncing everything.

Regards

**Comment by hansrouge** [comment]
@lc-ikrumov I do it every 20 minutes and just if there new contacts in my list :)
I do it like: $this->w->sendSync($array_numbers,null,3);

**Comment by lc-ikrumov** [comment]
@mgp25 @hansrouge Great, thanks!

**Comment by matteocontrini** [comment]
What's the difference between delta interactive and delta background?
