### ISSUE TITLE
Can register/send messages

### ISSUE THREAD

**Issue by Wuuuz** [mgp25/WhatsAPI-Official#621]
Hi,

i have a problem sending messages with WhatsAPI.
```php
<?php
include_once('src/whatsprot.class.php');

$username = "xxx";
$nickname = "xxx";
$password = "xxx"; // The one we got registering the number
$debug = true; 

// Create a instance of WhastPort.
$w = new WhatsProt($username, $nickname, $debug);

$w->connect(); // Connect to WhatsApp network
$w->loginWithPassword($password); // logging in with the password we got!

$target = '4915253438535'; // The number of the person you are sending the message
$message = 'Yo :)';

$w->sendMessage($target , $message);

?>
```
This is my code for senden a message. But when i want to send, i get empty page and no message is sent.
I bought a prepaid card to register a new number. But why can't I see the debugtext?

Can it be, that there is a problem with the registration? I registrated my number, status ok, but i can work on my mobile phone any more.
So is there a registraion problem?

Here some more details:

When I request a code, this is sent:
```
Array ( [in] => 157527xxxx [cc] => 49 [id] => | º‡aØ;#sË9,>Ó4|��,� [lg] => de [lc] => DE [sim_mcc] => 262 [sim_mnc] => 000 [method] => voice [token] => e7b86212dbbd6802a300d1a5612a83ae ) stdClass Object ( [status] => sent [length] => 6 [method] => voice [retry_after] => 82805 )
```
When I register a code, I get a blank website.

Now when i open my `codeRequest.php`, i get this:
```
Array ( [in] => 157527xxxx [cc] => 49 [id] => | º‡aØ;#sË9,>Ó4|��,� [lg] => de [lc] => DE [sim_mcc] => 262 [sim_mnc] => 000 [method] => voice [token] => e7b86212dbbd6802a300d1a5612a83ae ) stdClass Object ( [status] => ok [login] => 491575xxxxx [pw] => OmmAcKjEvxxxxx [type] => existing [expiration] => 1461094518 [kind] => free [price] => 0,89 â‚¬ [cost] => 0.89 [currency] => EUR [price_expiration] => 1432720295 )
```
When i now want to send a message, I get a blank site, too :(

**Comment by mgp25** [comment]
@Wuuuz you need to add `$w->pollMessage();` after sending the message, try it and tell me.

Regards

**Comment by Wuuuz** [comment]
Ok, i tried it. Don't get any text on my screen when opening the script :(
Yesterday it worked with my normal sim card, when i bought the prepaid one, it doesn't work. How can i be, that I register my normal sim card with WhatsAPI (requestcode + register), same with status ok, and not being unregistered on my mobile ?

**Comment by mgp25** [comment]
@Wuuuz you cant use the number in your phone and with the api at the same time.

Regards

**Comment by Wuuuz** [comment]
@mgp25 
I know this :) So I bought the prepaid card ;-)
But when i register my new number, I get a password and when I will send a message, it doesn't work and there is no text on my site, so no debugtext.
How can this be?
