### ISSUE TITLE
Getting Read 

### ISSUE THREAD

**Issue by jesusvalverde** [mgp25/WhatsAPI-Official#622]
Sometimes the read signal, sometimes no, same number (mine) some procedures..all seems to be te sames.

Any clue ?

**Comment by CODeRUS** [comment]
If you do not receive read signal then recepient does not send read acknowledge. Whatsapp client have option to send or not it.

**Comment by jesusvalverde** [comment]
The number that get the text is mine...I know I read the text 'cos I do control my own phone, and ist's an Iphone and there is no option to option to avoid this, 

Any other sugestion.

**Comment by CODeRUS** [comment]
android have this option also

**Comment by CODeRUS** [comment]
run in debug mode and check if read is actually received

**Comment by jesusvalverde** [comment]
tnks...

**Comment by mgp25** [comment]
@jesusvalverde post debug log to see the nodes.
