### ISSUE TITLE
Sending message not working

### ISSUE THREAD

**Issue by jesperveldhuizen** [mgp25/WhatsAPI-Official#624]
On one of my numbers it's not possible to send messages anymore, but not always. Most of the time it's not working though. 

Here's the debug log:

```javascript
rx  <chatstate from="**@s.whatsapp.net">
rx    <composing></composing>
rx  </chatstate>

rx  <message from="**@s.whatsapp.net" id="1429646589-324" type="text" t="1429694610" notify="
Jesper">
rx    <body>Hello</body>
rx  </message>

tx  <receipt type="read" to="**@s.whatsapp.net" id="1429646589-324" t="1429694573"></receipt>

tx  <iq id="5" xmlns="urn:xmpp:whatsapp:sync" type="get">
tx    <sync mode="delta" context="background" sid="130741717740000000" index="0" last="true">
tx      <user>+**</user>
tx    </sync>
tx  </iq>

rx  <ack from="**@s.whatsapp.net" id="1429646589-324" class="receipt" type="read"></ack>

rx  <iq from="**@s.whatsapp.net" id="5" type="result">
rx    <sync index="0" sid="130741717740000000" last="true" version="1429618760908643">
rx      <in>
rx        <user jid="**@s.whatsapp.net">+**</user>
rx      </in>
rx    </sync>
rx  </iq>

PHP Notice:  Undefined index: get_lists in /mnt/CRONTABS/varia/whatsapp_cron/classes/src/whatsprot.cla
ss.php on line 3030
tx  <chatstate to="**@s.whatsapp.net">
tx    <composing></composing>
tx  </chatstate>

tx  <chatstate to="**@s.whatsapp.net">
tx    <paused></paused>
tx  </chatstate>

tx  <message to="**@s.whatsapp.net" type="text" id="6" t="1429694582">
tx    <body>Ik snap je bericht niet.</body>
tx  </message>

rx  <ack from="**@s.whatsapp.net" id="6" class="message" t="1429694620"></ack>

rx  <receipt from="**@s.whatsapp.net" id="6" t="1429694620"></receipt>

tx  <ack to="**@s.whatsapp.net" id="6" type="read" t="1429694583"></ack>
```

I do notice the error, but on my other numbers it's working fine... Any idea's?

EDIT:

The number is not blocked by the way.

**Comment by mgp25** [comment]
@jesperveldhuizen As you can see here:

```xml

tx  <message to="**@s.whatsapp.net" type="text" id="6" t="1429694582">
tx    <body>Ik snap je bericht niet.</body>
tx  </message>

rx  <ack from="**@s.whatsapp.net" id="6" class="message" t="1429694620"></ack>

rx  <receipt from="**@s.whatsapp.net" id="6" t="1429694620"></receipt>
```

The message has been sent. Whats your problem?

**Comment by jesperveldhuizen** [comment]
Sorry should have been more clear.

I see the message is send on the log yes, but it's not arriving on my phone.

**Comment by mgp25** [comment]
@jesperveldhuizen the phone receives and sees the message:

```xml
rx  <receipt from="**@s.whatsapp.net" id="6" t="1429694620"></receipt>
```

Are you using latest version? try with other numbers and try to debug and give more info.

**Comment by jesperveldhuizen** [comment]
Yes I updated this morning.

Very strange this... I do see the 'typing...' in the chat, but the message then never arrives. Will run more tests and get back to you.

**Comment by ruenue58** [comment]
the same problem here...  sending text from PC to Handy dont works, Message "Success: Message Sent!" but no Message on the Phone.. sending from Phone to PC works.. after updating Whatsapp Messenger on the PC.
What goes wrong ?

**Comment by mgp25** [comment]
Please post script code

**Comment by ruenue58** [comment]
i am using: examples/whatsapp.php

**Comment by mgp25** [comment]
@ruenue58 use `exampleFunctional.php`

**Comment by ruenue58** [comment]
oki.. i try... :-) no Message....

**Comment by ruenue58** [comment]
[] Logging in as 'rudi' (4917626117206) tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="4917626117206">���4917626117206�;a��/�v�$�w�Ɓ��]�1429697068</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>���ZW{q�,�F�j^�</challenge>

tx  <response>�\�l�CD(��Z�f?�٠V���)���<���L</response>

rx  <success t="1429697068" props="4" kind="free" status="active" creation="1429539650" expiration="1461075650">��Y�6�=�E�cRؑn�F��</success>

tx  <presence name="rudi"></presence>

tx  <iq id="1" type="get" xmlns="w:profile:picture" to="491522805xxxx@s.whatsapp.net">
tx    <picture type="image"></picture>
tx  </iq>

rx  <ib from="s.whatsapp.net">
rx    <offline count="0"></offline>
rx  </ib>

rx  <presence from="4917626117206@s.whatsapp.net"></presence>

rx  <presence from="491522805xxxx@s.whatsapp.net"></presence>

rx  <iq from="491522805xxxx@s.whatsapp.net" id="1" type="result">
rx    <picture id="1418729443" type="image"> 57558 byte data</picture>
rx  </iq>

**Comment by mgp25** [comment]
@ruenue58 send me an email with your data..

**Comment by ruenue58** [comment]
Send Mail to you...  thanks :-)

**Comment by jesperveldhuizen** [comment]
Just made a little testcase to go outside my complete script and just try it with the basics, and it's still not working:

```php
<?php

require_once('src/whatsprot.class.php');

$to = '**';

$w = new WhatsProt('**', 'Whatsapp', true);
$w->connect();
$w->loginWithPassword('**');
$w->sendSync(array($to));
$w->sendMessage($to, 'Hi Hi');     
$w->disconnect();

?>
```

I did notice that I did got a push notification (but only one time during my tests), but there was no message in the chat. Debug log is the same as I posted above.

I also notice that it takes quite a while before the scripts continues to run after that `get_list` notice, about 2 seconds I guess.

**Comment by mgp25** [comment]
@jesperveldhuizen you have the script coded wrong. Add this after send message:

```php
$w->pollMessage();
$w->pollMessage();
```

Try it and tell me

@ruenue58 please, send me your number and password so i can test in my side.

Regards

**Comment by jesperveldhuizen** [comment]
I have the `pollMessage()` in my production script, but forgot to add it to the test case above. Make no difference unfortunatly.

**Comment by mgp25** [comment]
@jesperveldhuizen send in my email your number ans password, ill try to see whats happening.

**Comment by jesperveldhuizen** [comment]
Done :+1:

**Comment by ruenue58** [comment]
Done :-)

**Comment by mgp25** [comment]
@ruenue58 i have sent you already the test message

**Comment by ruenue58** [comment]
No Message here..  sorry..

**Comment by mgp25** [comment]
@ruenue58 then its you app, that its buggy, delete chat or reinstall and try again

**Comment by ruenue58** [comment]
first Time i try with Whatsapp.php yesterday it send for one Time a Message..  but only one.

**Comment by ruenue58** [comment]
oki.. thanks

**Comment by ruenue58** [comment]
I habe reinstall Whatsapp.. no changes. No Message on the Phone. When i send from Handy to the PC und update the php programm i see on the phone 2 blue marks...

**Comment by jesperveldhuizen** [comment]
Okay this is interesting... I'm now using an old version of the `src` and now it's working fine. When I switch to the latest `src` (which I downloaded this morning) it's not working.

**Comment by jesperveldhuizen** [comment]
Not sure why this is closed now because something is still cleary going wrong on some wierd occassions.

I just downloaded a fresh copy of the `src` again and my demo code is not working.... when I include the older `src` it is working fine. 

Maybe this is all caused by this `get_lists` notice that we get now??

**Comment by mgp25** [comment]
@jesperveldhuizen can you try with latest commit?

Regards

**Comment by jesperveldhuizen** [comment]
Bingo! Works fine now :+1:

**Comment by ruenue58** [comment]
Ok :-)
What Version do you use ?

Can you tell me ?

Rudi



Am 22.04.2015 15:46, schrieb Jesper Veldhuizen:

**Comment by mgp25** [comment]
@jesperveldhuizen use latest commit

**Comment by ruenue58** [comment]
After deleting old Messages from Phone i can send Text to the phone. 2. try.. no Message on the phone. Delete the old Message on the phone and send new one.. it works. Only if you have deletet all old Messages.... it works for one Message.

**Comment by mgp25** [comment]
Use latest commit and add pollmessage

**Comment by ruenue58** [comment]
No success..  only one Message. If i delete the old Message on the Phone.. it Works for one time.

**Comment by mgp25** [comment]
@ruenue58 send me an email please

**Comment by mgp25** [comment]
Sorry. Fixed in the latest commit. Not its working 100% :smile:

**Comment by ruenue58** [comment]
Hi it works :-) I will do some tests now..  and try to bind in our Portalsoftware.
Thanks for nice work. :-)

**Comment by ruenue58** [comment]
does anyone now how to send special chars like the german ?
I found the code for äüö and it works
I am looking for: ÖÄÜß

**Comment by mgp25** [comment]
@ruenue58 
```php
$msg = utf8_encode(' ÖÄÜß');
```

**Comment by ruenue58** [comment]
Thanks :-) It works !!

**Comment by ruenue58** [comment]
Hi from Cologne, is this true that the Whatsapp API needs every Day a new Password ?
I integrate yesterday the working function in our portalscript and its working fine.. last Message via the API was today 07:22...  after this an login error appears.
I use the WART Programm, get an new password and now its working again...

**Comment by mgp25** [comment]
@ruenue58 no.

And the API its called 'Chat API'

**Comment by ruenue58** [comment]
This function i have integrated in our portalsoftware and its working fine..
What  do you mean with Chat API ?

.......................................................................................................................
require ("./whatsapp/src/whatsprot.class.php");

function whatsapp($wmessage,$wsubject,$wto,$wuser,$pmbild)
{
	$submessage = addslashes($wmessage);
	$timestamp = time();
	$datum = date("d.m.Y",$timestamp);
	$uhrzeit = date("H:i",$timestamp);
	$watime = $datum." - ".$uhrzeit." Uhr";
	$wamessage = "EW-Portal PN von ".addslashes($wuser).":\n".$watime."\n"."Betreff: ".addslashes(htmlspecialchars($wsubject))."\n".
				$submessage."\n-------------\nHinweis:\nAntwort über Whatsapp nicht möglich! ";
	$wamessage = utf8_encode($wamessage);
	$w = new WhatsProt('491762611xxxx', 'Whatsapp', false);
	$w->connect();
	$w->loginWithPassword('hSRB+NK2YB/3lcF8V72L78taxxxx');
	$w->sendSync(array($wto));
	$w->sendMessage($wto, $wamessage); 
        if(strlen($pmbild) > 8) {
		$w->sendMessageImage($wto, $pmbild);	
	}
	$w->disconnect();
}

**Comment by mgp25** [comment]
Now this API its called Chat API...

If you use the same number in your device, the password will be resetted.

**Comment by ruenue58** [comment]
i dont understand..  i only use this phone number for my function. No other programm or phone use this phonenumber for whatsapp.

**Comment by ruenue58** [comment]
same problem after 6 hours again...

Fatal error: Uncaught exception 'LoginFailureException' in /var/www/htdocs/ks421/html/Board/whatsapp/src/whatsprot.class.php:2201 Stack trace: #0 /var/www/htdocs/ks421/html/Board/whatsapp/src/whatsprot.class.php(534): WhatsProt->doLogin() #1 /var/www/htdocs/ks421/html/Board/pmtest.php(18): WhatsProt->loginWithPassword('hSRB+NK2YB/3lcF...') #2 /var/www/htdocs/ks421/html/Board/pmtest.php(30): whatsapp('Message...', 'Test', '491522805xxxx', 'Rudi', NULL) #3 {main} thrown in /var/www/htdocs/ks421/html/Board/whatsapp/src/whatsprot.class.php on line 2201

**Comment by mgp25** [comment]
@ruenue58 It could be for this reason:

- Someone has your identity
- Connection / IP issues
- Using it in device
- Using checkCredentials

Remove your identity from `wadata` folder, register the number again.

**Comment by ruenue58** [comment]
oki.. thank you :-) i am now on the job.. i try tomorrow.. register completly new. 
have a nice afternoon.
Rudi

**Comment by vlnsnewton** [comment]
Hi.. All

Dear @mgp25 please help me.
I am having a number which is working since starting of this year but while i am using this number with chat-API it is not sending message.

Code i am using
$sender = 	"91801020XXXX"; // Mobile number with country code (but without + or 00)
$password =   "mK8yRaArf9V2QGlwSzvY4oxxxxxx"; // Password you received from WhatsApp
$nickname="fhruy";
$dst = "919717474431";
require '../src/whatsprot.class.php';
$w = new WhatsProt($sender, $nickname, true);
$w->connect();
$w->loginWithPassword($password);
$newContact = array($dst);
$w->sendSyn($newContact);
$w->sendPresenceSubscription($dst);
$w->sendMessageComposing($dst); // Send composing
$w->sendMessagePaused($dst); // Send paused
$message = 'Hi! :) this is a test message';
$w->sendMessage($dst , $message); // Send message
$w->pollMessage();  


and output i am getting is:

tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="918010202721">YK,0918010202721�����a����HiE���͙1444200703</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>���M�b����؈@��,���J</challenge>

tx  <response>�>�OgP?I���K��G�ZLwSX�/���1�c</response>

rx  <success t="1444201094" props="4" kind="free" status="active" creation="1440050283" expiration="1471586283">P� �KK1@#�v�H�e��</success>

tx  <presence name="fhruy"></presence>

**Comment by vlnsnewton** [comment]
my output is:

tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="918010202721">YK,0918010202721�����a����HiE���͙1444200703</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>���M�b����؈@��,���J</challenge>

tx  <response>�>�OgP?I���K��G�ZLwSX�/���1�c</response>

rx  <success t="1444201094" props="4" kind="free" status="active" creation="1440050283" expiration="1471586283">P� �KK1@#�v�H�e��</success>

tx  <presence name="fhruy"></presence>

**Comment by vlnsnewton** [comment]
Hi.. All

Dear @mgp25 please help me.
I am having a number which is working since starting of this year but while i am using this number with chat-API it is not sending message.

Code i am using
$sender = 	"91801020XXXX"; // Mobile number with country code (but without + or 00)
$password =   "mK8yRaArf9V2QGlwSzvY4oxxxxxx"; // Password you received from WhatsApp
$nickname="fhruy";
$dst = "919717474431";
require '../src/whatsprot.class.php';
$w = new WhatsProt($sender, $nickname, true);
$w->connect();
$w->loginWithPassword($password);
$newContact = array($dst);
$w->sendSyn($newContact);
$w->sendPresenceSubscription($dst);
$w->sendMessageComposing($dst); // Send composing
$w->sendMessagePaused($dst); // Send paused
$message = 'Hi! :) this is a test message';
$w->sendMessage($dst , $message); // Send message
$w->pollMessage();  


and output i am getting is:

tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="918010202721">YK,0918010202721ferg</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>gdfg</challenge>

tx  <response>gfdg</response>

rx  <success t="1444201094" props="4" kind="free" status="active" creation="1440050283" expiration="1471586283">dgdf</success>

tx  <presence name="fhruy"></presence>

**Comment by technofreaky** [comment]
The same its not working for me
i get the below error
```php
Fatal error: Uncaught exception 'LoginFailureException' in C:\xampp\htdocs\Chat-API-master\src\Login.php on line 53
( ! ) LoginFailureException: in C:\xampp\htdocs\Chat-API-master\src\Login.php on line 53
Call Stack
#	Time	Memory	Function	Location
1	0.0020	292720	{main}( )	...\whatsapp.php:0
2	0.0220	1548984	Whatsapp->process( )	...\whatsapp.php:286
3	0.0220	1549296	Whatsapp->sendMessage( )	...\whatsapp.php:416
4	0.0220	1549352	Whatsapp->connectToWhatsApp( )	...\whatsapp.php:618
5	0.2980	1549792	WhatsProt->loginWithPassword( )	...\whatsapp.php:511
6	0.2980	1550552	Login->doLogin( )	...\whatsprot.class.php:279
```

**Comment by Jacky8888** [comment]
gfsd

**Comment by Jacky8888** [comment]
Is not related to my environment version

**Comment by Jacky8888** [comment]
@ruenue58  
I have the same problem here... sending text from PC to Handy dont works, The message is sent, but no receive the message on the Phone.. sending from Phone to PC works.. after updating Whatsapp Messenger on the PC.
I have been based on the way you offer, but not yet.
Is it because of my environment version？
**My Linux version:centos6.5 64bit
PHP version:PHP 5.6.18
Apache version :httpd2.4.18**
I have installed all the expansion,including curve25519 and protobuf!But,the problem is still not solved.
What goes wrong ?

**Comment by Jacky8888** [comment]
This is my code:
`<?php

require __DIR__.'/../src/whatsprot.class.php';

// #### DO NOT ADD YOUR INFO AND THEN COMMIT THIS FILE! ####
$nickname = 'Coke';
$sender = '8613412534626'; // Mobile number with country code (but without + or 00)
$password = 'k0vusD3yX3aVtvsWSmAjcKXxnPM='; // Password you received from WhatsApp

$dst = $_GET['phone'];
$msg = $_GET['message'];

echo "[] Logging in as '$nickname' ($sender)\n";
$wa = new WhatsProt($sender, $nickname, true);

$wa->connect();
$wa->loginWithPassword($password);

echo "\n[] Send message to $dst: $msg\n";
$wa->sendMessage($dst, $msg);
echo "\n";`

**Comment by Jacky8888** [comment]
@mgp25 
I have the same problem here... sending text from PC to Handy dont works, The message is sent, but no receive the message on the Phone.. sending from Phone to PC works.. after updating Whatsapp Messenger on the PC.
I have been based on the way you offer, but not yet.
Is it because of my environment version？
**My Linux version:centos6.5 64bit
PHP version:PHP 5.6.18
Apache version :httpd2.4.18**
I have installed all the expansion,including curve25519 and protobuf!But,the problem is still not solved.
What goes wrong ?

**Comment by Jacky8888** [comment]
@mgp25 
`<?php

require __DIR__.'/../src/whatsprot.class.php';

// #### DO NOT ADD YOUR INFO AND THEN COMMIT THIS FILE! ####
$nickname = 'Coke';
$sender = '8613412534626'; // Mobile number with country code (but without + or 00)
$password = 'k0vusD3yX3aVtvsWSmAjcKXxnPM='; // Password you received from WhatsApp

$dst = $_GET['phone'];
$msg = $_GET['message'];

echo "[] Logging in as '$nickname' ($sender)\n";
$wa = new WhatsProt($sender, $nickname, true);

$wa->connect();
$wa->loginWithPassword($password);

echo "\n[] Send message to $dst: $msg\n";
$wa->sendMessage($dst, $msg);
echo "\n";`

**Comment by Jacky8888** [comment]
> rrtrt

**Comment by Jacky8888** [comment]
@mgp25 
This is my code:
`
require __DIR__.'/../src/whatsprot.class.php';
$nickname = 'Coke';
$sender = '8613412534626'; // Mobile number with country code (but without + or 00)
$password = 'k0vusD3yX3aVtvsWSmAjcKXxnPM='; // Password you received from WhatsApp
$dst = $_GET['phone'];
$msg = $_GET['message'];
echo "[] Logging in as '$nickname' ($sender)\n";
$wa = new WhatsProt($sender, $nickname, true);
$wa->connect();
$wa->loginWithPassword($password);
echo "\n[] Send message to $dst: $msg\n";
$wa->sendMessage($dst, $msg);
echo "\n";
`

**Comment by Jacky8888** [comment]
@mgp25 
And this is the debug log:

> [] Logging in as 'Coke' (8613412534626) tx  <stream:features></stream:features>

tx  <auth user="8613412534626" mechanism="WAUTH-2">594b2c303836313334313235333436323657e9c9171f2fef09e3a968796a70cc1f8d31681e31343537353937393631</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>a8c6246bccc890fbfdfa8cf59509ea253c647ace</challenge>

tx  <response>b2de7dda471670890e8cc5f836444e947c411500663cec3d957995454543b523b94da7cc4170a3c30d7893a149313c7a50988568cf890e39ce8b6038c71fec66bb11c1dc0ed57f59e70e95c3863751</response>

rx  <success t="1457597838" props="4" kind="free" status="active" creation="1446608000" expiration="4444444444">bc42b927127419e20f180e0a919b106715b72601</success>

tx  <presence name="Coke" type="available"></presence>

tx  <iq id="01" xmlns="jabber:iq:privacy" type="get">
tx    <query>
tx      <list name="default"></list>
tx    </query>
tx  </iq>

tx  <iq id="02" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net">
tx    <config></config>
tx  </iq>

[] Send message to 8613128281826: 第三方的 tx  <message to="8613128281826@s.whatsapp.net" type="text" id="bcf9756e27336d0413d4aa" t="1457597962" notify="Coke">
tx    <enc v="1" type="pkmsg">3328cea6b1a70a0883ddb9063000122105c0707cc5b4bab7ba66926f741ee0920724b1e181a455f6c5fb873e62e5c00e011a2105ebb3824806f8f41c622937650691b0cacbd33bec218697ccc4772186b02b3b2b2240330a2105d4ad815c30416da78219155ea864b8b0ead3f46191f0b415cf80c08252565760100222101ccbd3204c017c9df7b0990b3a48b56a4e65265c76da29dc</enc>
tx  </message>
