### ISSUE TITLE
Proposal on Code formatting.

### ISSUE THREAD

**Issue by jonnywilliamson** [mgp25/WhatsAPI-Official#73]
I have a proposal I would like to make to the "members" of the contributing team here. I am keen to stress I am not looking for any controversy or, indeed, trying to impose my preferences on others.

I've been working with this package for a while, mainly using PhpStorm as my editor. I don't have any interest in trying to convert anyone to use this software, BUT it does give me an huge amount of options with how we can make this code look and help track down bugs etc.

At the moment with all the contributors using different coding styles, the code is very messy. It makes it more difficult to work with to spot bugs, to re-factor etc.

I was hoping that we could pick a coding style to format the code with. It doesn't have to be one that we all like, just one that we can tolerate!

For example, with one click I can select from multiple PHP based coding styles and then the entire project would be auto-formatted and consistent (in terms of visual layout and format of methods, if statements, returns, tabs, spaces etc).

![styles](https://cloud.githubusercontent.com/assets/2513663/4799666/6a38d39a-5e1e-11e4-98d6-169992f1fd88.png)
 
I would recommend PSR1-PSR2, as its becoming much more mainstream, but if there's a consensus for anything else, I'll just click the button.

I believe there are also modules for Sublime etc that allow PSR-1 coding style to be applied to code, so that perhaps is another nod in that direction.

So how do people feel about this? I don't want a protracted discussion, just a general feel for how people would react if I made a pull request with this type of change?

Comments?

PS, if this doesn't wet your appetite for PHP development I don't know what will! [Be Awesome In PhpStorm](https://laracasts.com/series/how-to-be-awesome-in-phpstorm)

**Comment by mgp25** [comment]
O its way... https://github.com/mgp25/WhatsAPI-Official/commit/36fa98c6644f55b8843609934f5f5a68952d46a5

I close this issue, but as soon as we can we will adopt PSR-1/PSR-2 Standard

**Comment by mgp25** [comment]
Enhacements in code formatting and code efficiency:

https://github.com/mgp25/WhatsAPI-Official/commit/b996bc91349e0fe6dddd64482820eb26f57746ac
https://github.com/mgp25/WhatsAPI-Official/commit/f9ad4904e756f57d27b21edd45214c757a074130
https://github.com/mgp25/WhatsAPI-Official/commit/670888ebbee2f3610313bbe2b332d4d4630e556b
https://github.com/mgp25/WhatsAPI-Official/commit/d4cb95d16a5ca78fdcfb1942428e59bb7db568d4
https://github.com/mgp25/WhatsAPI-Official/commit/09fc457c0554b35aca913f0dfea2b327224e73e6
